### ISSUE TITLE
Date not working as store value

### ISSUE THREAD

**Issue by buzzin0609** [ctrlplusb/easy-peasy#102]
Hello,

I believe I have encountered what appears to be a bug with using Dates as store values. 

### Test instructions

* Create a new model where a `new Date()` is the initial value
* Add an action that updates the date value with a different date
* The action is triggered in Redux Dev Tools, however, it will not trigger a re-render of your component

### Code example

Please see the Code sandbox link for a reproduced example: https://codesandbox.io/s/vjvz168ny

### Workaround

Simply store the `date.toString()` or `date.getTime()` value instead and update these string/number primitive values in your actions. When you use the store result and you need it to be a `Date` object, just use `new Date(storedDateStringOrNumber)` to get the object.

**Comment by ctrlplusb** [comment]
Yep, this is a known restriction. We use redux under the hood and redux requires that you use serialisation data. So no dates, regex or functions as state values. 👍

Your workaround is a good approach.

**Comment by buzzin0609** [comment]
Ohhhh, ok thanks for confirming! It's not that much of a big deal to use the timestamps.

P.S thanks for maintaining this. It's a pleasure to use 👍

**Comment by ctrlplusb** [comment]
No problem. 👍

Glad you are enjoying it. ❤️
