### ISSUE TITLE
How to use in a "normal" statefull class component?

### ISSUE THREAD

**Issue by gino8080** [ctrlplusb/easy-peasy#103]
Like the subject,

how to access global state inside a stefaull class component?

i can't use useState because:
Hooks can only be called inside the body of a function component.

**Comment by sibartlett** [comment]
I think the options are either:

* try to use only functional components
* or also use `react-redux` (https://github.com/ctrlplusb/easy-peasy#alternative-usage-via-react-redux)

**Comment by ctrlplusb** [comment]
Yep @sibartlett is right. You can use react-redux with this lib.

**Comment by hanquf1** [comment]
hi 

I want use with react-redux 

so It's like code is it right?
--------------------------------------------------------------------
import { StoreProvider, createStore } from 'easy-peasy';
import { Provider } from 'react-redux'; // 👈 import the provider
import model from './model'

const store = createStore(model);

const App = () => (
  <StoreProvider store={store}>  👈  StoreProvider
      <Provider store={store}>  👈  Provider
        <TodoList />
      </Provider>
  </StoreProvider>
)
------------------------------------------------------------------

**Comment by ctrlplusb** [comment]
You are correct @hanquf1
