### ISSUE TITLE
access local actions in local listeners

### ISSUE THREAD

**Issue by pitops** [ctrlplusb/easy-peasy#104]
First of all this is a great library and thank you for creating it.

I am looking into migrating to this lib, but I am not sure if this is supported yet. I would like to trigger a listener when the state of a model changes with the difference that the listener is also attached to the same model. 

Something like this

```javascript
export default {
  filters: initialState,
  updateFilters: (state, payload) => {
    state.filters = Object.assign(state.filters, payload)
  },
  listeners: listen(on => {
    on('@actions.updateFilters', actions => {
      console.log('fired')
    })
  })
}
```

As seen above I tried using the action dispatched by redux in devtools but it doesn't work this way. Any help appreciated

**Comment by ctrlplusb** [comment]
Hey @pitops - thanks for this. I'll look into it. Fundamentally I _think_ you should be able to do this (although I need to do more investigation into the internals). As a workaround the following should work:

```
const myModel = {
  filters: initialState,
  updateFilters: (state, payload) => {
    state.filters = Object.assign(state.filters, payload)
  },
  listeners: listen(on => {
    on(myModel.updateFilters, actions => {
      console.log('fired')
    })
  })
}

export default myModel
```

**Comment by pitops** [comment]
Thanks @ctrlplusb - I will try it out tomorrow.
