### ISSUE TITLE
Error in react dev tools

### ISSUE THREAD

**Issue by lyyourc** [ctrlplusb/easy-peasy#105]
Suppose I have a component calling `useStore` ,

```ts
function User() {
  const { currentUser: user} = useStore(state => state.user)

  return <div>{user.name}</div>
}
```

When I check the `User` component in [react-developer-tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi), and error occurs,

```
TypeError: Cannot read property 'currentUser' of null
at User.js:2
at backend.js:1
    at S (backend.js:1)
    at i (backend.js:1)
    at e.<anonymous> (backend.js:1)
    at e.r.emit (backend.js:1)
    at backend.js:1
    at backend.js:1
    at Array.forEach (<anonymous>)
    at backend.js:1
    at Array.forEach (<anonymous>)
    at t.value (backend.js:1)
    at e (backend.js:1)
```

P.S.
* easy-peasy: 1.14.0
* React Dev Tools: `3.6.0`

**Comment by ctrlplusb** [comment]
Hi, to help debug this issue would you mind creating a minimal example within codesandbox.io?

**Comment by lyyourc** [comment]
codesandbox example may not work well with React Dev Tools, but

I had tried the [easy-peasy-typescript](https://github.com/ctrlplusb/easy-peasy-typescript) in local, and got the error screenshot as follow

![image](https://user-images.githubusercontent.com/6823863/53347606-6b323780-3954-11e9-8a13-e8e3c532ac96.png)

**Comment by ctrlplusb** [comment]
I've created an issue in `react-devtools`.

**Comment by bvaughn** [comment]
https://github.com/facebook/react/pull/14940

**Comment by ctrlplusb** [comment]
Thanks for letting us know about this @bvaughn 👍
