### ISSUE TITLE
Filter not working in changing state, splice removes wrong items

### ISSUE THREAD

**Issue by pitops** [ctrlplusb/easy-peasy#108]
I am observing something peculiar when trying to remove an item from an array. Consider the case below:

```javascript
const notifications = {
  NEW_DATA_AVAILABLE: {
    message: '',
    description:'',
    showButton: true,
    buttonText: 'FETCH',
    duration: 0,
    type: 'info'
  }
}

export default {
  // STATE
  notificationsBUS: [],
  // ACTIONS & THUNKS
  showNotification: (state, payload) => {
    const notification = Object.assign({}, notifications[payload], {
      key: `open-${Date.now()}`
    })

    state.notificationsBUS.push(notification)
  },
  removeNotification: (state, payload) => {
	// method 1 - does not do anything
    state.notificationsBUS = [
      ...state.notificationsBUS.filter(
        notification => notification.key !== payload
      )
    ]
	// method 2 - removes wrong item
    state.notificationsBUS.splice(
      state.notificationsBUS.findIndex(
        notification => notification.key === payload
      ),
      1
    )
  }
}

```

The flow is -> showNotification -> attach key -> push to notificationsBUS

On calling `removeNotification`, the filter function never returns a mutated state.

The `splice` method seems to work in mutating the state but doesn't mutate the correct state each time for some reason.

Any insight welcome

**Comment by ctrlplusb** [comment]
Hey @pitops 

Would you mind throwing this into codesandbox.io so we can quickly debug it.

**Comment by pitops** [comment]
Ah never mind, I had a nasty bug which caused this weird issue. Nothing to do with easy-peasy. I am closing this.
