### ISSUE TITLE
How do I support this project? (It's so amazing!)

### ISSUE THREAD

**Issue by benjaminvdb** [ctrlplusb/easy-peasy#111]
First of all: thank you so much for this library! 😃🎉 

I've just finished refactoring my entire codebase to Easy Peasy. I wasn't using Redux and I only knew its basics from the official tutorials. I was a bit anxious that Easy Peasy would require more Redux knowledge during some stage of the refactoring process, but everything went smoothly. Because I was able to get rid of a lot of code and complexities (lots of props threading!), I even managed to get rid of a few bugs and performance of the app has improved.

So here's my question: how do I best support this project? Perhaps we could open a host of issues for improving documentation, adding features, etc. I'm also willing to donate, so maybe you can put up a button for it? I'd like this project to stay alive for as long as possible 😄

**Comment by ctrlplusb** [comment]
Amazing words @benjaminvdb - thank you kindly. 😍

I will get back to you shortly with my thoughts on contributing. I think you have highlighted some important areas - I'll try to expand some ideas I have for you soon. 👍

**Comment by ctrlplusb** [comment]
I've tried to sign up for the GitHub sponsors effort. Will see how that goes. :)

For now I have been receiving a lot of support and feedback from the community regarding the evolution of the v3 API.

❤️
