### ISSUE TITLE
Access state in listeners?

### ISSUE THREAD

**Issue by vemundeldegard** [ctrlplusb/easy-peasy#112]
Hi!

I am wondering how I can access state in listeners? I want to fire an action by listening to another action. But to fire the action I need to access state. 

```
   single: {
      _id: 1112,
   },
    updateSingle: (state, payload) => {
        state.single = payload
    },
    getSingle: thunk(async (actions, payload) => {
        await axios.get('/api/customers/' + payload)     // id here
        .then(res => {
            actions.updateSingle(res.data)
        })
        .catch(function (error) {
            console.log(error);
        })
    }),
    listeners: listen((on) => {
        on(leads.new, (actions, payload) => {
          actions.getSingle( ## NEED TO ACCESS SINGLE STATE HERE ## );
        })
    }),
```

**Comment by ctrlplusb** [comment]
Hi @vemundeldegard!

Yep, you can do this via the 3rd parameter that gets passed to a thunk.

```javascript
    listeners: listen((on) => {
        on(leads.new, (actions, payload, { getState }) => {
			console.log(getState().foo)
        })
    }),
```

At the moment it returns the _full_ store state. In v2, which lands very soon it will only return the local state related to where the listeners are attached. There will be an additional helper called `getStoreState` that will continue to expose the full store state.

**Comment by vemundeldegard** [comment]
@ctrlplusb Thank you, thank you!
