### ISSUE TITLE
New website for docs (please review)

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#115]

**Comment by ctrlplusb** [comment]
FYI, this is in progress.

https://easy-peasy.now.sh

**Comment by ludwigbacklund** [comment]
Nice! `Help us improve this page!` seems to lead to a 404 wherever I try it though.

**Comment by GGAlanSmithee** [comment]
@ctrlplusb looking really good 👍

I have been evaluating this for quite some time as a candidate to replace vanilla `redux` / `react-redux` in my companys main tech stack. This makes the choice much easier as it will greatly aid me in communication with fellow co-workers.

Keep up the great work!

**Comment by waynevanson** [comment]
That's the same style as the Vue one, right? Looks great and feels nice to navigate as a new user.

**Comment by ctrlplusb** [comment]
@waynevanson - yep I used VuePress. Impressive as I have zero Vue experience. The devs on that project did sterling work.
