### ISSUE TITLE
Renaming useStore to useReduxState ?

### ISSUE THREAD

**Issue by revskill10** [ctrlplusb/easy-peasy#116]
This is my suggestion on naming:

Currently `useStore` actually returns the `state`, not the `store`, so it's a bit unnatural to name it as `useStore`.
Should we (or we should) provide the actual `store` as the return result for `useStore` ? And renaming current `useStore` as `useReduxState` instead.

**Comment by ctrlplusb** [comment]
Yeah, I initially had the same concerns, but eventually felt like I was overthinking it. Pity `getState` is taken by React. 😛

I wouldn't rename it now as I definitely want to avoid any breaking changes for as long as possible. An alias could be created though.  It would be easy enough to create the alias in your own project in the interim too if you like.

```javascript
import { useStore } from 'easy-peasy';

export const useReduxState = useStore;
```

👍

**Comment by revskill10** [comment]
@ctrlplusb In some cases, what's the best way to access the real `store` ?
I see new API in V2 about lazy reducers with `store.addModel` . 
To access `store` now, i have to put it in another global context for now. Could it be easier if the library expose a Context for the store ?
