### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by adrienWeiss** [ctrlplusb/easy-peasy#12]
Hi,
just a quick thank you for this lib, it look awesome 😄 
I've been checking how it could be used in a [NextJS](https://nextjs.org) project, and while I'm still not comfortable with hooks I wonder how this warning can be a problem : 
```
Warning: useLayoutEffect does nothing on the server, because its effect
 cannot be encoded into the server renderer's output format. 
This will lead to a mismatch between the initial, non-hydrated UI 
and the intended UI. To avoid this, useLayoutEffect should only be 
used in components that render exclusively on the client.
```

The whole purpose of nextJS is to provide SSR out of the box, and this warning happens if I use your `useStore` hook in a function component rendered server-side. It does seem to work (I've been only trying with hardcoded store data), but I think you may want to know this use case and eventually provide a hook which uses `useEffect` if possible 🤔 

Also, if anybody has some examples using nextjs & easy-peasy that would be awesome to share them !

cheers 👏

**Comment by ctrlplusb** [comment]
Sorted in 1.3.2 👍

Great to learn about the difference there in an SSR context. Thanks for raising this issue.
