### ISSUE TITLE
How to type Thunk helpers? 

### ISSUE THREAD

**Issue by damassi** [ctrlplusb/easy-peasy#120]
I've tried experimenting with a few things, but I can't seem to find any way to type a thunk's injections parameter without explicitly casting it: 

```typescript
interrace MyState {
  someAction: Thunk<MyState, void, ...?>
} 

const myState: MyState = {
  someAction: thunk((actions, _, { getState }) => {
     const state = getState() as StoreModel // this seems less efficient 
  })
}
```

The same goes for `dispatch`:

<img width="474" alt="Screen Shot 2019-03-14 at 9 19 54 PM" src="https://user-images.githubusercontent.com/236943/54408378-f3c40e00-469e-11e9-8557-ae934d81c4d5.png">

Thoughts?

**Comment by ctrlplusb** [comment]
Will get back to you soon. In the interim have you looked at using listeners? This is my recommended approach for cross model communication.

**Comment by DmacLoyaltyOne** [comment]
Running into something similar:

```
src/client/utilities/hooks/useOffersAPI.ts:15:5 - error TS2554: Expected 1 arguments, but got 0.

15     getRegionalOffers()
       ~~~~~~~~~~~~~~~~~~~

  node_modules/easy-peasy/index.d.ts:74:9
    74         payload: Model[P]['payload'],
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'payload' was not provided.
```


The code is as follows:

```
interface OffersModel {
  getRegionalOffers: Thunk<OffersModel> //even setting 'void' as second arg, gives this error
}

getRegionalOffers: thunk(async (actions) => {
    ...
  }),
```

Any thoughts on this?

**Comment by ctrlplusb** [comment]
Is this with v2.0.1?

**Comment by DmacLoyaltyOne** [comment]
Correct!

**Comment by ctrlplusb** [comment]
🤔 

Hmm, I just tried the same in my create-react-app based app and I am not getting the same error.

Can you share your tsconfig or better yet a small repo that reproduces the error?

**Comment by DmacLoyaltyOne** [comment]
Here you are!
https://github.com/DmacLoyaltyOne/EasyPeasyIssue120

Just build typescript on tsconfig and you'll see the error. 
I tried to strip it down to the absolute basic.
There is a offers.ts in the models, and a useOffersAPI hook under hooks folder.
The only component in src is then using the hook.

The code itself will work, but typescript seems to complain

**Comment by ctrlplusb** [comment]
What version of Typescript are you using?

**Comment by DmacLoyaltyOne** [comment]
3.1.6 in the project and 3.3.3 in vscode

Vscode shows no errors but the project does when i build it. 
Do you think its fixed in a newer typescript version?

**Comment by damassi** [comment]
@DmacLoyaltyOne just as a side note, its often good to set your typescript sdk version in your [`.vscode/config`](https://github.com/artsy/reaction/blob/master/.vscode/settings.json#L20) folder so as to avoid mismatches.

**Comment by DmacLoyaltyOne** [comment]
Yeah looks like the error goes away updating typescript to 3.3.3

**Comment by ctrlplusb** [comment]
@damassi in order to have a typed `dispatch` within your thunk you need to pass in the `Model` that represents your entire store.

```typescript
interface Injections {
  axios: AxiosInstance;
}

interface TodosModel {
  items: string[];
  save: Thunk<TodosModel, string, Injections, StoreModel>;
}

interface StoreModel {
  todos: TodosModel;
}
```

I have also shown how to type `injections`.

You can run into problems however. If you split your model interfaces across files then you can get circular references. i.e. your store model imports the todos model, and the todos model imports the store model. O_o

To avoid that you will need to keep your model interfaces in a single file, or use an alternative approach.

I generally suggest using the listener approach, as it reverses the responsibility. I feel like it also becomes a lot clearer, as your listeners live with the state that gets mutated when the associated action from another part of your tree fires.

**Comment by damassi** [comment]
Thank you!
