### ISSUE TITLE
Undo / redo using immer Patch ?

### ISSUE THREAD

**Issue by vikasaditya** [ctrlplusb/easy-peasy#124]
hi,

We are using you lib in a large project and team is loving your approach. 

There is one thing that is not clear to me at least is how can we use immer Patch to implement an undo / redo ? 

And if not then any pointers would be greatly appreciated, maybe something like redux undo/redo example?

Thanks

**Comment by ctrlplusb** [comment]
Hey @vikasaditya 

Great to hear. 👍

I would try to avoid leaning on `immer` to provide you with this functionality. You could use the [`redux-undo`](https://github.com/omnidan/redux-undo) library, and then use it's [`undoable`](https://github.com/omnidan/redux-undo#making-your-reducers-undoable) within the `reducerEnhancer` configuration value of [`createStore`](https://github.com/ctrlplusb/easy-peasy#createstoremodel-config).

Kind of like:

```javascript
import undoable from 'redux-undo';
import { createStore } from 'easy-peasy';

const store = createStore(model, {
  reducerEnhancer: reducer => undoable(reducer, reduxUndoConfig),
});
```

It looks like `redux-undo` supports filtering etc, which you could use to limit the feature to specific paths of your state (e.g. `action.startsWith('action.notifications')`).

Hope this helps.

**Comment by vikasaditya** [comment]
Thanks for prompt reply. 
I will get  your suggestion tested. Will update here for anyone else looking.
Then we can close this  ticket. Also you should label this "question"

**Comment by vikasaditya** [comment]
Can you take a quick look at https://codesandbox.io/s/rj5mnjz7wn ?
If we add redux-undo, it crashes in the thunk with state not defined. Any pointers?

**Comment by ctrlplusb** [comment]
My apologies @vikasaditya I looked into this a bit more and we won't be able to support redux-undo. This is because it changes the shape of your store state. :(

I will have a think and if any new ideas come to me I will let you know.

**Comment by vikasaditya** [comment]
okey, will wait.
Expose immer api via store?

**Comment by ctrlplusb** [comment]
I did have some ideas, but I need to let them sit for a while. Generally it takes me a few cycles/revisions until I come up with an API/solution that is effective.

**Comment by ctrlplusb** [comment]
Not planning anything like this for now. Going to leave the problem in user-land for now unless much bigger demand comes for it.
