### ISSUE TITLE
custom middleware needs to go before mockActionsMiddleware

### ISSUE THREAD

**Issue by ivosh** [ctrlplusb/easy-peasy#125]
Currently custom _middleware_ is passed as the last argument into `applyMiddleware` of `reduxCreateStore`.

This creates a problem for me when I want to use **both** custom _middleware_ and `mockActions:true`. That's because my custom _middleware_ accepts an object describing interaction with API, translating it to standard _Redux_ actions.

With the current setup when `mockActions=true` used for testing, my custom _middleware_ never sees that object passed to it. I think that's because it is swallowed by `mockActionsMiddleware` as created by `easy-peasy`'s `createStore`.

If the sequence would be reversed, that is:
```
 applyMiddleware(
        reduxThunk,
        dispatchActionStringListeners,
        ...middleware,
        mockActionsMiddlware,
      )
```
then my custom _middleware_ will have the opportunity to translate object into actions and those actions will then be available via `getMockedActions`.
This could be also configurable.

Let me know if such a change would be acceptable for `easy-peasy` - I can prepare a pull request and a test case.

**Comment by ctrlplusb** [comment]
This sounds fair. I believe you are correct, we should apply the mockActionsMiddleware as the last item. 👍

**Comment by ivosh** [comment]
Thanks. I will prepare a pull request and a test case, hopefully today.

**Comment by ctrlplusb** [comment]
https://github.com/ctrlplusb/easy-peasy/releases/tag/v2.1.1

🎉
