### ISSUE TITLE
`isObject` in `src/lib.js` might be incorrect

### ISSUE THREAD

**Issue by yeskunall** [ctrlplusb/easy-peasy#13]
https://github.com/ctrlplusb/easy-peasy/blob/ea33f4e7d9d3ec1acbc999c3888367a1280f5062/src/lib.js#L1

... will return `true` for `function`, `RegExp`, among others. Is this intended?

<br />

Thanks for `easy-peasy`, BTW. 💖

**Comment by ctrlplusb** [comment]
Thanks yes. Function would be false in the above implementation, however, RegExp would be considered an object. To be honest you shouldn't be adding functions or RegExp to your state object anyway as they aren't JSON serialisable. I extract functions off of the model anyway so there will be a small chance that RegExp could cause you an issue if you do some persisting of your state somehow. I've renamed the helper and added a test to make this more obvious that it isn't a strict test. I'd rather be more generic/unsafe and have a more performant solution in this case but let's see if anyone experiences issues down the line. 👍

Thanks for raising this, and I am so stoked you like the lib. 😊
