### ISSUE TITLE
Provide a better mechanism by which to test listeners

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#132]
In response to #128 and #129 the root problem is that it is difficult to assert listeners in isolation.

To address this I am proposing to add two new APIs to the `store`.

Work has been done on this via #133 and is available via the `next` tag.

```
npm install easy-peasy@next
```

I would really appreciate it if someone could try use them and feed back. 

@ivosh 😀

## store.triggerListeners(action, payload)

Allows you to trigger all registered listeners across the store that are listening to the provided `action`.

### Arguments

 - `action` (Action | Thunk | string, required)

    The action to fire that will trigger listeners that are targeting it.

 - `payload` (any)

    The payload to provide.

### Returns

  A promise that resolves when all fired listeners have completed.

## store.triggerListener(listener, action, payload)

Allows you to trigger a specific listener registration with the provided `action`.

### Arguments

 - `listener` (Listen, required)

    The listener instance to trigger the action against. 

 - `action` (Action | Thunk | string, required)

    The action to fire that will trigger listeners that are targeting it.

 - `payload` (any)

    The payload to provide.

### Returns

  A promise that resolves when all fired listeners have completed.

## Examples

Given the following store definition:

```javascript
const model = {
  session: {
    user: undefined,
    registerSession: action((state, payload) => {
      state.user = payload;
    }),
    logIn: thunk(async (actions, payload) => {
      const user = await loginService(payload);
      actions.registerSession(user);
    }),
  },
  audit: {
    logs: [],
	sessionHistory: [],
	logSessionHistory: action((state, payload) => {
      state.sessionHistory.push(payload);
	}),
    listeners: on => {
      on(model.session.registerSession, thunk((actions, payload) => {
        actions.logSessionHistory(payload.username);
      });
      on(model.session.logIn, action((state, payload) => {
        state.logs.push(`Authenticated ${payload.username} against server`);        
      });
    }
  }
}

const store = createStore(model);
```

We can trigger all listeners for a specific action like so:

```javascript
store.triggerListeners(
  model.session.logIn, // The action to trigger the listeners with
  { username: 'bob' } // The payload for the action
);

// assert the changes
expect(store.getState().audit.logs).toEqual(['Authenticated bob against server']);
```

You can also target a specific listener:

```javascript
store.triggerListeners(
  models.audit.listeners, // The listeners to trigger
  model.session.logIn, // The action to trigger them with
  { username: 'bob' } // The payload for the action
);

// assert the changes
expect(store.getState().audit.logs).toEqual(['Authenticated bob against server']);
```

If you fire a thunk listener then you can await on the returned promise before asserting any changes:

```javascript
store.triggerListeners(
  models.audit.listeners, // The listeners to trigger
  model.session.registerSession, // The action to trigger them with
  { username: 'bob' } // The payload for the action
).then(() => {
    // assert the changes
    expect(store.getState().audit.sessionHistory).toEqual(['bob']);
});
```

You can also use the `mockActions` configuration to assert the thunk listener in isolation:

```javascript
import { actionName } from 'easy-peasy';

const store = createStore(model, { mockActions: true });

store.triggerListeners(
  models.audit.listeners, // The listeners to trigger
  model.session.registerSession, // The action to trigger them with
  { username: 'bob' } // The payload for the action
).then(() => {
    // assert the changes
    expect(store.getMockedActions()).toEqual([
        { type: actionName(models.audit.logSessionHistory), payload: 'bob' }
    ]);
});
```

**Comment by ivosh** [comment]
@ctrlplusb Thanks a lot for the proposal. I believe the new API sounds plausible and easy to work with.

At this point I am still prototyping necessary changes to convert my existing/legacy Redux subsystem into easy-peasy one's and I cannot give you a feedback for listeners right now. Listener testing will eventually come handy for sure.

**Comment by xaun** [comment]
Hi @ctrlplusb, this looks great, any ideas when it will be released? Thanks

**Comment by xaun** [comment]
@ctrlplusb, this looks great. Just tried to install it via easy-peasy@next which includes version v2.2.0.alpha.4. Though the methods are not available i.e `store.triggerListeners `. To fix this I've needed to point to the trigger-listeners-api branch, loading v2.2.0.alpha.0.
