### ISSUE TITLE
Injections in actions

### ISSUE THREAD

**Issue by chikamichi** [ctrlplusb/easy-peasy#134]
Hi,

I have a recurring use-case / need for accessing injections within actions, in addition to thunks.

Here's an example:

``` ts
proposeWord: thunk((actions, _, { injections, getState }) => {
  const { Rules } = injections.services
  const { current: word } = getState()
  if (Rules.isValidWord(word)) actions.persistWord()
}),

persistWord: action(state => {
  state.list.push(state.current)
  state.current = last(state.current)!
}),
```

The context is a word-guessing game where there is a `Rules` service dedicated to enforcing rules. A word may be proposed (as currently typed by the user) for validation; if validated, a new current word is to take its place in the form of the validated word's last letter… but in some special cases :) For instance, when the player successfully validates all the words one must guess, the new `current` word should simply be left undefined/empty. There could be many such rules, so for the sake of [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle) it'd be best relying upon the dedicated `Rules` service rather than adding business logic to the model.

So here's the code I wish I could wrote:

``` ts
persistWord: action((state, { injections }) => {
  const { Rules } = injections.services
  state.list.push(state.current)
  state.current = Rules.nextWord(state.current)
})
```

What do you think?

**Comment by ctrlplusb** [comment]
Undecided. 😃

I tend to just use imports for these types of "services". The injections is primarily leveraged by myself to aid mocking/testing.

I'll give it some thought.

**Comment by chikamichi** [comment]
Injections are actually ultra-useful. Because it allows to create configured services (instances of services classes configured with dynamic/runtime objects, for instance user settings, production URL, etc.) Dependency injection is so useful for both actions and thunks (and arguably selectors) :D

**Comment by chikamichi** [comment]
Btw it fits right within the [multitier approach](https://en.wikipedia.org/wiki/Multitier_architecture). I'm teaching this architecture to junior programmers and easy-peasy has proven to be an excellent match (but for this missing feature :upside_down_face:)
