### ISSUE TITLE
How to use "useDispatch"

### ISSUE THREAD

**Issue by ely-alamillo** [ctrlplusb/easy-peasy#142]
Could you provide an example on how to use the "useDispatch" hook.

**Comment by ctrlplusb** [comment]
```javascript
  function MyComponent() {
    const dispatch = useDispatch();
    dispatch({ type: 'ANSWER', payload: example })
	return '👍';
  }
```

**Comment by ely-alamillo** [comment]
So I ran up on another question, I'm using the library with typescript and when I try to trigger a thunk using `useAction` hook I get type errors. Should thunks instead be dispatch using `store.dispatch` ?

**Comment by ctrlplusb** [comment]
@ely-alamillo what version of typescript are you using? also, any code snippet to share?

**Comment by ely-alamillo** [comment]
I'm trying to do this:

the compiler says: TypeError: Object(...) is not a function
```
const getIdeas = useAction(actions => actions.ideas.fetchIdeas);
```

This is the model:
```
IdeasModel = {
  ideas: [],
  setIdeas: action((state, payload) => {
    state.ideas = payload;
  }),
  fetchIdeas: thunk(async (actions, payload) => {
    const ideasRes = await IdeaService.getMany();
    actions.setIdeas(ideasRes);
  }),
  addIdea: thunk(async state => {
    // do stuff with thunk
  })
};
```


and this is the store: 
```
export const { useAction, useStore, useDispatch } = createTypedHooks<StoreModel>();

export const createdStore = createStore(store);
```

**Comment by ely-alamillo** [comment]
The way i've got it to work now is using:

```
const getIdeas = createdStore.dispatch.ideas.fetchIdeas;
```

**Comment by ctrlplusb** [comment]
Ah, `useAction` is deprecated, can you try `useActions` hook instead.
