### ISSUE TITLE
Typescript 3.4 breaks definitions

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#143]
Seeing some issues whilst trying 3.4. I'll add more detail later, but for now sticking with 3.3

**Comment by phmatray** [comment]
Thank you for opening this issue. I was investigating the code and it seems to me that this issue in the TypeScript repository seems to be related to this regression.

https://github.com/Microsoft/TypeScript/issues/30554

**Comment by estaub** [comment]
Note that https://github.com/Microsoft/TypeScript/issues/30554 describes this as a fix (though a poorly-documented breaking change), not a regression:

> In TypeScript 3.4, variance of types declared with interface is now correctly measured in all cases.

... so it is unlikely to be addressed.

**Comment by ctrlplusb** [comment]
Fixed in https://github.com/ctrlplusb/easy-peasy/releases/tag/v2.1.6
