### ISSUE TITLE
No way to reset the store.

### ISSUE THREAD

**Issue by Windynik** [ctrlplusb/easy-peasy#146]
In the application that we're building, after the user logs out, there's no way to reset the store. 

We have tried setting it to undefined,null or an empty object(it crashes the app), but that doesn't help.

**Comment by Windynik** [comment]
Any update?

**Comment by revskill10** [comment]
You can add a `resetStore` action ?

**Comment by Windynik** [comment]
@revskill10  We tried that, but it didn't make any change.

**Comment by ctrlplusb** [comment]
As a temporary solution you could do something similar to:

```javascript
const store = createStore({
  ...,
  setState: action((state, payload) => payload),
});

const initialState = store.getState();

// Later... reset store
store.dispatch.setState(initialState);
```

**Comment by ctrlplusb** [comment]
And if you would like it wrapped in an action...

```javascript
let initialState = {}

const store = createStore({
  ...,
  reset: action((state, payload) => ({
   ...initialState,
  }),
});

initialState = store.getState();

// Later... reset store
store.dispatch.reset();
```
