### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by MathiasKandelborg** [ctrlplusb/easy-peasy#147]
Hi! I just stumbled upon this awesome repository, I'm really excited to try it out!

I've also just finished writing some documentation with [Docusaurus](https://docusaurus.io/), it makes everything more organized and looks more inviting than a long README. 

I'm wondering if there are any plans to make the documentation searchable and more organized? I'd love to help you get started btw,

**Comment by ctrlplusb** [comment]
Hi @MathiasKandelborg!

Yeah, this is most definitely something I would like to explore. The documentation has gotten to the point where it really needs to be a separate site. This will also allow me to expand the documentation a bit more.  I would like to write more docs on patterns, practices, testing etc.

If you have experience with bootstrapping lib docs I would really appreciate your help with this. ❤️

**Comment by ctrlplusb** [comment]
Related #115 #123

**Comment by MathiasKandelborg** [comment]
I wouldn't mind spending a few hours refactoring the existing documentation, then link it together via an organized menu. Other than that, I don't have any experience with bootstrapping lib docs. I wouldn't mind spending some hours on this. This project is without a doubt worth it!

So far, there isn't any repo/places to contribute to yet. If that got done, I'd be all over it!

I hadn't seen 113, sorry for making a duplicate issue.

**Comment by ctrlplusb** [comment]
I've create a repo and made you a collaborator. 👍

https://github.com/ctrlplusb/easy-peasy-website

**Comment by MathiasKandelborg** [comment]
Nice! Should I start by setting up Docusaurus in the repo, or did you think of some other approach?

**Comment by ctrlplusb** [comment]
That would be amazing 👍

Thanks ♥️

**Comment by MathiasKandelborg** [comment]
No problem, thanks for letting me help! :smile: 

I'm on it. I'll keep progress on a dev branch and make PR's for now, you can expect something later today.

**Comment by chachora** [comment]
Hi. I want to pinpoint one issue, that the search in the browser doesn't work with folding in `README.md`, it makes it hard to navigate the current documentation.

**Comment by ctrlplusb** [comment]
Closing this as it's being covered by other work.
