### ISSUE TITLE
Omit payload argument in thunks? 

### ISSUE THREAD

**Issue by bassplayerch** [ctrlplusb/easy-peasy#149]
Is there any way to omit the payload argument for thunks? (Or maybe offer a type where there isn't a payload argument)?

```typescript
// my thunk type is defined like this:
logout: Thunk<AuthState, null, Injections>;
// the actual thunk:
logout: thunk(async (actions, _, { injections: { auth } }) => {....
```
The issue now is that typescript expects an argument and thus i have to call the action like this:
```typescript
logout(null);
```

I've tried changing the second argument to void, undefined and never. All result in the same issue

**Comment by ctrlplusb** [comment]
This is certainly not how it should be behaving. What version of typescript are you using? 3.4 has some [issues](#143) - I believe it is around recursive types and the inference engine updates. I am tracking for updates to Typescript.

In the interim you can use v3.3

**Comment by bassplayerch** [comment]
Thanks.
Setting the typescript version of vscode to 3.3.1 fixed the issue!

**Comment by damassi** [comment]
@ctrlplusb - would it be worth adding a Typescript `3.4` label to track these things? Noticing an uptick of issues specifically related to this.

**Comment by ctrlplusb** [comment]
Fixed in https://github.com/ctrlplusb/easy-peasy/releases/tag/v2.1.6
