### ISSUE TITLE
Ability to view state within an action for debugging

### ISSUE THREAD

**Issue by hutber** [ctrlplusb/easy-peasy#152]
I realise this isn't really valid as a ticket, but I wondered if there is a way to easily see the current state during an auction?

I also wondered if there would be any way for me to set up something like [redux-logger](https://github.com/LogRocket/redux-logger) after each mutation.

Sorry again

```
{
  boms: {},
  addToAll: action((state, payload) => {
    console.info(state.boms);
  }),
```
![image](https://user-images.githubusercontent.com/1344898/56583483-90989600-65d1-11e9-859a-f2201fba9c03.png)

**Comment by ctrlplusb** [comment]
Hi @hutber 

You can certainly register any middleware you like to help with logging. Check the `createStore` API docs for the secondary argument.

Also, to log within an action see #107

**Comment by hutber** [comment]
Thanks very much bud. This is exactly what I'm after.
