### ISSUE TITLE
TypeScript and `getStoreState`

### ISSUE THREAD

**Issue by alizahid** [ctrlplusb/easy-peasy#155]
When calling `getStoreState` inside a `thunk`, I can access the properties of my entire store. But TypeScript throws this error;

```
src/store/models/nav.ts
TypeScript error in src/store/models/nav.ts(16,13):
Property 'teams' does not exist on type 'Compact<{} & Compact<{} & {}>>'.  TS2339

    14 | 
    15 |   setTeam: thunk(async (actions, payload, { getStoreState }) => {
  > 16 |     const { teams } = getStoreState()
       |             ^
    17 | 
    18 |     console.log(teams)
    19 | 
```

How can I work around this?

**Comment by ctrlplusb** [comment]
Hey @alizahid;

A couple of things, could you provide me with:

1. Your typescript version
2. easy-peasy version
3. Your model interface definition for nav.ts

👍

**Comment by alizahid** [comment]
Hey!

TypeScript is at `3.4.4`
easy-peasy at `2.1.6`

```
interface NavModel {
  team?: Team

  setTeam: Thunk<NavModel, string>
  updateTeam: Action<NavModel, Team>
}
```

**Comment by aalpgiray** [comment]
I think it's ts version. Could you check 3.3.4000

**Comment by alizahid** [comment]
I will give it a shot, thanks!

**Comment by racingrebel** [comment]
I have the same issue, but I not even using TS.

**Comment by alizahid** [comment]
@racingrebel I think the issues are different. I’m able to get the proper state from either methods. Just TS not able to know what’s in the variables.

**Comment by ctrlplusb** [comment]
Hey @alizahid;

I wasn't sure this would work, due to circular dependencies, but I tested and it seems to work okay.

You need to import the model that represents your entire store and apply it as a type argument to your thunk.

For example, say you had the following store model:

```typescript
// store/index.ts

import { createStore } from 'easy-peasy';

import nav, { NavModel } from './nav';
import teams, { TeamsModel } from './teams';

// 👇 note how we export the store model
export interface StoreModel {
  nav: NavModel;
  teams: TeamsModel;
}

const store = createStore<StoreModel>({
  nav,
  teams,
});

export default store;

```

Then you need to update your nav model as so:

```typescript
// store/nav.ts

//          👇 we import our entire store model
import { StoreModel } from './index';

export interface NavModel {
  team?: Team;
  //  apply the store model to the thunk's 4th argument position
  //                                      👇
  setTeam: Thunk<NavModel, string, any, StoreModel>;
  updateTeam: Action<NavModel, Team>;
}

const nav: NavModel = const nav: NavModel = {
  team: undefined,

  setTeam: thunk(async (actions, payload, { getStoreState }) => {
    const state = getStoreState();
    //      👇 this is now typed
    state.teams
  }),

  // ...
};

export default nav;
```

**Comment by alizahid** [comment]
@ctrlplusb That worked. Question: what goes in that `any` spot? Can I ignore and use `any` or should I use the correct type?

Also, I see four parameters on the `NavModel` interface but only three on the implementation? Since `getStoreState` is destructured?

**Comment by ctrlplusb** [comment]
Hey @alizahid ,

The 3rd type parameter is for store injections (provided via the config second parameter to createStore). If you aren't using injections you can safely cast this as any. 👍

**Comment by ctrlplusb** [comment]
Sorry, I need to get round to full documentation on the Typescript API.
