### ISSUE TITLE
[Thunk] getStoreState is undefined and getState gives root state

### ISSUE THREAD

**Issue by racingrebel** [ctrlplusb/easy-peasy#159]
Thank you for the awesome library! Even with react-redux w/ hooks being in alpha, I still prefer the simplicity that you've laid out in this library.

Anyway, the issue.

My model looks like this:
```
{
  foo: {
    ha: null,
    myThunk: thunk(async (actions, payload, { getState, getStoreState }) => {
       getState(); // {foo: {...}, bar: {...}}
       getStoreState(); // Not a function, undefined.
       await someAsync();
    }
  },
  bar: {
    haha: null,
  }
}
```
Seems that getState gets the root state and getStoreState is not defined? 

Might be related to #155.

**Comment by ctrlplusb** [comment]
Hey @racingrebel,

Could you please provide the version for `easy-peasy`. Also a reproducible example within Codesandbox would be great 👍

**Comment by racingrebel** [comment]
Sorry, I did a version rollback at some point, and forgot to upgrade :sweat_smile:
All is good, thanks again for the library :smile:
