### ISSUE TITLE
How to use "useStore" with "selector"?

### ISSUE THREAD

**Issue by danielmahon** [ctrlplusb/easy-peasy#161]
I can't seem to access a selector function with `useStore`... It simply returns`undefined`. What am I doing wrong?

```ts
// The model type
interface AuthModel {
  token: string | null;
  user: any | null;
  logout: Action<AuthModel>;
  login: Action<AuthModel, { token: string; user: object }>;
  isEditor: Select<AuthModel, boolean>;
}

// The store
...
  auth: {
    token: null,
    user: null,
    isEditor: select(state => {
      return state.user !== null
        ? ['EDITOR', 'ADMIN'].includes(state.user.role)
        : false;
    }),
    logout: action(state => {
      state.token = null;
      state.user = null;
    }),
    login: action((state, { token, user }) => {
      state.token = token;
      state.user = user;
    }),
  },
...

// Using the react hook
const isEditor = useStore(state => state.auth.isEditor);
console.log(isEditor); // undefined
```

**Comment by ctrlplusb** [comment]
Hey @danielmahon 

What version of easy-peasy are you using?

**Comment by danielmahon** [comment]
@ctrlplusb just updated, "2.1.6"

**Comment by ctrlplusb** [comment]
Hey @danielmahon 

I am not experiencing any issues, see:

https://codesandbox.io/s/23lpq9xm3r

**Comment by danielmahon** [comment]
@ctrlplusb `typeof` returns `undefined`. If I return the `auth` object in your sandbox I see both the `user` and `isEditor` fields, but I don't see `isEditor` when I do it... Everything else seems to be working fine, with actions and state and on the model, just not the selects. The only difference I can see in my code is my state file is typescript. The component is not (yet) however. I'm going to keep digging... 😕 If I find a typo somewhere I'm going to cry....

**Comment by danielmahon** [comment]
@ctrlplusb Making progress... definitely seems to be an issue with integrating `redux-persist`. Removed all that logic and 👍 . I'll let you know what I find out.

**Comment by danielmahon** [comment]
@ctrlplusb OK, looks like the `stateReconciler` for redux-persist was overriding the initial values, since the default is set to `autoMergeLevel1` meaning `auth` was being overwritten by the "incoming" persisted object which did not include the `isEditor` field. So to fix (at least for this scenario) I just need to either wipe the persisted data on any store model update or set the `stateReconciler: autoMergeLevel2`. I'm not sure if there is a better solution. Should easy-peasy check the store structure at runtime and update it so it can still access/initialize `undefined` fields which were deleted by redux-persist or other? Either way, thanks for taking the time to look into this for me!

```ts
const config = {
  reducerEnhancer: (reducer: Reducer) => {
    return persistReducer(
      {
        key: pkg.name,
        storage: localforage,
        // Setting this to "autoMergeLevel2" allows us to shallow merge
        // the top two levels of our store, everything else will be
        // overwritten by the incoming persisted fields, delete cache to resync 
        stateReconciler: autoMergeLevel2,
        serialize: process.env.NODE_ENV !== 'development',
      },
      reducer
    );
  },
  devTools: process.env.NODE_ENV === 'development',
};

const store = createStore<StoreModel>(models, config);

const persistor = persistStore(store);
```
