### ISSUE TITLE
Have the ability to destruct assignment when using `useState`

### ISSUE THREAD

**Issue by hutber** [ctrlplusb/easy-peasy#163]
Current implementation:

```
state = {
    form: true,
    balls: false
}
  const stockListStore = useStore(state => state.form);
  const balls = useStore(state => state.balls);
```

I would love to be able when using the state:
```
  const { stockListStore, balls } = useStore(state => state);
```

Of course this example won't work :) but the idea should be there I hope.

**Comment by ctrlplusb** [comment]
Hey @hutber 

You can destruct state, I've made an example here:

https://codesandbox.io/s/wlnv4kj35
