### ISSUE TITLE
Add native support for store persistence (i.e. integrate redux-persist like behaviour)

### ISSUE THREAD

**Issue by macrozone** [ctrlplusb/easy-peasy#164]
in redux-persist, i can define a blacklist and whitelist for persistence, 

but its awkward to use when you have nested state. Usually you would want to define persistence per model or per property on a model.

Did anyone find a good solution to define persistence with easy-peasy?

**Comment by ctrlplusb** [comment]
Hey @macrozone 

Is there any way you could set up an example in codesandbox? I have a starter here:
https://codesandbox.io/s/yv76p30w8v

👍

**Comment by filipjnc** [comment]
Well I think you can take this sandbox as example: https://codesandbox.io/s/5464z4190x

Let's suppose only the theme branch should be persisted, how would we approach it?

**Comment by macrozone** [comment]
I already done it, but its far from ideal. Basically you can define a whitelist: https://codesandbox.io/s/easy-peasy40-ym3tv

but that requires you to manage persistence outside of the models and you can only define blacklist / whitelist for the root properties of your store model (unless you use nested persists, but that looks awkward and i am unsure how to use with easy peasy https://github.com/rt2zz/redux-persist#nested-persists)

that's why i am asking if someone found a better way of doing it

**Comment by ThePaulMcBride** [comment]
I've ran into the same problem. Essentially, `redux-persist` already has a [solution](https://github.com/rt2zz/redux-persist#nested-persists) this but as far as I can tell, it can't be used with `easy-peasy` when you are using more than one model.

Right now, we only have access to a global `reducerEnhancer`. We would need to be able to add a separate `reducerEnhancer` to each model.

@ctrlplusb I'm not familiar with the internals of easy-peasy. Would this be a lot of work to implement?

**Comment by ctrlplusb** [comment]
@ThePaulMcBride 

redux-persist unfortunately doesn't lend itself to nicely integrate with easy-peasy. 

I've had some long standing ideas and believe now it is time to act on them.

I am investigating the addition of a native `persist` helper to easy-peasy. This would make in fundamentally simple to add this behaviour to your stores.

A few off the cuff examples of what I have in mind in terms of API.

```javascript
import { persist } from 'easy-peasy';
//         👆 import the helper

// Then you wrap a model with the helper to indicate that you would like
// to persist

// persist all
let model = persist({
  counter: 0,
  todos: [],
  increment: (state) => {
    state.counter += 1;
  }
});

// select keys to persist via whitelist
model = persist(
  {
    counter: 0,
    todos: [],
    increment: (state) => {
      state.counter += 1;
    }
  }, 
  // secondary argument is a configuration:
  {
    whitelist: ['counter'],
  }
);

// ignore keys to persist via blacklist
model = persist(
  {
    counter: 0,
    todos: [],
    increment: (state) => {
      state.counter += 1;
    }
  }, 
  {
    blacklist: ['todos'],
  }
);

// persist at any depth within the model
model = {
  counter: 0,
  todos: [],
  increment: (state) => {
    state.counter += 1;
  },
  session: persist({
    user: null,
    login: thunk(/* ... */)
  })
}

// you can also specify multiple persist configurations, including nested
model = persist({
  counter: 0,
  todos: [],
  increment: (state) => {
    state.counter += 1;
  },
  session: persist(
    {
      user: null,
      token: null,
      login: thunk(/* ... */)
    },
    {
      whitelist: ['token']
    }
  )
}

// full set of configuration values available:
model = persist(
  { 
    counter: 0,
    todos: [],
    increment: (state) => {
      state.counter += 1;
    },
  }, 
  {
    // list of middleware that will be applied to data prior to persist.
    // they get run left to right
    // this emulates the behaviour of "transforms" by redux-persis
    persistMiddleware: [
      (key, data) => data 
    ],
    // list of middleware that will be applied to data prior to rehydration.
    // they get run left to right
    // this emulates the behaviour of "transforms" by redux-persis
    rehydrateMiddleware: [
      (key, data) => data 
    ],
    // isolate the data keys to persist via...
    whitelist: ['counter'],
    // set data keys to be ignore skipped...
    blacklist: ['todos'],
    // specify a custom storage engine
    // we will have built in ones for sessionStorage and localStorage
    // default is localStorage
    storage: MemoryStorage,
    // specify a strategy to be used for rehydration
    rehydrateStrategy: 'overwrite', // or 'merge' or 'mergeDeep'
  }
)

// pass into the store
const store = createStore(model);

// the store will have additional APIs to work with peristence
store.persist.commit(); // commit outstanding changes to persistence
store.persist.clear(); // remove current data in persistence
// I don't see the value in having a pause/resume API similar to redux-persist

// when rendering your application the StoreProvider will wait for all 
// data to be rehydrated prior to rendering it's children
const app = (
  <StoreProvider store={store}>
    <MyApp />
  </StoreProvider>
) 
```

I am still of two minds on whether we should support a PersistGate like component as is available via redux-persist. This could be added at a later stage though I suppose? I believe it would only be useful in cases where the storage engine being used has asynchronous rehydration.

Thoughts?

**Comment by ctrlplusb** [comment]
Great. 😀

I will ping you for some beta testing.

**Comment by ctrlplusb** [comment]
Progress is being made... 😀

<img width="408" alt="Screenshot 2019-10-29 22 11 20" src="https://user-images.githubusercontent.com/12164768/67813292-1a518080-fa99-11e9-8f13-0a69fa8b6f87.png">

I will hopefully have a beta out soonish for testing. It'll need some robust testing. I need to refactor the code a few times over to clean it up and optimise it too. Far more tests will be needed to try and cover edge cases too.

That all being said, it is looking very promising.

**Comment by ctrlplusb** [comment]
Todo

- [ ] More tests to gain 100% API coverage along with as many edge cases as I can guess
- [ ] Docs
- [ ] Beta release
- [ ] Clean code refactor
- [ ] Optimisation

**Comment by ctrlplusb** [comment]
One thought though, instead of a persist gate what do you think about this type of API?

```javascript
const store = createStore(persist(model, { storage: localForage });

store.persist.resolveRehydration().then(() => {
  ReactDOM.render(
    <StoreProvider store={store}>
      <App />
    </StoreProvider>,
    document.getElementById('app')
  );
});
```

**Comment by GuillaumeAmat** [comment]
@ctrlplusb Could you consider a cross tab synchronization/rehydration feature?

Like the former https://github.com/rt2zz/redux-persist-crosstab

**Comment by ThePaulMcBride** [comment]
That API makes it a little more challenging to show something else while we wait for the store to rehydrate. I wonder would there be a way for the rehydration state to be exposed to the user, say, with a hook like `const ready = isStoreHydrated()`.

Obviously this would only work in a component wrapped in a store provider.

**Comment by ctrlplusb** [comment]
@ThePaulMcBride ok no worries, I am going to include a PersistGate equivalent component - it is named `RehydrateBoundary`, but it behaves the same. I've got everything tested now. Busy writing docs and need to do the TypeScript definitions. Then it will be ready for testing.

**Comment by ctrlplusb** [comment]
@macrozone @ThePaulMcBride 

See #343 

Would appreciate your feedback on experience with it. 👍

**Comment by macrozone** [comment]
> @macrozone @ThePaulMcBride
> 
> See #343
> 
> Would appreciate your feedback on experience with it. 👍

looks very nice! will try it out when i have the oportunity!

**Comment by ctrlplusb** [comment]
v3.2.0 👍
