### ISSUE TITLE
model action - change another model state

### ISSUE THREAD

**Issue by Kashio** [ctrlplusb/easy-peasy#165]
Is there a way to define an action of model A to also act upon the state of model B?

**Comment by ctrlplusb** [comment]
Hey @Kashio ,

Yep, check out the `listen` helper. You attach to model B and listen to the respective action from model A.

**Comment by Kashio** [comment]
> Hey @Kashio ,
> 
> Yep, check out the `listen` helper. You attach to model B and listen to the respective action from model A.

Thanks!!
But I have a unique scenario where my listener needs to act upon the changed state in 2 way, if the new payload is set to a new value then use the use that value, if it is set to null then I need the previous value, like demonstrated here:
```
const cityGiftGrantModel = {
    [ReportConfig.CITY_GIFT_GRANT]: null,
    set: action((state, payload) => {
        state[ReportConfig.CITY_GIFT_GRANT] = payload;
    })
};

const missingEquityForLowerLeverageLevelModel = {
    [ReportConfig.MISSING_EQUITY_FOR_LOWER_LEVERAGE_LEVEL]: null,
    set: action((state, payload) => {
        state[ReportConfig.MISSING_EQUITY_FOR_LOWER_LEVERAGE_LEVEL] = payload;
    }),
    listeners: listen((on) => {
        on(cityGiftGrantModel.set, action((state, payload) => {
            if (payload) {
                state[ReportConfig.MISSING_EQUITY_FOR_LOWER_LEVERAGE_LEVEL] = Math.max(payload - payload.value, 0);
            } else {
                state[ReportConfig.MISSING_EQUITY_FOR_LOWER_LEVERAGE_LEVEL] = Math.max(payload + previous.value, 0);
            }
        }))
    })
};
```
where `previous.value` should be like the value before it was null so I could "reset" the current model state.
Can I achieve this somehow?
