### ISSUE TITLE
How to test listeners with v2.1.x 

### ISSUE THREAD

**Issue by xaun** [ctrlplusb/easy-peasy#167]
Hey @ctrlplusb ,

Having some trouble testing listeners and was hoping for some help as I can't find anything on the subject online (except your WIP PR #133 - which looks great, when will it be finished?). 

```js
describe('listeners', () => {
  const store = createStore({
    project: {
      current: null,
      update: action((state, payload) => {
        state.current = payload
      }),
      things: {
        fetch: thunk(...)
      }
      listeners: listen(on => {
        on(
          project.update,
          thunk((actions, payload) => {
            actions.things.fetch(payload)
          })
        )
      })
    }
  })

  it('on project.update', () => {
    store.dispatch.project.update(project)

    // how to test listener thunk internal thunks where invoked? Can I mock the `actions.things.fetch` to just track it was called?
  })
})
```

Also, something else I experience is that when dispatching a thunk action (via `store.dispatch.project.myThunk(...)` which is registered as a  listener target, in Jest, the listener handler seems to never be invoked (works when running app). Is there something I should be aware of here? 

Thanks heaps

**Comment by xaun** [comment]
@ctrlplusb awesome, no worries, will do :) CC: @bentron2000

**Comment by ctrlplusb** [comment]
Hi @xaun!

I have published a new released (described within the PR).

Please note that I have also updated the example tests on this branch. It is still a work in progress but these tests showcase different strategies for testing your easy peasy based apps. I am adding a lot of comments and descriptions to the examples. It should hopefully be a useful reference.

https://github.com/ctrlplusb/easy-peasy/tree/trigger-listeners-api/src/__tests__/testing

I would appreciate any and all feedback. Please don't be shy to criticise. It would be great to make the testing experience as pleasant as the implementation experience.
