### ISSUE TITLE
thunk is giving Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by DrYSG** [ctrlplusb/easy-peasy#169]
Just tried this in Chrome V73

        fetchNextJobNum: thunk(async (actions, payload) => {
            const nJobNum = await fetcher(payload);
            actions.setJobNum(nJobNum);
          })

and I am getting the error

```
App.jsx:19 Uncaught ReferenceError: regeneratorRuntime is not defined
```

Do I need more presets in my babelrc?

```
{
    "presets": [
        "@babel/preset-react"
    ]
}
```

I have also tried:

```
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ]
}
```
It is an issue with any async, and even this is not helping:

```
{
    "presets": [
        [
            "env",
            {
                "targets": {
                    "browsers": [
                        "last 1 versions"
                    ]
                }
            },
            "@babel/preset-react"
        ]
    ]
}
```

**Comment by damassi** [comment]
This is more of a Babel issue, rather than an issue with `easy-peasy`. See https://github.com/babel/babel/issues/7824.

**Comment by DrYSG** [comment]
@ctrlplusb exactly. Now I did not want to include the polyfill for async, so it took me a bit longer to fix this. But I can only say that easy-peasy is so pleasant, (as is the no-config parcel bundler) that I forgot there are other parts of this toolchain that are messy. So for the ediification of others, I am tellling folks that you want to do everything you can to keep IE or other low use browsers from forcing the include of regeneratorRuntime. Pre is funny in all the browserlist tags, so this one is working for me, for the latest Chrome and Edge Chromium browsers.

```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "chrome": ">70",
                }
            },
            "@babel/preset-react"
        ]
    ]
}
```
