### ISSUE TITLE
Implementation example with SSR (Next.js)

### ISSUE THREAD

**Issue by dai4** [ctrlplusb/easy-peasy#171]
Hey, first of all, this library is amazing and I think it has nailed the state management strategy down to the T. It's by far the simplest way to have a global store. Thank you!

I've setup everything with NextJS and it works flawlessly, however I would like to hydrate the store from the server side and have the initial state prefilled when the client side loads, based on the URL query params. In my use case, I have a sidebar which only opens when a url param called `st` exists and I would like to set a `sidebarOpen` variable to true before the client loads.

Are there any examples on how this can be achieved?

**Comment by lishine** [comment]
I have done something like that.
This subject though is not related to this lib.
I use nextjs redux integration. And then it is fiddling with the getinitialprops, the constructor and the render.
I can copy some from my project

**Comment by dai4** [comment]
I did manage to get it working by using the nextjs redux integration and dispatching actions in getInitialProps, but for some reason that didn’t feel right for me. I also had to add a special action to track whether the server actions had been dispatched, so they are not being triggered every time I change to the same route but with different query params. I still think an example would be helpful for people new to this library how didn’t really use redux in the past.

**Comment by ctrlplusb** [comment]
Might be a worthwhile exercise creating an example to PR into the Next repo. I might be open to doing that as soon as v2.3.0 is released. 👍

**Comment by hutber** [comment]
I've not set up SSR yet, but am just sitting down to do this, so any support to be able to use easy-peasy with SSR would be greatly appreciated.

**Comment by lishine** [comment]
I put the front part of my project.
https://github.com/lishine/next-easy
Next.js + easy-peasy
It should actually even run as it is: yarn dev.
Mainly the logic of SSR is in _app and features/model
Look at it. If you have questions (probably will:) - ask.

**Comment by BjoernRave** [comment]
What is the status of this? @lishine I am not sure if I understand exactly what you are doing. Is it really required to get the router from next for this?

**Comment by lishine** [comment]
@BjoernRave router is your choice. What exactly is the question?

**Comment by BjoernRave** [comment]
@lishine Well, if you are really nice my question would be whether you could extract the `easy-peasy` related logic out of the rest, because for me it's not very clear what is part of setting up `easy-peasy` with next.js and which is your own logic, that is in `_app.js` and also/especially in `features/model.js`.

**Comment by ctrlplusb** [comment]
It would be great if we could convert the official redux example in the next repo into an easy-peasy one.

https://github.com/zeit/next.js/tree/canary/examples/with-redux

One of the important differences is the [creation of the store](https://github.com/zeit/next.js/blob/af890406221ff7af4310ef1b4ac56e54913db889/examples/with-redux/store.js#L63).

Instead of:

```javascript
export function initializeStore (initialState = exampleInitialState) {
  return createStore(
    reducer,
    initialState,
    composeWithDevTools(applyMiddleware())
  )
}
```

You will need the easy peasy version:

```javascript
export function initializeStore (initialState = exampleInitialState) {
  return createStore(
    model,
    { initialState }
  );
}
```

Otherwise it should share a lot of the same code in terms of the app.

**Comment by ctrlplusb** [comment]
I would be happy to do this, but I am still deep into creating the new docs website and finalisation of new APIs.

**Comment by lishine** [comment]
These are the relevant parts of connect easy-peasy to next (without my initial-state-reset stuff):

```
import { createStore, action } from 'easy-peasy'
const storeStructure = {...}
export const makeStore = (initialState, options) => {
    const store = createStore(storeStructure, { initialState })
     return store
}

import React from 'react'
import withRedux from 'next-redux-wrapper'
import App, { Container } from 'next/app'
import { useStore, StoreProvider } from 'easy-peasy'
import Head from 'next/head'

import { makeStore } from 'features/model'
export let store

class MyApp extends App {
    static async getInitialProps({ Component, ctx }) {

    const pageProps = Component.getInitialProps
            ? await Component.getInitialProps(ctx)
            : {}
        return { pageProps }
    }

    constructor(props) {
        super(props)
        store = props.store

        if (process.browser) {
            console.log('* BROWSER in constructor')
        } else {
            console.log('* SERVER in constructor')
        }
    }
    render() {
        const { Component, pageProps, store } = this.props

        return (
            <Container>
                <Head>
                    <title>Dance Salsa</title>
                </Head>
                <StoreProvider store={store}>
                    <ThemeProvider theme={theme}>
                        <GlobalCss />
                        <div className="page-container">
                            <Header />
                            <ModalSelect />
                            <Component store={store} {...pageProps} />
                        </div>
                    </ThemeProvider>
                </StoreProvider>
            </Container>
        )
    }
}

export default withRedux(makeStore, { debug: false })(withRouter(MyApp))

```

**Comment by BjoernRave** [comment]
@lishine thanks alot for this. I am using it in my app for now, but I think for the example we should try to have something without `next-redux-wrapper`

**Comment by BjoernRave** [comment]
okay, I created a basic repo for the `with-easy-peasy` example, but it still needs a README and maybe more sophisticated examples: https://github.com/BjoernRave/with-easy-peasy

**Comment by lishine** [comment]
So you basically inserted a stripped version of next-redux-wrapper in the example.
While next-redux-wrapper is well maintained, it can be used as is.

**Comment by BjoernRave** [comment]
@lishine I just took the `with-redux` repo. I didn't touch the `with-redux-store.js` file.

**Comment by hutber** [comment]
Awsome @BjoernRave thanks for the repo. Struggling to get this to work when I'm using hot reloading as I'm running the project with `nodemon --inspect -w server.js server.js` I'm wondering with nextjs do I have to run it with `dev: next`? I got the idea for nodemon from their [examples](https://github.com/zeit/next.js/tree/master/examples/custom-server-nodemon)

https://github.com/hutber/goldendemon is the repo :/

**Comment by hutber** [comment]
Ah... move `_app.js` inside the `/pages`... lol got it
