### ISSUE TITLE
Whats in a name

### ISSUE THREAD

**Issue by tonypee** [ctrlplusb/easy-peasy#172]
Love the project so far - Silly thought - what about shortening the name to simply 'peasy' ? Would make talking about the library a little easier, less verbose, maybe a little more professional (less wtf - is that a lib name?).. just a tought

**Comment by ctrlplusb** [comment]
Funnily enough Syntax.fm did a live broadcast where they posed a question to the audience: "Is easy-peasy a React state management library or a children's spoon set?"

:)

**Comment by tonypee** [comment]
So peasy it is! keeps with the heritage of the library! concise. amazing.. print it!
