### ISSUE TITLE
Unified, Branch-specific API object 

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#173]
In a Hooks environment, I'd like to load an 'object' that contains _all_ methods & properties relevant to a 'branch of state', _instead of_ using separate `useState`, `useAction`, etc. hooks.

The terminology for such a hook could be `useBranch()`, `useModel()`, or whatever terminology matches your concept for 'branches of the state-tree'. It should handle branches at any depth, like: `useBranch('user/profile/addresses')`

This example _extracts_ each property/method from a branch object.
```
const { items, add, remove, fetch, dispatch } = useBranch('todos');
return (
    { items.map( ... ) }
    <Button onClick={ add }>New</Button>
    <Button onClick={ fetch }>Refresh</Button>
)
```

Or, using it in an _object-oriented_ manner. This also shows a sample 'configuration'.
```
const config = { prefix: 'TODO_' }
const todos = useBranch('todos', config)
return (
    { todo.items.map( ... ) }
    <Button onClick={ todos.add }>New</Button>
    <Button onClick={ todos.fetch }>Refresh</Button>
)
```

If I call the `dispatch` method of this branch-object, it should _automatically_ prefix the action-names. For example, calling `todos.dispatch("ADD", {...}) ` would become a "TODOS_ADD" action. (Note the 'prefix' option in the example above.)

I created a similar 'Branch' wrapper for a project. I found it a good 'modular' approach. It's very DRY, and allows for creating reusable helpers to further reduce boilerplate, (if consistent naming is used, like 'items', 'add' & 'fetch').

**No new functionality is needed.** This could just be a special "hook" that _unifies_ the various elements into a single 'object' representing the specified branch. Internally the hook could use the existing API, plus handle special features like auto-prefixing.

**Comment by ctrlplusb** [comment]
I investigated this and given that we are leveraging redux under the hood exposing a unified model during consumption phases isn't easily achieved. I am going to leave everything as is for now.
