### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by cevr** [ctrlplusb/easy-peasy#174]
Are there performance benchmarks that measure how it performs against something like react-redux? I know React-Redux was having performance issues from versions 5-6. How does easy-peasy fair?

**Comment by ctrlplusb** [comment]
I do actually have some based on the react redux benchmarks. I will try finish the last few off and publish soonish. Initial results looked good 👍

**Comment by cevr** [comment]
@ctrlplusb Awesome, interested in seeing that!
