### ISSUE TITLE
How select access select or state in other subtrees without put the select root

### ISSUE THREAD

**Issue by homura** [ctrlplusb/easy-peasy#175]
the use-case

```js
const store = createStore({
  authors: {
    data: {
      1: { name: "John Smith" }
    }
  },
  posts: {
    data: {
      1: { authorId: "1", title: "post title 1" },
      2: { authorId: "1", title: "post title 2" }
    },
    detail: select(posts => postId => ({
      ...posts.data[postId],
      author: ?? // how to reference the author in subtree of store
    }))
  }
});

```

**Comment by ctrlplusb** [comment]
Hi @homura,

I am actually unhappy with selectors as they stand. They have a couple of pitfalls/downsides/limitations, including the one that you have raised above.

It's been some time that they have been around now and I have learned a great deal about the issues with the current design of selectors. Luckily I have been able to take these learnings and I now have a clear strategy for a new selectors based API that will allow you to use state from across your model. It is also far far far more performant than the current selector design.

I am hoping to get some time this weekend to be able to work on it. 🤞

I will keep you posted.

**Comment by ctrlplusb** [comment]
FYI I have published a new helper. Check out #177 for more info. I've still got loads of docs to write out. I'll be writing how to use them via Typescript too after I finish the standard JS examples.

Would really appreciate your feedback.
