### ISSUE TITLE
Updated API ideas

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#176]
This API update would make interfacing with your store from your components far more concise. Instead of using `useStore` and `useActions` hooks to access state and actions respectively, we can merge the two concepts and have `useStore` return both state and actions. i.e. it would represent the same structure as your model definition.

For example...

```javascript
import { action, createStore, StoreProvider, useStore } from 'easy-peasy';

const store = createStore({
  todos: {
    items: ['Install easy-peasy', 'Define your model', 'Have fun'],
    add: action((state, payload) => {
      state.items.push(payload)
    })
  }
});

const App = () => (
  <StoreProvider store={store}>
    <TodoList />
  </StoreProvider>
)

function TodoList() {
  //               👇                   👇
  const todos = useStore(state => state.todos)
  return (
    <div>
      {todos.items.map((todo, idx) => <div key={idx}>{todo}</div>)}
      <AddTodo onAdd={todos.add} />
    </div>
  )
}
```

Note how actions are bound and made available via the `useStore`. You would then only need this singular hook.

I feel like the state and actions split just screams out Redux, where really this is meant to be an abstraction of Redux that shouldn't require any prior Redux experience/knowledge. This would map much more naturally to what newcomers may expect.

The ability to then tinker with Redux is more of an advanced case, but really shouldn't be advertised as the primary API of this library.

**Comment by lishine** [comment]
I like that

**Comment by ctrlplusb** [comment]
Yep, they were a huge inspiration for my API 👍

**Comment by ctrlplusb** [comment]
Some initial experiments show some big problems with this. I am closing this for now as I want to do further investigation and thinking. I will reopen or create a new issues with findings/plan when ready.
