### ISSUE TITLE
Thunks are executed not synchronously ?

### ISSUE THREAD

**Issue by lishine** [ctrlplusb/easy-peasy#179]
THUNK
ACTION
THUNK

Seems like the above action executed before the first thunk...

**Comment by lishine** [comment]
This asynchronous nature is unexpected. For example not like with react-easy-state.

**Comment by ctrlplusb** [comment]
Hi @lishine 

I will explain soon the intentions of the thunk. In the mean time it would help if you could give me an example of what you are trying to achieve. 👍

**Comment by lishine** [comment]
I think this will demonstrate:
Click increase and see in the console value of 0. If it was sync, it would be 1
https://codesandbox.io/s/easy-peasy-starter-k7fxp

**Comment by ctrlplusb** [comment]
Hmm I am not seeing any updates to ui or console logs when clicking the button. Are you sue this is the correct sandbox you linked me to?

**Comment by lishine** [comment]
![image](https://user-images.githubusercontent.com/6741645/57974409-3b795580-79c0-11e9-8f84-c5639c6eeaf7.png)

**Comment by ctrlplusb** [comment]
Okay just be my mobile.

![Screenshot_20190518_210129_com android chrome](https://user-images.githubusercontent.com/12164768/57974457-41ffd100-79b0-11e9-867c-047268704293.jpg)

**Comment by lishine** [comment]
BTW I don't like the name 'thunk' - it only reminds me of redux.
But I have no other much better idea. Effect was better than thunk. 
'Logic' is and option

**Comment by lishine** [comment]
Found this in README, so sorry for not noticing...
```
You can dispatch a thunk action in the same manner as a normal action. A thunk action always returns a Promise allowing you to execute any process after the thunk has completed.
```
