### ISSUE TITLE
addModel resets store to default state

### ISSUE THREAD

**Issue by dai4** [ctrlplusb/easy-peasy#184]
Hello,

I'm working on an app where I need to split everything into modules, and therefore split the store into different chunks too.

I saw the functionality for `store.addModel`, but I might be missing something as it resets the store to the initialState when used. I would expect it to keep whatever state exists, but inject the model I'm passing dynamically, ready to be used from that point onwards.

Steps to reproduce:
1. Dispatch any action to update a value in the store
2. Call `store.addModel('test', { newModel: true })`
3. Observe how the value changed in point 1. has now reverted to default

**Comment by ctrlplusb** [comment]
Hey @dai4 

Thanks for raising this. Will look into it.

The work I am doing ok #131 actually raises some interesting primitives and opportunities to dynamically load stores. I have some really interesting ideas around this which I am excited to share.

**Comment by dai4** [comment]
Thanks @ctrlplusb !
Are you planning on including these changes in the 2.3.0 release?

**Comment by ctrlplusb** [comment]
Yep 👍

**Comment by dai4** [comment]
Hi @ctrlplusb,

I had a look at your PR related to #131 and I think that functionality wouldn't actually fix the issue in this thread. It looks good as a pattern and definitely useful, but dynamically loaded store chunks are sort of separate. From the way I understand it so far, local stores can be accessed via `Component.useStore | Component.useActions` etc, but a dynamically loaded store chunk would actually allow one to just `useStore` as usual, without specifying a component. What are your thoughts on this?

**Comment by lishine** [comment]
Similar issue of mine
#180

**Comment by ctrlplusb** [comment]
This is next on my hit list. 👍

**Comment by ctrlplusb** [comment]
Fixed in `easy-peasy@2.3.2` 👍

**Comment by dai4** [comment]
Brilliant! Thanks!

**Comment by ctrlplusb** [comment]
FYI, updated docs on the `addModel` and `removeModel` APIs are coming within the next minor release (v2.4.0 - currently)

**Comment by dai4** [comment]
Great, I'll wait for that! The typescript types seem to be missing too.

FYI, the changes you merged to 2.3.2 don't include the compiled dist folder.

**Comment by ctrlplusb** [comment]
Ah dang, missed the types too. Will sort that.

The dist folder is available on the latest publish:

https://unpkg.io/easy-peasy@2.3.2/dist/

**Comment by dai4** [comment]
Thanks for the types!

What I meant about the dist folder is that your changes are not compiled in there. It still shows the old version of the code. I think your husky prepublish script failed somehow and it didn't push the latest compiled code.

**Comment by ctrlplusb** [comment]
AH! That sounds like a nasty bug. Thanks for pointing this out dude. ❤️❤️❤️

**Comment by ctrlplusb** [comment]
Released new version 👍
