### ISSUE TITLE
UMD support: dependency globals

### ISSUE THREAD

**Issue by wmik** [ctrlplusb/easy-peasy#19]
I could be wrong but I think redux and redux-thunk export their [globals](https://github.com/ctrlplusb/easy-peasy/blob/3b01cec96d93e54c9a20317d28f499428a6c2b78/rollup.config.js#L54) as `Redux` and `ReduxThunk` respectively.

Great package btw 🙂 🎉 💚

**Comment by ctrlplusb** [comment]
You are correct...

https://unpkg.com/redux@4.0.1/dist/redux.js
https://unpkg.com/redux-thunk@2.3.0/dist/redux-thunk.js

😊

Would you be open to creating a PR to fix?

Glad you are liking the package. 👍

Have you been trying to use it much within a UMD context? Are you loading directly in the browser? I was wondering if I should consider bundling all the dependencies, except for React and React DOM, into the UMD build to avoid more difficult initial setups. I pretty much always work from a Node based environment with a bundler so I am not the best to decide this. Would appreciate your thoughts. 👍

**Comment by wmik** [comment]
Sure I'd be happy to take this.

Yes I'm attempting to load it directly using a script tag which also requires the dependencies to be setup manually.
I'll try testing amd as well while applying the patch.

***Side note***:
- Not sure how you feel about bundling `prop-types` for production. I noticed it's only used [here](https://github.com/ctrlplusb/easy-peasy/blob/3b01cec96d93e54c9a20317d28f499428a6c2b78/src/provider.js#L9)
- Also doubt `shallowequal` has a umd distribution but it should be easy to create one since it's relatively small.
