### ISSUE TITLE
Dynamically adding and removing listeners

### ISSUE THREAD

**Issue by lishine** [ctrlplusb/easy-peasy#192]
For example, listening to global modal closing only when that modal opened from the current store part.
Otherwise it will have to listen to every modal closing.
Another way is to addModel the store part dynamically and remove when going away from the page. The only shortcoming is that addModel works currently only on key , not on path

**Comment by ctrlplusb** [comment]
Hey @lishine 

Apologies for the delayed response. Is there any way you could provide a minimal codesandbox example of your problem? I would be better suited to give you a recommendation then.

**Comment by lishine** [comment]
Thank you for your response!
Before doing codesandbox, I would just explain,  maybe it is enough, if not I will do codesandbox.

In the current implementation easy-peasy can:
1 feature. add listener to a model
2 feature. add model at a root key

I would like to have:
1 feature. remove listener from a model
2 feature.  add model in any place in the store tree ( at a path)

The purposes
1. If the model don't need to listen anymore, remove the listener in order to save computing
2.  When the page loaded, the model added to the store, when the loaded another page, this model get removed.

**Comment by ctrlplusb** [comment]
Thanks for the explanation. To be honest I would prefer a codesandbox. I appreciate you have an idea of how you would like to solve your problem, but it may be of value for me to look at it and consider alternative approaches.

**Comment by ctrlplusb** [comment]
Closing this for now. Happy to review any codesandbox that comes along.
