### ISSUE TITLE
Function reference, maybe need documentation

### ISSUE THREAD

**Issue by lishine** [ctrlplusb/easy-peasy#193]
It looks like a feature detail but it took me a few hours to find out
My listeners didn't work,  so I found out this thing.

1.
```
const fModel = () => ({
   a: thunk(() => {}),
})
```
vs
2.
```
const a = thunk(() => {})
const fModel = () => ({
   a,
})
```
vs
3.
```
const a = () => thunk(() => {})
const fModel = () => ({
   a: a(),
})
```

And the createStore:
```
createStore({ a: ...fModel(), b: ...fModel() })
```

Now, option 1 and 3 will work. Option 2 will not work.

BTW listeners, when trigger a thunk, though working,  this thunk does not show in Redux devtools...

**Comment by ctrlplusb** [comment]
This should probably be classified as a bug. I will add a test case for the new listener API in next
