### ISSUE TITLE
What does <Notification> do on easy-peasy-typescript?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#198]
I've read all the documentation and am loving the idea of `easy-peasy`. Now I'm running the typescript example but nothing renders from the `<Notification>` component. 

Can you help me understand it's purpose?

Thanks! 👍

**Comment by ctrlplusb** [comment]
Hey @GollyJer - glad to hear you like the library. 😃

The notification component should display in the bottom right corner of your UI when you add an item. It's a fairly random example overall. Apologies for that.

FYI, v2.4.0 is around the corner with some great improvements to the way we manage derived state and listeners. I will be deprecating a lot of the older APIs and will eventually cut a v3.0.0 release that removes them.  For now I am not introducing any breaking changes - I will output console warnings if you use a deprecated API.

That all being said you may be better off using the beta version of v2.4.0. You can reference the new versions docs here: https://easy-peasy.now.sh

```
npm install easy-peasy@2.4.0-beta.1
```

👍
