### ISSUE TITLE
replace useStoreState API by useStore 

### ISSUE THREAD

**Issue by ELBEQQAL94** [ctrlplusb/easy-peasy#202]
In intro of your docs i find error in useStoreState API because the correct function is useStore.
i hope to fix this error in docs.
https://easy-peasy.now.sh/docs/api/use-store-state.html
thank you at all.

**Comment by ctrlplusb** [comment]
Yeah sorry you came at a stage where we are moving from v2.3.3 to v2.4.0. The `useStoreState` was published with v2.4.0. It will work now.
