### ISSUE TITLE
Redux combineReducers compatibility?

### ISSUE THREAD

**Issue by chukcha-wtf** [ctrlplusb/easy-peasy#211]
@ctrlplusb thank you for such a great library!

I'm currently interested in making it work with `redux-persist` (spoiler - works like a charm) but want to store different models in different storages. They suggest using `combineReducer` for such purposes but I'm not sure how to integrate this into `reducerEnhancer` so any hints will be much appreciated.

I've created a boilerplate https://codesandbox.io/s/easy-peasy-starter-j4l2o with working redux-persist config and commented out sections that aren't working `store.js:42`.

It's not a real issue, but I believe it can be a nice example for Recipes docs section.

**Comment by veevidify** [comment]
Hi @chukcha-wtf 
I'm also using `easy-peasy` with `redux-persist` and manage to get persistent store behaviour working. Not sure if this is exactly what you're looking for:

```typescript
import auth, { AuthModel } from './auth'
import user, { UserModel } from './user'
import { createTypedHooks, createStore, reducer as makeReducer } from 'easy-peasy'

import storage from 'redux-persist/lib/storage'
import { persistReducer, persistStore } from 'redux-persist'
import { Reducer as ReduxReducer } from 'redux'

interface StoreModel {  // these are my easy-peasy models
  auth: AuthModel
  user: UserModel
}

const models: StoreModel = {
  auth,
  user,
}

const store = createStore(models, {
  reducerEnhancer: (reduxReducer: ReduxReducer) =>
    makeReducer(persistReducer({ key: 'EasyPeasyStore', storage }, reduxReducer)),
})

```

**Comment by ctrlplusb** [comment]
Hey @chukcha-wtf 

I am glad you like the library. 😀

In regards to persisting specific models of your store - I don't think we can support this. I don't map the reducers in the traditional fashion that redux-persist would expect. I think the best case would be an all or nothing really for now.

I haven't had the need to do this myself as of yet, but there have been a few requests for this now. Once I have settled passed the v3 upgrade and fixing up all the docs I will make some time to see what options we have to support this type of persistence within Easy Peasy.

**Comment by chukcha-wtf** [comment]
Thanks @ctrlplusb 

Not a big deal really, I ended up with all or nothing approach as there's much information to store in SecureStore so can do it manually 😅
