### ISSUE TITLE
Does destructuring state have any performance implications?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#212]
Typed state looks like this.

```typescript
import { Action, action } from "easy-peasy";

export interface SettingsModel {
  activeTheme: string;
  setActiveTheme: Action<SettingsModel, string>;
}

const settings: SettingsModel = {
  activeTheme: "LightTheme",
  setActiveTheme: action((state, payload) => {
    state.activeTheme = payload;
  })
};

export default settings;
```

When accessing 👆 is there any gotchas to be aware of by destructuring...
```javascript
const { activeTheme } = useStoreState(state => state.settings);
```

...instead of straight variable assignment?
```javascript
const activeTheme = useStoreState(state => state.settings.activeTheme);
```

Thanks! 👍

**Comment by ctrlplusb** [comment]
I would say 95% of the time there wouldn't be any implication between the two. The only time it would matter would be if there was another property within your `model.settings` that updated often. Your component using the destructured `activeTheme` would rerender for any update to `settings`. I mean you would have to be talking about a significant number of updates happening in a short period to make this noticeable though. I wouldn't worry about it. Use what is convenient and refactor if you notice a bottleneck.

The main thing to avoid, like the docs state, is to avoid returning a new array/object instance from your state mapper.

e.g. 

```javascript
const { activeTheme } = useStoreState(state => {
  return { theme: state.settings.theme, user: state.session.user };
});
```

That is a red flag as you would return a new object instance which would break the === check.
