### ISSUE TITLE
Does redux-devtool work out of the box for react-native apps?

### ISSUE THREAD

**Issue by pavermakov** [ctrlplusb/easy-peasy#214]
I've created a new react-native project and added easy-peasy to it. However, I am not able to see my state and/or changes in the redux-devtool. Are there any extra steps I need to take?

**Comment by ctrlplusb** [comment]
Nope, but there is a recipe for this on the website 👍

https://easy-peasy.now.sh/docs/recipes/react-native-devtools.html

**Comment by pavermakov** [comment]
@ctrlplusb Thank you! And sorry for not reading the docs till the end&
