### ISSUE TITLE
Bug: Nested computed properties -- computedPropertyCreators[key] is not a function

### ISSUE THREAD

**Issue by seanstrom** [ctrlplusb/easy-peasy#217]
When using the `computed` api, I am unable to create computed properties in a nested model. I receive an error message saying `computedPropertyCreators[key] is not a function`. Here's a [codesandbox demo](https://codesandbox.io/embed/easy-peasy-30-example-4kgt0?fontsize=14) to illustrate.

**Comment by ctrlplusb** [comment]
Hey @seanstrom 

Thanks for raising this. I know exactly why this is. Bug fix to come soon. 👍

**Comment by seanstrom** [comment]
Thanks @ctrlplusb! Awesome work btw 👍

**Comment by ctrlplusb** [comment]
Sorted in v2.6.1 👍
