### ISSUE TITLE
Bug: Missing computed properties after nested state change

### ISSUE THREAD

**Issue by seanstrom** [ctrlplusb/easy-peasy#218]
When using the `computed` api, if I call an action from a nested model (during initialization), the computed properties from the state are missing. Here's a [codesandbox demo](https://codesandbox.io/embed/easy-peasy-26-computed-properties-missing--nested-action-fbbok?expanddevtools=1&fontsize=14&module=%2Fsrc%2Fcomponents%2Ftodos.js) to illustrate.

**Comment by ctrlplusb** [comment]
This should be fixed in 2.6.1 too 👍

**Comment by ctrlplusb** [comment]
Ah... Wait hmm

**Comment by ctrlplusb** [comment]
Fixed 👍

https://codesandbox.io/s/easy-peasy-26-computed-properties-missing--nested-action-lfsg5

**Comment by ctrlplusb** [comment]
Thanks for all these. I'll wait for all these silly bugs to be resolved over the next few days and then will do a patch release to warn of deprecation of the selector API.
