### ISSUE TITLE
Am I shooting myself in the foot trying to pull state and actions at once?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#220]
I have this in my `store` file.

```typescript
export const useStoreStateAndActions = branch => {
  const state = useStoreState(branch);
  const actions = useStoreActions(branch);
  return { ...state, ...actions };
};
```

I'm using it to grab a chunk of state and it's actions and put them in a namespace like this...
```typescript
  const app = {
    settings: useStoreStateAndActions(_ => _.settings),
  };
```

Then in my components I access them like...
```typescript
    onDarkModeSwitchPress: () => {
      if (app.settings.activeTheme === "LightTheme") {
        app.settings.setActiveTheme("SuperDarkTheme");
      } else {
        app.settings.setActiveTheme("LightTheme");
      }
    },
```

In trying to make my development experience more friendly I sometime shoot myself in the foot and it doesn't show up until later on.

What am I missing with this one?

Thanks! 👍

P.S. Loving the 2.6 API. Nice work!! 💪 👊

**Comment by ctrlplusb** [comment]
> P.S. Loving the 2.6 API. Nice work!! 💪 👊

Awesome love the feedback. ❤️

In regards to your question... like all things - it depends. This could very well be okay in your case. I can't pretend to know the smallest part of your application and its design. I would need to see a lot more code to be able to provide more critique.

Don't worry about optimising prematurely if you feel like your abstraction provides a lot of value. You can revisit it later if you like. Just make sure you understand the mechanisms by which easy peasy is optimised (same as react-redux) - immutable strict equality checking. 👍

**Comment by ctrlplusb** [comment]
One thing I am interested in...

```javascript
    onDarkModeSwitchPress: () => {
      if (app.settings.activeTheme === "LightTheme") {
        app.settings.setActiveTheme("SuperDarkTheme");
      } else {
        app.settings.setActiveTheme("LightTheme");
      }
    },
```

This looks like a class component property. Are you using functional and class components? Passing down the `app` state/actions slice via props?

**Comment by GollyJer** [comment]
No. It's all functional. 

But (and I think I'm the only one that does this) I like to put my props/handlers/components into helpful namespaces. Then, when viewing the `return()` it's faster to reason where things comes from.

Here's the whole component. 
(P.S. I'm moving `my.isDarkModeOn` to easy-peasy computed) 👍

![2019-06-27_10h39_36](https://user-images.githubusercontent.com/689204/60287960-0669f800-98c8-11e9-9547-bc97a62f60d0.png)

And the style for completeness.

![2019-06-27_10h40_21](https://user-images.githubusercontent.com/689204/60287984-1681d780-98c8-11e9-9b01-914e2c7033bb.png)

**Comment by GollyJer** [comment]
Looks like my little abstraction won't work for computed properties. 😟

The Settings model.

```typescript
import { Action, action, Computed, computed } from "easy-peasy";

export interface SettingsModel {
  activeTheme: string;
  setActiveTheme: Action<SettingsModel, string>;
  isDarkModeOn: Computed<SettingsModel, boolean>;
}

const settings: SettingsModel = {
  activeTheme: "LightTheme",
  setActiveTheme: action((state, payload) => {
    state.activeTheme = payload;
  }),
  isDarkModeOn: computed(_ => _.activeTheme === "SuperDarkTheme")
};

export { settings };
```

Accessing the model inside the SettingsScreen from the above.

```typescript
  const app = {
    settings: useStoreStateAndActions(_ => _.settings),
    isDarkModeOn: useStoreState(_ => _.settings.isDarkModeOn),
  };

  console.log(app.settings.isDarkModeOn); // undefined 😭
  console.log(app.isDarkModeOn); // true/false
```

**Comment by GollyJer** [comment]
OK. Just to overload this post a little more... 😜

My `computed` value `isDarkModeOn` is undefined when the app loads. It doesn't compute an initial value until `setActiveTheme` is called.

Am I doing something wrong?

**Comment by ctrlplusb** [comment]
Got a fix for the object spread and computed properties on the way. Could you please give me more info/example of the initial value issue you are experiencing with `setActiveTheme`?

**Comment by ctrlplusb** [comment]
Can you please try the newest version? 2.6.4

It should support the spreading operations now.

**Comment by GollyJer** [comment]
2.6.4 object spread works great. 🎉 Thanks! 👊

RE: isDarkModeOn 
I moved it from the component (in the screenshotted code above) to computed state (in the Settings Model code immediately above).

Once in the Settings Model, the first time I go to the SettingsScreen it should be `false` because the default is `activeTheme: "LightTheme",` but I am getting `undefined`.

Once I tap my Switch toggle, which calls setActiveTheme, then isDarkModeOn computes the correct value.

Hopefully that explains it. 😀

**Comment by ctrlplusb** [comment]
Is there any chance you could create a minimal codesandbox example?

**Comment by GollyJer** [comment]
Well... no matter what I do I can't recreate the bug in codesandbox. The same code works.
The only difference; my real program is React Native but I can't imagine there's a reason it would make a difference. 🤷‍♂️

**Comment by GollyJer** [comment]
Scratch that last post... it hit me that one other thing was different.
I'm exporting my model as a named export and not a default export. Strangely, that causes the bug.

You can see an example [here on codesandbox](https://codesandbox.io/s/easy-peasy-typescript-8r9cf?fontsize=14).
Toggle lines 17 & 18 on `todos.ts` and lines 1 & 2 on `index.ts` from the model folder.

**Comment by ctrlplusb** [comment]
What am I supposed to be seeing? :)

I used the named export and get a "Todo List - 0" in the app. Is this correct?

https://codesandbox.io/s/easy-peasy-typescript-o6egz

**Comment by GollyJer** [comment]
Yup. And if you add an item a `computed` count gets updated. Seems like it's working exactly as expected. I'll move on from this. Sorry to waste your time. There must be something on my end I'm not seeing.
