### ISSUE TITLE
Syntax checking rules

### ISSUE THREAD

**Issue by DrYSG** [ctrlplusb/easy-peasy#221]
I recently turned on syntax checking in VSCODE by adding a jsconfig.json (Yes, I am using JavaScript not typescript, but VSCODE parses and uses the TS type checking, expecially if you use JSDOC, so you get the same style of static type checking.

I don't know if I am missing a type definition file for easy-peasy, but as you can see I am getting errors about properties not being found on sate. and actiions (which I am not surprised about).

JSCONFIG.JSON follows:

![image](https://user-images.githubusercontent.com/2865368/60186184-46ae7500-97f9-11e9-9b6d-0a2e72a351a9.png)

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "checkJs": true,
        "jsx": "react"
    },
    "exclude": [
        "node_modules",
        "data",
        "docs",
        ".cache",
        "dist"
    ]
}
```

**Comment by ctrlplusb** [comment]
I am unfamiliar with JSDoc based typings, but off the cuff I would be surprised if it could match the experience of native TS code.

For typings to work with Easy Peasy you have to provide a full interface definition that describes your store, and then use this interface in your store creation. I have no idea how one might do that via JSDoc.

Sorry.
