### ISSUE TITLE
index signature of type number breaks typings

### ISSUE THREAD

**Issue by Ls777** [ctrlplusb/easy-peasy#223]
Defining a property of state as an object with an index signature of type number breaks the typings for that property. The type becomes `Compact<{} & Compact<{} & {}>>`

Worked fine in 2.1.6

Here's a [sandbox ](https://codesandbox.io/s/serene-archimedes-fdbyx)with the issue (look at helperNoGeneric.ts, the data property)

may be related to #117, #189

**Comment by ctrlplusb** [comment]
Can you try the latest version of easy peasy I just published?

**Comment by ctrlplusb** [comment]
Fix working https://codesandbox.io/s/strange-sara-dhkf9

👍

**Comment by Ls777** [comment]
Fantastic, thanks for the quick fix!
