### ISSUE TITLE
Including "keyof" of generic type within a generic model interface breaks typings

### ISSUE THREAD

**Issue by Ls777** [ctrlplusb/easy-peasy#224]
Typing a property of state as a keyof a generic breaks the typings for all state and actions. 

Worked fine in 2.1.6

Here's a [sandbox](https://codesandbox.io/s/serene-archimedes-fdbyx) with the issue (look at helper.ts, commenting out sortBy fixes the types)

**Comment by ctrlplusb** [comment]
I've fixed the keyof issue, but there is an outstanding issue with the actions not being typed within the `fetch` thunk. Needs more investigation still.

**Comment by ctrlplusb** [comment]
Phew thats a tricky one. The actions work via the store instance, but not the thunks. Hmmmm

**Comment by ctrlplusb** [comment]
Hey @Ls777 - this works in `easy-peasy@2.6.5`, but you need >= 3.5.1 of `typescript`.

**Comment by ctrlplusb** [comment]
Actually this issue may be bigger than I thought. We can't depend on this fix I believe. Doing more research.

**Comment by ctrlplusb** [comment]
Hey @Ls777 

I feel like the `keyof` issue may be an issue with Typescript. I forked your codesandbox and it is working without the `keyof` against the v3 alpha of easy peasy.

https://codesandbox.io/s/blissful-boyd-xnj2z

It would be good to do a minimal experiment without Easy Peasy involved to see if the keyof would still be an issue.

**Comment by ctrlplusb** [comment]
I'm going to create a "known issues" section under typescript docs. 👍

**Comment by ctrlplusb** [comment]
Added to v3 docs

**Comment by skoshy** [comment]
Is this still an issue with v4 and the latest version of Typescript?
