### ISSUE TITLE
How to pass state between branches?

### ISSUE THREAD

**Issue by luisroel91** [ctrlplusb/easy-peasy#225]
Let me start by saying that THIS is the way redux should be done. There is no more elegant, simple and efficient approach I have found when using Redux. I doubt I will use anything else for the foreseeable future when dealing with state management.

Anyways, lets say for example, if I have:
**model.js**

```javascript
const authModel = {
  isLoggedIn: false,

  login: action((state,payload) => {
   state.isLoggedin = true;
 }),
};

const userModel = {
 defaultPage: "#",

 setDefaultPage: action(
   (state, payload) => {
     if(state.isLoggedIn === true) {
        console.log(state.isLoggedIn) // prints undefined
        state.defaultPage = "/welcome";
      } else {
        console.log(state.isLoggedIn) // also prints undefined
        state.defaultPage = "/"
     }
   },
   { listenTo: [authModel.login]}
 )
};

const model = {
  auth: authModel,
  userData: userDataModel
};

export default model;
```

**store.js**

```javascript
import { createStore } from "easy-peasy";
import model from "./model";

export const store = createStore(model, {
  name: "AppStateStorage"
});
```

If I change the check in setDefaultPage to state.auth.isLoggedIn I get 

`TypeError: Cannot read property 'isLoggedIn' of undefined`

When console.logging state.isLoggedIn it is also undefined. However, I can see that firing login action did indeed change the state to true in Redux Dev tools.

**My gut feeling is that this happens because state isn't being passed to the listener, I've read docs. No info on how to config this so it happens.**

Is there a way to attach the isLoggedIn state to the payload before it gets to the listener?

Thank you!

**Comment by ctrlplusb** [comment]
Hey @luisroel91 

Thanks for the kind words.

If you need to access the entire store state within your listener you can create a thunk listener. I have refactored your code below.

```javascript
const authModel = {
  isLoggedIn: false,

  login: action((state,payload) => {
   state.isLoggedin = true;
 }),
};

const userModel = {
 defaultPage: "#",

 setDefaultPage: action((state, payload) => {
  state.defaultPage = payload;
 }),

 setDefaultPage: thunk(
   (actions, payload, { getStoreState }) => {
     if(getStoreState().auth.isLoggedIn) {
        actions.setDefaultPage("/welcome");
      } else {
        actions.setDefaultPage("/");
     }
   },
   { listenTo: [authModel.login]}
 )
};

const model = {
  auth: authModel,
  userData: userDataModel
};

export default model;
```

Hope that helps. 👍

**Comment by luisroel91** [comment]
Thank you! That worked
