### ISSUE TITLE
[thunk] state returns from getState is mutable and will change the model state value

### ISSUE THREAD

**Issue by stevenao** [ctrlplusb/easy-peasy#226]
I have a strong feeling that is not intended as there are no reducers internally created for `thunk`'s. `action`'s should be the place where state mutation should happen.

**Comment by luisroel91** [comment]
Just tested this. Can confirm.

easy-peasy 2.6
redux 4.0.1
react 16.8.6

**Comment by ctrlplusb** [comment]
Yeah, don't do that. 😛

Sorry, yeah, this is inline with experiences of Redux and Redux Thunk. You could equally mutate Redux state, but they recommend against this.

I don't think there is any dependable manner for me to prevent you from doing this. I will take serious consideration, in that you are raising this issue, and will look to update the docs to make this warning/anti-pattern a bit more explicit.

**Comment by ctrlplusb** [comment]
Add a note about this in the v3 docs.
