### ISSUE TITLE
What's the idiomatic way to reuse easy-peasy code? 

### ISSUE THREAD

**Issue by patrickjm** [ctrlplusb/easy-peasy#23]
For example, in react-redux, containers can be reused. One container can be wrapped around as many presentational components as needed.

I understand I could make my own hooks that call easy-peasy's, but that still puts my Redux logic right next to my rendering. What if I have a component that I want to behave differently in three places? Do I still need a HOC for this to pass my own hooks into the presentational component?

**Comment by ctrlplusb** [comment]
Hey @patrickjm 

I'm not sure I am following you here. You should still be able to maintain container/presentational distinctions via hooks. Can you possibly give us an example of the problem you are facing?
