### ISSUE TITLE
Calculated field does not update immediately when value updates

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#230]
I tested a model with an array of items, a calculated field for the item-count, and a thunk that fetches items. The flow is like this:

- The initial value of `items` contains 3 items
- Therefore the initial value of the calculated `count` = 3
- A `getItems()` _thunk_ fetches 200 additional items, then...
- An `appendItems()` action appends these to `items`

When the items are appended, the `<List>` component re-renders, as expected. 
However the `count` still reports only 3 items.

The `<List>` immediately re-renders _again_; with the correct count this time.
Here is the output of `console.log({ count, items })` for each render...

```
List.js { count: 3, items: Array(3) }
List.js { count: 3, items: Array(203) }
List.js { count: 203, items: Array(203) }
```

This is not a serious problem since it re-renders correctly a few ms later. However the calculated value is incorrect in the first re-render, and there should only be a single re-render.

**Comment by ctrlplusb** [comment]
Hmmm, thunks are asynchronous. If you are dispatching multiple actions then I would expect there may be some delay between renders.

Are you dispatching a single action from your think with the resolved list?

**Comment by allpro** [comment]
A single thunk which calls a single action on completion. Here is the relevant model code...

```javascript
const listModel = {
    items: ['Create store', 'Wrap application', 'Use store'],
    count: computed(s => s.items.length),

    getItems: thunk((actions, config, { injections }) => (
        injections.api.getItems(config)
        .then(actions.setItems)
    )),
    setItems: action((state, items) => {
        state.items = state.items.concat(items)
    }),
}
```

**Comment by ctrlplusb** [comment]
I am not seeing the same behaviour at all, even in different component trees.

See [this sandbox example](https://codesandbox.io/s/easy-peasy-starter-p4bxu) where I "fetch" 2000 items even.

**Comment by allpro** [comment]
This code is on GitHub so you can see it unaltered. It's a simple test-app so no cruft to complicate things. If need be you can pull it and give it a try.

- https://github.com/allpro/easy-peasy-tester/blob/master/src/data/store/listModel.js
- https://github.com/allpro/easy-peasy-tester/blob/master/src/components/List/List.js

The only related code I skipped in my previous comment were _listeners_ that set an isFetching flag. I didn't think that would have any effect...

```javascript
    setIsFetching: action(
        state => { state.isFetching = true },
        { listenTo: '@thunk.list.getItems(started)' }
    ),
    setNotFetching: action(
        state => { state.isFetching = false },
        { listenTo: [
            '@thunk.list.getItems(completed)',
            '@thunk.list.getItems(failed)'
        ]}
    )
```

**Comment by allpro** [comment]
> I am not seeing the same behaviour at all, even in different component trees.
> 
> See [this sandbox example](https://codesandbox.io/s/easy-peasy-starter-p4bxu) where I "fetch" 2000 items even.

**ACTUALLY your sandbox shows the same resulte.** You just aren't noticing the 2nd re-render. I added some console.log output to your sample...

- https://codesandbox.io/embed/easy-peasy-starter-ldkg3

This is what the console shows for each of the 3 renders. Note that in the 2nd render the 'count' is out of sync with the number of items.

```javascript
Object {items: Array[0], count: 0}
Object {items: Array[2000], count: 0}
Object {items: Array[2000], count: 2000}
```

**Comment by ctrlplusb** [comment]
Thanks for raising this 👍

**Comment by ctrlplusb** [comment]
Fixed in `easy-peasy@3.0.0-alpha.4`  👍

https://codesandbox.io/s/easy-peasy-starter-pgxqz

**Comment by ctrlplusb** [comment]
Nice side effect of this is that we no longer need to declare dependencies on the useStoreState hook.

**Comment by allpro** [comment]
> Nice side effect of this is that we no longer need to declare dependencies on the useStoreState hook.

That's cool. Simpler and simpler.
