### ISSUE TITLE
Incorrect type signature for reducerEnhancer

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#231]
I'm seeing a type-error that seems inaccurate. I _think_ `config.reducerEnhancer` is being typed as a 'Reducer', but actually its a function that _returns_ a Reducer. I'm using **Easy-Peasy v2.6.5**. 

I'm NOT using Typescript and this is just an editor warning so it doesn't affect functionality. 
The warning I get is:

> Argument type {name: string, reducerEnhancer: (function(*): function(*, *=): *)} is not assignable to parameter type EasyPeasyConfig | undefined
Type function(*, *=): * is not assignable to type Reducer

Below is the storeConfig I'm passing, including the reducerEnhander function.

```javascript
const reducerEnhancer = (epRootReducer) => (
    (prevState, action) => {
        let nextState = prevState
        nextState = rootReducer(nextState, action)
        nextState = epRootReducer(nextState, action)
        return nextState
    }
)

const store = createStore(model, {
    name: 'Test Store',
    reducerEnhancer
})
```

**Comment by ctrlplusb** [comment]
Hmmm, I think this is just an invalid report by VSCode. 👍

The type signature looks correct:

```typescript
reducerEnhancer?: (reducer: Reducer<any, any>) => Reducer<any, any>;
```

**Comment by allpro** [comment]
FYI, reported by IntelliJ IDEA, so probably Webstorm too.
