### ISSUE TITLE
Suggest a thunk "settled" state/action

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#233]
**I suggest firing a "settled" state for thunks.** This would dispatch after _both_ "success" and "failed" states. It's equivalent to `promise.finally()` or `promise.settled()`. It would make it easier to _listen_ for thunk 'completion'. For example, if an "isFetching" flag is set then this must be _unset_ when the promise is 'settled', one way or the other.

**Example**
```javascript
setIsFetching: action(
    state => { state.isFetching = true },
    { listenTo: '@thunk.list.getItems(started)' }
),

// Current Syntax
setNotFetching: action(
    state => { state.isFetching = false },
    { listenTo: [
        '@thunk.list.getItems(completed)',
        '@thunk.list.getItems(failed)'
    ]}
),

// Easier Syntax with 'settled' state
setNotFetching: action(
    state => { state.isFetching = false },
    { listenTo: '@thunk.list.getItems(settled)' }
),
```

This could be added to `actionCreator()` in `create-store-internals.js`, as below.
If you like this addition then I can create a PR, but it's a simple update.

```javascript
// Thunk Action Creator
    const actionCreator = payload =>
        tick()
        ...
        .then(result => {
            references.dispatch({ type: `${name}(completed)`, payload });
            references.dispatch({ type: `${name}(settled)`, payload });
            return result;
        })
        .catch(err => {
            const error = { payload: errorToPayload(err), error: true };
            references.dispatch({ type: `${name}(failed)`, ...error });
            references.dispatch({ type: `${name}(settled)`, ...error });
            throw err;
        });
```

**NOTE: The _current_ error-action is incorrect (see below).** The 'errorToPayload' is in the `error` key. However, in an Flux-Standard-Action `error` should be a boolean, so: `error: true`. The error itself should be the `payload`. **The example _above_ has corrected syntax.**

**Current, Incorrect Action**
```javascript
    .catch(err => {
        references.dispatch({
            type: `${name}(failed)`,
            payload,
            error: errorToPayload(err),
        });
        throw err;
    });
```

**Comment by ctrlplusb** [comment]
This is an interesting proposal @allpro! Thanks for taking the time to provide such a detailed description.

I am going to let this sit with me a bit and will consider it. 👍

**Comment by allpro** [comment]
The changes to `listenTo` syntax means this suggestion is now for a `thunkSettledName()` helper, like...
```
thunkSettledName(actions.user.requested)
```

This could return an array containing _both_ settled states, like:

````javascript
thunkSettledName(actions.user.requested) === [
    `@thunk.user.requested(complete)',
    `@thunk.user.requested(failed)'
]
````

In this scenario there would NOT be an extra `@thunk.user.requested(settled)` action dispatched, which is cleaner.

The only issue is whether the current code can handle an array _inside_ an arrays, ie:

````javascript
listenTo( actions => [ thunkSettledName(actions.user.requested), actions.user.set ] )
// which would translate to:
listenTo( actions => [ [ thunkCompleteName(actions.user.requested), thunkFailedName(actions.user.requested) ], actions.user.set ] )
````

**Comment by ctrlplusb** [comment]
Closing in favour of #247
