### ISSUE TITLE
Proper way to debounce an axios request inside of a thunk

### ISSUE THREAD

**Issue by jsheffers** [ctrlplusb/easy-peasy#234]
I'm using a thunk to fetch some data from a public API using Axios.  If I try to add the debounce function inside of the thunk it's not actually triggering the Axios request.   Any idea how this should be handled?  This code is using the debounce function from lodash.

```javascript 
fetchTeams: thunk((actions, query) => {
  debounce(query => {
    axios(
      'https://example.com/teams?t=${query}'
    ).then(response => {
      console.log(response);
    });
  }, 500);
}),
```

If I remove the debounce it works as expected, but it's firing for every character typed (onChange handler not shown).  I tried adding the debounce function to the onchange handler, but that didn't work either.  Hopefully this is enough info.

**Comment by silicakes** [comment]
Not sure how your `debounce` function is implemented, but in most cases, it returns a new function.

Assuming that: you never invoke it.
That in mind, I'd go with something like:

```
const debouncedFetchTeams = debounce(query => {
    axios(
      'https://example.com/teams?t=${query}'
    ).then(response => {
      console.log(response);
    });
  }, 500);

fetchTeams: thunk((actions, query) => {
  deboumcedFetchTeams(query);
})
```

**Comment by jsheffers** [comment]
Yes, that did it!  Thanks for the help.   I was making updates to the store as well so I had to pass actions into the `debouncedFethTeams` function, but it worked.

**Comment by ddikodroid** [comment]
> Yes, that did it! Thanks for the help. I was making updates to the store as well so I had to pass actions into the `debouncedFethTeams` function, but it worked.

did you use `debounce` from lodash?
