### ISSUE TITLE
usage with redux-observable

### ISSUE THREAD

**Issue by razagill** [ctrlplusb/easy-peasy#235]
This is more of a question than an issue, has anyone got any idea how to go about integrating `easy-peasy` with `redux-observable`?

**Comment by silicakes** [comment]
Why would you want to do something like that?

**Comment by ctrlplusb** [comment]
I haven't used redux-observable, but from what I remember it would be a bad fit with easy-peasy. It's kind of it's own abstraction of redux.  If you prefer the pure observable land then definitely go with redux-observable. Easy Peasy doesn't offer much in terms of reactivity - only the listenTo configurations on actions/thunks.

**Comment by razagill** [comment]
@silicakes Oh I don't know, probably just like just randomly integrating libraries ;) (jk)

@ctrlplusb Not sure if that is correct though. `redux-observable` is like a middleware which can be applied as an enhancer on your store, same as `redux-saga` to do side effects. It doesn't do any state management whatsoever or provide you with any sort of action creators/reducers etc, so I don't get why it would be a bad fit? Could you please explain a little bit more?
This is a great library and I think if `redux-saga` can work with it then surely `redux-observable` shouldn't be a problem also.

**Comment by ctrlplusb** [comment]
@razagill could you provide an example of what features of redux-observable you would like to integrate into easy-peasy.

I was just looking at one their examples:

```javascript
const INCREMENT = 'INCREMENT';
const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD';

const increment = () => ({ type: INCREMENT });
const incrementIfOdd = () => ({ type: INCREMENT_IF_ODD });

const incrementIfOddEpic = (action$, state$) => action$.pipe(
  ofType(INCREMENT_IF_ODD),
  filter(() => state$.value.counter % 2 === 1),
  map(() => increment())
);

// later...
dispatch(incrementIfOdd());
```

Are you looking to use redux-observable to manage action dispatch workflows?

**Comment by razagill** [comment]
> @razagill could you provide an example of what features of redux-observable you would like to integrate into easy-peasy.

I think there might have been a slight miscommunicaiton, I was actually looking to integrate as in *use* the two libraries together, not add any certain feature into `easy-peasy` from `redux-observable`. Sorry if that caused confusion.

Essentially, I would like to use `redux-observable` for all side effects like doing network calls, writing to disk etc and use `easy-peasy` to manage the state, dispatch actions and so on.

The problem for me appeared while I was trying to add `redux-observable` to `createStore` from `easy-peasy`. If you look at [this doc](https://redux-observable.js.org/docs/basics/SettingUpTheMiddleware.html) where we are applying the middleware and have to add `createEpicMiddleware()` as an enhancer on the store and later on run `epicMiddleware.run(rootEpic);` - this is the part which doesn't work with `easy-peasy` at the moment.

**Comment by ctrlplusb** [comment]
Looking at that I can't see why it wouldn't work at this based integration layer. Is there any chance you could create a codesandbox of this?

**Comment by razagill** [comment]
@ctrlplusb I would do that and message you back in a few days.

**Comment by razagill** [comment]
@ctrlplusb looks like I have some other issue in my code base, the integration actually works fine when I did that in codesandbox. Thanks!

Here is an example if anybody else stumbles upon it https://codesandbox.io/s/easy-peasy-example-d1ze3
