### ISSUE TITLE
thunkStartName doesn't work in action listenTo

### ISSUE THREAD

**Issue by jamaljsr** [ctrlplusb/easy-peasy#237]
First off, this is such a great library! Sooo developer friendly. I'm starting a new project and was on the hunt for something that simplifies redux's verbosity. After my playing with redux-starter-kit, I stumbled upon this little gem. I must say that you NAILED IT with the API! So thank you for making my future life easier.

Ok, now onto the issue that I'm running into. I am trying to add a loading state for my data fetching thunk. So I created a `LoadingModel` which has an action with `listenTo` set to the thunk from another model. I would like to listen to the `(started)` and `(completed)` actions of the thunk but my loading actions are not called when using `thunkStartName`, `thunkCompleteName`, etc. After a bit of debugging, I realized that these utility functions do not return the correct action names when they are used before `createStore` is executed. For example, `thunkStartName` returns `undefined(started)` instead of `@thunk.user.requested(started)`.

I have been able to work around this problem by hard-coding the string representation of the action name manually. i.e. `{ listenTo: '@thunk.user.requested(started)' }`. Obviously, these magic strings are not ideal long-term.

I created a demo at https://codesandbox.io/embed/peaceful-kilby-zpguy to show the problem in v2.6.5. I am running v3.0.0-alpha.2 locally, but the problem is still present.

If you have any better suggestions for dealing with displaying loaders when executing thunks, I am all ears.

**Comment by ctrlplusb** [comment]
Hi @jamaljsr 

Thanks for the really kind words. ❤️

This is definitely a bug - I agree with you in regards to the magic strings.

I'll get this queued up for a fix.

👍

**Comment by jamaljsr** [comment]
Hi @ctrlplusb 

As a followup question that may be slightly unrelated, how do I access the error object when listening to `(failed)` thunk events? I can see that the error is dispatched aside the payload in https://github.com/ctrlplusb/easy-peasy/blob/master/src/create-store-internals.js#L159 but it's not clear to me how it can be accessed from the listener action.

```js
  onFailed: action(
    (state, payload) => {
      console.log(payload); // undefined
    },
    {
      listenTo: "@thunk.user.requested(failed)"
    }
  )
```

Updated demo at https://codesandbox.io/s/peaceful-kilby-zpguy

**Comment by ctrlplusb** [comment]
Hey @jamaljsr - I have changed the way that you define listenTo, a breaking change unfortunately, but luckily we have v3 around the corner.

Please check #216 for notes on how to use the new version of the `listenTo` config. Using the `thunkStartName` and other helpers _should_ work when wrapping the resolved functions.

e.g. 

```javascript
  onFailed: action(
    (state, payload) => {
      console.log(payload); // undefined
    },
    {
      listenTo: (actions) => thunkFailedName(actions.user.requested)
    }
  )
```

**Comment by ctrlplusb** [comment]
In terms of the error object, that sounds like a bug. I will investigate this too.

**Comment by jamaljsr** [comment]
Wow, thanks for the quick update. I will give v3 a try tomorrow and let you know how it goes.

**Comment by jamaljsr** [comment]
Hey @ctrlplusb, thanks for the latest updates in v3. This does indeed fix the original `thunkStartName` problem. You also now made it possible to place the listener actions on the same model which is definitely better than separate models for loaders. I have a working demo testing a few of the varying listening methods at https://codesandbox.io/embed/peaceful-kilby-zpguy.

Unfortunately, this functionality introduced some new issues when using typescript. There are a couple type mismatches which are causing compilation errors in my app. 

Using `thunkStartName` with local model actions passed to `listenTo`:

![image](https://user-images.githubusercontent.com/1356600/60735435-4f055f00-9f21-11e9-8af8-ac1d1a95abc1.png)

Using `storeActions` from a different model:

![image](https://user-images.githubusercontent.com/1356600/60735486-8d9b1980-9f21-11e9-9f75-32408cff7033.png)

The full typescript demo is available at https://codesandbox.io/embed/sleepy-sun-7jyvq

**Comment by ctrlplusb** [comment]
Hey @jamaljsr - I have fixed the typescript issues.

I published a new alpha.

You were also missing a `StoreModel`, and needed to pass it to the action which was listening to an action across the other part of the model (i.e. the `onStartedViaRemoteActions` action).

https://codesandbox.io/s/silly-robinson-mlzdb

I still need to investigate the error payload case.

**Comment by jamaljsr** [comment]
Awesome! I just tested. This fixes all of the typing issues. Thanks for getting these issues resolved so quickly. 👍

**Comment by ctrlplusb** [comment]
Closing in favour of #247
