### ISSUE TITLE
Non primitive model initial value (instance of class) converted to plain object

### ISSUE THREAD

**Issue by strobox** [ctrlplusb/easy-peasy#238]
This happens for all non javascript classes.
https://codesandbox.io/s/easy-peasyissue238-30xnw

**Comment by strobox** [comment]
When I use *initialState* config all works as expected: https://codesandbox.io/s/easy-peasyissue238-j42ws

**Comment by ctrlplusb** [comment]
Hey @strobox - yep, sorry, this needs to be more explicitly stated within the docs. As we use `redux` under the hood we have the same restrictions - i.e. only JSON serialisable data can be stored.

Therefore `Map`, `Set`, `Date`, `Regex`, classes etc are all not supported.

**Comment by strobox** [comment]
As I've researched in redux FAQ's that technically it is no difference what to store, and that restrictions is only highly recommended things (for persistence and rehydration): https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state

**Comment by strobox** [comment]
On my mind it is have sense to align behavior of state instantiation for different cases:
So, no matter if we use: 
```js
import { LocalDate } from "js-joda";

const store = createStore(model, {
  initialState: {
    todos: {
      lastDoneDate: LocalDate.now().plusDays(10)
    }
  }
});
```
or providing initial value in model definition object:
```js
const todosModel: TodosModel = {
  lastDoneDate: LocalDate.now().plusDays(10),
};
```
initial value in instantiated store should be same.
# Now we got:
For 1st case we get :
```js
lastDoneDate instanceof LocalDate // true 
```
And for second:
```js
lastDoneDate instanceof LocalDate // false 
```

**Comment by ctrlplusb** [comment]
I suspect this is because we use `immer`. I was considering adding an option that would allow you to opt of immer for a store instance, but then you would be force to returning immutable versions of your state.

i.e.

```javascript
addTodo: action((state, payload) => {
  return { ...state, items: [...state.items, payload] };
})
```

vs the immer way:

```javascript
addTodo: action((state, payload) => {
  state.items.push(payload);
})
```

This would likely be the tradeoff you would have to make if we were to support non-primitive types.

**Comment by strobox** [comment]
I was trying to experiment with *immer* and fount works perfectly with non-primitive values (event no matter mutable this value or not) - https://codesandbox.io/s/immer-with-mutable-and-immutable-jc5ge

**Comment by ctrlplusb** [comment]
Hmm, interesting. Thanks for the example case. I am snowed under right now with other Easy Peasy work but I am happy to queue this up for investigation.

**Comment by ctrlplusb** [comment]
@strobox I actually have a fix for this! 🎉

Unfortunately class types as model properties won't work correctly via our Typescript definitions until either https://github.com/Microsoft/TypeScript/issues/29063 or https://github.com/microsoft/TypeScript/issues/12936 are resolved.

Do you use Typescript?

**Comment by ctrlplusb** [comment]
I've publish this support.

```
npm install easy-peasy@3.0.0-alpha.8
```

**Comment by strobox** [comment]
Yes, I used typescript. And grate, it works now :) Without may crazy workaround used before (wrap problematic value with single item array) :
```ts
export type BackeventsModel = {
  dayDateInArr: LocalDate[],
  selectDay: Action<BackeventsModel,LocalDate>
};

const model : BackeventsModel = {
  dayDateInArr: [now],
  selectDay: action((state,payload) => {
    state.dayDateInArr = [payload];
  }),
};
// elsewhere:
  const {dayDateInArr} = useStoreState<StoreModels>( ({backevents:{dayDateInArr}}) => ({dayDateInArr}));
  const {selectDay} = useStoreActions<StoreModels>( ({backevents:{selectDay}}) => ({selectDay}));
  const focusedDate = dayDateInArr[0];//LocalDate.parse(dayDateInArr.toString());

```
