### ISSUE TITLE
Why is selector() deprecated?

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#240]
The documentation shows that _both_ `select()` and `selector()` are now deprecated, and have been purged from the tutorial.

**Is there another pattern/helper to replace the need for a selector?** For example, if I want to pass an ID and get back a single item from an array; _plus_ related data. Obviously I can grab all the raw data and 'select' the parts I want, but that requires too much knowledge in my 'dumb' components.  I would end up writing an _external_ 'selector' function for this, which I do not want to do.

Whatever the answer to this is, I suggest adding to the documentation; maybe in the tutorial. I read every page _again_ to see if I missed anything!

**Comment by ctrlplusb** [comment]
The selector API was overly complex and the fact that you had to execute them even when you didn't require runtime args made them awkward to use.  The new computed API solves these issues whilst also being even more performant that the selector.

You can return a function from your computed property to do something similar.

```javascript
const todos = {
  items: [{ id: 1, text: 'answer questions' }],
  // Note how we are returning a function instead of state
  //                          👇
  todoById: computed(state => id => state.items.find(todo => todo.id === id)) 
}
```

You can then use it similar to a selector.

```javascript
function Todo({ id }) {
  //                                      execute the todo 👇
  const todo = useStoreState(state => state.todos.todoById(id));
  return todo ? <div>{todo.text}</div> : null;
}
```

You can even support memoisation of your functions by utilising the `memo` helper.

```javascript
import { memo } from 'easy-peasy';

const todos = {
  items: [{ id: 1, text: 'answer questions' }],
  // Wrap your function with memo and set the cache size
  //                          👇
  todoById: computed(state => memo(
    id => state.items.find(todo => todo.id === id),
    100 // 👈 cache size  
  ))
}
```

**Comment by allpro** [comment]
Thanks for the detailed response. I wonder if a simple 'select' _wrapper_ around computed would make it simpler and _more intuitive; perhaps with auto memoization as well? For example...

````javascript
  todoById: computed(state => memo(
    (id, key) => state.items.find(todo => todo.id === id)[key],
    100 // 👈 cache size  
  ))
// Can also be written as...
  todoById: select(
    (state, id, key) => state.items.find(todo => todo.id === id)[key],
    100 // 👈 cache size  
  ))
```

**Comment by ctrlplusb** [comment]
Added to v3 docs
