### ISSUE TITLE
Define a meta object on an action

### ISSUE THREAD

**Issue by coldi** [ctrlplusb/easy-peasy#241]
I have a middleware that looks for actions that have a special property. In classic Redux I normally added a `meta` key to the action object, which holds information like this, e.g. `meta.canUndo` or `meta.batched`.
I thought maybe the second parameter of the `action()` helper could be used for something like this, but as of now it seems to only support the `listenTo` option.

Is there a way to have static meta information on an action right now? Or is it considerable to add this in the future?

Btw: With or without a meta object - easy-peasy is an amazing library! Thank you! :)

**Comment by ctrlplusb** [comment]
Hey @coldi 

Could you provide an example of where, why, and how you would use this meta information?

**Comment by coldi** [comment]
Yeah, sure.

I try to explain it a little bit more clearer: Let's say I have a custom persistenceMiddleware:
```js
const persistenceMiddleware = (store) => (next) => (action) => {
  if (typeof action !== 'object') return next(action);
  
  // instead of checking for a specific action type,
  // the action itself can have a meta prop that marks it as a "trigger"
  // for the persistence middleware
  if (action.meta && action.meta.persist) {
    // persist state to local storage or something here ...
  }
}
```

This is the simplest use case I can think of. I know that other Redux middlewares have a similar concept.
You basically check if there is a special property set on an action and then let some middleware do something. Otherwise the action is ignored by the middleware.
Putting these properties in `meta` (instead of `payload`) is a common practice AFAIK, since it's completely unrelated to state transitions.

I think this use case could be handled in the `config` parameter of the `action(fn, config)` helper. And through that it could be passed to the actual action that gets created.
 
I can create a sandbox if it helps, but I think this is more a conceptual thing.

**Comment by ctrlplusb** [comment]
@coldi thanks for the explanation. Definitely helps. 👍

Ok, and this meta data, it would be bound against the action when it is defined right? Instead of when it is dispatched. I assume this is typically useful as a type of configuration of actions, rather than runtime provided behaviour overrides.

**Comment by coldi** [comment]
@ctrlplusb Yes, these are all correct assumptions.
I could think of edge cases where someone may wants to set the meta data at runtime, but normally its bound to the action on setup.

**Comment by allpro** [comment]
I use metadata regularly for thunks. This allows the 'payload' to be the post data. Any additional params, like a parent-item-it, I pass in a meta object. So many API's have a signature like:
````javascript
const postFormData = (payload, meta) => (
    const postPath = `${apiBase}/property/${meta.propertyId}/licenses/${payload.id}`
    ...
)
````

I can pass an object as payload that contains _both_ the meta and post data, but this makes API signatures inconsistent so it's not my first preference.

**Comment by allpro** [comment]
My feature request is for a meta param so that EP matches the capabilities of a normal 'dispatch' of a Flux-Standard-Action (FSA). Otherwise EP has a deficiency in this regard, because there are real-world uses for meta data.

This means a change to actions/thunk signatures, listener params, and action generation; like so...

````javascript
// Action params
action(state, payload, meta)
thunk(actions, payload, meta)

// Dispatch action - FSA format
dispatch({
    type: '...',       // Required
    payload: { ... },  // If exists
    meta: { ... }      // If exists
})

// Sample thunk listener, with all possible params
actionListenTo(state, target - {
    type: '...',
    name: '...',
    payload: { ... },
    meta: { ... },
    response: { ... },
    error: true
})
````

I'm mentioning this now so can be considered for the listener signature #247

**Comment by ctrlplusb** [comment]
I'm not feeling entirely convinced by adding a `meta` parameter to action/thunk dispatching - can't this data be encapsulated within the payload? I feel like a consumer could write wrapping utilities that added meta data to payloads, and maintain their own "schema" around payloads that included meta data.

The design time meta data include still rings as being useful to me though. I can appreciate the value in this, but then again, if I were to add this as a supported feature then perhaps we should allow a mechanism by which to override/extend meta data at runtime.

Perhaps the safest/easiest route to go for is to include a test implementation allowing for meta data definition at design time. We could then monitor this and look to extend the feature into runtime if we felt there was sufficient value in doing so.

**Comment by allpro** [comment]
> can't this data be encapsulated within the payload

The Flux-Standard-Action (FSA) includes a `meta` key for anything that's not part of "the payload". In the **reducer pattern below**, the data returned by the API does not include a `category_id`, but both the API and reducer need it. The `action` argument contains `{ type, payload, meta }`, but type isn't needed here

````javascript
const updateCollectionByCategoryId = (state, { payload, meta }) => {
    const id = meta.category_id
    let newState = state
    newState = set(newState, `category.${id}`, payload)
    newState = set(newState, `state.categoryDataLoaded.${id}`, true)
    return newState
}
````

To keep intermediate methods _dumb_, meta-data should be passed in a standard/generic way, just as payloads are. **_Without_ a separate key/param for this, payloads need a nested, non-standard structures, like this:** 

````javascript
action = {
    type: "saveName",
    payload = {
        content: { first: "Sean", last" "Matheson" },
        meta: { companyId: 1234 }
    }
}
````

However the FSA pattern is simpler and more standard. No longer need a custom payload design.

````javascript
action = {
    type: "saveName",
    payload = { first: "Sean", last" "Matheson" },
    meta: { companyId: 1234 }
}
````

Occasionally an API  and/or reducer requires meta-data. A passed 'action' contains _both_ payload and meta. If 'payload' becomes it's own argument, it's natural for meta to be the next arg. This maintains the flexibility and simplicity of the FSA pattern `{ type, payload, meta }`. That's my pitch!

**Comment by psachs21** [comment]
I'm personally interested in this feature as I pass feature flag information through the meta and populate that meta with a custom middleware tied to my feature flag implementation. It doesn't make sense to place that in the payload. @ctrlplusb Any idea when the PR will be merged?

**Comment by ctrlplusb** [comment]
Sorry just not enough interest in this. I worry about the added complexity involved and personally have yet to need it.

**Comment by allpro** [comment]
I worked around this by _mixing_ data and metadata keys in thunk payloads. I use dedicated thunks and requests handlers for each endpoint so can customize the code to separate metadata from real data at each level. It would be _nice_ to have a standard easy to receive metadata - like as `helpers.meta` - but I've been able to work around it.

For those wanting a _generic way_ to handle metadata, the `payload` param in thunks could replicate the standard action structure, like...

```
thunk((actions, action) => {
  const { payload, meta } = action;
  ...
})
```

This could be an _optional_ pattern in common code, accepting a _normal_ payload when metadata is not needed. This sample helper will never change the 'payload' value and _always_ returns a 'meta' object for consistency...

```
const parseAction = action => ({
  payload: (action || {}).payload || action,
  meta: (action || {}).meta || {},
});

function handler(action) {
  const { payload, meta } = parseAction(action);
  ...
}
```

A couple of ideas for anyone wanting the same metadata option as provided by the FSA action shape.

**Comment by DanielPe05** [comment]
I know this is pretty old but I came across it recently. Ideally, you are able to declare this "meta" data at design time, for example, say you have a middleware that will do some polling on a given thunk, it would be very nice to declare `thunk(actions, payload, meta: { shouldPoll: true, interval: 300 })` and then have the middleware look for this to decide whether it should poll that thunk or not. The approach for using payload doesn't really work as well since you'd have to pass `{ shouldPoll: true, interval: 300 }` on every call to your thunk from any place where said thunk is invoked. Has anybody over the years come across a more elegant solution to this issue?
