### ISSUE TITLE
Suggest @@thunk and @@action for listeners

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#243]
Most of EP automatically scopes state to the 'current slice'. For example, the `state` and `actions` object passed in to methods are **scoped to the current slice**. However, when adding listeners the _full state-path_ must be specified, like `@thunk.user.preferences.getSomething`. This allows access to the entire store, but doesn't allow for scoping.

**I suggest a special prefix like `@@thunk` or `&thunk`**, (with similar for `@@action`). This syntax would map to thunks/actions _in the same scope/slice_, so these would be equivalent: 

```javascript
@@thunk.getSomething === @thunk.user.preferences.getSomething
```

The difference is that with the scoped syntax, I don't need to know the state-tree structure, because `getSomething()` is in the same slice.

I prefer scoped references because it simplifies re-organizing state as it grows in complexity. Since _most_ listeners are likely for actions in the same slice, this minimizes the number of code changes required when a slice is _moved_ in the state tree.

**Comment by ctrlplusb** [comment]
Have you taken a look at the new `listenTo` API (breaking change) within v3. It solves exactly this issue.

See #216 and #237 for more information.

**Comment by allpro** [comment]
Yup, that handles it - closing.
````javascript
listenTo: (actions, storeActions) => storeActions.todos.added
````
