### ISSUE TITLE
Suggest v3 listenTo thunk syntax alternative

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#244]
I like the new syntax for listeners in v3. However, helpers like `thunkCompleteName()` make the code more verbose and less readable. Plus this adds more imports and helpers to learn.

**I think it would be _optimal_ if the status-names were available as simple properties on the thunk, like...**

````javascript
listenTo: (actions) => thunkCompleteName(actions.user.requested)
// Can also be written as...
listenTo: (actions) => actions.user.requested._complete
````

The second version is much more concise and readable imo, and no 'helper' is needed. Adding this _alternate syntax_ should be simple because **thunk-functions already have properties added**. This sample code includes a 'settled' status as suggested in issue #233 ...

````javascript
// create-store-internals.js
  ...
  else if (value[thunkSymbol]) {
    const name = `@thunk.${path.join('.')}`;
    value[actionNameSymbol] = name;
    // Add status-names as properties
    value._started = thunkStartedName(value);
    value._complete = thunkCompleteName(value);
    value._failed = thunkFailedName(value);
    value._settled = [ thunkCompleteName(value), thunkFailedName(value) ];
````

_(Probably would want a `thunkSettledName()` helper, but this illustrates the point.)_

**Comment by ctrlplusb** [comment]
I agree, and have been thinking about this too recently. I've also trying to consider it in the context of Typescript. Another concern I have is how we surface error payloads to thunk failed listeners - I think this needs a closer look too.

**Comment by allpro** [comment]
> Another concern I have is how we surface error payloads to thunk failed listeners

It makes sense to pass a flux-standard-action (FSA) for the error. This conforms to norms. 

This param could be followed by all params passed into the original action. This would be the payload plus any others args.

This provides the listener with everything it might need. It could a use common handler for the FSA because it has a predictable shape. It can also perform custom logic because it had all the input data too, so it can read an ID or other relevant value.

*A successful action would have the exact same signature.* However the FSA 'payload' would contain the response instead of an error, and the FSA would not have an error=true key.

So, ALL listeners would receive the same params, and errors are easily detected by checking `action.error` (true or undefined).

Just a suggestion.

**Comment by ctrlplusb** [comment]
Closing in favour of #247
