### ISSUE TITLE
Some quick questions

### ISSUE THREAD

**Issue by kaleidawave** [ctrlplusb/easy-peasy#245]
I am considering using this in a existing project but before I do I have some quick questions that were not answered from reading the documentation. 

#### Can you mutate `model` directly?

You see I am using a library that has an event listener. Can that event listener directly mutate the `model` object or should I mutate the store?

**Comment by ctrlplusb** [comment]
Hey @kaleidawave 

Thanks for raising these questions. I'll make sure we get this information added to the new website docs (v3).

> Can you mutate model directly?

Don't do any mutations outside of an `action`. The update won't be tracked and it could lead to very strange behaviour in your application.  Within your event listener you can fire an action to do updates.

> Can actions return things or are they voids?

You can't return anything to the point at which you dispatch them. If you return a value within your action we will consider this as the new value you would like to use for your state, and update your state accordingly (this is to support a more "immutable" based API that some people prefer over the "mutable" one).

> Does the top level items in store have to be objects or can they be direct actions?

The absolute root of your model needs to be an object. You can compose the subtree as you please.
