### ISSUE TITLE
multiple usingStoreState via sibling JSX

### ISSUE THREAD

**Issue by DrYSG** [ctrlplusb/easy-peasy#248]
Perhaps this is part of the design and not a real problem.

I had to child JSX controls each bound to the store via usingStoreState to the same property in the store. (and the parent is not subscribing to that part of the store).

I found that actions from one child that updated the state, were modifying the store (confirmed via the Chrome Redux tool) but that this was not being propogated to the sibling.

In addition, when I had multiple references to the same action in the store from siblings, I was often getting memory errors from recursive actions to the store. 

I am assuming the real answer is always to pass down actions and common state values via properties from the parent?

If that is the case, maybe the documentation can say so?

**Comment by ctrlplusb** [comment]
Hey @DrYSG 

Something doesn't sound right at all there. Would you be able to create a minimal example on CodeSandbox.io for me to debug?

**Comment by DrYSG** [comment]
The current example is too big. I think I might have time in a few days.

**Comment by DrYSG** [comment]
I was about to create the sandbox. But I think I know what the issue is, and since I have a "work-around" I don't want to waste anyone's time if that can be avoided. I really like the pace you are improving this tool at.

Basically, I am using the DevExtreme DataGrid component. They wrap their core functionality so that it can be used by REACT, AngularJS, Angular, VUE, etc. Not ideal, but it works well and we need it's features fast.

Anyway. I wanted a column of buttons on each row of the grid, and a custom button for copying the row (it is wired to an async function called mover() which calls a number of ustStoreActions).

As you can see from line I am not using onClick: {mover} but rather mover itself

Why? it is because this prop is being passed in an array. Now what I was seeing is that mover is being called immediately on component load, and also on each click, and this seemed to get into some sort of recursive call of the store creation, and was (a) killing the Chrome React extension, killing the debugging tool and causing memory issues in chrome (running out of heap). 

Anyway there is a better way to handle selects on rows, and I am now doing                     onSelectionChanged={chooser} where chooser is a simple synchronous function. Works fine and it can call store actions. 

If you don't follow all of this. feel free to close the issue. Because I am satisfied.



```
/**
 * MasterOpTable module.
 * 
 * Holds the Master Operation Table. Provides Search, Group, Filter operations for the table. Button to copy row to the OpList.
 * @module OpListBuilder/MasterOpTable
 */

import Grid from '@material-ui/core/Grid'
import { withStyles } from '@material-ui/core/styles'
import DataGrid, { Column, FilterRow, Grouping, GroupPanel, HeaderFilter, Paging, SearchPanel } from 'devextreme-react/data-grid'
import DataSource from "devextreme/data/data_source"
import 'devextreme/dist/css/dx.common.css'
import 'devextreme/dist/css/dx.dark.compact.css'
import { useStoreActions, useStoreState } from 'easy-peasy'
import React, { useEffect, useRef } from 'react'
import { store } from './EasyStore'

const styles = theme => ({});

function MasterOpTable(prop) {
    const masterOpGrid = useRef(null)
    const gridStore = useStoreState(state => state.gridStore)
    const incOpListTop = useStoreActions(actions => actions.incOpListTop)
    const source = useStoreState(state => {
        return new DataSource({
            store: {
                type: "array",
                key: "OpID",
                data: state.masterOpTable
            }
        })
    })
    const mover = (async (e) => {
        let row = e.row.data
        incOpListTop(null)
        let count = store.getState().opListTop
        row = { OpSequence: count, ...row }
        console.log(row)
        gridStore.store().insert(row)
        await gridStore.reload()
    })

    useEffect(() => {
        console.log("starting")
    }, [])

    return (
        <Grid container spacing={0} alignContent="center" alignItems='center'>
            <Grid item xs={12} >
                <DataGrid
                    dataSource={source}
                    allowColumnResizing={true}
                    showBorders={true}
                    ref={masterOpGrid}
                >
                    <GroupPanel visible={true} />
                    <SearchPanel visible={true} />
                    <Grouping autoExpandAll={false} />
                    <FilterRow
                        visible={true}
                        applyFilter={true} />
                    <HeaderFilter visible={true} />
                    <Paging defaultPageSize={20} />
                    <Column type={'buttons'} width={50}
                        buttons={[{
                            hint: 'Choose',
                            icon: 'save',
                            visible: true,
                            onClick: mover
                        }]} />
                    <Column dataField={'OpID'} width={80} />
                    <Column dataField={'OpDescription'} width={280} />
                    <Column dataField={'TestingCategory'} width={120} />
                    <Column dataField={'Phase'} width={80} />
                    <Column dataField={'Duration'} dataType='number' width={80} />
                    <Column dataField={'Document'} width={100} />
                </DataGrid>
            </Grid>
        </Grid >
    )
}

export default withStyles(styles)(MasterOpTable);
```

**Comment by ctrlplusb** [comment]
I think I followed. :)

Thanks for reporting back. Closing. 👍
