### ISSUE TITLE
Suggestion: Store metadata about thunk stages

### ISSUE THREAD

**Issue by jamaljsr** [ctrlplusb/easy-peasy#249]
I've been playing with easy-peasy for a few days now and one of the first hurdles I encountered was figuring out how to manage the progress for my thunks. Specifically, how to display a loader in the UI when a thunk is being executed to fetch data from an API, for example. I believe this is a really common use-case for most apps, so I am throwing this out there as a suggestion to be included in the library. If there is a good reason why this functionality shouldn't be included in the library, I'm curious to know.

Here's the full helper implementation
```javascript
import {
  action,
  thunkStartName,
  thunkCompleteName,
  thunkFailName
} from 'easy-peasy';

// HACK: this isn't exported from easy-peasy/src/constants.js,
// but we need it to identify thunks in the model. This would
// no be necessary if this helper is included in the library
const thunkSymbol = '🙈thunk🙈';

export type LoaderModel<T extends Object> = T & {
  loaders: {
    // TODO: filter out non-thunks from the keys to exclude
    // actions & state keys from auto-complete lists in useStoreState()
    [K in keyof T]: {
      loading: boolean;
      error: Error | undefined;
    };
  };
};

export default function injectThunkLoaders<T>(model: T): LoaderModel<T> {
  if (model['loaders']) {
    throw new Error(
      'Do not use a key named "loaders" on your model with this helper.'
    );
  }
  // copy the model and add the 'loaders' key
  const loaderModel = { ...model, loaders: {} } as LoaderModel<T>;
  // iterate over all model keys
  Object.keys(loaderModel).forEach(key => {
    const value = loaderModel[key];
    // add listeners only to thunks
    if (typeof value === 'function' && value[thunkSymbol]) {
      // initialize the default values for loader state
      loaderModel.loaders[key] = { loading: false, error: undefined };
      // add started listener
      loaderModel[`${key}(loading)`] = action(
        (state: LoaderModel<T>) => {
          state.loaders[key].loading = true;
        },
        { listenTo: () => thunkStartName(value) }
      );
      // add complete listener
      loaderModel[`${key}(stopped)`] = action(
        (state: LoaderModel<T>) => {
          state.loaders[key].loading = false;
          state.loaders[key].error = undefined;
        },
        { listenTo: () => thunkCompleteName(value) }
      );
      // add failed listener
      loaderModel[`${key}(error)`] = action(
        (state: LoaderModel<T>) => {
          state.loaders[key].loading = false;
          // TODO: set the error property from the action
          state.loaders[key].error = new Error(`action '${key}' failed`);
        },
        { listenTo: () => thunkFailName(value) }
      );
    }
  });
  return loaderModel;
}
```

When defining our StoreModel, we just need to call the helper
```javascript
import todosModel, { TodosModel } from "./todos";
import auditModel, { AuditModel } from "./audit";
import productsModel, { ProductsModel } from "./products";
import basketModel, { BasketModel } from "./basket";
// import the helper and generic return type
import injectThunkLoaders, { LoaderModel } from "../helpers/loaders";

export interface StoreModel {
  // update the model type
  todos: LoaderModel<TodosModel>;
  audit: AuditModel;
  products: ProductsModel;
  basket: BasketModel;
}

const storeModel: StoreModel = {
  // execute the helper to add the listeners and loader metadata
  todos: injectThunkLoaders(todosModel),
  audit: auditModel,
  products: productsModel,
  basket: basketModel
};

export default storeModel;
```

And finally, in the component, we have access to the loading state
```javascript
render() {
  const { loading, error } = useStoreState(state => state.todos.loaders.saveTodo);
  ...
  return (
    <>
      {loading && <i className="fa fa-spinner fa-spin" />}
      {error && <div className="error">{error.message}</div>}
    </>
  );
}
```

Full demo available at https://codesandbox.io/s/loaders-model-helper-3ciyk?fontsize=14

Unfortunately, there are some open issues which could use some improving:
1. The `thunkSymbol` variable is hard-coded because it's not exported by EP
2. I may need some typescript assistance with the `LoaderModel` type definition. It currently shows every key of the model in `useStoreState(...)` but it should only display the thunks.
3. The metadata key that gets added to the model is called `loaders`. Maybe this should be called `meta` and can be a place for other helpers to add additional data to the model.
4. The `error` is currently not being set properly. This will be likely be fixable once v3.0.0 is released

This current implementation would need some tweaking and probably simplifying once the new listener API is finalized in #247.

My thought is that this could be included in easy-peasy in one of three ways:
1. Automatically added for every `thunk()` with no configuration required
2. Available as a built-in helper that can be imported and more easily used in consuming apps
3. Available as a configuration true/false option on the `StoreConfig` object used in `createStore`. I know some folks may not want to pollute their redux state with this metadata if they aren't going to use it in their app

I personally found the need for this because I didn't want to add three listener actions for every thunk in all of my reducers, it would make the actual code a mess. If this doesn't make it into easy-peasy, I would still be interested in hearing other's approaches to solving this thunk-loading problem.

**Comment by ctrlplusb** [comment]
Thanks for this detailed example @jamaljsr - I am going to try an experiment out later and will get back to you. I've updated the proposal on listeners btw. 👍

**Comment by allpro** [comment]
It's is easy to set loading and error states locally by using the promise returned by the thunk, rather than _passing it through_ the Redux store...

````javascript
function MyComponent( props ) {
    const [ isLoading, setLoading ] = useState(false)
    const [ error, setError ] = useState(null)

    const storeContent= useStoreState('slice.section.contents')
    const actions = userStoreActions('slice.section')

    useEffect(() => {
        // Skip if content is loaded
        if (storeContent) return;

        // init new load
        setLoading(true);
        setError(null);

        // Redux will be updated IF the fetch is successful
        actions.fetchSomething()
            .catch(setError)
            .finally(() => setLoading(false))
    })

    if (isLoading) return <LoadingSpinner />

    if (error) return <ErrorMessage error={error} />

    return (
        <p>{storeContent}</p)
    )
}
````

**Comment by ctrlplusb** [comment]
I strongly support this suggestion by @allpro as my preferred approach to dealing with this. Generally the "loading" state is only used by the calling component, and therefore does not need to be encapsulated within a global store.  

This is my general rule of thumb really - anything transient or very component level (e.g. loading state, or form states) I will use standard React hooks to track the state with.

I appreciate this may not fit every case and there may be times a loading or form state does need to be represented within the global store. I've found these cases to be exceedingly rare though (in my experience).

That all being said, I'd still like to propose a strategy by which to define these types of helpers. I'll try get back to this asap.

**Comment by jamaljsr** [comment]
@allpro thank for the suggestion and sample code. This was my original approach but it then felt like too much boilerplate in my UI components. I was trying to minimize this logic into a few lines of code in my component, which is why I moved it to the redux state. I'm fairly new to hooks, but I will give that a shot.

@ctrlplusb I see your point about not mixing component state (loaders/errors) in with the global state. It makes perfect sense, I just couldn't think of a better place to put the repetitive chunks of code. I will try using a hook instead as @allpro suggested.

Thank you both for your feedback.
