### ISSUE TITLE
integrate third-party redux tools with createStore

### ISSUE THREAD

**Issue by markoshust** [ctrlplusb/easy-peasy#25]
How would one implement https://github.com/supasate/connected-react-router with easy-peasy -- specifically around the createStore documentation?

easy-peasy has it's own createStore function that accepts an object, but redux's createStore accepts a function. I'd like to know how to integrate modules like connected-react-router with easy-peasy (if it's possible).

I apologize this isn't an "issue", however it's unclear from the documentation on how to accomplish this. I'll make a PR to update the readme based on feedback from this issue.

**Comment by ctrlplusb** [comment]
Thanks for opening this @markoshust 👍

I'll review this tomorrow.

**Comment by ctrlplusb** [comment]
Hey @markoshust - I've had a review and the main blocker here is being able to provide your own reducer. TBH I have been tossing around the idea of adding the following helper, which would then unlock the ability for you to use things like `connected-react-router` which require both a middleware and a reducer config.

```javascript
import { createStore, reducer } from 'easy-peasy';

const store = createStore({
  router: reducer((state, action) => state),
  foo: 'bar'
});
```

I need to have a bit more a think about any complexities this may introduce though.

**Comment by ctrlplusb** [comment]
Hey @markoshust, managed to get this working albeit with a different library - [redux-first-history](https://github.com/salvoravida/redux-first-history). It's a newer lib but I prefer the approach and that it doesn't require react-redux or a connected router.

Pass the middleware to the createStore via the config/options second param, and then configure the reducer using the new `reducer` helper available in v1.6.0

👍

**Comment by markoshust** [comment]
@ctrlplusb thank you so much! sorry i've been busy on another project. i'll check this out and confirm usage, but should be great 👍

**Comment by ctrlplusb** [comment]
@aalpgiray did you enable the time travelling feature?

See their docs:

```javascript
export const createReduxHistoryContext = ({
  history, routerReducerKey = 'router', oldLocationChangePayload = false, reduxTravelling = false, 
})
```

Those are the default values above, you need to opt in to time travelling.

**Comment by ctrlplusb** [comment]
Interesting, may be worth opening an issue in the respective repo.

**Comment by salvoravida** [comment]
https://github.com/salvoravida/redux-first-history/issues/2

Fixed on 4.0.0-7

Salvo.

**Comment by ctrlplusb** [comment]
Amazing thanks @salvoravida 👍

@here we should consider adding this tip in the new "Tips and Tricks" section of the README. 👍

**Comment by pranaypratyush** [comment]
How do I `export const history = createReduxHistory(store);` at the end to get my new history?

**Comment by pranaypratyush** [comment]
How do I `export const history = createReduxHistory(store);` at the end to get my new history?
