### ISSUE TITLE
Move prop-types to dependencies instead of peerDependencies?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#250]
I noticed easy-peasy expects `prop-types` as a peer but I'm using Typescript and don't install `prop-types`. 

Facebook recommends `prop-types` be dependency for apps **and** libraries. 
https://github.com/facebook/prop-types#how-to-depend-on-this-package

All the best, 💪
Jeremy

**Comment by ctrlplusb** [comment]
Makes sense, thanks for raising this 👍

**Comment by ctrlplusb** [comment]
Done ✌️
