### ISSUE TITLE
Race condition on accessing computed property derived from a thunk?

### ISSUE THREAD

**Issue by stevelizcano** [ctrlplusb/easy-peasy#252]
If I have a thunk that pulls in an API data of say, an array of notes that are Strings, and I then have a computed property that concatenates and joins the arrays into one large string after they've been saved into the state by the thunk, I think a race condition emerges when accessing a computed value afterwards.

I notice that the computed variable is not computed properly after resolving the promise in the above use case. For example:

`
fetchNotesThunk().then(()=> {console.log(computedPropertyOfConcatenatedArrays)}
`

It will not show the updated  values using the thunk fetchNotes.
Could create race conditions or unexpected behavior in code due to this delay.

Unless I am going about this wrong?

As an aside, you have an absolutely fantastic solution that is quite a joy to use. Thank you.

**Comment by ctrlplusb** [comment]
Hey @stevelizcano - stoked to hear that you are enjoying the lib. 😃

I am going to make some assumptions here. Is your component analogous to the following:

```javascript
function MyComponent() {
  const computedPropertyOfConcatenatedArrays = useStoreState(state => 
    state.notes.computedPropertyOfConcatenatedArrays
  );
  const fetchNotesThunk = useStoreActions(actions => actions.notes.fetch);

  const onButtonClick = () => fetchNotesThunk().then(() => {
    console.log(computedPropertyOfConcatenatedArrays);
  });
}
```

If this roughly resembles the mechanisms by which your component is using the computed property and thunk then the following applies;

1. If you are resolving the computed property directly within your `useStoreState` hook you will be returned the value at that point in time. You will not receive an updated version of this value until the redux subscriptions fire and your `useStoreState` hook returns the new value.
2. You are creating a closure over the value of `computedPropertyOfConcatenatedArrays`. So it's very likely that this value will remain stale, even if you introduce some arbitrary time between the resolution of the thunk and the console.log statement.

Without understanding how you would like to use the `computedPropertyOfConcatenatedArrays` value within your component I can't make much of a recommendation, but my intuition tells me that you should likely consider creating a `useEffect` that has the computed property value as a dependency.

**Comment by stevelizcano** [comment]
Thanks for the detailed reply!

 Basically, I'm refreshing my local copy of notes from my graphQL server. After I receive them, I immediately send the computed results to another server to do some AI/ML work on the notes to extract some entity values for the user.

If a user adds a note, I'll probably push it to the server, refresh, and do another ML analysis on it.

So I guess therein lies the crux, if I want to immediately use my computed value after it's been updated. I think a useEffect with a dep on the computed value would be fine. 

Only question is this would be a long strong probably, and the computed iterates over many different arrays (we work with medical text is why), do you imagine this being a performance bottleneck?

Thanks!

Interesting point about a useEffect
