### ISSUE TITLE
redux dev tools chrome extension not working at 3.0.0 version

### ISSUE THREAD

**Issue by KirillSuhodolov** [ctrlplusb/easy-peasy#253]
I see just infinite loading, without errors. At major it worked

**Comment by ctrlplusb** [comment]
Hey @KirillSuhodolov 

Are you sure there is nothing else at play in your app? I can see the extension with latest beta `easy-peasy@3.0.0-beta.1`

**Comment by ctrlplusb** [comment]
I have created a codesandbox utilising v3, and my Redux Dev Tools are working.

I suspect you may have an unhandled error or some other issue within your store.

https://wqtnc.codesandbox.io/

**Comment by KirillSuhodolov** [comment]
thx, @ctrlplusb my fault, sorry
