### ISSUE TITLE
conditional rendering

### ISSUE THREAD

**Issue by DrYSG** [ctrlplusb/easy-peasy#254]
I have a state variable (true/false) that I am using for conditional rendering

```
    const unauthorized = useStoreState(state => state.unauthorized)
```

and It is being used as:

```
                    {unauthorized ? (<div>unathorized</div>) : (<div>authorized</div>)}
```

When watching in the REDUX Chrome Dev tools I can see the state of {unauthorized} flipping from true (initial value) to false and then back again. But REACT is only rendering always as false 'authorized'

The entire JSX is just one large stateless functional control (which I can provide if that helps).

Any idea why?
 
Upon further study of easy-peasy. I wonder of I should be using a listener, instead of updating to state variables in the same branch with a single action?

```
const store = createStore({
    employee: employee,
    dateTime: now.toString(),
    itemCode: "",
    locationCode: "",
    unauthorizied: true,
    setDateTime: action((state, payload) => {
        state.dateTime = payload
    }),
    setItemCode: action((state, payload) => {
        state.itemCode = payload
        if (payload == "666") {
            state.unauthorizied = false
        } else {
            state.unauthorizied = true
        }
    })

````

**Comment by ctrlplusb** [comment]
I believe you have a typo of your flag.

In your model it is spelled:     `unauthorizied`
In your component it is spelled: `unauthorized`

In regards to the listener - this would be a complete matter of preference. :)

**Comment by DrYSG** [comment]
**blush**

**Comment by ctrlplusb** [comment]
Haha! Don't worry, it happens to us all. :)

**Comment by DrYSG** [comment]
BTW: The line on page :  https://easy-peasy.now.sh/docs/tutorial/defining-computed-properties.html

Currently reads:

```
    totalPrice: computed(state =>
      products.reduce((acc, cur) => acc + cur.price, 0)
``
But should it not read:

```
    totalPrice: computed(state =>
      state.products.reduce((acc, cur) => acc + cur.price, 0)
```
