### ISSUE TITLE
A demo using Easy Peasy with RxJS

### ISSUE THREAD

**Issue by phmatray** [ctrlplusb/easy-peasy#255]
Hello @ctrlplusb,

This morning I was looking at how to interface easy-peasy with RxJS.

It works quite well at all, here is a demo.
https://codesandbox.io/s/hungry-maxwell-ok6x5

However, I have a question. Is it a problem to interact with variables outside the store?

**Comment by phmatray** [comment]
Maybe I can write a documentation page called "Usage with RxJS" in the recipes section...

**Comment by ctrlplusb** [comment]
Awesome @phmatray - I would be stoked for this to go into the recipes section. 👍

I don't think there is any problem with reaching for a variable outside of the model, however, to help with the "testability" of your store I would recommend you encapsulate either the store or the model within a function, which will maintain it's own scope of Rx subjects.

For example

```javascript
import { createStore, action, thunk } from "easy-peasy";
import { timer, Subject } from "rxjs";
import { takeUntil } from "rxjs/operators";

function myCreateStore() {
    // my observable: emit a value each second
    const unsubscribe$ = new Subject();
    const everySecond$ = timer(0, 1000).pipe(takeUntil(unsubscribe$));

    const store = createStore({
    counter: 0,

    startCounter: thunk(actions => {
        everySecond$.subscribe(actions.incrementCounter);
    }),

    stopCounter: thunk(() => {
        unsubscribe$.next();
    }),

    incrementCounter: action(state => {
        state.counter++;
    }),

    resetCounter: action(state => {
        state.counter = 0;
    })
    });
}

export default myCreateStore;
```

**Comment by phmatray** [comment]
Taking your point into account, I cooked a second example a little more advanced: a bitcoin/euro ticker. The price is automatically updated every 5 seconds.

I like mixing easy-peasy with RxJS. It is thus possible to perform very advanced operations in a few lines while remaining scalable and readable.

https://codesandbox.io/s/serene-thunder-h2q2y

**Comment by corysimmons** [comment]
Would love to see an `examples` dir in v4 like the one in NextJS. 🤤 

About to explore this RxJS pattern in depth. ty 🙇
