### ISSUE TITLE
'Computed' doesn't get updated

### ISSUE THREAD

**Issue by pranaypratyush** [ctrlplusb/easy-peasy#257]
I have a `computed` defined like this
```
computed((n) => n.length > 0 ? n.slice(-1)[0] : null,
    [state => state.notificationData])
```
where `notificationData` is an array of objects. One of my thunks push to the array from inside a catch statement but the computed state remains null. Checked with ReduxDevTools.

**Comment by ctrlplusb** [comment]
Hey @pranaypratyush 

You shouldn't update state within a thunk. You need to dispatch an action from a thunk to do state updates.  Sorry V3 docs will be making this more explicit.

**Comment by pranaypratyush** [comment]
Thanks.
