### ISSUE TITLE
Should listeners be on the getActions() object?

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#261]
I initially posted a non-existent bug in this issue. It _looked like_ an `actionOn()` listener was not working correctly in my test. However, right after calling a `thunk()`, I _accidentally_ called the same `actionOn()` listener _directly_ (instead of a similarly named, regular `action()`).

It took me a while to realize that I called an `actionOn` method instead of an `action()`. Calling it directly, with a normal payload, caused a bad value (undefined) to be written into state - because it was expecting `target.result`. This confused me; hence my bogus bug report.

**Since a listener should **never**, (under normal circumstances), be called directly, perhaps they should not be exposed as "actions" by `store.getActions()` or `useStoreAction()`.** If they _need_ to be exposed for testing then maybe it could be something like `store.getListeners()`. This prevents doing something dumb by accident, as I did. I think it's predictable this will happen regularly, so protecting users from their own mistakes would be a good thing!

**Comment by ctrlplusb** [comment]
Super idea. I've done exactly this in the `easy-peasy@3.0.0-rc.2` release. 👍
