### ISSUE TITLE
TypeScript with redux-persist

### ISSUE THREAD

**Issue by revmischa** [ctrlplusb/easy-peasy#262]
@ctrlplusb More TypeScript problems! 😅

Using the code results in this when using with TypeScript;

```
Argument of type '{ reducerEnhancer: (reducer: Reducer<any, any>) => Reducer<any, any>; }' is not assignable to parameter of type 'EasyPeasyConfig<any, any>'.
  Types of property 'reducerEnhancer' are incompatible.
    Type '(reducer: import("/node_modules/easy-peasy/index").Reducer<any, any>) => import("/node_modules/redux/index").Reducer<any, any>' is not assignable to type '(reducer: import("/node_modules/easy-peasy/index").Reducer<any, any>) => import("/node_modules/easy-peasy/index").Reducer<any, any>'.
      Type 'Reducer<any, any>' is missing the following properties from type 'Reducer<any, any>': type, result  TS2345
```

_Originally posted by @alizahid in https://github.com/ctrlplusb/easy-peasy/issues/40#issuecomment-489314071_

**Comment by revmischa** [comment]
I am too experiencing this

**Comment by ctrlplusb** [comment]
Hey @revmischa 

No worries, could you please post a reproducible example, either as a CodeSandbox, or a code snippet? 👍

Regards

**Comment by revmischa** [comment]
```typescript
import { createBrowserHistory } from 'history'
import * as localForage from 'localforage'
import { persistReducer, persistStore } from 'redux-persist'
import { createStore } from 'easy-peasy'
import { IUser } from '../types/User'

export const history = createBrowserHistory()

export interface IUserState {
  user?: IUser
}

export interface IApplicationModel {
  user: IUserState
}

export const userModel: IUserState = {}

export const model: IApplicationModel = {
  user: userModel,
}

export function createPersistedStore(model: IApplicationModel) {
  const persistConfig = {
    key: 'root',
    storage: localForage,
  }
  const store = createStore(model, {
    reducerEnhancer: reducer => persistReducer(persistConfig, reducer),
  })
  const persistor = persistStore(store)

  return { store, persistor }
}
```

**Comment by ctrlplusb** [comment]
Hey @revmischa - I would suggest using a `@ts-ignore` comment on the reducer enhancer for now. The `@next` branch is definitely the way to go for optimal TS experience.

**Comment by revmischa** [comment]
What do I use instead of `useStoreState` to access state now?

**Comment by ctrlplusb** [comment]
https://easy-peasy-v3.now.sh/docs/typescript-tutorial/typed-hooks.html

I'm still updating all the codesandbox demos.

**Comment by ctrlplusb** [comment]
Fixed in `easy-peasy@3.0.0-alpha.rc4`.

[Demo](https://codesandbox.io/s/easy-peasy262-8cjtv)

Also, the [v3 website](https://easy-peasy-v3.now.sh) has been updated. 👍

**Comment by revmischa** [comment]
splendid thanks!

**Comment by PabloCR** [comment]
Hey all.

I have followed the example on the codesandbox to successfully implement the persist but now I'm looking to split my store given some issues with redux-persist, specifically: https://github.com/rt2zz/redux-persist/issues/1155

I was looking the replace the global "createStore" with a couple "createContextStore" to split the persisted data.
But when attempting to create the store with the persistReducer configuration while using "createContextStore" I get an error:

**TypeError: _Store.default.getActions is not a function. (In _Stode.default.getActions()', '_Store.default.getActions' is undefined)**

Any ideas how to overcome this?
