### ISSUE TITLE
Thunks should support sync or async workflow

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#265]
**There are scenarios where it would be convenient to call an action from another action.** This helps keep code DRY and avoids a complicated maze of listeners to accomplish the same thing.

For example, an action could apply branching logic to decide _which_ of 3 different updates to do. There may be individual `actions` for each of these updates, with their own data-transformation logic. Therefore it's cleaner and DRYer to call these actions rather than _duplicate_ their code.

**I propose passing appending 'actions' as a 3rd argument to `action()` &  `actionOn()`.** This _usually_ won't be needed, just as `storeState` isn't often needed, but would be available when it is...
````
action: (state, payload, actions) => {...}
actionOn: (state, target, actions) => {...}
````

Thunks, (a type of action) receive an `actions` arg, so this is not-inconsistent.

Here's a contrived example, using the _proposed_ 3rd argument to the handler:

````
updateValue: action((state, payload, actions) => {
    const { data, category } = payload;
    const { rights } = state.user;
    if (category === 'top') {
        if (rights === 'admin') {
            actions.setTopValue(data)
        } else {
            actions.setCategoryIfAllowed(payload)
        }
    } else {
        actions[`set${category}Value`](data)
   }
})
````

It's not a great example, but hopefully it illustrates how `branching` to other actions can help keep things DRY and simple.

_Why not put this logic in the calling code?_ 
If this action is called from multiple places, I don't want to repeat this logic. 

_Why not create a helper method?_ 
This simple branching logic is based on data already in state, so an action seems the logic place for it. An action _should_ be able to handle such logic, without replicating code from other actions that can also be called _directly_ in other scenarios.

**Comment by ctrlplusb** [comment]
Why not use a thunk to achieve this?

```javascript
updateValue: thunk((actions, payload, { getState }) => {
    const { data, category } = payload;
    const { rights } = getState().user;
    if (category === 'top') {
        if (rights === 'admin') {
            actions.setTopValue(data)
        } else {
            actions.setCategoryIfAllowed(payload)
        }
    } else {
        actions[`set${category}Value`](data)
   }
})
```

**Comment by allpro** [comment]
I love the listener capabilities for decoupling loosely-related updates. However there are times when code would be more expressive and the logic clearer if the 'next step' is _explicitly_ called inside the action. Calling a common _sub-routine action_ facilitates this.

I could create a listener with 5+ target-resolvers, but this can make closely-coupled logic harder to grok. To see IF there is another 'step' I would have to check _every_ listener in the model. That makes logic less readable so sometimes I'd rather show the next-step explicitly...

````
doSomething: action(state, payload, actions) => {
    state.dataTypeQueue.push[ payload ]
    actions.syncData('dataType', payload.id)
})
````

**Comment by ctrlplusb** [comment]
Again, doesn't a `thunk` provide this?

```javascript
doSomething: thunk(actions, payload, { getState }) => {
    actions.addDataTypeQueue(payload);
    actions.syncData(payload.id);
})
```

**Comment by allpro** [comment]
> Why not use a thunk to achieve this?

I thought of that, since thunks are the only action-type that receive an actions arg. However it's not intuitive to use an _asynchronous_ method for synchronous code! Plus the thunk will _convert_ the action to a promise, making tests confusing. (Why is this asynchronous?)

The thunk also cannot do any state updates of its own, so cannot facilitate _sub-routines_ as in the example in my comment above. I'm a fan of subroutine patterns for both method brevity and DRYness.

**Comment by ctrlplusb** [comment]
I think this is the actual core issue. Thunks shouldn't actually be _always_ async. They should just support it. Reviewing redux-thunk seems to imply this too. I am going to review this.

**Comment by ctrlplusb** [comment]
Sorry this was actually a terrible oversight in my original design.

**Comment by ctrlplusb** [comment]
Yeah, just tested this change and it is very easy to make. I am going to make sure the docs are updated with this, making it far more explicit that thunks are for the following use cases:

1. Synchronous action dispatch workflows (i.e. allows logic) 
2. Side effects
3. Side effects with actions dispatching

**Comment by allpro** [comment]
Thunks are generally understood to be for side-effects, so not intuitive for ordinary state-updates. Could still work except that...

Thunks currently cannot update state, because were designed for async actions. Therefore even a simple call to an already-existing subroutine would require 2 new methods:

````
addItemA: thunk((actions, payload) => {
    actions.addItemB(payload)
    actions.subroutine(payload.id)
},
addItemB: action((state, payload) => {
    state.value = payload
}
````

This seems unnecessary verbose and redundant. It also complicates action naming since they are both for exactly the same 'action'.

**Comment by ctrlplusb** [comment]
Hey @allpro 

I have been thinking about this, and have a few suggestions. Would you mind giving me a more concrete example - more real life, as my suggestions won't feel as valid within an real life example to apply against.

Thanks

**Comment by allpro** [comment]
> Would you mind giving me a more concrete example - more real life

I ran into another usecase just yesterday. I created a "notifications" model so various services could `addItem()`. The Notifications component provides feedback for long-running background tasks. Services also call `addItem()` to _update_ the progress of a task.

When a task is 'done', the service calls `addDoneItem()` to add the task to an `itemsDone` array, which will trigger a toast message. This action _also_ removes the now-done item from the in-progress `items` array, *by calling `actions.removeItem(item)`*. Or at least that's what I'd like to do!

To keep things DRY, I don't want to replicate the removeItem() code; I'd rather call the method as a sub-routine. This action _should_ be very simple, if I had access to 'actions' somehow... 
(code simplified for brevity)

````
addDoneItem: (state, item, actions) => {
    state.itemsDone.push(item)
    actions.removeItem(item)
}
// Or
addDoneItem: (state, item, { getActions }) => {
    state.itemsDone.push(item)
    getActions().removeItem(item)
}
````

Clear and simple, right?

However, I _can't_ access the removeItem() action/sub-routine. :( Instead I had to create an `actionOn()` listener. This required 3-times as much code _plus_ comments in both the action and the listener to explain the flow.

I created this model for another dev who was using Easy-Peasy for the first time. This extra complexity made the flow harder to grok. When asked why I used a listener for this simple process, I had to explain that there is no other way. Not a satisfying answer.

Yes, I make it work with a listener, but this made things notably more complex and verbose, with no conceptual benefits n this scenario. It felt like I was writing "boilerplate" for something that should be easier!

I _could have_ replicated the removeItem code so I didn't need to call that action. In this case the action is small and simple, but this will not always be the case. It goes against my principles to duplicate functionality so I try to set an example by never doing it!

However, when faced with this scenario, many devs _will_ copy-n-paste code rather than bother with the complexity of a listener. I'm already fighting a copy/paste mentality - devs gravitate to the fastest solution.

I like listeners for decoupling discrete actions, especially those in different models/slices. Within the same model though, I'd like to _have the option_ to call another action explicitly. The concept of small, single-purpose functions is a best practice for JavaScript so I want to follow that pattern in store-models. I think of a model like 'class' with properties and methods. If I had to write an event-observer every time I wanted to call another class-method, it would drive me nuts!

Using a _synchronous_ thunk in this scenario would just replace the extra complexity of an unnecessary listener with the extra complexity of an unnecessary thunk! A _separate_ addDoneItem() method would still be required so there is little difference.

Giving ALL actions the ability to call other same-model actions is logical, and facilitates writing smaller, more modular model methods.

*To synchronize actions and thunks, and provide for future updates, the 3rd argument to actions could be a `helpers` object...*

````
myAction: (state, payload, helpers) => { },
myThunk: (actions, payload, helpers) => { },
````

I've seen other requests for access to data in actions, like the injections object. So maybe 'helpers' includes _everything_ that thunks get. A `getActions()` helper would be added to get the same-model actions. *Now thunks and actions would be _equally_ flexible - instead of thunks bring able to do _anything_ while actions are _deliberately limited_.* I don't like limitations!

*To keep things simple, the `helpers` object could be identical for both. It doesn't matter that one method would be redundant for each.* Thunks don't need `getAction()` because they get that as the first param; and actions don't need `getState()` because they get that as a first param.  I think consistency is better than worrying about a single redundant method. In complex scenarios, this could using an external helper to apply complex logic. It wouldn't matter whether a thunk or an action calls it, because the signature is consistent for both.
````
    calculateFinalValue(payload, helpers)
````

**Comment by ctrlplusb** [comment]
I appreciate your desire to keep things DRY, however, dispatching actions from an action should be considered an anti-pattern. It would be the equivalent of dispatching an action from within a Redux reducer, and would suffer the [same pitfalls](https://stackoverflow.com/questions/36730793/can-i-dispatch-an-action-in-reducer).

The primary motivation you seem to have is avoiding duplication of code. We could solve this much as you would in a "pure" redux implementation. Instead of reducer delegation, we could just do function delegation.

```javascript
function removeInProgressItem(state, item) {
    state.inProgress = state.inProgress.filter(x => x !== item.id);
}

export const notificationModel = {
    removeInProgressItem: action((state, item) => {
        removeInProgressItem(state, item);
    }),
    addDoneItem: action((state, item) => {
        state.itemsDone.push(item)
        removeInProgressItem(state, item);
    })
}
```

You could even write an arbitrary helper to help compose multiple functions together.

```javascript
const composedAction = (...actions) => {
    return action((state, payload) => {
        actions.forEach(x => x(state, payload));
    });
}
```

You could then use it like so:

```javascript
function removeInProgressItem(state, item) {
    state.inProgress = state.inProgress.filter(x => x !== item.id);
}

function addDoneItem(state, item) {
    state.itemsDone.push(item);
}

export const notificationModel = {
    itemDone: composedAction(
        addDoneItem,
        removeItemInProgress
    )
}
```

**Comment by ctrlplusb** [comment]
Closing this, but happy to continue discussion. 👍

**Comment by allpro** [comment]
````javascript
function removeInProgressItem(state, item) {
    state.inProgress = state.inProgress.filter(x => x !== item.id);
}

export const notificationModel = {
    addDoneItem: action((state, item) => {
        state.itemsDone.push(item)
        removeInProgressItem(state, item);
    })
}
````

In this example, the `removeInProgressItem` 'function' is _really_ an 'action' that lives _outside_ the model. The anti-pattern/limitation has not been avoided - just worked around.

You noted this is "the equivalent of dispatching an action from within a Redux reducer". Yes and no. Normal reducers are 'listeners'. _Every_ reducer is called for _every_ action, so _multiple_ reducers can act on the same action-name. EP _maps_ each action to a specific reducer, which is what _creates_ the limitation of one reducer per-action

My own Redux wrappers also mapped one-action to one-reducer. When I needed a second reducer to fire, I triggered it. In simplified form: `reducers.doSomething(action)`. Remembering this made me realize that I can do the same thing with EP model methods!

Instead of using an _external_ function, this example calls another model action directly. Since I only want to trigger other actions within the same model/slice, this should work for me.

````javascript
const notificationModel = {
    items: [],
    itemsDone: [],

    addDoneItem: action((state, item) => {
        state.itemsDone.push(item)
        notificationModel.removeItem(item)
    }),

    removeItem: action((state, item) => {
        state.items= state.items.filter(x => x !== item.id);
    })
}
````
