### ISSUE TITLE
Continuous re-rendering with react-router-dom

### ISSUE THREAD

**Issue by ubaidseth** [ctrlplusb/easy-peasy#266]
I checked every single prop down from App.js to the child component and there should be no reason to re-render. I installed a script to check why and it kept pointing to the this.props.match key. Even though that key doesn't change, it still re-renders. 

This may be an issue with react-router-dom but when I uninstall easy-peasy the error goes away. I'd rather choose this module over react-router-dom -- has anyone had any success with another routing module that works much better with easy-peasy?

**Comment by ctrlplusb** [comment]
Hey @ubaidseth 

Is there any chance you could create a minimal reproduction in codesandbox or share some code. I use react-router-dom extensively with no issues.

**Comment by bentron2000** [comment]
@ubaidseth 
We're hunting down some extraneous re-rendering and performance issues as well and I saw this ticket - can I ask what environment you're running in? Also, are you using 'memoryRouter' perchance?

**Comment by ctrlplusb** [comment]
Have you seen this? Might help 👍

https://github.com/welldone-software/why-did-you-render

**Comment by ubaidseth** [comment]
Using browserHistory. Env is a linux debian 9

**Comment by ctrlplusb** [comment]
Hi both, I am going to close this due to lack of information. If you can provide a reproducible code sandbox I would be happy to review.
