### ISSUE TITLE
store.getActions is not a function, using Typescript and V3

### ISSUE THREAD

**Issue by abuch21** [ctrlplusb/easy-peasy#268]
Hi,

First off I'm new to GitHub and this is my first issue opening so sorry if I don't follow the usual guidelines correctly.

Today, I've been trying to upgrade to V3 and typescript at the same time. I followed the tutorial but at the very end I got this error message: **store.getActions is not a function**

Here is what I get from the console: 
`Uncaught TypeError: store.getActions is not a function
    at Object.useStoreActions (easy-peasy.esm.js:80)
    at RouteRender (RouterRender.tsx:28)
    at renderWithHooks (react-dom.development.js:12938)
    at mountIndeterminateComponent (react-dom.development.js:15020)
    at beginWork (react-dom.development.js:15625)
    at performUnitOfWork (react-dom.development.js:19312)
    at workLoop (react-dom.development.js:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)`

`The above error occurred in the <RouteRender> component:
    in RouteRender (created by PureLifecycle(RouteRender))
    in PureLifecycle(RouteRender) (created by Index)
    in Switch (created by Index)
    in main (created by Index)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Index)
    in Index (created by Root)
    in StoreProvider (created by Root)
    in Root`

`Uncaught TypeError: store.getActions is not a function
    at Object.useStoreActions (easy-peasy.esm.js:80)
    at RouteRender (RouterRender.tsx:28)
    at renderWithHooks (react-dom.development.js:12938)
    at mountIndeterminateComponent (react-dom.development.js:15020)
    at beginWork (react-dom.development.js:15625)
    at performUnitOfWork (react-dom.development.js:19312)
    at workLoop (react-dom.development.js:19352)
    at renderRoot (react-dom.development.js:19435)
    at performWorkOnRoot (react-dom.development.js:20342)
    at performWork (react-dom.development.js:20254)`

My RouteRender component is basically a wrapper component I use to render all my routes and it looks like this:

```
import * as React from 'react'
import { Route } from 'react-router-dom'
import { useStoreActions } from '../store/hooks'
import lifecycle from 'react-pure-lifecycle';

const methods = {
  componentWillMount() {
    window.NProgress.start()
  },

  componentDidMount (props) {
    document.title = props.title ? `${props.title} | Sesame` : 'Sesame'
    window.NProgress.done()
  }
}

const RouteRender = (props) => {
  const updatePath = useStoreActions(actions => actions.router.setPath)

  React.useEffect(() => {
    if (!props.path) updatePath(undefined)
  }, [])

  return (
    <Route {...props} />
  )
}

export default lifecycle(methods)(RouteRender);
```

my app.tsx file where I render React :
```require('./bootstrap');

import * as React from 'react';
import { render } from 'react-dom';
import { StoreProvider } from 'easy-peasy';
import Index from './views/Index';
import storeProviderModel from './store/models';

const store = storeProviderModel

function Root() {
  return (
    <StoreProvider store={store}>
      <Index />
    </StoreProvider>
  );
}

render(<Root />, document.getElementById('app'));
```

My store model : 
```
import routerModel, { IRouter } from './router';
import modalModel, { IModal } from './modal';

export interface IStoreProvider {
  router: IRouter,
  modal: IModal
}

const storeProviderModel: IStoreProvider = {
  router: routerModel,
  modal: modalModel
}

export default storeProviderModel
```
Hooks.ts file :
```
import { createTypedHooks } from 'easy-peasy';
import { IStoreProvider } from './models';

const typedHooks = createTypedHooks<IStoreProvider>();

export const useStoreActions = typedHooks.useStoreActions;
export const useStoreDispatch = typedHooks.useStoreDispatch;
export const useStoreState = typedHooks.useStoreState;
```

Also, I am getting this typescript error when using StoreProvider in my app.tsx file
```Type 'IStoreProvider' is missing the following properties from type '_Merge<_Pick<Store<_Merge<StateMapper<_Pick<_Pick<{}, never>, never>, "1">, _Pick<_Pick<{}, never>, never>>, AnyAction>, "getState" | "subscribe" | "replaceReducer">, _Pick<...>>': getState, subscribe, replaceReducer, dispatch, and 7 ```

Thank you !

**Comment by ctrlplusb** [comment]
Hey @abuch21 

Welcome to GitHub! That's a pretty decent first issue raised. 👍 Plenty of detail.

Having a quick look I can see you aren't actually creating a store instance.

You need to make the following changes.

```diff
import * as React from 'react';
import { render } from 'react-dom';
- import { StoreProvider } from 'easy-peasy';
+ import { StoreProvider, createStore } from 'easy-peasy';
import Index from './views/Index';
import storeProviderModel from './store/models';

- const store = storeProviderModel
+ const store = createStore(storeProviderModel);

function Root() {
  return (
    <StoreProvider store={store}>
      <Index />
    </StoreProvider>
  );
}

render(<Root />, document.getElementById('app'));
```

**Comment by abuch21** [comment]
@ctrlplusb omg I can't believe I actually raised an issue for that, I had the store created but in another file and I mixed them up. Sometimes it's the most obvious of mistakes that pass right by you ! I guess I should stop programming after coming back from work. Doing an internship in angular right now, I hope for the next one I can find something in React and if so maybe try bringing up your library to the team. 

I really love it ! I worked with Redux before and the boilerplate set-up was so tedious. Easy-Peasy is my favorite state management library and I thank you for sharing it with us ! Excited to see that new tutorial !

Also thanks for the welcome lol I've been using Bitbucket for a while since that's what I learned in school but I think it's time to hop in on the Github community

**Comment by ctrlplusb** [comment]
Haha, don't worry about it! Happens to us all. That's what peer reviews are great for. :)

Really happy to hear that you are enjoying this library and are exploring React. 

All the best for your journey, and feel free to ask questions any time you like. 👍
