### ISSUE TITLE
Computed properties fail in conjunction with `redux-persist`

### ISSUE THREAD

**Issue by siefkenj** [ctrlplusb/easy-peasy#269]
Using `easy-peasy` with `redux-persist` works as long as only actions and state is used. When a part of the state is `computed`, the app fails to start (even if the computed property is blacklisted).

A minimal example can be found here:
https://codesandbox.io/s/easy-peasy-example-ot5nm

If you comment out the computed property on line `13` of `model.js`, the app will work.

**Comment by ctrlplusb** [comment]
Can you try `easy-peasy@3.0.0-rc.6`?

**Comment by siefkenj** [comment]
`easy-peasy@3.0.0-rc.6` fixes the issue. Thank you!
