### ISSUE TITLE
Need a way to get info on underlying action name, state name, etc.

### ISSUE THREAD

**Issue by pranaypratyush** [ctrlplusb/easy-peasy#270]
I can get these details through other means but in my opinion easy-peasy should be completely transparent and interoperable with redux and all middlewares.

**Comment by ctrlplusb** [comment]
The type information is exposed on action creators.

```javascript
console.log(store.getActions().todos.addTodo.type);
// @action.todos.addTodo
```

State is as is I guess?

**Comment by pranaypratyush** [comment]
Oh thanks.
