### ISSUE TITLE
Migrating to 3.0.0 - TS - reference to Redux

### ISSUE THREAD

**Issue by bentron2000** [ctrlplusb/easy-peasy#277]
Hi @ctrlplusb,

I'm migrating to the new API / `v3.0.0` from `2.4.0` and I'm getting this message from typescript @ `createTypedHooks()` and `createStore()`. This happens on npm install to the latest with no changes to the code.

`The inferred type of 'useStoreDispatch' cannot be named without a reference to 'easy-peasy/node_modules/redux'. This is likely not portable. A type annotation is necessary.ts(2742)`

Is this easy-peasy or something in my config?

Loving the changes :)

B

![Screen Shot 2019-07-26 at 2 29 15 pm](https://user-images.githubusercontent.com/5344375/61926032-3d5c2800-afb2-11e9-8bd0-262574789548.png)

@xaun - do you get this on the EP update branch?

**Comment by ctrlplusb** [comment]
Hey @bentron2000 

Hmmm, sounds like TypeScript server may have gotten confused. Have you tried clearing down your node_modules and restarting the TypeScript server?

**Comment by bentron2000** [comment]
Problem fixed by deleting the package-lock.json - only took two of us to work that out. 🙄

Thanks @ctrlplusb & @xaun

**Comment by thieu75** [comment]
Hi guys,

Is it possible to repoen it? I have the same problem and the fix doesn't work for me :-/
