### ISSUE TITLE
Option to fluidly switch from immer.js to returning immutable state on my own

### ISSUE THREAD

**Issue by pranaypratyush** [ctrlplusb/easy-peasy#279]
Earlier easy-peasy allowed me to either mutate the state or return new state in an immutable fashion. Sometimes the former is prefered and at other times later. Why can't I have both? Tried `state= [...state,...payload]` but it doesn't work.

**Comment by ctrlplusb** [comment]
Unfortunately this has become an architectural limitation due to the nature of computed properties. They cause havoc with immer, and I was unable to resolve this case. I've had to settle for the ability to toggle immer on/off.

**Comment by pranaypratyush** [comment]
ah. ok

**Comment by ctrlplusb** [comment]
@pranaypratyush 

I discovered that this was actually a bug and have fixed it in the latest release. 👍

**Comment by pranaypratyush** [comment]
Wow. Thanks.
