### ISSUE TITLE
Thoughts on opt-in/opt-out for immer?

### ISSUE THREAD

**Issue by vincentjames501** [ctrlplusb/easy-peasy#28]
Would be cool if we could optionally opt-in for immer or optionally opt-out. 

As middleware:

```js
const store = createStore({
  todos: {
    items: ['Install easy-peasy', 'Build app', 'Profit']
  }
}, {
  middleware: [immerMiddleware()]
});
```

As a function wrapper:

```js
const store = createStore({
  todos: {
    add: immer((state, payload) => {
      state.items.push(payload)
    })
  }
});
```

**Comment by ctrlplusb** [comment]
Hey @vincentjames501 👋

Thanks for this suggestion. This has come up a couple of times and I am thinking that perhaps I should update the docs to reflect that the behaviour is already "opt-in", albeit not in the manner in which you suggest.

With you actions you can _either_ mutate state, or return a new immutable instance. 👍

```javascript
const store = createStore({
  todos: {
    add:(state, payload) => {
      return [
		...items,
		payload
      ];
    })
  }
});
```

Would this be ok?

**Comment by ctrlplusb** [comment]
I've updated the docs to reflect this. 👍

**Comment by vincentjames501** [comment]
My thought was just so that immer could be tree-shaken away if left unused. I love the concepts in easy-peasy and I hope it gives new life to Redux!

**Comment by ctrlplusb** [comment]
Yeah, I don't think this will be possible as I use immer internally. :)

But don't be too scared: https://bundlephobia.com/result?p=immer@1.7.4

:)

**Comment by rheaditi** [comment]
@ctrlplusb related question; LMK if it's better to open a new issue. (Asking in the same thread since this one is searchable.)

If we don't mutate the state and return a new instance of state, does it skip the proxy check?

**Comment by ctrlplusb** [comment]
@rheaditi you can do this, but to be 100% sure use the `disableImmer` option via the store's config. 👍
