### ISSUE TITLE
Computed isn't getting updated on referencing other computed

### ISSUE THREAD

**Issue by pranaypratyush** [ctrlplusb/easy-peasy#280]
I am on v3.0.0. 
```
 botRoutes: computed(
    [(state, storeState) => storeState.bots.bots],
    (bots) => bots.map(bot => {
      return {
        layout: "/admin",
        path: `/b${bot.id}`,
        name: `Bot id:${bot.id}`,
        icon: "pe-7s-helm",
        component: "BasicControl",
        mini: `B${bot.id}`
      };
    })
  ),
  routes: computed(state => [...state.botRoutes, ...routes]),
```
The former works fine but the latter does not.

**Comment by ctrlplusb** [comment]
Hey @pranaypratyush 

I set up an example of chained computed properties [here](https://codesandbox.io/s/easy-peasy280-kecg3), but I am observing expected behaviour.

Could you set up a reproducible example for me please.

**Comment by pranaypratyush** [comment]
Sorry for the trouble. This was being caused because of bad imports.
