### ISSUE TITLE
cannot support  low version of chrome

### ISSUE THREAD

**Issue by henryzp** [ctrlplusb/easy-peasy#281]
Hi, I really like your library, and Amway gave my colleagues.
But there is a problem, our project needs to support the version below chrome 54, your code has `Object.values`, no `ployfill`, resulting in the code can not run under the lower version of chrome.
Can you fix it in the next version? Thank you...

![image](https://user-images.githubusercontent.com/3849702/61948287-f8e48280-afd9-11e9-8343-fe4f92a2b0aa.png)

**Comment by avilaj** [comment]
@henryzp my suggestion would be to add the polyfill to your project.
If you are transpiling code you probably have the mechanism to add it.

**Comment by ctrlplusb** [comment]
Hey @henryzp 

How are you consuming Easy Peasy? Via Create React App? Custom Webpack config? Parcel?

It is possible to set transpilation to your desired target, failing that, you can alternatively polyfill any features that you like.

In terms of polyfilling, I personally recommend the polyfill.io service. You can create custom selections of the features you would like to polyfill and include the result script URL in the head of your HTML doc.  Cool thing is that it will only actual fetch and perform the polyfills if a user's browser doesn't have native support. This keeps bundle sizes right down.

For example, here is the script to polyfill `Object.values` only.

```html
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Object.values"></script>
``` 

You can even polyfill enter featuresets, such as ES2015.

```html
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=es2015"></script>
```

**Comment by henryzp** [comment]
@ctrlplusb We are using webpack, and babel compilation ignores the node_modules directory.
You said this, we are currently adding a js file in the html, the content inside is to handle `Object.values`.
But my colleagues think that this solution is too low, can it be implemented inside the component? After all, the three-party components provided are still compatible with chrome.

**Comment by henryzp** [comment]
The website `polyfill.io` you mentioned, I am afraid that it will be unstable in China.

**Comment by henryzp** [comment]
@avilaj but other third libraries have not encountered similar problems.

**Comment by henryzp** [comment]
@ctrlplusb ，i visite `https://polyfill.io/v3/polyfill.js?features=Object.values`，but get：

![image](https://user-images.githubusercontent.com/3849702/61989319-0cd2c780-b060-11e9-8730-ac84c7ca9d07.png)

**Comment by ctrlplusb** [comment]
@henryzp yeah, it won't return anything if the browser you requested it from doesn't need the polyfill. :) That's what makes this service really great. Try the same URL in a browser that doesn't support Object.values. 👍

**Comment by henryzp** [comment]
@ctrlplusb ，thank you。。。I know。

The final conclusion still needs to add a polyfill?

**Comment by ctrlplusb** [comment]
@henryzp I am closing this. Can you also please double check things on your end as I checked the distributed source and there are no instances of Object.values being used.

https://unpkg.com/easy-peasy@3.0.0/dist/easy-peasy.cjs.js

**Comment by henryzp** [comment]
@ctrlplusb ，i used the version 2.6.5，it has `Object.values`。3.0.0，no found
