### ISSUE TITLE
Idea: getStoreModel() for slice-specific methods

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#282]
**Proposal:** I mentioned the idea of a slice/branch object previously. I have now implemented such a helper so thought I'd share it here. **It's a lightweight wrapper using existing methods.** It significantly simplifies interacting with nested store-models, imo.

**EDIT July 30, 2019**: Update code and added suggestion for string-options in _all_ store methods.
**EDIT August 3, 2019**: Add useStoreState hook example
**EDIT August 8, 2019**: Scrap useStoreState hook in favor of 'hook methods' on getStoreModel
**EDIT September 3, 2019**: Refine getSlice method to handle more

Note: In my app, I export a `getStore()`  helper so code _outside_ the app-context can access the store. This obviously wouldn't be needed if was internal to Easy-Peasy. I also included the simple `get()` helper I'm using. I do have a test for getStoreModel.

**`getStoreModel()` Helper**

````javascript
/**
 * Simple path-recursion helper to parse a path-string delimited by periods.
 * NOTE: This method WILL throw() an error if path does not exist; by design.
 *
 * @param {Object} obj    Any object
 * @param {string} path   Example: 'path.to.nested.model'
 * @returns {*}
 */
const get = (obj, path) => {
  if (!path) return obj;
  const keys = path.split('.');
  return keys.reduce((branch, key) => branch[key], obj);
};

/**
 * @param {(string|Function)} selector
 * @param {Object} [customStore]
 * @returns {Object}        An object representing the model, with properties and methods
 */
function getStoreModel(selector, customStore) {
  const store = customStore || getStore();

  /**
   * @param {(Object|undefined)} obj  Source object to extract value from
   * @param {(string|Function|undefined)} pathSelector
   * @param {*} param  Param to pass to computed() state method
   * @returns {*}
   * @throws {TypeError}  Throws if pathSelector is an invalid type
   */
  const getSlice = (obj, pathSelector = '', param) => {
    // Throw an error if passed path is something other than a string or a function
    // This is a code error so we want to catch it immediately
    if (pathSelector && !isFunction(pathSelector) && !isString(pathSelector)) {
      throw(new TypeError(
        `Path-selector passed to getStoreModel("${modelSelector}") should be` +
        ` a string or a function, but received: ${pathSelector}`
      ));
    }

    // First, get the model-slice of passed state, actions or listeners
    let slice;
    if (isString(modelSelector)) {
      slice = get(obj, modelSelector);
    } else {
      // Wrap call in try/catch because some objects, like 'listeners', may fail selector's path
      try {
        slice = modelSelector(obj);
      } catch(e) {
        slice = {};
      }
    }

    // Get path WITHIN the model-slice OR pass slice to selector function
    const value = isString(pathSelector)
      ? get(slice, pathSelector)
      : pathSelector(slice);

    // Handle computed-state methods - 'value' will be a function
    return isFunction(value) && !isUndefined(param)
      ? value(param)
      : value
  };

  const getState = key => getSlice(store.getState(), key);
  const getActions = key => getSlice(store.getActions(), key);
  const getListeners = key => getSlice(store.getListeners(), key);
  const useState = key => useStoreState(state => getSlice(state, key));
  const useActions = key => useStoreActions(actions => getSlice(actions, key));

  return {
    // The store object, just to be complete
    store,
    // Curried store methods, presented as 'properties'
    get state() { return getState() || {}; },
    actions: getActions() || {},
    listeners: getListeners() || {},
    // Curried store methods
    getState,
    getActions,
    getListeners,
    // Curried Hook methods
    useState,
    useActions,
  };
}
````

**Single-model object**

This helper allows code to be isolated to one 'store model', _as if_ the specified model is the entire store-model. **This avoids repetitive references to the path within the store - it makes code DRY**. The model object has methods that provide ALL applicable store functionality, including the hook helpers..

**Simple-object keys**

In addition to 'store methods', the model also exposes simple 'properties' for all item-types. **Therefore all model 'data' and 'methods' can be accessed _directly_ instead of by using the methods.** This includes `model.state`, which is a getter-method that is equivalent to calling `getState()`.

* **model.state.items** === model.getState().items
* **model.actions.fetch** === model.getActions().fetch
* **model.listeners.afterFetch** === model.getListeners().afterFetch

**Scoped Store-Hooks**

The `model.useState()` method is a _pass-through_ to the `useStoreState()` hook. This method is _scoped_ just like all the other methods. See the examples below.

A `model.useActions()` method is provides so the model is consistent with both standard hooks, even though there is no difference between `model.actions`, `model.getActions()` and `model.useActions()`. The `model.useActions()` method passes-through to the `useStoreActions()` hook, just in case some difference is introduced in the future.

**String-keys option for recursion**

**All methods accept a recursion-function _or_ a string-path.** Strings have a number of benefits: they are shorter and make it easy to 'share' a store-path. The examples below show a `modelPath` being exported from a component so it can be used in tests, so the tests _do not_ require any hard-coded store paths.

**I suggest that ALL Easy-Peasy methods _and_ hooks accept string paths, like:**
````javascript
const items = useStoreState('path.to.model.items')
````
It's a simple update that provides a lot of flexibility. A path is easily converted to a getter-function. If users need something more complex, like array-traversal, then they can use a recursion-function.

This example shows _numerous ways_ that model state and actions can be accessed...

**`getStoreModel()` Examples**

````javascript
// MyComponent.js
import { getStoreModel } from 'src/data/store';

export const modelPath ='path.to.nested.model';

function MyComponent(props) {
    // Accepts a string-path OR a method
    const model = getStoreModel(modelPath);
    const model = getStoreModel(obj => obj.path.to.nested.model);
 
    // getState method returns model-root-state OR accepts a key-string
    const data = model.state.data;
    const data = model.getState().data;
    const data= model.getState('data');
    // Sub-keys are even more versatile 
    const items = model.state.data.items;
    const items = model.getState().data.items;
    const items = model.getState('data').items;
    const items = model.getState('data.items');

    // getActions method works the same
    const fetchItems = model.actions.fetchItems;
    const { fetchItems } = model.actions;
    const fetchItems = model.getActions().fetchItems;
    const fetchItems = model.getActions('fetchItems');
    const { fetchItems } = model.getActions();

    // getListeners method works the same
    const { afterFetch } = model.listeners;
    // etc.
}
````

**`model.useState()` Examples**

````javascript
import { getStoreModel } from 'src/data/store';

export const modelPath = 'path.to.nested.model';

function MyComponent(prop) {
  // Create a reusable, curried object
  const model = getStoreModel(modelPath);

  const data = model.useState('data');
  const items = model.useState(state => state.items);

  const getData = model.useActions('getData');
  const { getData } = model.useActions();
  ...
}

function MyComponent(prop) {
  // Use object & method as single-statement hooks
  const data = getStoreModel(modelPath).useState('data');
  const { getData } = getStoreModel(modelPath).useActions();
  ...
}
````

**`getStoreModel()` Tests Example**

**Using getModel with a string-path allows **a single source of truth** for the model.** This path-string can be exported so tests are _automatically_ kept in perfect sync. For example, here is a test based on `<MyComponent>` above...

````javascript
// MyComponent.test.js
import { createStore, getStoreModel } from 'src/data/store';

import MyComponent, { modelPath } from './MyComponent';

test('it works', () => {
    const store = createStore();
    const model = getStoreModel(modelPath, store);
    // If part of Easy-Peasy, then could be one of...
   // const model = store.getModel(modelPath);
   // const model = createStore().getModel(modelPath);

    model.actions.addItem({ id: 1 });
    expect(model.state.items[0]).toEqual({ id: 1 });
});
````

This example does not actually test `<MyComponent>`. It's intended only to show that we can interact with the store-model without hard-coding the model-path within the test. There is a single-source-of truth for the `modelPath`, used by _both_ the component and the tests. This greatly simplifies refactoring the store structure.

**Conclusion**

**I believe scoped access has a lot of benefits (obviously).** I think many users would find it a useful option. It's just a wrapper so does not affect any existing functionality. Even adding the string-capability to existing store methods would not require much work

**Comment by ctrlplusb** [comment]
Thanks for opening this @allpro - I need to find some time to properly sit and digest this. Lots going on for me right now. Shall get to it ASAP. 👍

**Comment by allpro** [comment]
No hurry. Thanks for your dedicated efforts working on EP v3.

*Here's a further idea for when you have time...*

This `getSlice()` method & hook is really an 'add-on', because it 'extends' the library without requiring changes to core functionality. Perhaps there is a way to add a 'plugins' interface to EP for things like, which could...

- Integrate _optional_ features, without adding everything to the 'core' library.

- Provide a way to 'test' potential new features without changing the EP version. A popular plugin could eventually be _promoted_ to the core library.

- Encourage community input by providing a standard 'interface' for enhancements. Users can create and _demonstrate_ their ideas instead of just making a feature request. 

- Encourage _sharing_ of enhancement ideas between users. A simple discussion page on the website could handle this.

If some users create hacky plugins, it doesn't matter. Other users may offer feedback to refine it. Even if a plugin is not elegant, it may still illustrate a good concept, and get community feedback.

A plugin interface should/could offer...

- A way to access internal methods, probably by receiving an object with internals as 'methods'.

- The ability to _extend_ the store object. This includes both new methods (`store.getSlice()` as well as _overriding_ the core methods. (see conceptual example below)

- Allow some internal logic to be overridden by extracting things to API methods. For example, instead of _hard-coding_ `a === b`, move this to an `api.isEqual` method so it can be overridden/enhanced.

````javascript
// Simplistic concept
const store = {...}
const api = {...};
plugins.forEach(plugin => {
    Object.extend(store, plugin(api));
}
````

Another example is the recently discussed `getState()` _enhancement_ of adding an _optional_ equality-test param. This could be a plugin that _overrides_ the standard getState method with an enhanced version, which calls the core method after applying it's own equality test.

If you like this idea then you could start with the easiest to implement plugin interface. More internals could be exposed when/if deemed worthwhile.

The one thing that probably had to remain external is a new 'hook'. This is minor in comparison to the ability to enhance the store though.

In my case this would _sync_ `store.getSlice()` (internal) and `useStoreSlice()` (external). Currently I use an _external_ `getStoreSlice(store, path)`. *I'd prefer this to be core functionality.* However a plugin would be the next best thing.

More food for thought!

**Comment by ctrlplusb** [comment]
@allpro whilst I can see how this can be useful I am going to pass on this for now. I'll leave this type of API wrapping to user land implementations. 👍
