### ISSUE TITLE
Reusing schemas

### ISSUE THREAD

**Issue by siefkenj** [ctrlplusb/easy-peasy#284]
I have "real" state and "test" state. I want the test state to have the same schema as the real state, and so I constructed the store-model like:

```javascript

const model = {
   a: null,
   setA: action((state, payload) => { state.a = payload })
}

model.test = { ...model }
```

However, 

```javascript

const setA1 = useStoreAction(a => a.setA)
const setA2 = useStoreAction(a => a.test.setA)
setA1(54)
setA2(55)
```

will both set `state.test.a`.

Is there another way I should be cloning my schema? (Using version `3.0.0-rc6`)

**Comment by ctrlplusb** [comment]
I've changed the title as it is was a bit misleading.

This is really a matter of preference, and is [discussed within a recipe](https://easy-peasy.now.sh/docs/recipes/generalising-models.html).

I will say that I would lean towards creating a function to encapsulate the schema.

One way could be:

```javascript
const setterSchema = () => ({
  a: null,
  setA: action((state, payload) => { state.a = payload })
});

const model = {
  ...setterSchema(),
  test: setterSchema()
};
```

Or you could make the function a decorator.

```javascript
const withSetterSchema = (model = {}) => ({
  ...model,
  a: null,
  setA: action((state, payload) => { state.a = payload })
});

const model = withSetterSchema({
  test: withSetterSchema()
});
```
