### ISSUE TITLE
Nested stores and providers

### ISSUE THREAD

**Issue by olup** [ctrlplusb/easy-peasy#285]
Hey,

I try to use easy-peasy as my main global store - no pb.

I also want easy peasy to manage my localized store, in a specific part of my app - let's say the search part. It is a hooked store nevertheless because I want all my complex search architecture to access the store.

However, the provider of the search store, nested inside the global app store provider, overrides the whole store. Then, I cannot access my global app store from the search part of my app.

Is that a design that is managable with easy peasy ? 

I like my app decoupled and my stores placed near my components, is easy-peasy the good tool for this ?

I love it so much otherwise that it would be hearthbreaking to be limited that way.

**Comment by ctrlplusb** [comment]
Hey @olup 

Check out the extended API docs, detailing [createComponentStore](https://easy-peasy.now.sh/docs/extended-api/create-component-store.html) and [createContextStore](https://easy-peasy.now.sh/docs/extended-api/create-context-store.html), which allow you to do exactly this.

👍

**Comment by olup** [comment]
Ooops ! I read this part indeed but guess I overlooked it. Thanks for the
quick response !

Le lun. 29 juil. 2019 à 12:31, Sean Matheson <notifications@github.com> a
écrit :
