### ISSUE TITLE
Idea: Plugins Interface

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#287]
I suggest _considering_ a 'plugins interface' in EP. This would allow extensions to core functionality and syntax without bloating the library.

**This is not a priority for v3.0.0**, but something to consider as it might influence how EP internals are structured.

The content below is from a comment I originally left on another issue, so mentions of "getModel()" refer to _that_ suggestion (#282 )...

This `getModel()` method & hook is really an 'add-on', because it 'extends' the library without requiring changes to core functionality. Perhaps there is a way to add a 'plugins' interface to EP for similar things, which could...

- Integrate _optional_ features, without adding everything to the 'core' library.

- Provide a way to 'test' potential new features without changing the EP version. A popular plugin could eventually be _promoted_ to the core library.

- Encourage community input by providing a standard 'interface' for enhancements. Users can create and _demonstrate_ their ideas instead of just making a feature request. 

- Encourage _sharing_ of enhancement ideas between users. A simple discussion page on the website could handle this.

If some users create hacky plugins, it doesn't matter. Other users may offer feedback to refine it. Even if a plugin is not elegant, it may still illustrate a good concept, and get community feedback.

A plugin interface should/could offer...

- A way to access internal methods, probably by receiving an object with internals as 'methods'.

- The ability to _extend_ the store object. This includes both new methods (`store.getModel()` as well as _overriding_ the core methods. (see conceptual example below)

- Allow some internal logic to be overridden by extracting things to API methods. For example, instead of _hard-coding_ `a === b`, move this to an `api.isEqual` method so it can be overridden/enhanced.

````javascript
// Simplistic concept
const store = {...}
const api = {...};
plugins.forEach(plugin => {
    Object.extend(store, plugin(api));
}
````

Another example is the recently discussed `getState()` _enhancement_ of adding an _optional_ equality-test param. This could be a plugin that _overrides_ the standard getState method with an enhanced version, which calls the core method after applying it's own equality test.

If you like this idea then you could start with the easiest to implement plugin interface. More internals could be exposed when/if deemed worthwhile.

The one thing that probably has to remain external is a new 'hook'. This is minor in comparison to the ability to enhance the store though.

In my case this would _sync_ `store.getModel()` (internal) and `useStoreModel()` (external). Currently I use an _external_ `getStoreModel(store, path)`. **I'd prefer getModel to be core functionality.** However a plugin would be the next best thing.

More food for thought!

**Comment by dpyzo0o** [comment]
What's the status of this?  I think it's a really good idea which we can already see in rematch and dva.  One feature I like most from them is the loading plugin.  If we have the plugin system we can easily add this feature as a plugin.

**Comment by ctrlplusb** [comment]
Closing in favour of #411
