### ISSUE TITLE
Debug still not unwrapping state

### ISSUE THREAD

**Issue by bmccord** [ctrlplusb/easy-peasy#289]
I saw this posted under #229 which has been closed and I commented on that issue.  Sadly, it is still happening.

Example at: https://codesandbox.io/s/easy-peasy-tutorial-computed-02di7

Look in basket-model.js. Add an item to the basket. Output is:
Brian
common-sandbox.d6a25806.chunk.js:8 Proxy {scope: ImmerScope, modified: false, finalized: false, assigned: {…}, parent: {…}, …}

**Comment by gupei515** [comment]
I am having the same issue

**Comment by baschte** [comment]
I have the issue as well. Getting only the Proxy stuff.

**Comment by joelmoss** [comment]
Just use immer's `original` instead. Same thing I believe.

**Comment by joelmoss** [comment]
Although FWIW, I don't think easy-peasy should be aliasing this. I see no benefit, and as this ticket demonstrates; it increases the surface area for bugs.

I'd recommend you use Immer's `original` directly, and I'd suggest that easy-peasy should remove the `debug` wrapper.

Just my 2 cents 🙂

**Comment by ctrlplusb** [comment]
It's not strictly an alias, it does a basic check too, however, I would grant that it provides little value.

I will take your 2 cents into consideration and may consider deprecating the helper.
