### ISSUE TITLE
How to have type intellisense in v3 ?

### ISSUE THREAD

**Issue by nateshmbhat** [ctrlplusb/easy-peasy#290]
In V2 , I used to export my own useStoreActions as below : 

**myStore.ts**
```
const store = createStore(initialState);

export const useStoreActions = store.useStoreActions;
export const useStoreDispatch = store.useStoreDispatch;
export const useStoreState = store.useStoreState;

```

So when I am using the store by importing the useStoreActions and useStoreState as shown above , I would get typescript code intellisense .
```
import {useStorateState,useStoraeActions } from './myStore' ;


const [globals, profiles, configFlags] = useStoreState((state) => [state.globals, state.profiles, state.terminalConfig])
const [setGlobals, setKeybinding] = useStoreActions((actions) => [actions.setGlobals, actions.setSpecificKeyBinding]);
``` 

But in V3 , since there are no properties like useStoreActions and useStoreDispatch on the store object thats created , I don't have a way to get the type suggestions and have to use the useStoreState method from 'easy-peasy'.

How do I work around it ? 

I figured I can still get all actions using store.getActions . Does using this cause unnecessary renders ? I strongly think the docs should mention about what exactly to use given the several ways taking performance into account .

**Comment by ctrlplusb** [comment]
Hey @nateshmbhat

You are in luck.

See the release notes:
https://github.com/ctrlplusb/easy-peasy/releases/tag/v3.0.0

The TypeScript tutorial:
https://easy-peasy.now.sh/docs/typescript-tutorial/typed-hooks.html

And the TypeScript API:
https://easy-peasy.now.sh/docs/typescript-api/create-typed-hooks.html

As a note, I specifically bumped the major (i.e. from V2 to V3) to indicate the fact that there are breaking changes. I'd strongly suggest reading the release notes for any library you use that does the same.

**Comment by nateshmbhat** [comment]
I had read the release notes. What I don't understand is how to still get type suggestions when using the useStore hook of easy-peasy

**Comment by nateshmbhat** [comment]
Can u please provide a code sample?

**Comment by nateshmbhat** [comment]
Thank u so much 😊
