### ISSUE TITLE
Computed runtime arguments not working

### ISSUE THREAD

**Issue by pranaypratyush** [ctrlplusb/easy-peasy#293]
I have a computed defined like this...

```
getBase64Video: computed([state => state.video], video => {
      return botid => {
        try {
          let b64 = btoa(video[botid].image);
          return `data:image/jpeg;base64,${b64}`;
        } catch (e) {
          console.log(e);
        }
      };
    })
```
And I get the error `hooks.js:42 Uncaught Error: An error occurred trying to map state in a useStoreState hook: state.bots.getBase64Video is not a function.` when I try calling it with `let video = useStoreState(state => state.bots.getBase64Video(props.botid));`

**Comment by ctrlplusb** [comment]
Hey @pranaypratyush - would you mind creating a reproducible example in codesandbox please?

**Comment by pranaypratyush** [comment]
I figured it out. It's incompatible with redux-persist. Anything I can do to fix it?

**Comment by ctrlplusb** [comment]
There are a few issues created discussing redux-persist, I would recommend reading those. If you are unable to solve your problem a reproducible example would help.

**Comment by pranaypratyush** [comment]
The problem is specifically that if a `computed` returns a function then redux-persist with cause problems with it. I used `redux-persist-transform-filter` to filter it out and there are no problems now. In fact, I would want a way for `redux-persist` to ignore all computed fields.

**Comment by HZahran** [comment]
@pranaypratyush Actually i had the exact same issue before with both `redux-persist` and `computed` fields in which i did the same approach of using `redux-persist-transform-filter` at the end

However after installing the **latest version 3.0.1** and tried adding a computed field to the white list, it's working properly now.

Here's my config inside the `createStore()` function

```
reducerEnhancer: reducer => {
    return persistReducer(
      {
        key: "store",
        storage,
        whitelist: ["auth", "user"], 
        stateReconciler: autoMergeLevel2,
        transforms: [
          createWhitelistFilter("auth", [
            "accessToken.data",
            "loginType",
            "isLoggedIn"
          ]),
          createWhitelistFilter("user", ["details.data"])
        ]
      },
      reducer
    );
  }
```
`isLoggedIn` is the computed field and is being persisted and re-hydrated properly now.
