### ISSUE TITLE
Broken links on Quick Start page

### ISSUE THREAD

**Issue by luceliu** [ctrlplusb/easy-peasy#295]
On the [Quick Start](https://easy-peasy.now.sh/docs/quick-start.html) page there are multiple links to parts of the API, e.g. store, createStore, storeProvider. Unfortunately, they are currently broken as each link is missing a `.html`, resulting in the following error message:
```
The page could not be found.
The page could not be found in the application.

404: NOT_FOUND
Code: FILE_NOT_FOUND
ID: cle1:zxmrd-1565123242469-482b1104dc02
```
e.g. under "Use a model to define your store," the link is `https://easy-peasy.now.sh/docs/api/store` instead of `https://easy-peasy.now.sh/docs/api/store.html`.

**Comment by ctrlplusb** [comment]
Thanks so much for bringing this to my attention.
