### ISSUE TITLE
State Setters boilerplate: suggestions, counter-arguments?

### ISSUE THREAD

**Issue by DrYSG** [ctrlplusb/easy-peasy#297]
I find that I am creating a lot of boilerplate setters for each StoreState object.

E.g.

```
const JobStore = {
    jobData: {},
    jobBoard: [],
    jobList: [],
    setJobData: action((state, payload) => {
        const json = JSON.stringify(payload, ' ', 4)
        state.jobData = json
    }),
    setJobBoard: action((state, payload) => {
        state.jobBoard = payload
    }),
    setJobList: action((state, payload) => {
        state.jobList = payload
    }),
```

I have to do this because my thunks cannot directly set the state (which I understand the reason for that).

But it is a common feature in OO Programming to be able to automate the creation of property accessors (get/setters) for Object properties.

The userStoreState() makes the getters trivial for store properties. What about some sort of shorthand we can use in a thunk  for property setters (a helper function?). I am only talking about items in the same store slice, (eg. setState() and not setStoreState() - but you could have that for folks that want to live dangerously).

**Comment by joelmoss** [comment]
I've done something similar but for single state changes, and created a `set` helper...

```javascript
import { action } from 'easy-peasy'
import { forEach, set } from 'lodash'

// Generic action to allow us to set/change the value of a path in the state. If the path does not
// exist, it will be created.
//
// See https://lodash.com/docs/#set
//
// Example:
//
//  set({ 'some.path': 'some value' })
export default action((state, payload) => void forEach(payload, (val, key) => set(state, key, val)))
```

Just add append to your model when creating the store...

```javascript
createStore({ ...model, set })
```

I've only done it for single state props, as I think it would be asking for trouble allowing complete and unknown state changes.

Hope that helps a little tho ;)

**Comment by DrYSG** [comment]
@ctrlplusb Any chance we can get a officially supported way of doing this correctly?

**Comment by DrYSG** [comment]
I did not hear back from anyone. But can anyone tell me if this is a bad pattern to use where the thunk gets the slice of the store it wants to set, and instead of an explicit setXXX action in the store, it directly sets the value (given that is is the only thunk or action that will be updating the store property, so we don't have a multiple writers issue).

```
    fetchOpList: thunk(async (actions, payload, { getStoreState, getStoreActions }) => {
        const data = await RAction.fetchOpList(getStoreState().jobFields.JobNum)
        getStoreActions().job.setJobData(data)
        const me = getStoreState().runner
        me.TOL = data
        //actions.setTOL(data)
```
where

```
const RunnerStore = {
    TOL: TOL,
    opBoard: null,
    ResourceGrpID: "STSRG",
    LaborHedSeq: '',
    LaborDtlSeq: '',
    EmployeeName: '',
    setTimeLeft: action((state, payload) => {
        state.timeLeft = payload
    }),
    setTOL: action((state, payload) => {
        state.TOL = payload
    }),

````

**Comment by DrYSG** [comment]
@ctrlplusb & @joelmoss 

I have been using the following technique in all my EasyPeasy Stores for doing a state setter (that can easily be access from a thunk().) Do you see this as a bad pattern? Can it be improved on?

```
const JobListStore = {
    jobList: [],
    response: "",
    boardState: "table",
    currentJob: "",
    boardStore: null,
    set: action((state, payload) => {
        Object.entries(payload).forEach(([key, value]) => {
            state[key] = value
        })
    }),    ...


```

and then in the thunk I use it like this:

```
        actions.set({ boardState: "completeMove", currentJob: job.GUID_c })
```

**Comment by DrYSG** [comment]
also, since a thunk can be written without async functions (which then lets you get to the very useful helper functions, which you do not have with actions) - is there any reason to have both actions and thunks()?


```
    cancelMove: thunk((actions, payload, {getStoreState}) => {
        const job = getStoreState().job
        actions.set({ boardState: "table", currentJob: "" })
    }),
```

**Comment by DrYSG** [comment]
One can also make this a bit more robust by using the immer {original} function:

```
    set: action((state, payload) => {
        const base = Object.keys(original(state))
        Object.entries(payload).forEach(([key, value]) => {
            if (base.includes(key)) 
                state[key] = value
        })
    }),
``

**Comment by ctrlplusb** [comment]
@DrYSG - I am going to shy away from introducing additional abstractions as being described above. My gut feeling is that this should belong in user-land. It is fairly easy to introduce your own helpers/abstractions in order to achieve what you feel is necessary on a per case basis.

Thanks for going through this in detail though. Perhaps others can learn from your journey if they visit this issue. 👍
