### ISSUE TITLE
how to apply a middleware like redux-logger with easy-peasy ? 

### ISSUE THREAD

**Issue by nateshmbhat** [ctrlplusb/easy-peasy#299]

**Comment by ludwigbacklund** [comment]
The `[config](https://easy-peasy.now.sh/docs/api/store-config.html#advanced-configuration)` object of `createStore`

**Comment by ctrlplusb** [comment]
Hey @nateshmbhat,

Yep, please see the documentation linked by @ludwigbacklund above. Shout if anything is unclear. ✌️
