### ISSUE TITLE
Make return type of action more strict

### ISSUE THREAD

**Issue by timolins** [ctrlplusb/easy-peasy#301]
I'm using easy-peasy without `immer`, so I depend on returning the immutable states. While doing so, I found out that I can return any properties I want, as long as I include all required properties, which will always be the case as long as I spread the previous state.

```ts
import { Action, action } from 'easy-peasy'

interface TokenModel {
	token: string
	updateToken: Action<TokenModel, string>
}

export const tokenModel: TokenModel = {
	token: '',
	updateToken: action(
		(state, token) => ({
			...state,
			token,
			foo: 'bar',     // 👈 Should not be allowed
			anything: 123,  // 👈
			here: [1, 2, 3] // 👈
		})
	)
}
```
> Live demo on [CodeSandbox](https://codesandbox.io/s/frosty-shaw-kvd07)

A possible workaround would be to explicitly set the return type of the action `action((): State<TokenModel> => {})`, but this is not too elegant.

I had quick look at the types but wasn't able to pin-point the issue – so maybe someone here can help.

**Comment by ctrlplusb** [comment]
I think this may depend on [this](https://github.com/microsoft/TypeScript/issues/12936) TS feature being added.
