### ISSUE TITLE
Write an article for Programmez! magazine

### ISSUE THREAD

**Issue by phmatray** [ctrlplusb/easy-peasy#302]
Hello, 

I was contacted by **programmez!** magazine, the developers' magazine, to write an article about javascript.
I thought I would talk about easy-peasy by emphasizing the added value that an architecture with service injection brings.
React is unfortunately (in Belgium and France) still little used for enterprise grade projects and easy-peasy could help.

what do you think of it?
do you have any suggestions?

**Comment by ctrlplusb** [comment]
Hey @phmatray 

Wow man this sounds great. I am honoured you would even consider using easy peasy as a topic.

I trust your judgement in terms of what you feel is best for the audience of the magazine and would be happy to review any content (I may need to lean on Google translate though 😄).

Keep me posted. I'd be happy to help in any way I can.

**Comment by phmatray** [comment]
Today, I wanted to do a test to integrate WebSocket with easy-peasy.
I abandoned the idea of working with a middleware that returned a "meta" property in addition to the "payload".

And I finally started from a simpler solution but is it the best one?
Do you have any suggestions?

```javascript
import { action, thunk, computed } from 'easy-peasy';

export const socketModel = {
  connected: false,
  readyState: null,
  socket: null,
  messages: [],

  lastMessage: computed(({ messages }) => {
    return messages.length === 0 ? '' : messages[0];
  }),

  socketConnectionInit: action((state, socket) => {
    state.connected = false;
    state.socket = socket;
  }),

  socketConnectionSuccess: action(state => {
    state.connected = true;
  }),

  socketConnectionError: action(state => {
    state.connected = false;
  }),

  socketConnectionClosed: action(state => {
    state.connected = false;
    state.socket = null;
  }),

  socketMessage: action((state, data) => {
    // You can ALSO listen this action to do your logic with 'actionOn'
    state.messages.unshift(data);
  }),

  initializeSocket: thunk((actions, url, helpers) => {
    const socket = new WebSocket(url);
    actions.socketConnectionInit(socket);

    socket.onopen = () => {
      socket.send('hey');
      actions.socketConnectionSuccess();
    };

    socket.onerror = error => {
      console.error(`WebSocket error: ${error}`);
      actions.socketConnectionError();
    };

    socket.onmessage = event => {
      console.log(event.data);
      actions.socketMessage(event.data);
    };

    socket.onclose = () => {
      actions.socketConnectionClosed();
    };
  })
};
```

**Comment by ctrlplusb** [comment]
How did it go @phmatray ?
