### ISSUE TITLE
What is the recommended approach for returning "success" status back to the UI?

### ISSUE THREAD

**Issue by shoeman22** [ctrlplusb/easy-peasy#303]
The error case seems straight forward, populate some `actionYouRanErrorMessage: null` state variable and when it becomes non-null show an error.

The success case is easy if you're doing something that you care about the data return on like say `login`.  Check if the state variable `authenticationToken: null` is now non-null and you can assume you have a successful login.

But for an action like say `sendPasswordReset` you are just getting a status back from the return call, but you wouldn't think to really care about any state on it really.  So far my thought is to have a `sendPasswordResetSuccess: false` variable and toggle it true when the request finishes but this doesn't feel elegant.

Is there a better / recommended way to handle this use case?

**Comment by Asrover** [comment]
You can to use [listener](https://easy-peasy.now.sh/docs/api/listeners.html) **actionOn** for action **sendPasswordReset** and perform actions depending on server response.
```
actionOn(
    actions => [
        actions.login.startType,
        actions.login.failType,
        actions.login.successType,
    ],
    (state, target) => {
        const [start, fail, success] = target.resolvedTargets;
        
        switch (target.type) {
            case start:
                state.loading = true;
                break;
            case fail:
                state.loading = false;
                state.error = target.error;
                break;
            case success:
                state.loading = false;
                state.user = target.result;
                AuthService.setToken(target.result.token);
                break;
        }
    },
),
```

**Comment by ctrlplusb** [comment]
@shoeman22 another consideration is that you can utilise the return from a thunk to determine of an error/success occurred at the call site.

Closing this for now, as it's more of a philosophical discussion around state organisation.
