### ISSUE TITLE
State in useStoreState calculated 2x on every state change

### ISSUE THREAD

**Issue by Ivannnnn** [ctrlplusb/easy-peasy#307]
[Codsandbox (short) example](https://codesandbox.io/s/sharp-darkness-svbtj)

Open console.
Why do you see "calculating state" logged 2x initially & 2x on every input onChange?

**Comment by ctrlplusb** [comment]
Wow, thanks for raising this @Ivannnnn - I've found the issue. Shall release a patch soon. 🙏

**Comment by ctrlplusb** [comment]
Hi @Ivannnnn - actually this isn't a bug. There is one case where it runs unnecessary, but every other case is expected with the current configuration. To be clear though your component isn't rerendering, it's only the selector being executed again to ensure that a change hasn't come via redux/parent component. I will provide more detail on this soon. You can avoid the double call by lifting your selector function into a constant but honestly this should make near 0 perf impact in almost every case.
