### ISSUE TITLE
Interop with an existing React Redux application

### ISSUE THREAD

**Issue by jaredmeakin** [ctrlplusb/easy-peasy#309]
I have a current React application that makes heavy use of combine reducers, and in some cases those reducers are nested. Is my only course of action to replace all instances of combined reducers with easy-peasy's reducer function?

Just trying to find some alternative options before I trudge down the refactor route. Thanks!

**Comment by ctrlplusb** [comment]
Hey @jaredmeakin 

AFAIK you _should_ only need to replace the root level with easy peasy's `reducer`. Any nested `combineReducers` calls should be fine. 👍
