### ISSUE TITLE
cause problem when a model used both in createComponentStore and createStore

### ISSUE THREAD

**Issue by hardfist** [ctrlplusb/easy-peasy#318]
easy-peasy: 3.0.0

**Comment by hardfist** [comment]
demo here https://github.com/hardfist/hardfist_tools/blob/master/packages/spa/src/components/counter/index.tsx

**Comment by ctrlplusb** [comment]
Thanks for the report. I'll see if I can create a test case to verify this. 👍

**Comment by ctrlplusb** [comment]
Yeah, I reviewed the code and can already see the culprit here. Due to mutation rather than using an immutable approach. I'll definitely patch this up for the v3.4.0 release. 👍

**Comment by ctrlplusb** [comment]
Hi @hardfist - this should be fixed in the latest beta; `easypeasy@3.4.0-beta.1`.

Would you mind try it out for me?
