### ISSUE TITLE
Correct way to cancel request in thunk

### ISSUE THREAD

**Issue by filipjnc** [ctrlplusb/easy-peasy#323]
Coming from redux-observable and rjxs, I'm rubbing my head on how to cancel a request using thunks in easy-peasy. I couldn't find anything in the docs and I don't want to create my own over-engineered method to do it.

With redux-observable I'd have up to four actions for a resource:
```
import { createAsyncAction } from 'typesafe-actions';
export const fetchAsync = createAsyncAction(
  'SKILLS_FETCH',
  'SKILLS_FETCH_SUCCESS',
  'SKILLS_FETCH_FAILURE',
  'SKILLS_FETCH_CANCELLED',
)<undefined, EntityList<Resource>, ApiError, undefined>();
```
and then create the following epic:
```
export const fetchEpic: MyEpic = (action$, state$, { api }) => 
  action$.pipe(
    filter(isActionOf(fetchAsync.request)),
    switchMap(() =>
      from(api.skills.getAll()).pipe(
        map(response => response.data),
        map(fetchAsync.success),
        catchError(error => of(fetchAsync.failure(error.response))),
        takeUntil(action$.ofType(fetchAsync.cancel)),
      )
    )
  );
```
where the following line would cancel the execution of `fetchAsync.success` or `fetchAsync.failure` if the action `fetchAsync.cancel` is dispatched:
`takeUntil(action$.ofType(fetchAsync.cancel)),`

**Comment by ctrlplusb** [comment]
Sorry just a quick note. I have been distracted the past month. You can return out of a think to the caller. Therefore you could return a cancellable promise/stream and have the unmount of your component do the necessary.

**Comment by ctrlplusb** [comment]
i.e. you could also return a function which would do the cancel and dispatch an action to represent the cancel (if you need)

**Comment by filipjnc** [comment]
@ctrlplusb Makes sense, thanks!
