### ISSUE TITLE
What am I doing wrong with this nested array / lookup type?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#325]
I'm not sure if this is a easy-peasy or typescript issue.
This is my first time using lookup-types.

```typescript
// user.ts

import { Action, action } from 'easy-peasy';

export interface UserModel {
  token: {
    auth0Id: string;
    email: string;
    name: string;
  }[];
  setToken: Action<UserModel['token'], object>;
}

export const user: UserModel = {
  token: undefined,
  setToken: action((state, payload) => {
    state.token = { ...payload };
  }),
```

But I'm getting this error on state.token.
![image](https://user-images.githubusercontent.com/689204/66089935-24ce3800-e536-11e9-8247-489afc2e9ae7.png)

Does this have to do with the `action` import or should I look somewhere else?

_Feel free to close if this is a typescript issue and I'll ask somewhere else._

Thanks! 👍

**Comment by ctrlplusb** [comment]
Hi @GollyJer 

Have you tried something like this:

```typescript
// user.ts

import { Action, action } from 'easy-peasy';

export interface UserModel {
  token: {
    auth0Id: string;
    email: string;
    name: string;
  }[];
  setToken: Action<UserModel, UserModel['token']>;
}

export const user: UserModel = {
  token: undefined,
  setToken: action((state, payload) => {
    state.token = [ ...payload ];
  }),
```

The first type argument to `Action` must be the model, the second being the payload type against which we can use your lookup type. 👍 

I see your token is declared as an array of objects. Is this correct?

**Comment by ctrlplusb** [comment]
Personally I would do:

```typescript
// user.ts

import { Action, action } from 'easy-peasy';

export interface Token {
    auth0Id: string;
    email: string;
    name: string;
}

export interface UserModel {
  token: Token | undefined;
  setToken: Action<UserModel, UserModel['token']>;
}

export const user: UserModel = {
  token: undefined,
  setToken: action((state, payload) => {
    state.token = { ...payload };
  }),
```

As your token can be undefined you should declare that as being the case. Also, I have assumed here you didn't mean token to be an array.

**Comment by GollyJer** [comment]
Hey @ctrlplusb. Thanks for the help! 
_Sorry for not getting back to you sooner._

Your first approach works great. 👍
(and yes I didn't mean for it to be an array).

With the second approach I get 

> 'Token' only refers to a type, but is being used as a value here.  ts(2693)

on the line ` token: Token | undefined;`
