### ISSUE TITLE
actionOn / thunkOn every failType

### ISSUE THREAD

**Issue by marvinroger** [ctrlplusb/easy-peasy#326]
Hi,

Thanks for easy-peasy, it helped making our code cleaner. 😉
I have a common use-case on which I haven't been able to find any info in the docs or in the issues.

We want to dispay an error overlay wherever there's a specific network error. In other words, we want to `actionOn` on every `failType`, then we can get the `target.error` and check whether or not this is a network error.

Currently, we can specifiy as target resolvers: `[storeActions.todo.saveTodo.failType, storeActions.todo.removeTodo.failType, ...]`, but we obviously don't want to do that for every possible thunk. Is there a way to do that? Or is this an acceptable feature request?

Thanks!

**Comment by ctrlplusb** [comment]
Hey @marvinroger 

If you purely want to do state updates (i.e. not a thunk) you could use the reducer type and then do a regex style pattern match on the incoming actions. 👍

**Comment by marvinroger** [comment]
Thanks for your answer.
Yes, that's what we ended up doing. So, what if we want a thunk instead?

**Comment by ctrlplusb** [comment]
My suggestion would be to consider a custom middleware for this case.

It's slightly more complex however it feels like an edge case in terms of a models structure.

**Comment by marvinroger** [comment]
Alright, I thought it was a quite common use case. 😉
Perhaps some docs on a recommended error handling method would be useful then!
Anyway, I'll close this ticket. Thanks again for the great lib. 👍
