### ISSUE TITLE
actionOn for *all* actions

### ISSUE THREAD

**Issue by otang** [ctrlplusb/easy-peasy#327]
I'd like to react to *all* changes to my store. How best can I subscribe to this event?

The use-case is that I want to save state to localStorage whenever a change is made. And, when the app loads, hydrate initial state from local storage.

Thanks

**Comment by ctrlplusb** [comment]
Hey @otang 

One option would be to utilise the store.subscribe method, potentially adding a denounce on it too in order to avoid heavy writes to local storage. 

Rehydration could be done at store create time via the initialState config option.

**Comment by otang** [comment]
Thank you that worked perfectly.
