### ISSUE TITLE
expose useLocalStore and useContextStore

### ISSUE THREAD

**Issue by hardfist** [ctrlplusb/easy-peasy#328]
It will be very convenient to expose `useLocalStore` and `useContextStore`,
since It already expose `useStore` and I think expose `useLocalStore` and `useContextStore` also make sense , and will simplify the work to switch between local model and redux model。

**Comment by ctrlplusb** [comment]
I'm not sure I am understanding the benefit/API here. Could you please explain further?

What does it give you that [`createComponentStore`](https://easy-peasy.now.sh/docs/extended-api/create-component-store.html) and [`createContextStore`](https://easy-peasy.now.sh/docs/extended-api/create-context-store.html) can't?

**Comment by hardfist** [comment]
The thing I like most about`easy-peasy` is that, the model can be used both at global level and component level without any change which make `easy-peasy` fractal . And most of the situation is that I just want to use the model abstraction but don't want put my state to global store( for locality and not pollute global store).
but it's kind of cubersome that I always need to create an local hook and then use the local hook, so 
```typescript
const useLocalStore = createComponentStore(model);  // most of case , this is unnecessary
const [ state,actions] = useLocalStore();
```
which could be simplified by 
```
const [state,actions] = useLocalStore(model);  // use local store
// const [state,actions] = useReduxStore(model); // use Redux Store 
```
and we can easily refactor our local store to redux store, which is very common

**Comment by ctrlplusb** [comment]
Superseded by #458
