### ISSUE TITLE
Handling try and catch logic, under thunks with a Higher Order Function.

### ISSUE THREAD

**Issue by yaldram** [ctrlplusb/easy-peasy#332]
- The Following is just a **Question** and not a **Bug**
- Hello all, I need some help regarding handling errors.
- Errors for 401 and 403 should be handled globally and the user should be redirected to Login Screen.
- For all other errors, I have my own Error Handlers.
-  My approach was to create a Higher Order Function like so
- **as we all know an easy-peasy thunk should always return a Promise in case of async functions and for listeners to work** : -

```javascript 
import { message } from "antd";

import { store } from "./index";

export const hoc = ({ loadingField, main, errorCallback, finallyBlock }) => (
  actions,
  payload
) => {
  if (loadingField) {
    actions.toggleLoading(loadingField);
  }
  return main(actions, payload)
    .then(_ => _)
    .catch(error => {
      if (!error) {
        message.error("Please Check Your Internet Connection");
        store.dispatch({
          type: "@action.users.logout"
        });

        return;
      }

      const { status, data } = error;

      if (status === 401 || status === 403) {
        message.error(data.message);
        store.dispatch({
          type: "@action.users.logout"
        });

        return;
      }

      if (errorCallback) {
        errorCallback(actions, error);
      } else {
        message.error(error.data.error);
      }
    })
    .finally(() => {
      if (finallyBlock) {
        finallyBlock(actions);
      } else if (loadingField) {
        actions.toggleLoading(loadingField);
      }
    });
}; 

```

- Second, my thunks are like below -

```javascript 
  editEmailConfigById: thunk(
    hof({
      main: async (actions, payload) => {
        actions.toggleLoading("editLoading");
        const { emailConfigId, updatedValues } = payload;
        const { data } = await editEmailConfigById(
          emailConfigId,
          updatedValues
        );
        actions.updateEmailConfigOnEdit(data.email_config);
        message.success("Updated Successfully");
      },
      errorCallback: error => {
      // My Custom Error Code
      },
      finallyBlock: actions => {
        actions.toggleLoading("editLoading");
      }
    })
  ),
```
- What I achieve by the `Higher Order Function` is I am able to reduce duplication while handling 
`401` and `403` errors and `No-Internet Connection`. 
- Most of my thunk errors I am just showing a simple message so I am just using `message.error()` in one place i.e. under the `HOC` reducing more duplication.

- `My Questions`
1. Is this the right way or `easy-peasy` way to handle try{}catch(){} in one place?
2. Is my abstraction right or should I opt for duplication over wrong abstraction?
3. I need to use `Promise.resolve().catch().finally()`, if instead I use `try{}catch(){}finally` under the Hoc , I am getting `Promised Unresolved`.

Thanks, Community for your help.

**Comment by yaldram** [comment]
@ctrlplusb Hello there,
I tried implementing the above `HOF` and for most cases, it is working, but when I follow the above approach with `Listeners` it is failing, and my fetch thunk fails with an empty error. Please guide. Thanks

**Comment by yaldram** [comment]
@ctrlplusb I am getting the data too and setting it but the component is not rerendering.

**Comment by yaldram** [comment]
Actually the following should be the correct Higher Order Function for Handling Error Request,
 **as we all know an easy-peasy thunk should always return a Promise in case of async functions and for listeners to work** : -

```javascript 
import { message } from "antd";

import { store } from "./index";

export const hoc = ({ loadingField, main, errorCallback, finallyBlock }) => (
  actions,
  payload
) => {
  if (loadingField) {
    actions.toggleLoading(loadingField);
  }
  return main(actions, payload)
    .then(_ => _)
    .catch(error => {
      if (!error) {
        message.error("Please Check Your Internet Connection");
        store.dispatch({
          type: "@action.users.logout"
        });

        return;
      }

      const { status, data } = error;

      if (status === 401 || status === 403) {
        message.error(data.message);
        store.dispatch({
          type: "@action.users.logout"
        });

        return;
      }

      if (errorCallback) {
        errorCallback(actions, error);
      } else {
        message.error(error.data.error);
      }
    })
    .finally(() => {
      if (finallyBlock) {
        finallyBlock(actions);
      } else if (loadingField) {
        actions.toggleLoading(loadingField);
      }
    });
};

```
The above function can be further broken down, for more readability and also variable names can be further improved.

**Comment by ctrlplusb** [comment]
Hey @yaldram;

Sorry for the late response.

I did something similar in another project of mine. 

I don't think there is any one right way here. Abstractions will come out on a per project basis. Start with the duplicated code always at first, and if the abstraction presents itself then you should of course feel free to move towards it.

A couple of minor notes...

You can do this instead to dispatch actions from your store:

```javascript
store.getActions().users.logout();
```

You can also access the global actions from the thunk API should you please, allowing you to avoid using the store directly. See the docs for thunk for more on this.

🙏

**Comment by yaldram** [comment]
@ctrlplusb Thanks a lot sir for your help. Another request for you Sir, please whenever you have time please please write a blog post regarding the easy-peasy library code itself. Like how this library is structured If I were to contribute to it or for example I want something like easy-peasy for Reason React. I was reading the library code it is very compact and the library itself is amazing. Thanks, easy-peasy team for the great work.

**Comment by ctrlplusb** [comment]
@yaldram that's great to hear that you are interested in contributing and/or creating Reason bindings.

I plan to do an internal architecture refactor which will make the code base far easier to reason about and contribute to. After I have done so I would be happy to create some sort of contributing guide and walkthrough of the codebase to invite collaborators. It would be great to have other people onboard helping to maintain the library.

💜

I think writing the Reason bindings will be easier than the TypeScript bindings. Their type system is far more powerful, and along with pattern matching I think it will be far easier to express some of the complex types I have had to create in the TypeScript definition.
