### ISSUE TITLE
How to use thunkOn middleware to get error details?

### ISSUE THREAD

**Issue by ramiglez30** [ctrlplusb/easy-peasy#333]
Hi, this is a question. 

How can I use thunkOn middleware and stage **failType** of target to get error detail? 

Thanks.

**Comment by ctrlplusb** [comment]
Hey @ramiglez30 

The `target` parameter for listeners (`actionOn`/`thunkOn`) will contain an error for a **failType**.

See the [respective docs here](https://easy-peasy.now.sh/docs/api/listeners.html).
