### ISSUE TITLE
Migrating from Redux && Extends Typescript Interface

### ISSUE THREAD

**Issue by MatthieuLab** [ctrlplusb/easy-peasy#334]
Hi all,

We are moving a stack [current stack] with a classical Redux/saga to a brand new stacks with two modules that we import. For sure those new modules use easy-peasy!

- One module contains the DataStore (connected to GraphQL).
- The other one contains AuthenticationStore.

We manage to remove nine on ten reducers thanks to those NPM Modules... But we have 2 reducers from this Front that have to stay there (and not in a module). We manage to create Easy-Peasy Models for those two and pass the models to the store. Houra! I have a store with everything.

But we are using Typescript.

NPMs are imported with the declaration files and I would like to extends the Interface. But it's not working. For sure the Type of state: IntermediateStateMapper contains everything that come from the module but when I try to pass my local settingsModel. Here where we are:
  
```
// this is NOT OK, come from the package
  const locale = useStoreState(
    (state: IntermediateStateMapper<SettingsModel, any>) =>
      state.settings.locale
  );

// this is OK, come from the package
  const user = useStoreState(state => state.user.user);
```

SettingsModel is my interface for my settingsModel. Quite simple: 

```
export interface SettingsModel {
  locale: string | null;
  changeLocale: Action<SettingsModel, string>;
}

```

For sure we can continue to use 

` const locale = useStoreState((state: any) => state.settings.locale);
`

But it's not as elegant that having a strong type.

I need some advice to smooth our migration. If one of you has already been confronted to this, I'd love the share.
Thanks,

Matthieu

**Comment by ctrlplusb** [comment]
Hey @MatthieuLab!

Happy to help. 

Firstly, have you been through the [Typescript Tutorial](https://easy-peasy.now.sh/docs/typescript-tutorial/)?

**Comment by MatthieuLab** [comment]
Sorry for the delay! I haven’t seen your reply. 
I have probably figured it out. Thanks for your support. Looking forward for the announced v4!
