### ISSUE TITLE
Idea: use funding to translate website docs

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#336]
Now that I have started to receive some funding I am trying to think of ways that I can improve the library. One way would be to provide translations of the docs. I had a look at the analytics and it appears that there are a fair amount of visitors with zh-cn and ru-ru as their locales.

I can start looking into services to help with this, but wanted to put this issue down here in case anyone has experience with this.

✌️

**Comment by ctrlplusb** [comment]
If this is something you think you can help with please reach out. x

**Comment by Wil-g2** [comment]
I have interesting in help easy peasy, I'm thinking of doing the example and record video explain with use easy peasy in project with react Portuguese Language.
Is a good idea translate documentation for Portuguese, I can help and share with other people the Brazil.

**Comment by ctrlplusb** [comment]
That is amazing news @Wil-g2 - thank you for this 👍👍👍

**Comment by ctrlplusb** [comment]
Is there a platform I can DM you on? Twitter/Hangouts/Skype/etc?

**Comment by Wil-g2** [comment]
Follow my Social Networks You can send message for me in:  
Skype: wil-g2
Email: wil-g2@hotmail.com
Gmail account: willian.gaurez@gmail.com
Linkedin: https://www.linkedin.com/in/willian-gaudencio-38864312b

**Comment by ctrlplusb** [comment]
Amazing, thanks I will be in touch 👍

**Comment by ctrlplusb** [comment]
Sorry for the deleay @Wil-g2 

I have pinged you via google hangouts 👍

**Comment by velsa** [comment]
Hey @ctrlplusb 
Glad the library is gaining popularity. 
Will be happy to assist with Russian translations.
You can write to me on telegram: `@velsa `

**Comment by ctrlplusb** [comment]
@velsa 

This is amazing news. Thank you so much.

I have been on holiday and therefore not very active. I'll reach out soon to you though.

💜

**Comment by Madsn** [comment]
Sorry for kicking an old issue here..

Would it actually make a difference for any of those users/visitors, or are they perfectly happy reading English docs? And how would they know if the translated version has been kept up to date?

Docs being available in multiple languages doesn't bother me as such, but if I know the English version is likely to be the most correct / up-to-date one, I would 100% not bother looking at the docs in my native language.

Tutorials is another matter though. You kind of expect those to go stale after some time has passed.
