### ISSUE TITLE
Not working on Firefox 63.0.3

### ISSUE THREAD

**Issue by EnterRavement** [ctrlplusb/easy-peasy#34]
When I open the Codesandbox or a code which includes 'easy-peasy in firefox 63.0.3 on MacOs Mojave I get the following error, when on Chrome it is working:

`TypeError: e[n] is undefined
unliftState
http://localhost:3000/:2:30806
getState
http://localhost:3000/:2:30882
useStore
node_modules/easy-peasy/dist/easy-peasy.esm.js:420

  417 | var dependencies = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : [];
  418 | var store = useContext(StoreContext);
  419 | 
> 420 | var _useState = useState(mapState(store.getState())),
      | ^  421 |     _useState2 = _slicedToArray(_useState, 2),
  422 |     state = _useState2[0],
  423 |     setState = _useState2[1]; // As our effect only fires on mount and unmount it won't have the state

./src/components/Map.js/__webpack_exports__.default
src/components/Map.js:18

  15 | `
  16 | 
  17 | const getPos = useAction(dispatch => dispatch.clickedPos.getPos)
> 18 | const pos = useStore(state => state.clickedPos.latlng)
     | ^  19 | const markerPosition = [pos.lat, pos.lng]
  20 | 
  21 | return (

./src/index.js
src/index.js:24

  21 |     },
  22 | })
  23 | 
> 24 | ReactDOM.render(
  25 |     <StoreProvider store={store}>
  26 |         <BrowserRouter>
  27 |             <Switch>

__webpack_require__
/Users/bjoernrave/projects/coolplacesjs/webpack/bootstrap:782

  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;

fn
/Users/bjoernrave/projects/coolplacesjs/webpack/bootstrap:150

  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {

0
http://localhost:3000/static/js/main.chunk.js:544:18
__webpack_require__
/Users/bjoernrave/projects/coolplacesjs/webpack/bootstrap:782

  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;

checkDeferredModules
/Users/bjoernrave/projects/coolplacesjs/webpack/bootstrap:45

  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | return result;

webpackJsonpCallback
/Users/bjoernrave/projects/coolplacesjs/webpack/bootstrap:32

  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;

(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:57`

**Comment by ctrlplusb** [comment]
Very strange. Could you please try it in an incognito window?
