### ISSUE TITLE
Typescript, action - void added to payload's type when payload is a generic

### ISSUE THREAD

**Issue by ae2438** [ctrlplusb/easy-peasy#345]
It seems that when a payload of an action is typed as a generic type, the type of the payload becomes `void & T`, an "impossible" type as this is equivalent to `never`:
 
```
interface Base {
  a: string;
}

interface Model<M extends Base> {
  data: M[];
  add: Action<Model<M>, M>;
  doSomething: Thunk<Model<M>, { x: string }>;
}

function getModel<M extends Base>(): Model<M> {
  return {
    data: [],
    add: action((state, payload) => {
      state.data.push(payload);
    }),
    doSomething: thunk((actions, { x }) => {
      actions.add({ a: x }); // <-- Here actions.add expects parameter to be `void & string`
    }),
  };
}
```

An error is given that the parameter is not assignable to void.
```
Argument of type '{ a: string; }' is not assignable to parameter of type 'void & M'.
  Type '{ a: string; }' is not assignable to type 'void'.ts(2345)
```

`actions.add` is reported by my IDE to have the type `add: (payload: void & M) => void`.
I would expect this to have the type `add: (payload: M) => void`.

**Comment by ctrlplusb** [comment]
Hey @ae2438 

Thanks for the report. 👍

Fixed in v3.2.1
