### ISSUE TITLE
generalising typescript issue

### ISSUE THREAD

**Issue by ebadta81** [ctrlplusb/easy-peasy#346]
Hello,

I am trying to generalize models in a react and typescript based project.

I modified an example easy-peasy project [to illustrate the problem.](https://codesandbox.io/s/easy-peasy-typescript-generalising-error-2f0zo)

In the browser console, after you add a todo item, you can see, it appears in the main2 section of the store, instead of the main section.

I think the problem is here:

```javascript
main: { ...todos, ...notification },
```

The todo item appears in the last defined TodosModel compatible section of the store, so if I replace the main2 with the todo, it appears in the todo section.

What is the right syntax here?

How can I resolve this problem? 

Please help me. Thank You!

**Comment by lukebarton** [comment]
https://codesandbox.io/s/easy-peasy-typescript-generalising-error-v5h5e?fontsize=14

You'll want to create a new `TodoModel` for each section. See `model.ts` and `store.ts`.

**Comment by ebadta81** [comment]
Thank You Luke, that's the trick.
