### ISSUE TITLE
❤️ A love msg to contributors ❤️

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#350]
I've had a few very generous contributions being made to Easy Peasy already. I must admit that I was surprised and humbled by this.

❤ Thank ❤ you ❤ so ❤ much ❤ for ❤ supporting ❤ this ❤ library❤  

I've poured tons and tons of hours into it, and it feels really great to get this level of validation and support.

🙇‍♂️

**Comment by 24dev** [comment]
This library + Typescript + async/await is insanely good. Big thanks to everyone who maintains, especially @ctrlplusb !
