### ISSUE TITLE
Add an "alternatives" page

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#351]
It ain't a competition.

People should make informed decisions based on the landscape and their own needs / preferences / experience.

Currently thinking of adding:

Redux Starter Kit
Mobx State Tree
Zustand

Any others stand out to people?

**Comment by tamagokun** [comment]
Rematch (https://github.com/rematch/rematch)

**Comment by jmyrland** [comment]
A reference to this article might be helpful: https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367
