### ISSUE TITLE
Update root state in sub state action

### ISSUE THREAD

**Issue by joelmoss** [ctrlplusb/easy-peasy#352]
So it's easy to access root state from a `thunk` using `getStoreState`, but it seems that it is not possible to do the same from within an `action`. Is there a reason for this?

**Comment by ctrlplusb** [comment]
TBH I regret that I ever exposed `getStoreState` in the thunk API. I prefer leveraging listeners to perform operations at proximity of the state.

Similar with state, I don't like the idea of any arbitrary action being able to mutate global state. Try to close the scope and leverage listener actions where needed.

**Comment by joelmoss** [comment]
I'm reluctant to use listeners as they can become very messy, and end up with lots of actions being dispatched, which I think for a simple state change is overkill.

**Comment by ctrlplusb** [comment]
The alternative would be to lift the actions up in order to increase their scope. 👍

**Comment by ctrlplusb** [comment]
You could also place a synchronous thunk at the root that dispatches actions below it.
