### ISSUE TITLE
Idea: Typescript support for Computed runtime arguments

### ISSUE THREAD

**Issue by mickmister** [ctrlplusb/easy-peasy#353]
Currently, a computed property that accepts a runtime argument cannot be properly expressed with typescript.

It may work with something like:

`Computed<Model, Result, StoreModel, Payload>`

**Comment by viniciusHagamenon** [comment]
You can already do that, you just need to declare your `Result` as a function.

e.g. `Computed<Model, (someProp1: string, someProp2: number)  => boolean, StoreModel>`

**Comment by mickmister** [comment]
@viniciusHagamenon Awesome thank you!!
