### ISSUE TITLE
Nested actions lose state.

### ISSUE THREAD

**Issue by saviilsy** [ctrlplusb/easy-peasy#356]
Hi!

I Tried to create my model more structural so that each type on "thing" in store is nested under their own property. This causes state to be lost inside actions.

Using the Counter example :

Model and store
```typescript
type CounterModel = {
  state: {
    count: number;
  };
  actions: {
    inc: Action<CounterModel, number>;
  }
}
export const Counter = createContextStore<CounterModel>({
  state: { count: 100 },
  actions: {
    inc: action((store, number) => {
      store.state.count += number;
    })
  }
});
```
Usage
```typescript
const SomeComponent: React.FC = () => {
  const count = Counter.useStoreState(store => store.state.count);
  const inc = Counter.useStoreActions(store => store.actions.inc);
  console.log(count); // This is 100 as intended
  useEffect(() => { inc(2) }, []); // This will fail as store.state is undefined
};
```

If you drop the nesting on action (so that inc will be at the root of the model) it works correctly.

Is this working as intended? Looking at the typings it seems the action wrapper is meant to support nesting.

If this is not supported, what is the proper way to separate thunks and actions that essentially share name?

**Comment by ctrlplusb** [comment]
Actions are scoped to the object they are applied to. Therefore the following would work.

```javascript
type CounterModel = {
  state: {
    count: number;
  };
  inc: Action<CounterModel, number>;
}
export const Counter = createContextStore<CounterModel>({
  state: { count: 100 },
  inc: action((store, number) => {
    store.state.count += number;
  })
});
```

Perhaps not the degree of separation that you are looking for, but still provides some distinction.

**Comment by rmariuzzo** [comment]
Thank you! Your reply gave me direction.
