### ISSUE TITLE
How to achieve generalizing and code splitting at model level with typescript?

### ISSUE THREAD

**Issue by ebadta81** [ctrlplusb/easy-peasy#358]
Hello all,

I am trying to achieve code reusing and code splitting with generalizing and store addModel/removeModel functions.

I get the "Type 'Computed<StoreModel, string[], {}>' has no call signatures.ts(2349)" error message.
I see this is a common issue with ts, I checked a number of posts about it, but cannot figure out, how to avoid this error in my case.

[There is a sandbox example](https://codesandbox.io/s/easy-peasy-typescript-no-call-signature-error-86xqz) for the problem illustration.

There is a newmodule.tsx component, wich is lazily loaded, and it adds it's own slice to the model level, but cannot call the nextTodos function from the generalized commonModuleModel model.

How can I get this functionality?

**Comment by ebadta81** [comment]
I figured out, this is because I set newmodule to undefined at StoreModel.

But if I have to set all the procedures in StoreModel at create time, what is the point of using addModel/removeModel with typescript?

**Comment by ctrlplusb** [comment]
The type mapper doesn't seem to like optional members when mapping models/objects. 🤔
