### ISSUE TITLE
Generalising effects/actions/data

### ISSUE THREAD

**Issue by RuedigerLudwig** [ctrlplusb/easy-peasy#36]
Hello,

first: great and easy to use library. Thank you very much for it

I came along a small problem when trying to reuse my code. I have some state trees, that look very similar to each other. In general they all look the same: Some data, some actions, some selects and some effects. In the effects I need to call actions via the dispatch. 

Here the ability to reuse stops, because I need to call the set method with an absolute path and not a relative one. But I might not know in general where and how deep I might be in the "store tree".

Is there an elegant way to solve this?

Cheers
Rüdiger

```javascript
const store = {
  helper {
    material: {
      list: [],

      ids: select(state => R.pluck('id', state.list)),
      loaded: select(state => state.list === []),

      setList: (state, payload) => {
        return { ...state, list: payload}
      },

      loadAll: effect(async (dispatch, _payload, _getState) => {
        const data = await getAllMaterialien()
        dispatch.helper.material.setList(data) // <<-- I do not know how to generalize this to call this action of my part of the store
      }),
    },
    form: {
      list: [],

      ids: select(state => R.pluck('id', state.list)),
      loaded: select(state => state.list === []),

      setList: (state, payload) => {
        return { ...state, list: payload}
      },

      loadAll: effect(async (dispatch, _payload, _getState) => {
        const data = await getAllFormen()
        dispatch.helper.form.setList(data)
      }),
    },
  },
}
```

**Comment by adrienWeiss** [comment]
I've been using a function that takes the name and the url to fetch (that would be the function to call for you, `getAllMaterialien` or `getAllFormen`) that returns the state tree
```js
{
  [name]: {
    list: [],
    loadAll: effect(...) => {
      ...
      dispatch.helper[name].setList(...
  },
}```

and then spreading those 
```
const model = {
  ...materialState,
  ...formState,
},```

But I agree with you, one would want to easily parse the local state, but it is also important to be able to dispatch elsewhere.
Also, with the project growing there is a risk of conflicting names.

**Comment by ctrlplusb** [comment]
@RuedigerLudwig I have opened a PR which may help you with this. Utilising the meta data exposed to the effect function you could do something like:

```javascript
import _ from 'lodash';

const list = (endpoint) => ({
  list: [],
  setList: (state, payload) => ({ ...state, list: payload }),
  loadAll: effect(async (dispatch, _payload, _getState, _injections, meta) => {
    const data = await getAllMaterialien()
    const setList = _.get(dispatch, meta.parent.join('setList'));
    setList(data);
  }),
})

const store = {
  helper: {
    material: {
      ids: select(state => R.pluck('id', state.list)),
      loaded: select(state => state.list === []),
      ...list(getAllMaterialien)
    },
    form: {
      ids: select(state => R.pluck('id', state.list)),
      loaded: select(state => state.list === []),
      ...list(getAllFormen)
    },
  },
}
```

Let me know what you think. 😊

@adrienWeiss - would appreciate your input too.

**Comment by ctrlplusb** [comment]
The only thing I dislike about this helper approach is that it can be harder to visualise your state tree, however, when the typescript work lands you should get typesafe autocomplete on your model which will help dramatically. :)

**Comment by ctrlplusb** [comment]
Available in latest release.

https://github.com/ctrlplusb/easy-peasy/releases/tag/v1.7.0

🤘

**Comment by RuedigerLudwig** [comment]
Wow, that is quick. Thank you for the quick addition. I am pretty sure that it solves my use case.
