### ISSUE TITLE
How to use addModel with Typescript?

### ISSUE THREAD

**Issue by ebadta81** [ctrlplusb/easy-peasy#371]
Hi,

I prepared a [codesandbox example](https://codesandbox.io/s/easy-peasy-typescript-no-call-signature-error-4lz8r).

I created a addModuleModel thunk (model/index.ts) for ts module loading, and it using dynamic import, like [in the typescript documentation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html), but I cannot instantiate through addModule method.
You can see the problem in the components/newmodule.tsx file.

How can I use Dynamic Import with typescript and easy-peasy?

**Comment by ebadta81** [comment]
Can you please create a quick demo for this?

**Comment by ctrlplusb** [comment]
Would you mind creating a minimal reproduction in codesandbox?

**Comment by ebadta81** [comment]
I already created the reproduction in codesandbox. Please check my first comment.

This is the error in the components/newmodule.tsx file: 

This expression is not callable.
  Type 'Computed<CommonModuleModel, string[], StoreModel>' has no call signatures.ts(2349)

**Comment by ctrlplusb** [comment]
Hi @ebadta81;

I've looked at this and already have ideas. I am going to be implementing a new `lazy` API which will give you exactly what you want whilst also maintaining type safety.

Track #412 for more information.

I have yet to discuss the API ideas I have within that issue, so ignore the current conversation. I will eventually update it once I have had time to experiment and prove the API.
