### ISSUE TITLE
Dependency Injection Improvement

### ISSUE THREAD

**Issue by aalpgiray** [ctrlplusb/easy-peasy#372]
Hello Sean, I hope you're well. I need help with the situation. 

Here is the situation. 
I am storing logged in user token in the store with persist helper. 
I am injecting my services to the store. However, these services need access to the store to obtain the token. This creates a circular reference. 
` store => service => store`.
With the current implementation of injections, we are passing dependencies as key-value pairs. My suggestion is to use a factory function that we pass the current store state as an argument. 

``` typescript
createStore(model, {
  injections:{
    getData: (storeState) => getDataServiceFactory(state.loggedInUser.token)
  }
}
```
Is this a job you would call "easy-peasy" ? :)  If you regard this improvent as out of scope. Do you have any sugestions to help solve this "require cycle" problem.

**Comment by jmalins** [comment]
One solution is to mutate the `injections` object after the store is created:
```javascript
const injections = { };
const store = createStore(model, { injections });

const AppWrapper = () => {
  const injectionsInitializedRef = useRef(false);
  const isRehydrated = useStoreRehydrated();

  if (isRehydrated && !injectionsInitializedRef.current) {
    const token = store.getState().loggedInUser.token;

    //  set getData in injections after the store is available
    //           👇
    injections.getData = getDataServiceFactory(token);
    injectionsInitializedRef.current = true;
  }
  return isRehydrated ? <App /> : null;
}

ReactDOM.render(
  <StoreProvider store={store}>
    <AppWrapper />
  </StoreProvider>,
  document.getElementById('app')
);
```
The advantage of using a `ref` here is that `injections` are guaranteed to be set before `App` is first rendered. A `useEffect` would also work, but then there would be one render tick without `injections` set, which may or may not be ok.

**Comment by aalpgiray** [comment]
Thanks @jmalins this will allow me to fix the problem.

**Comment by shulcsm** [comment]
This is hacky but more or less fine if you want values just for initialization, what about cases where you want storeState at runtime?
