### ISSUE TITLE
How to use it with nextjs?

### ISSUE THREAD

**Issue by dpyzo0o** [ctrlplusb/easy-peasy#373]
Hi everyone, is there an official demo with nextjs? Has anyone tried to integrate them?

**Comment by Prattjames** [comment]
Did you find a way? I tried with [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper) but still don't know how to make them work together...

**Comment by ctrlplusb** [comment]
Have you seen #171?

**Comment by dpyzo0o** [comment]
> Have you seen #171?

My bad, should have done some research into it.  I will close this issue.  Thanks for the amazing library!
