### ISSUE TITLE
Using connect from redux?

### ISSUE THREAD

**Issue by kladnik** [ctrlplusb/easy-peasy#376]
I would like to connect to store state changes and force a re-render each time.
There is connect in react-redux that does that, but I can not find any here.

How would we do this with easy-peasy?

EDIT: To further explain my use case. I am using a form that I load from store and on input change, I save it back to store. The problem is that it does not re-render automatically. For now, I am using useState each time I write to store to force rerender (and I am sure this is not the correct way).

**Comment by dpyzo0o** [comment]
It's easier for others to help if you can give a minimal demo.

**Comment by ctrlplusb** [comment]
Closing due to lack of information.
