### ISSUE TITLE
useStoreState hook 'getState' of undefined

### ISSUE THREAD

**Issue by jchamb** [ctrlplusb/easy-peasy#379]
I have a bit of a unique issue I can't figure out. Working on a setup that has an "abstracted core" module as a dependency. This module exports a store and some additional helpers that get used across other submodules and combined into a single app. But anytime I try to use `useStoreState` inside of a component in the core lib I get a **Cannot read property 'getState' of undefined.** error

Basic structure of my combined app looks like this:
index.js
```
... react imports ...

import App from './app.js';
import { store } from '@mine/core';

ReactDOM.render(
  <StoreProvider store={store}>
    <App />
  </StoreProvider>,
  document.getElementById('app'),
);
```

App.js
```
... react/react-router imports ...

import { PrivateRoute, PublicRoute } from '@mine/core';
import SignIn from './pages/SignIn';
import { SubModule } from '@mine/submodule';

const App = () =>(
    <Router>
      <Switch>
        <PublicRoute exact path="/signin" component={SignIn} />
        <PrivateRoute path="/" component={SubModule} />
      </Switch>
    </Router>
);
```

So from the above the error is thrown by PrivateRoute trying to use the store.

Here is what my store export and private route look like.

store (inside @mine/core)
```
import { createStore,  action } from 'easy-peasy';

const store = createStore({
  user: {
  authorized: false,
  authChecked: false,
  user: null,

  changeAuthorized: action((state, payload) => {
    state.authorized = payload;
    state.authChecked = true;
  })
 },
});

export default store;
```

PrivateRoute  (inside @mine/core)
```
import { checkAuthorization } from '../utils';

export default function PrivateRoute(props) {

  checkAuthorization();  // calls an action that updates below props
  const authChecked = useStoreState(state => state.user.authChecked);
  const authorized = useStoreState(state => state.user.authorized);

 if( ! authChecked ) return null; 

  return authorized ? (
      <Route {...props} />
  ) : (
    <Redirect to="/signin" />
  );
};
```

If I change the above method to use a direct import of the store and use the getState() api then the error goes away but I never get any re-render based on authChecked being updated.

Overall it looks to me like when useStoreState is called it doesn't have access to the EasyPeasy Context and I'm not sure why. Any help would be much appreciated.

**Comment by ctrlplusb** [comment]
🤔

Are each of the packages referencing the exact same version of `easy-peasy`?

My guess is that your private route package has a different version and therefore is resolving a different context instance and breaking.

Expand your node_modules to investigate. 👍

**Comment by jchamb** [comment]
@ctrlplusb thanks for taking a look. I double checked that and both are 3.2.3. I did just figure out if I create a Provider wrapper in my module and export that then everything works. So seems like definitely something to do with the context being lost. This solution works for me, and prob rare for others to do this, so i'm gonna close this out.

eg:
module
```
const CoreProvider = ({ children }) => (
  <StoreProvider store={store}>{ children }</StoreProvider>
);
```
app
```
ReactDOM.render(
  <CoreProvider>
    <App />
  </CoreProvider>,
  document.getElementById('app'),
);
```

**Comment by jchamb** [comment]
One Final update, @ctrlplusb your initial thought of different easy-peasy packages was right. I was using `yarn link` to run my local version. Didn't really think about it referencing having its own easy-peasy when using linking it in. 

I switched over to using [yalc](https://github.com/whitecolor/yalc) to link the local package and it took care of the problem.

**Comment by PiPoutch** [comment]
You will also get this error on any hook if you plug easy-peasy into an existing redux application and keep importing the provider from redux instead of easy-peasy.
