### ISSUE TITLE
TypeError: Cannot convert undefined or null to object - only in tests

### ISSUE THREAD

**Issue by jmyrland** [ctrlplusb/easy-peasy#380]
Hi! We are trying to upgrade from version 3.0.2 to the latest version (3.2.3) - and we get the followin errors for some tests:

![image](https://user-images.githubusercontent.com/837651/70521625-ce860280-1b3f-11ea-8505-2250069d760d.png)

When running the app - everything seems to be working. As far as I can tell - only the tests are failing.

This is an example test, that is failing:
```ts
import { wait } from '@testing-library/react';
import { StoreProvider } from 'easy-peasy';
import { createMemoryHistory } from 'history';
import React from 'react';
import ReactDOM from 'react-dom';
import { Router } from 'react-router-dom';

import model from 'redux/model';
import { createStoreWithMockInjections } from 'redux/store.test.helpers';
import App from './App';

const withStore = (ui: React.ReactElement, store: any = createStoreWithMockInjections(model)) => (
  <StoreProvider store={store}>{ui}</StoreProvider>
);
const withRouter = (ui: React.ReactElement, history = createMemoryHistory({ initialEntries: ['/'] })) => (
  <Router history={history}>{ui}</Router>
);

it('renders without crashing', async () => {
  const div = document.createElement('div');
  ReactDOM.render(withRouter(withStore(<App />)), div);
  await wait();
  ReactDOM.unmountComponentAtNode(div);
});
```

createStoreWithMockInjections: 
```ts
import { createStore } from 'easy-peasy';
import merge from 'lodash/merge';

export const createStoreWithMockInjections = <T>(model: T, injections: Partial<IInjections> = {}) => {
  const mockModel = merge({}, model, {
     // pre-mocked data, such as authentication etc..
  }) as T;
  const mockInjections: IInjections = {
    // ... combination of default mocks and incoming `injections`
  };
  return createStore(mockModel, {
    injections: mockInjections,
  });
};
```

Do you have an idea of what might be causing this?

**Comment by ctrlplusb** [comment]
Hey @jmyrland 

Looking at the stack trace it appears that you are passing undefined / null in as the model.

Can you please console log out the model value that is being passed into the `createStore`.

**Comment by jmyrland** [comment]
The value I pass into createStore is definitely not null. Here's an excerpt:
![image](https://user-images.githubusercontent.com/837651/70525963-c7afbd80-1b48-11ea-9f14-507f0df0cdff.png)

What's up with the keys? 🤣 

Is it something that I am missing in the second argument?
```ts
  // ... from the above createStoreWithMockInjections
  return createStore(mockModel, {
    // 👈 might something be missing here?
    injections: mockInjections,
  });
```

**Comment by jmyrland** [comment]
I've found it! 

It's got nothing to do with the actual tests - its my `store.ts` file, which is calling `createStore` with an undefined model (that store is not used for the tests).

However - I do not get why the `model` is undefined - as it is imported from `model.ts` 🤔

**Comment by jmyrland** [comment]
We're all good 😁 
![image](https://user-images.githubusercontent.com/837651/70528676-0d6f8480-1b4f-11ea-8520-7bc0f6e7b65c.png)

Thanks for being my [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) @ctrlplusb 😂

**Comment by jmyrland** [comment]
To clarify: I do not understand why `model` is imported as `undefined` in the `store.ts` file.

My "fix" is to change the following in `store.ts`:
```diff
- const store = createStore(model, { injections });
+ const store = createStore(model || {}, { injections });
```
