### ISSUE TITLE
How to call an Action from an Action ?

### ISSUE THREAD

**Issue by Tschuss69** [ctrlplusb/easy-peasy#381]
Hello 

I would like, in my store to call an action from an action. Is it possible?

**Comment by crissdev** [comment]
@Tschuss69 A [listener](https://easy-peasy.now.sh/docs/api/listeners.html) might be what you need.

**Comment by Tschuss69** [comment]
Finally I use thunk((actions, placeholder) => {...}) instead of action for action calling other actions

Thanks
