### ISSUE TITLE
Injections end up undefined

### ISSUE THREAD

**Issue by jndietz** [ctrlplusb/easy-peasy#382]
So, given my store config...

```javascript
import { createStore } from 'easy-peasy';
import model from '../app/model/app-model';
import api from './api';
import { toast } from 'react-toastify';

export const store = createStore(model, {
  injections: {
    api,
    toast
  }
});

export default store;
```

And a thunk where I want to use both `api` and `toast`...

```javascript
  ...
  saveReview: thunk(async (actions, payload, { injections }) => {
    const api = injections.api;
    const toast = injections.toast;
     //      this is undefined 👆
    try {
      await api.post('/reviews', payload);  
      toast.success('Review created!');     
    } catch (e) {
      console.log(e);
      toast.error('There was a problem saving the review.');
    }
  })
};

export default reviewsModel;
```

Anyone have some thoughts on what might be going on?  I swear I had this working, but now for some reason, `toast` doesn't even show up on the `injections` object.

I even tried adding an "injection" that shouldn't be undefined...

```javascript
export const store = createStore(model, {
  injections: {
    api,
    toast,
    pooper: {
      poop: val => console.log(val)
    }
  }
});
```

`pooper` still doesn't show up on `injections` when I inspect it in the browser.

**Comment by jndietz** [comment]
I am not smart... we had a duplicate store configuration left over from a nasty merge.

**Comment by ctrlplusb** [comment]
Never say you are not smart, even in jest, we all make mistakes. x

**Comment by jndietz** [comment]
Thanks for the encouragement @ctrlplusb.  Really love `easy-peasy`!
