### ISSUE TITLE
Allow HMR with context stores

### ISSUE THREAD

**Issue by formula349** [ctrlplusb/easy-peasy#384]
Currently the reconfigure function used for hot reloading is only exposed for the main state. I'd like to be able to hot reload a context store as well.

**Comment by raifemre** [comment]
have you found any solution for this @formula349 ?

**Comment by ctrlplusb** [comment]
Unfortunately, due to current design, I am unable to see a pathway to this that doesn't break current semantics of the API.

Sorry about that.
