### ISSUE TITLE
How to call other model action?

### ISSUE THREAD

**Issue by Maadtin** [ctrlplusb/easy-peasy#389]
How to call other model action inside a model action? thanks!!

Is getStoreActions from thunk param a good practice?

**Comment by raifemre** [comment]
Have you found any answer?

**Comment by Maadtin** [comment]
@raifemre  Hello, No but I'm just using getStoreActions.

**Comment by raifemre** [comment]
Thanks you are right, but it is not recommended. Instead recommending to use actionOn and thunkOn on the docs.

**Comment by Maadtin** [comment]
I had problems with listeners because of async operations. I do not know how to wait for the async calls inside the listener to complete before my main call. So intead im just using getStoreActions
