### ISSUE TITLE
Preact compatability ?

### ISSUE THREAD

**Issue by revskill10** [ctrlplusb/easy-peasy#39]
Any chance we could use this library with `preact` ?

**Comment by ctrlplusb** [comment]
It should be possible but we would have to consider splitting out the hooks into a React specific import.

e.g.

```javascript
import { useAction } from 'easy-peast/react';
```

**Comment by revskill10** [comment]
@ctrlplusb Last time i tried with preact, i got problem with `useContext` hook as preact doesn't have any hook on its core :D

**Comment by ctrlplusb** [comment]
@revskill10 yep, you would have to use `react-redux` instead of React Hooks. See the docs for an example of this.

**Comment by ctrlplusb** [comment]
@revskill10 Ah sorry, yeah, that is because it is all imported together. As per my previous comment if I split out all the React specific code so that you would have to explicitly import it then it would be fine.

It's a breaking change however, but perhaps one to consider.

**Comment by ctrlplusb** [comment]
I'm going to close this for now @revskill10, apologies, but I am not looking to support Preact right now. Personally I am happy to stick with React.

You could consider a fork though if needed? `preact-easy-peasy`? 😇
