### ISSUE TITLE
create a middleware which executes before thunk middleware

### ISSUE THREAD

**Issue by aalpgiray** [ctrlplusb/easy-peasy#390]
Hi,

We are creating a middleware that stops unnecessary requests to the backend. But this is not stopping thunks from executing. My guess is thunk middleware is running before my custom middlewares. 

Here is the code

``` typescript
const loaderHash: { [key: string]: boolean } = {};

export const debouseAPIRequests: Middleware = store => next => (action: {
  type: string;
  payload: any;
}) => {
   if (action.type.indexOf("@thunk") === 0) {
    const key =
      action.type.replace(/(.+)(\((success|fail|start)\))/, "$1") +
      JSON.stringify(action.payload);


    if (action.type.endsWith("(start)")) {
      if (!loaderHash[key]) {
        loaderHash[key] = true;
        next(action);
      }
    }

    if (action.type.endsWith("(fail)") || action.type.endsWith("(success)")) {
      loaderHash[key] = false;
      next(action);
    }
  } else {
    next(action);
  }
};

```

**Comment by aalpgiray** [comment]
Something like this may work. May not on the other hand :)

on create-store.js

``` javascript
  /* Before */
  const easyPeasyMiddleware = [
    createComputedPropertiesMiddleware(references),
    reduxThunk,
    ...middleware,
    createListenerMiddleware(references),
    persistMiddleware,
  ];

  /* After */

  const hasThunk = middleware.indexOf(reduxThunk) > -1;

  const easyPeasyMiddleware = [
    createComputedPropertiesMiddleware(references)];

  if(!hasThunk){
    easyPeasyMiddleware.push(reduxThunk)
  }

  middleware.forEach(m => easyPeasyMiddleware.push(m))
  easyPeasyMiddleware.push(createListenerMiddleware(references))
  easyPeasyMiddleware.push(persistMiddleware)
```

**Comment by ctrlplusb** [comment]
It would probably be ok for us to declare the thunk middleware below the rest. 😀

**Comment by ctrlplusb** [comment]
@aalpgiray 

I have made an update in #459 - the internal `redux-thunk` middleware is now bound **after** the user provided store config middleware. This should allow you achieve what you need. 👍

Apologies for the delay.

**Comment by alpates** [comment]
@ctrlplusb Thanks mate! I have searched for that middleware in the codebase to give it a try. But I guess we have taken another approach for the solution. Do you want me to validate anything? I suppose it should work.

**Comment by ctrlplusb** [comment]
I've added a test case so theoretically it should all be fine. Not to worry. 😊
