### ISSUE TITLE
Setting a state variable inside the thunk with the same value throws an error.

### ISSUE THREAD

**Issue by raifemre** [ctrlplusb/easy-peasy#395]
Example:

// store
isAuthenticated: false,
// action
setAuthStatus: action((state, payload) => state.isAuthenticated = payload),

login : thunk(async(actions, payload, { getState }) => {
       const { setAuthStatus } = actions;

       await doSomeStuff();
       setAuthStatus(false); // throws an error
       setAuthStatus(true); // no error
}

calling an action inside the thunk which sets the store object with the same value throws an error everytime.

**Comment by ctrlplusb** [comment]
Hey @raifemre 

That does sound very peculiar. Is there any chance you could create a [codesandbox.io](https://codesandbox.io/s/wizardly-jepsen-yv76p30w8v) minimal reproduction?

I'd be happy to take a look at it for ya.

**Comment by raifemre** [comment]
Here it is; 

https://codesandbox.io/s/easy-peasy-starter-sxbz6

**Comment by ctrlplusb** [comment]
Hi @raifemre 

This is not my experience.

See the my fork, updating the state multiple times:
https://codesandbox.io/s/easy-peasy-starter-k6qqx

Is this the correct reproduction?

**Comment by raifemre** [comment]
oh found the problem, my bad.. here is the difference;

setValue: action((state, payload) => (state.value = payload)), 
setValue: action((state, payload) => state.value = payload), <== without body wrapper
