### ISSUE TITLE
data state dose not want to be deep wrapped model

### ISSUE THREAD

**Issue by yongningfu** [ctrlplusb/easy-peasy#402]
just want user is a data state not a modal

```js
interface User {
   name: string;
   getDisplayName:  () => string
}

interface UserModal {
  user: User;
  fetchUser: thunk(.....)
}
```

const user = useStoreState(state => state.userModal.user)

**the user is StateMapper\<User\> ???   just want the user is User not  StateMapper\<User\>**

**Comment by ctrlplusb** [comment]
Hi @yongningfu 👋

I'm sorry to see you are frustrated. That being said can I please ask you avoid using things like "!!!!" in your communications. It comes off as an aggressive tone, and no-one needs that in their lives.

We will be happy to help, but could I ask that you create a minimal example on codesandbox.io. Here is a [starter template](https://codesandbox.io/s/wizardly-jepsen-yv76p30w8v) to help even.

**Comment by yongningfu** [comment]
@ctrlplusb  sorry abort that, i just write a example https://codesandbox.io/s/easy-peasytypescript-tutorialtyped-computed-entire-state-ld1zl

**Comment by yongningfu** [comment]
@ctrlplusb  i use immutable.js with easy-peasy, i want to keep user is a  immutable record modal, not wrapper state with it

**Comment by ctrlplusb** [comment]
Hi @yongningfu 

So to be clear you don't like that it is reporting `state.user` to be of type `_Merge<StateMapper<_Pick<_Pick<User, "id" | "name" | "displayName" | "has" | "get" | "hasIn" | "getIn" | "equals" | "hashCode" | "set" | "update" | "merge" | "mergeDeep" | "mergeWith" | "mergeDeepWith" | ... 16 more ... | "toSeq">, "displayName" | ... 28 more ... | "toSeq">, "2">, _Pick<...>>`?

Do the `immutable` API's still work even though the type is definition has changed to this?

**Comment by yongningfu** [comment]
> Hi @yongningfu
> 
> So to be clear you don't like that it is reporting `state.user` to be of type `_Merge<StateMapper<_Pick<_Pick<User, "id" | "name" | "displayName" | "has" | "get" | "hasIn" | "getIn" | "equals" | "hashCode" | "set" | "update" | "merge" | "mergeDeep" | "mergeWith" | "mergeDeepWith" | ... 16 more ... | "toSeq">, "displayName" | ... 28 more ... | "toSeq">, "2">, _Pick<...>>`?
> 
> Do the `immutable` API's still work even though the type is definition has changed to this?

@ctrlplusb yes That's what I'm confused about，because i write some util function , them accept the type is User not _Merge<StateMapper<_Pick<_Pick<User,

just like

```js
import { User } from "../model/user";

const store = createStore(model, {});

const user = store.getState().user.user;

function checkUser(user: User) {}

checkUser(user); // type error

```

**Comment by ctrlplusb** [comment]
Hi @yongningfu 

The latest 3.4.0 alpha release fixes this issue.

Let me know if it works for you. See #459 for more info. 👍

**Comment by yongningfu** [comment]
> Hi @yongningfu
> 
> The latest 3.4.0 alpha release fixes this issue.
> 
> Let me know if it works for you. See #459 for more info. 👍

that's exactly what I need，I wonder why the V4 Model API is abandoned.  [v4 pr](https://github.com/ctrlplusb/easy-peasy/pull/450/files), maybe Generics API design is more lightweight than Modal?

**Comment by ctrlplusb** [comment]
I abandoned v4 as the `Model` API was actually really annoying to use in practice and full of gotchas. I persisted with trying to solve the same problems it was solving with pure TypeScript typings magic and was luckily able to do so. Happy that we don't need to introduce a breaking change. I really want to keep breaking changes down to an absolute minimum based on the evolution and adoption of the library.

**Comment by pvinis** [comment]
I am getting the same thing with typescript 4.1 and easy-peasy 3.3, 4, and 5.
I have 
```
  userHasInternalEmail: Computed<AuthModel, boolean, GlobalStoreModel>
```
and 
```
 userHasInternalEmail: computed([(state) => state, (_, store) => store], (_, store) =>
    isInternalEmail(userEmail(store) ?? "")
  ),
```
and I get an error in `store` inside `userEmail(store)`. `userEmail` expects a `GlobalStoreModel` and the error is giving me `Argument of type 'StateMapper<_Pick<GlobalStoreModel, _FilterKeys<GlobalStoreModel, ActionTypes, "default">>>' is not assignable to parameter of type 'GlobalStoreModel'.`.

Help?
