### ISSUE TITLE
Is it possible for context stores to listen for actions from the global store and vice versa?

### ISSUE THREAD

**Issue by liegeandlief** [ctrlplusb/easy-peasy#404]
Hi there, and thanks for this great library! I have a question regarding action listeners as follows...

Given the following application setup:

- Application has one global store created using `createStore` which persists for the lifetime of the application.
- The application has many context level stores created using `createContextStore` which can come and go as components are mounted and unmounted.

Is it possible in this situation for the global store to listen for actions on the context stores (using `actionOn` and `thunkOn`) and vice versa can the context stores listen for actions on the global store?

Or is it only possible for each store to listen for actions from its own model?

Thanks :)

**Comment by kamikazePT** [comment]
You can only listen to actions from your store, context stores are different store instances and global is a different store instance as well

Although ive seen use cases for what you want to do, but I think you only have 2 options 

Option 1 : every time you call an action from the context you need to make a manual call to a global store action, which is ugly... And everything gets messy

Option 2 : create custom events for data sync, the global store has listeners for them and the context stores actions or thunks dispatch those events

I prefer option 2 since stores are clueless about each other, they Just follow an event based api to communicate

**Comment by liegeandlief** [comment]
Thanks @kamikazePT. I am now thinking that I will keep all state in one global store and not use context stores at all. Instead I will use `addModel` and `removeModel` to add and remove model slices as certain components mount and unmount.

In this scenario if a model slice is listening for an action on another model slice which does not exist would this throw an error?

For example if my model has a `user` slice which is always present and a `products` slice which is only present when a certain component is mounted would the following listener on the `user` slice work?

```
onAddProduct: thunkOn(
  (actions, storeActions) => {
     if (typeof storeActions.products !== 'undefined') return storeActions.products.addProduct
     return []
  },
  async (actions, target) => {
    // Do something here
  }
)
```

My thinking here is that this won't work because the target resolver only runs once when the slice is initialised and therefore if the `products` slice does not exist when the `user` slice is created then the `onAddProduct` listener will never run even when the `products` slice is later created.

This because when the `user` slice is initialised `storeActions.products` is not defined and so the target resolver returns `[]`. And the target resolver does not run again after the `user` slice is initialised and so it never knows that the `products` slice exists.

Is my thinking here correct?

**Comment by ctrlplusb** [comment]
@liegeandlief it listener logic should automatically bind/fire when using the `addModel` and `removeModel` APIs. Please report back if this isn't your experience. 👍

I definitely agree that using a global store sounds better suited for your case.

FYI - I am investigating a new helper for the v4 release, called `lazy` or `lazyModel` which will make code splitting on your store far more fluid.
