### ISSUE TITLE
Does returning a value in action() break store?

### ISSUE THREAD

**Issue by vigzmv** [ctrlplusb/easy-peasy#405]
In here there are two examples of `setName` action. One that returns undefined and others that returns the payload due to the implicit return of array function. 
We have been using this Implicit format in our codebase, it didn't provide any benefit, only helped to keep things in one line. But recently with upgrading some other package, this no longer works.

Reproduction: Tap Add twice
https://codesandbox.io/s/flamboyant-elion-nijr3

Possible Solution:
- Fix action in case of implicit returns Or
- Add to docs that action must not return a value.

Thanks!

**Comment by ctrlplusb** [comment]
@vigzmv - If you return a value from an action we assume you want to use that as the new state value.

In your example, the value getting assigned to `state.name` also gets returned. Check this example:

https://codesandbox.io/s/purple-violet-9uou4

Therefore you are returning a new state structure, which then breaks the subsequent request as the state structure is no longer valid/expected.

**Comment by vigzmv** [comment]
Thanks, @ctrlplusb for pointing this out. Got it now.
I also found this mentioned in the docs.
