### ISSUE TITLE
Modular state and code splitting

### ISSUE THREAD

**Issue by AlgoTrader** [ctrlplusb/easy-peasy#407]
I have a huge app with huge state. I would like is it possible to "modularize" easy peasy state by splitting it into chunks? I would like to start with pretty small state initially and extend it when chunks are loaded.

The problem with Redux is it is not extendable after store is initialized. The cause hundreds of reduces to be initialized before state is ready to accept actions.

I think Redux is really doubtful choice - it is monolithic, it is impossible to share reducers logic, it is not based on Proxy, so crutches like Immer need to be used to make it less painful.

**Comment by ctrlplusb** [comment]
> The problem with Redux is it is not extendable after store is initialized.

That's not true. Redux exposes APIs to extend the store at runtime. We make use of this via the store's `addModel' API.

> I think Redux is really doubtful choice - it is monolithic, it is impossible to share reducers logic, it is not based on Proxy, so crutches like Immer need to be used to make it less painful.

We use `immer` to power our actions. Hence the mutation syntax. Yep, Redux requires boilerplate, but it is a sound architecture. In terms of sharing reducer logic - reducers are just functions, so not sure how you wouldn't be able to share the logic?

**Comment by ctrlplusb** [comment]
In terms of the `addModel` API. I haven't announce it yet, but for v4, I have been thinking of a new API that will allow splitting and loading your store as chunks in a much nicer way. The new API will be called `lazy` or `lazyModel`. More details and examples will follow.

**Comment by AlgoTrader** [comment]
> Redux exposes APIs to extend the store at runtime. We make use of this via the store's [`addModel`](https://easy-peasy.now.sh/docs/api/store.html) API.

replaceReducer? It is quite difficult to use it with redux-toolkit. Redux toolkit is a not so radical wrapper around Redux, removing need of huge switches and action creators. I certainly need my own Reducer Manager to inject reducers. I absolutely don't like idea of using Redux without wrappers

> so not sure how you wouldn't be able to share the logic?

I have dozens of reducers that are copy and paste with minimal modifications. I cannot write a generic reducer (in state managers like MobX it is very easy to instantiate multiple store instances). In redux, I have to copy & paste code

You probably do the great job, but any solution above Redux will be monstrous. Why not to go Vue3 or MobX way and just use Proxies? Redux is the most reason I don't like modern React apps

**Comment by ctrlplusb** [comment]
Keep up with #410 for more
