### ISSUE TITLE
Dispatching actions in getInitialProps (Next.js) is not working properly

### ISSUE THREAD

**Issue by grazianodev** [ctrlplusb/easy-peasy#408]
Hi, 

thank you for a brilliant library! 

I'm testing easy-peasy with Next.js. I was able to set the app up to access the store on the server with the help of #171, so I can do this: 

```
Homepage.getInitialProps = async ( { store } ) => {
    store.dispatch.posts.savePosts()
    return {}
}
```

My store looks like this: 

```
import { action, createStore, computed, thunk } from "easy-peasy"
import fetch from 'isomorphic-unfetch'

const posts = {
    postsById: [], 
    savePosts: thunk( async ( actions ) => {
        const res = await fetch( url )
        const posts = await res.json()
        actions.setPosts( posts )
    }),
    setPosts: action( ( state, payload ) => {
        state.postsById = payload
        console.log( 'Posts: ', state.postsById );
    })
}

const model = { posts }

export const initializeStore = initialState => {
    return createStore( model, { initialState } )
}
```

I can tell that the savePosts() and setPosts() actions are called and work properly because when I console.log `postsById` I do see the fetched posts; but if I access the store from the Homepage component with `const initPosts = useStoreState( state => state.posts.postsById )` I still get an empty array. A similar issue was reported in #378 but I'm not persisting the store.

Am I missing something?

**Comment by ctrlplusb** [comment]
You should do an `await` against the `Promise` that will implicitly be returned by your async/await based thunk.

```diff
Homepage.getInitialProps = async ( { store } ) => {
-    store.dispatch.posts.savePosts()
+    await store.dispatch.posts.savePosts()
    return {}
}
```

**Comment by grazianodev** [comment]
Ah, sure! Thank you so much for the quick reply.
