### ISSUE TITLE
[Internal Refactor] Plugin architecture

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#411]
___Update___

I have had some discussions around this issue and have given it more thought. My intention now is to refactor the internal architecture to be plugin based, without exposing this as an external API. 

Moving to a plugin based architecture will still allow me to clean up the code base and provide the ability to easily experiment with new aspects of features in the future.

I will then let the internals sit for a while before deciding to expose them as an official consumer API as described below. 

💜

---

> Note: this a draft, early feedback proposal, intended to gather community feedback. It by no means guarantees that this feature will be implemented

This comes after considering of the following feature request: #287 

Easy Peasy has evolved over time, with the original API being quite simple. Since then we have introduced lots of concepts; thunks, computed properties, listeners, persistence, etc.

Whilst these features are useful, for the simple case Easy Peasy is quite a bloated library. If we moved to a plugin architecture we could keep a super slim "core" library, allowing to easily register the features that you intend on using. This would have a dramatic effect on bundle size.

The proposal also includes moving many of todays features into plugins.

I really love that you don't need to configure Easy Peasy, so the default import would still return Easy Peasy with all plugins configured.

```javascript
import { action, computed, createStore, ...etc } from 'easy-peasy';
```

But for users who want to optimise their bundle size they could leverage the `easy-peasy/core` import and then build their own Easy Peasy by registering the required plugins. In addition to this the react components themselves would also be available as a separate import.

Here is a full example showing for a custom build of Easy Peasy.

```typescript
import { createStore, registerPlugins } from 'easy-peasy/core';
import { StoreProvider, useStoreState, useStoreActions } from 'easy-peasy/react';

import persistPlugin from 'easy-peasy/plugins/persist';
import computedPlugin from 'easy-peasy/plugins/computed';
import immerPlugin from 'easy-peasy/plugins/immer';
import listenersPlugin from 'easy-peasy/plugins/listeners';
import thunkPlugin from 'easy-peasy/plugins/thunk';
import testingPlugin from 'easy-peasy/plugins/testing';
import contextStorePlugin from 'easy-peasy/plugins/contextStore';
import componentStorePlugin from 'easy-peasy/plugins/componentStore';

// Note: plugins must be registered before you create your store
registerPlugins([
  persistPlugin,
  computedPlugin,
  immerPlugin,
  listenersPlugin,
  thunkPlugin,
  testingPlugin,
  contextStorePlugin,
  componentStorePlugin,
]);

const store = createStore(...);

const app = (
  <StoreProvider store={store}>
    <MyApp />
  </StoreProvider>
)
```

In addition to this the plugin architecture would be well documented, allowing for 3rd party contribution and/or experimentation prior to adopting new APIs.

**Comment by ctrlplusb** [comment]
Along with this shift in architecture we could also create an export which has by default every plugin configured.

e.g.

```javascript
import { createStore } from 'easy-peasy/full';
```

**Comment by allpro** [comment]
Perhaps also a middle-ground export like `easy-peasy/basic`, which might cover 80% of uses. Includes all _basics:_ core + computed + thunk + _(maybe)_ listener.

I split my jQuery Layout widget into plugins for the same reasons; also with core and all-feature downloads. This allows separate versioning of plugins, so it's easy to test any combination of new or beta updates.

**Comment by ctrlplusb** [comment]
I have updated the proposal, and have instead gone for an approach where by default the primary `easy-peasy` import would return _everything_, and then you could leverage the `easy-peasy/core` import in order to build your own.

**Comment by kamikazePT** [comment]
That last approach seems more interesting, you could leverage a monorepo structure with core library and the "official plugins" and the root of the workspace would generate the "easy-peasy" library which is pretty much a re-export of all the packages available in the easy peasy "framework"

@easy-peasy/plugin-listener is the plugin package

easy-peasy/plugin-listener is the relative import from the easy-peasy framework, something like that
