### ISSUE TITLE
Are multiple useStore() calls from the same component allowed?

### ISSUE THREAD

**Issue by VladimirMorozov** [ctrlplusb/easy-peasy#418]
Are multiple useStore() calls from the same component allowed? It does seem to work with v3 
https://codesandbox.io/s/easy-peasy-example-v3-cgonm?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fcomponents%2Ftodos.js&theme=dark
but if I try to get an array in v2 and v1, the second value is outdated. 
https://codesandbox.io/s/easy-peasy-example-w0jnj?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fcomponents%2Ftodos.js&theme=dark
Objects do work in v2 and v1, unlike arrays.

The real use-case is that I want to get state in a custom hook independent of whether the component uses the same state itself.

I didn't find this in documentation, don't see a bug about this and the tests don't seem to test this exact scenario, so I am confused if this is a correct way of using easy-peasy.

**Comment by ctrlplusb** [comment]
Hi @VladimirMorozov 

Yes, of course, it is completely okay to use multiple `useStoreState` calls, grabbing the different parts of state that you need. I'm sorry this isn't more explicit in the docs. I'll ensure we clarify this point.

**Comment by VladimirMorozov** [comment]
My question was more about if it's ok to use it to grab the **same** part of state multiple times. If you look into console in my examples, you will see that in older versions it may lead to outdated values. Can you clarify if the library guarantees that if you use the same state multiple times you get the same result?

**Comment by ctrlplusb** [comment]
Hi @VladimirMorozov;

Yes. This should be the case with the v3 `useStoreState` hook. Every instance accessing the same state must receive the same result. 👍
