### ISSUE TITLE
easy-peasy way to do redux things. e.g. handle async errors

### ISSUE THREAD

**Issue by denu5** [ctrlplusb/easy-peasy#420]
Hello my vegi friends!

In order learn more about easy-peasy and to understand the differences between Redux Toolkit I have 1:1 "converted" a Redux Toolkit tutorial [see here](https://redux-toolkit.js.org/tutorials/advanced-tutorial), which brought up some questions of how to properly use thunks, how to structure the models and where to handle errors.

```
fetchIssues: thunk(
    async (actions, payload, { injections, getStoreActions }) => {
      const { org, repo, page } = payload;
      const { githubService } = injections;
      try {
        actions.getIssuesStart();
        const issues = await githubService.getIssues(org, repo, page);
        actions.getIssuesSuccess(issues);
      } catch (err) {
        actions.getIssuesFailure(err.toString());
      }
    }
  )
```
Q1. How to handle errors? 
I found something in the listeners secion [](https://easy-peasy.now.sh/docs/api/listeners.html#listening-to-specific-stages-of-a-thunk) -> is the idea to throw the error and handle it with the use of "actionOn" and .failType?

What also bugs me a bit is, how the models contain state, reducers, etc on one level; making it a bit harder see which properties belong to the state and to reset the state to the initial values, so I somehow splitted it up similiar to rtk, not sure if  makes sense though because of e.g. computed values which are in the state again...

In the rtk example I also like how the thunks are outside of the state model, making the whole thing a bit more readable, and maybe easier to "test".

```
interface IssuesState {
  issuesByNumber: Record<number, Issue>;
  currentPageIssues: number[];
  pageCount: number;
  pageLinks: Links | null;
  isLoading: boolean;
  error: string | null;
}

export interface IssuesModel extends IssuesState {
  getIssueStart: Action<IssuesModel>;
  getIssuesStart: Action<IssuesModel>;
  getIssueSuccess: Action<IssuesModel, Issue>;
  getIssuesSuccess: Action<IssuesModel, IssuesResult>;
  getIssueFailure: Action<IssuesModel, string>;
  getIssuesFailure: Action<IssuesModel, string>;
  fetchIssue: Thunk<IssuesModel, FetchIssuePayload, Injections, StoreModel>;
  fetchIssues: Thunk<IssuesModel, FetchIssuesPayload, Injections, StoreModel>;
}

const issuesModel: IssuesModel = {
  ...issuesInitialState,
  getIssueStart: action(startLoading),
  getIssuesStart: action(startLoading),
```

What I also didn't figure out is if its nicer to dispatch sideeffects from the components or using action/thunkOn's across the whole store

Anyway, thanks Sean for this really cool library! I'm really looking foward to all the great things to come! 

If anyone wants to play around with the whole thing: [codesandbox](https://codesandbox.io/s/github/denu5/react-rtk-github-issues-example-using-easy-peasy) or  [github](https://github.com/denu5/react-rtk-github-issues-example-using-easy-peasy)
- feel free to add your comments and share ideas, or just take the red pen and correct me!

**Comment by ctrlplusb** [comment]
Hey @denu5 👋

Apologies for the late reply. You caught me as my twin daughters were coming into this world. 😅

I have been slowly getting things back on track and getting v3.4.0 ready for release. A big one. Feels like a major release in terms of amount of work done, but stoked it's gonna be a non-breaking change.

In regards to your questions...

> Q1. How to handle errors?
I found something in the listeners section -> is the idea to throw the error and handle it with the use of "actionOn" and .failType?

I think a lot of this will come down to personal preference. The listener based solution (targetting the `.failType`) provides a nice separation of concerns, but it also increases complexity. It becomes slightly harder to directly see the relationships. IMO your example code (i.e. try/catch within a thunk) should be the primary mechanism by which to handle errors.

Listeners also become helpful when responding to errors across model boundaries.

> What also bugs me a bit is, how the models contain state, reducers, etc on one level; making it a bit harder see which properties belong to the state and to reset the state to the initial values

Yeah, I can feel this. It's a bit of give and take here. Working out some conventions in terms of naming can help (e.g. specific prefixes based on them being an action/thunk/etc).  I did play with the idea of separating the declarations initially but I personally found the entire model tree a lot easier to mentally parse and reason about if I kept things colocated.

> What I also didn't figure out is if its nicer to dispatch sideeffects from the components or using action/thunkOn's across the whole store

Again this comes down to ambitions of a project. I think it's completely okay to only use Easy Peasy for actions and state and then manage side effects through your components. There may be larger projects for scale that would prefer to manage side effects centrally, allowing them to more easily be reused and tested in isolation.

> If anyone wants to play around with the whole thing: codesandbox or github

Really cool to see this direct translation! Thanks for doing this. 💜

Hope that helps and that you are still finding the library useful. 🙏
