### ISSUE TITLE
PWA Caching

### ISSUE THREAD

**Issue by bmitchinson** [ctrlplusb/easy-peasy#424]
Looking into using easy-peasy for an upcoming PWA with very specific rules on when what data gets fetched when, and strict caching limits on when data needs to be refreshed / held onto in offline mode.

Anyone have any OS projects that involved caching data in easy-peasy for reference? Any recommendations to how to manage the easy-peasy store from a service worker perspective? 

Wondering if there could even be caching models / rules included within the store entries, would be interested in implementing that if that's not solved by other solutions / development methods.

Thanks for any feedback

**Comment by ctrlplusb** [comment]
Hey there, have you looked at the [persist](https://easy-peasy.now.sh/docs/api/persist.html) API?

This provides a mechanism by which to store your app data within.

**Comment by bmitchinson** [comment]
thanks exactly what i needed thank you! sorry i that didn't see it :/
