### ISSUE TITLE
Question - ​Is there anything like a fetch interceptor (just like axios interceptors)?

### ISSUE THREAD

**Issue by josoroma** [ctrlplusb/easy-peasy#426]
Question - ​Is there anything like a fetch interceptor (just like axios interceptors)?

Thanks!

**Comment by ctrlplusb** [comment]
Hi @josoroma 

Thanks for the question, unfortunately this question isn't specific to Easy Peasy. 

Unfortunately we don't have the capacity to answer questions outside of scope.

I would suggest asking on StackOverflow. 👍
