### ISSUE TITLE
Question: debounce useStoreState

### ISSUE THREAD

**Issue by macrozone** [ctrlplusb/easy-peasy#428]
i would like to debounce a value from `useStoreState`, because i send it straight to a apollo query. I don't want to debounce the action that sets this state, because i use it for a controlled input as well.

is there any good pattern to do that? Maybe with a computed property?

**Comment by marvinroger** [comment]
That's just a hook - just use a `useDebounce` hook, something like https://github.com/xnimorz/use-debounce

**Comment by macrozone** [comment]
@marvinroger that kind of works, but it would still trigger e rerun of that component whenever the result of `useStoreState` changes.

**Comment by ctrlplusb** [comment]
@macrozone - yep, but as you then proxy the result of the `useStoreState` into the `useDebounce` it wouldn't be a "full rerender".  👍
