### ISSUE TITLE
Can't seem to get middleware to work

### ISSUE THREAD

**Issue by skidrowe** [ctrlplusb/easy-peasy#43]
Trying to hook up some middleware but it doesn't seem to work. 
Simple code is as follows: 
`
import { createStore} from "easy-peasy";
import { applyMiddleware } from "redux";

const logger = store => next => action => {
  console.log("dispatching", action);
  let result = next(action);
  console.log("next state", store.getState());
  return result;
};
export const store = createStore({
    {my store here}
  },
  applyMiddleware(logger)
);`

It's probably me with a simple mistake (99% of the time it is) but I'm not having any luck and I think it's an error...

Thank you!

**Comment by ctrlplusb** [comment]
Hey @skidrowe 

You can pass any additional middleware via the config parameter to `createStore`.

See the docs for more info:
https://github.com/ctrlplusb/easy-peasy#createstoremodel-config

**Comment by skidrowe** [comment]
Thank you. Sorry, I scanned right over that too. Great library/tool btw - really enjoying using it. The option of using immer/spread is fantastic. Sometimes I just want it to work first and then I go back and recode it the spread way. :-)
