### ISSUE TITLE
How to call an action from another action?

### ISSUE THREAD

**Issue by shoeman22** [ctrlplusb/easy-peasy#430]
Say I have a cart application with these 2 methods

```javascript
addToCart: action(state, { id, quantity}) => { state.cart[id] = quantity },
increaseQuantity: action(state, { id, quantity }) => { state.cart[id].quantity += quantity }
```

If the item already exists in the cart when `addToCart` is called, how could I make `addToCart` turn around and just call `increaseQuantity` if the item was already in the `state.cart` object?

ie:
```javascript
addToCart: action(state, { id, quantity}) => { 
  if(state.cart[id]) {
    //dispatch actions.increaseQuantity({id, quantity}) here instead
    return
  }
  state.cart[id] = quantity
}
```

**Comment by CyriacBr** [comment]
You can't, you need to use a thunk instead. 
https://easy-peasy.now.sh/docs/api/thunk.html#dispatching-an-action-on-another-part-of-your-model

**Comment by ctrlplusb** [comment]
@shoeman22 there are quite a few ways to deal with this type of requirement:

- use a thunk to manage the logic and delegate to multiple actions
- leverage listener actions
- create a function that acts as shared logic between actions, which you can subsequently call from as many actions as you like, passing in the state etc
