### ISSUE TITLE
Question: Update deep nested object

### ISSUE THREAD

**Issue by Samushel** [ctrlplusb/easy-peasy#432]
I'm using the store to save the user profile that's fetched from the API. How can I update a deep nested object? Right now I'm trying to update the object, but I don't get the most recent changes on the store:

```es6
const userModel = {
  profile: { name: 'Bob', address: { streetAddress: 'Some Street' } },
  setProfile: action((state, payload) => {
    state.profile = payload;
  }),
};
const setProfile = useStoreActions(actions => actions.user.setProfile);

const updatedUser= { name: 'Bob', address: { streetAddress: 'Updated Street' } };

setProfile(updatedUser);
```

**Comment by ctrlplusb** [comment]
Hi @Samushel 

Updating the model in a nested manner is completely allowed. Could you create a simple reproducible example in CodeSandbox.io for me please?
