### ISSUE TITLE
UI frames drop when using thunkOn failType

### ISSUE THREAD

**Issue by JeromeDeLeon** [ctrlplusb/easy-peasy#435]
I have tried using both ant-design and rsuite to display an error during `catch` block or `thunkOn(failType)` of a thunk but the notification slows down. It only happens with `failType`.

```js
signInUser: thunk(
  (
    { clearFormError },
    { username, password },
    { injections: { userService } },
  ) => {
    clearFormError();

    return userService.signIn(username, password);
  },
),
onSignInUserFailed: thunkOn(
  action => action.signInUser.failType,
  ({ showFormError }, { error }) => {
    notification.error({
      message: 'Oops...',
      description: error,
    });
  },
)
```

**Comment by ctrlplusb** [comment]
Hey @JeromeDeLeon 

Have you tried utilising the chrome dev tools to see where the frames are being eaten up?

**Comment by JeromeDeLeon** [comment]
No, I haven't. Sorry about that. I do not have much knowledge about profiling performance of the app. I just tried it with codesandbox and the to my surprise, there was no frame drop at all. I don't know if it because of the API, or the approach I took because since listening to thunk dropped the frame, I instead tracked error inside `thunk`:

```js
thunk(
  async (
    { clearFormError },
    { username, password },
    { injections: { userService } },
  ) => {
    clearFormError();

    try {
      await userService.signIn(username, password);
    } catch(error) {
      notification.error({
        message: 'Oops...',
        description: error,
      });
    }
  },
)
```

**Comment by ctrlplusb** [comment]
Ok, gonna close this. Will reopen if issue presents itself again.
