### ISSUE TITLE
Creating a computed property from the same named state key

### ISSUE THREAD

**Issue by joelmoss** [ctrlplusb/easy-peasy#437]
So, I want to be able to create a computed property that is derived from a state key (as is usual for a computed property), but I want the computed property to have the same name as the state key.

As an example, I have a startDate that could be null/undefined, but if it is not, then I want to return a date object.

```javascript
{
  startDate: computed(state => {
    return state.startDate ? new Date(state.startDate) : state.startDate
  })
}
```

Obviously this means being able to access a state value of the same name. So it creates a max call stack error (a recursive loop), as it is trying to access itself.

It would be great to be able to access the "raw" state value without it calling the computed property of the same name.

Perhaps, a new way of defining an "accessible property"...

```javascript
{
  startDate: attribute({
    reader: rawValue => rawValue && new Date(rawValue),
    writer: newValue => newValue.toJSON()
  })
}
```

Thoughts?

**Comment by ctrlplusb** [comment]
Hi Joel;

I'm not entirely sure this would be the best thing to add to the library. To be honest I don't know if it will be that intuitive of a feature and I worry that it would cause confusion.

I feel like it would be best to work with some restrictions in terms of API and allow for this type of problem to be moved into user land space.

Sorry about that. Hope you managed to solve your problem and I hope you are staying safe. 💜
