### ISSUE TITLE
TypeError: Cannot read property 'getState' of undefined (Testing with Jest & Enzyme)

### ISSUE THREAD

**Issue by szmarci** [ctrlplusb/easy-peasy#438]
I'm trying to test a component with Jest and Enzyme, like this:

```
it('active tab is first', () => {
  const store = createStore(storeModel);

  const App = () =>
    <StoreProvider store={store}>
      <Tab children="test" id="a" index={1}/>
    </StoreProvider>
  
  const wrapper = shallow(<App />);
}
```

I'm trying to mock out the store with an initial state, then supplying it to `StoreProvider`.
Tab component is hooking into the state like this:

```
export const Tab: FunctionComponent<IChild> = ({ children, id }) => {
  const activeId = useStoreState(state => state.activeTab);
  ....
}
```

The error is thrown at the `useStoreState` line:

`TypeError: Cannot read property 'getState' of undefined`
```
at useStoreState (node_modules/easy-peasy/src/hooks.js:38:43)
at Tab (src/components/Tab.tsx:9:20)
at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:858:32)
at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:645:55)
```

Is this something I am missing or this is not supposed to work like that?

**Comment by ctrlplusb** [comment]
Hey @szmarci 

Sorry, I use `@testing-library/react` these days so I am no longer the best to advise on this. One thought though; if you switch to Enzyme's "mount" API does it work? If so it may be an issue with React's context and Enzyme's shallow renderer.

**Comment by szmarci** [comment]
Hey @ctrlplusb 
Thanks for stopping by. It does work with mount, however rendering the whole tree in every test is pretty slow unfortunately

**Comment by ctrlplusb** [comment]
You are likely facing this restriction:

https://github.com/enzymejs/enzyme/issues/2176

**Comment by barakadanny** [comment]
Hi @szmarci,
Did you solve the issue? or find any solution that I could use to solve the issue?

**Comment by mohamedsanoob** [comment]
I have similar issue, that I converted all .ts file to .js file in my project (Type script to java script), and while unit testing getting error as " cannot read property getState of undefined", While wrapping the testing component with <Provider store={store}>

Does anybody know the issue..?
Please help
