### ISSUE TITLE
[Question] Accessing global store actions from component store thunk

### ISSUE THREAD

**Issue by JeromeDeLeon** [ctrlplusb/easy-peasy#439]
I have this scenario where I have `SignInStore` that when successfully logged in, I need to save the current user globally in the context and what I currently did was created two exact copy of `setCurrentUser` in the component and global stores and used `useEffect` to handle communication between the two. Is there a way to access it directly from the component store?

**Comment by jchamb** [comment]
Some basic outline of how your models are structured would help. Do you have two completely different Stores or is everything in the same Store tree?

actionOn and thunkOn the resolver targets get both local actions and global store actions 

eg: `(actions, storeActions) => storeActions.SignIn.setCurrentUser`
[https://easy-peasy.now.sh/docs/api/listeners.html#targetresolver](https://easy-peasy.now.sh/docs/api/listeners.html#targetresolver)

If you're dealing with two completely different stores, would definitely need some basic example of your setup to make a recommendation.

**Comment by JeromeDeLeon** [comment]
Basically, what I had before was this kind of setup:

```js
// context store
const GlobalStore = createContextStore({
  currentUser: null,
  setCurrentUser: action((state, user) => {
    state.currentUser = user;
  }),
});

function App() {
  return (
    <GlobalStore.Provider>
      <SamplePage />
    </GlobalStore.Provider>
  )
}

// component store
const useSignInStore = createComponentStore({
  // exact same copy of setter and getter of the context
  currentUser: null,
  setCurrentUser: action((state, user) => {
    state.currentUser = user;
  }),
  fetchCurrentUser: thunk(async (actions, _, { injections: { userService }}) => {
    const user = await userService.getCurrentUser();
    actions.setCurrentUser(user);
  })
}, { injections: { userService }});

function SamplePage() {
  const setCurrentUser = GlobalStore.useStoreActions(actions => actions.setCurrentUser);
  const [{ currentUser }, { fetchCurrentUser }] = useSignInStore();

  useEffect(() => {
    fetchCurrentUser();
  }, []);

  useEffect(() => {
    setCurrentUser(user);
  }, [currentUser]);

  return (
    <p>Sample Page!</p>
  )
}
```

What I did was instead used `createStore` to be able to use `getActions`.

```js
// context store
const globalStore = createStore({
  currentUser: null,
  setCurrentUser: action((state, user) => {
    state.currentUser = user;
  }),
});

function App() {
  return (
    <StoreProvider store={globalStore}>
      <SamplePage />
    </StoreProvider>
  )
}

// component store
const useSignInStore = createComponentStore({
  fetchCurrentUser: thunk(async (actions, _, { injections: { userService }}) => {
    const user = await userService.getCurrentUser();
    globalStore.getActions().setCurrentUser(user);
  })
}, { injections: { userService }});

function SamplePage() {
  const [, { fetchCurrentUser }] = useSignInStore();

  useEffect(() => {
    fetchCurrentUser();
  }, []);

  return (
    <p>Sample Page!</p>
  )
}
```

**Comment by ctrlplusb** [comment]
Hi @JeromeDeLeon 

Yeah at the moment this is a restriction in terms of the API of the context/component stores. I have been doing some thinking and may introduce simplified APIs of them for v4 that would also essentially provide a mechanism by which you could solve the problem you are describing.

I'll post here when I get a PR together and would appreciate your feedback.

👍

**Comment by JeromeDeLeon** [comment]
Yes, that's my only concern when using some state management. No clever way of communicating between two stores or context to hook store something like that. Btw, I love this library. Good Job! :+1: 

I'm looking forward to the next version.

**Comment by ctrlplusb** [comment]
Hey all;

The new `useLocalStore` API binds your model within your component so you would have access to the context stores. 👍

See #459 for more info.

**Comment by JeromeDeLeon** [comment]
I just read the docs and still don't know how will I be able to access global stores inside `useLocalStore`

**Comment by ctrlplusb** [comment]
No worries dude,

I'll get an example together later 👍

**Comment by ctrlplusb** [comment]
@JeromeDeLeon 

So later in my world apparently means 5 months. 😅

You probably don't care anymore, but here is an example anyways. A modified version of your OP.

```javascript
// context store
const GlobalStore = createContextStore({
  currentUser: null,
  setCurrentUser: action((state, user) => {
    state.currentUser = user;
  }),
});

function App() {
  return (
    <GlobalStore.Provider>
      <SamplePage />
    </GlobalStore.Provider>
  );
}

function SamplePage() {
  const setCurrentUser = GlobalStore.useStoreActions(
    (actions) => actions.setCurrentUser,
  );

  const [state, { fetchCurrentUser }] = useLocalStore(
    () => ({
      fetchCurrentUser: thunk(
        async (actions, _, { injections: { userService } }) => {
          const user = await userService.getCurrentUser();
          setCurrentUser(user); // 👈 calling the context store action
        },
      ),
    }),
    [setCurrentUser], // 👈 note we set this external dependency
    { injections: { userService } },
  );

  useEffect(() => {
    fetchCurrentUser();
  }, []);

  return <p>Sample Page!</p>;
}

```

**Comment by JeromeDeLeon** [comment]
I totally forgot this one. 😂

Regardless, thanks for solution you provided. Totally appreciated!
