### ISSUE TITLE
Promise finally not called when testing

### ISSUE THREAD

**Issue by paoloiulita** [ctrlplusb/easy-peasy#441]
Hello!
First of all I want to take the opportunity to thank you for the awesome easy-peasy.
I am using v3.3.0
I admit I don't know if this is an easy-peasy issue, but it seems that, only in test environment, actions inside a finally block don't get called.
Since the involved code is pretty much, i set up a code sandbox that reproduces the problem.
You can find it [here](https://codesandbox.io/s/finally-bug-4elk3)
Just switch the commented lines 15 and 16 in the index.test.js to see that in the "finally" scenario the outcome of the console.log does not contain the second `setLoadingNewsletterConsent` action.
When running on the browser it's all working properly.

I thank everyone may have a look at this, given that, as said, I don't know if this is a Jest or easy-peasy problem

**Comment by ctrlplusb** [comment]
Hey @paoloiulita 

Glad you are enjoying it. 👍

In terms of your problem I think the problem may be with your implementation. Whilst thunks support async operations if you don't return the `Promise` that is getting executed within (or use async-await) then the `await` in your test isn't able to wait for the full resolution of the `Promise`.

I modified your codesandbox. Check it out [here](https://codesandbox.io/s/finally-bug-n4t0j). 

Have a good one, and stay safe with everything going on right now. 💜

**Comment by paoloiulita** [comment]
Hello and sorry for the delay.
Thank you very much for answering.
I have, indeed, changed the implementation.
Rather than calling the actions manually i switched to `actionOn`. I think is a more correct approach
Relevant code is

`
setLoading: actionOn(
		actions => actions.load.startType,
		state => {
			state.loading = true;
		}
	),
	unsetLoading: actionOn(
		actions => actions.load.type,
		state => {
			state.loading = false;
		}
	),
`
