### ISSUE TITLE
getState() of undefined error on nodeEnv: false

### ISSUE THREAD

**Issue by raifemre** [ctrlplusb/easy-peasy#442]
Hi, 

on my next.config.js for webpack, I've added this;

```
config.optimization = {
      nodeEnv: false,
 };
```

added this because in some cases I need the dev env variables in production build.

and tried to run the NextJS app after the build with "NODE_ENV=development next start -p 8000"... easy-peasy started to complain about getState() of undefined error. Does getState() something to do with NODE_ENV ?

**Comment by ctrlplusb** [comment]
It sounds like your app isn't correctly wrapped with the `StoreProvider`.
