### ISSUE TITLE
How to compare to previous state

### ISSUE THREAD

**Issue by AkalUstat** [ctrlplusb/easy-peasy#456]
If there is an action that executes based on diffs between current state and previous state, how can we access previous state?

**Comment by paoloiulita** [comment]
Hello, you use actions to mutate state, so AFAIK i would solve this problem by using a computed maybe

**Comment by ctrlplusb** [comment]
Hey @AkalUstat 

You could use a thunk to coordinate logic between state updates. They also have the capability to get the initial state / final state. Thunks can be executed synchronously if they only fire other synchronous actions.

```typescript
const myModel = {
   coordinatingThunk: thunk((actions, payload, { getState }) => {
      const initialState = getState();
      actions.doSomething();
      const newState = getState();
      if (initialState.foo !== newState.foo) {
        console.log('the state changed. 😅');
      }
   })
}
```

Hope that helps.

**Comment by AkalUstat** [comment]
Thanks @ctrlplusb! This is pretty much what i was looking for! 😊

**Comment by ctrlplusb** [comment]
💜
