### ISSUE TITLE
🚨 v3.4.0 - beta ready for testing  🚨

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#460]
We are prepping the `v3.4.0` release  🎉

This is a call for beta testers. We would super appreciate any early adopters and feedback. 💜

All the details can be found in #459 

**Todo** 

#364
#384
#410 

**Completed**

#300
#355
#359 
#361 
#378
#386 
#390
#402 
#411
#419
#427 
#440 
#444 
#446
#451 
#452 
#454
#462

**Comment by nainardev** [comment]
Why don't you create a milestone or project, instead of showing all completed and todos?

**Comment by nainardev** [comment]
Where's the status of v4 then?

**Comment by ctrlplusb** [comment]
Watch this space.

**Comment by mkuklis** [comment]
@ctrlplusb thank you for your progress on this.

I just wanted to give you a quick feedback.

We upgraded to 3.4.0-beta.2 from 3.4.0-alpha.23 and unfortunately the issue with computed properties described in #462 came back.

Our setup is pretty straightforward with "easy-peasy": "3.4.0-beta.2" in package.json without a direct immer dependency.

I do see immer v7.0.8 installed.

I wonder if something has changed which is triggering this behavior.

**Comment by ctrlplusb** [comment]
Hi @mkuklis 

Thanks for bring this to my attention! I'll look into this soon as my hope is to get 3.4.0 released within a month.

I really appreciate you taking the time to test drive it, and surface these issues.

I'll keep you posted. 🙏

**Comment by ctrlplusb** [comment]
FYI all this is now becoming v4 😅

**Comment by nainardev** [comment]
Wow! Thanks everyone for this amazing state library! Wonderful!

**Comment by onionhammer** [comment]
@ctrlplusb you got a ballpark date? :)

**Comment by ctrlplusb** [comment]
@onionhammer  

I mean don't hold me to it, but hoping to have the RC out within 2 weeks.

**Comment by ctrlplusb** [comment]
Closing this. Stay tuned for the update.
