### ISSUE TITLE
How to reuse action creators in redux-devtools-extension?

### ISSUE THREAD

**Issue by aspiers** [ctrlplusb/easy-peasy#467]
Firstly, thanks for easy-peasy - it is totally awesome, and really lives up to its name!!

From [release v2.4.0 of redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.4.0) onwards, it's possible to use action creators for the dispatcher.  As you can see from [that animated image](https://cloud.githubusercontent.com/assets/7957859/17291006/114e7da8-57ea-11e6-99a9-050cca68e95b.gif), it allows easy dispatching of actions without having to manually construct the correct JSON payload, which is a very handy feature for actions which are commonly needed during debugging.

However, I can't figure out how to use this from easy-peasy.

Those release notes link to [these examples](https://github.com/zalmoxisus/redux-devtools-extension/commit/477e69d8649dfcdc9bf84dd45605dab7d9775c03); however since [easy-peasy's API for `createStore()`](https://easy-peasy.now.sh/docs/api/create-store.html) is different to [Redux's API for `createStore()`](https://redux.js.org/api/createstore), it's not obvious how to take advantage of this feature by configuring the right enhancer.

I found [this comment in #119](https://github.com/ctrlplusb/easy-peasy/issues/119#issuecomment-473594317) which led me to https://easy-peasy.now.sh/docs/api/store-config.html#advanced-configuration which suggests I can do something like

```js
const storeConfig = {
  storage: "localStorage",
  enhancers:
    window.devToolsExtension && window.devToolsExtension({ actionCreators }),
  //compose: composeWithDevTools({ realtime: true, trace: true }),
};

const store = createStore(persist(storeModel, storeConfig));
```

but where do I get `actionCreators` from?  In plain Redux I know you tend to build these by hand, but in easy-peasy that is taken care of automatically.

**Comment by aspiers** [comment]
OK I think I figured out I can get the action creator via `store.getActions()` after the store has been created:

```js
const storeConfig = {
  storage: "localStorage",
  //compose: composeWithDevTools({ realtime: true, trace: true }),
};

const store = createStore(persist(storeModel, storeConfig));

const actionCreators = {
  updateState: store.getActions().activeState.updateState
};
```

... but that causes a chicken-and-egg scenario since I need the creator(s) before creating the store in order to configure it with them.

I tried to work around that issue by reconfiguring the store after creation:

```js
if (window.__REDUX_DEVTOOLS_EXTENSION__) {
  storeConfig.enhancers = window.__REDUX_DEVTOOLS_EXTENSION__({ actionCreators });
  console.log("Setting enhancers:", storeConfig.enhancers);
  store.reconfigure(persist(storeModel, storeConfig));
}
```

but I still don't see the nice template feature shown in the animated image in the release notes:

![](https://cloud.githubusercontent.com/assets/7957859/17291006/114e7da8-57ea-11e6-99a9-050cca68e95b.gif)

**Comment by ctrlplusb** [comment]
Very interesting. Thanks for bringing this to my attention.

**Comment by aspiers** [comment]
Any update?

**Comment by ctrlplusb** [comment]
Hi @aspiers 

Unfortunately nothing on my side. I don't have a strong motivation tbh to see this one through. Like you say there is an apparent chicken and egg scenario.

If you get any further ideas, I would be happy to discuss, but for now I am trying to minimise the issues I need to focus on.
