### ISSUE TITLE
SetState function

### ISSUE THREAD

**Issue by lishine** [ctrlplusb/easy-peasy#47]
Would be handy to have set function on each level:
```
				set: (state, newState) => {
					Object.assign(state, newState)
				},
```

What do you think?

**Comment by lishine** [comment]
Thanks for this great example!
But today I found out why this approach of using general object.assign function for setting state is not good. When I set some property that didn't exist there. Would I wrote setter for this property setAuth, I would get an error!

**Comment by ctrlplusb** [comment]
Ok, no worries. I am going to close this issue for now. 👍
