### ISSUE TITLE
Can't use hooks

### ISSUE THREAD

**Issue by ownedbypeli** [ctrlplusb/easy-peasy#471]
`import { useStoreActions } from 'easy-peasy';
import {getJavaProjects} from '../requestsHandler';

export const getPrepareAndSetJavaProjects = async() => {
    var response = await getJavaProjects();
    var data = response.data;
    const setJavaProjects = useStoreActions(actions => actions.javaProjects.setJavaProjects);
    setJavaProjects(data);
}`

The error is:
./src/services/javaProjectsService.js
  Line 7:  React Hook "useStoreActions" is called in function "getPrepareAndSetJavaProjects" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

**Comment by schrej** [comment]
The error even explains what you did wrong. You can only call hooks from react components or other hooks.

**Comment by ctrlplusb** [comment]
@ownedbypeli - welcome.

You may be new to React, or to their new hooks API. Our APIs are based around hooks. I would highly suggest you read the official React documentation on the subject. They are extremely well written.

Let us know if you need help with anything else.

👍

**Comment by ownedbypeli** [comment]
Okay, I think I understand the problem and yes I am pretty new to react :)

Thanks for the fast response!

So in my case, I want at the first render of my application to get some data from the backend and put it into the store. What's the "to-do" way for this case?

**Comment by ctrlplusb** [comment]
FYI, @ownedbypeli - when doing code block examples in GitHub issues. Surround the code block with a ``` above and below the code. I am going to edit your original post to do this. 👍
