### ISSUE TITLE
Persisting State offline

### ISSUE THREAD

**Issue by nainardev** [ctrlplusb/easy-peasy#472]
How Can i persist the state to localstorage? Do you have an API for that?

**Comment by ctrlplusb** [comment]
Yep, there is the [`persist`](https://easy-peasy.now.sh/docs/api/persist.html) API. 👍

Though, v3.4.0 is gonna bring some much needed fixes, improvements, and guides in regard to this API. The API itself shouldn't change though, so safe to start using.
