### ISSUE TITLE
Set up GitHub actions

### ISSUE THREAD

**Issue by nainardev** [ctrlplusb/easy-peasy#473]
For all tests?

**Comment by ctrlplusb** [comment]
Not sure I understand. We have travis running the tests already and they are run against each PR commit (with code coverage also reported). What did you have in mind?

**Comment by nainardev** [comment]
I didn't knew you had Travis.
Thanks bye🙂

**Comment by ctrlplusb** [comment]
Hahahaha no worries ☺️
