### ISSUE TITLE
Advanced tutorial

### ISSUE THREAD

**Issue by nainardev** [ctrlplusb/easy-peasy#474]
Can we build an advanced app with data fetching and similar things in easy peasy docs??

Like how redux has, but may not be the same

**Comment by ctrlplusb** [comment]
I think it would be good to list the type of things that people would like to see expressed in such a tutorial.

Feedback from the community in this regard would be appreciated. 💜

**Comment by nainardev** [comment]
idea #1: an app with data fetching, like to an api, reddit or github, like in redux docs

or why not the same app, so that people can see how easy it is to build with easy-peasy

**Comment by ctrlplusb** [comment]
Closing due to lack of engagement.

Happy to reopen if engagement ensues.
