### ISSUE TITLE
Accessing the store provided to StoreProvider outside of a React component

### ISSUE THREAD

**Issue by m1yon** [ctrlplusb/easy-peasy#479]
I'm having trouble accessing the store outside of a React component. We have a plain JavaScript function that does some initial state population. To do this, we just import the store directly and use store.getActions(), etc. The problem is for our Jest integration tests we want each tests to have it's own individual Easy Peasy store, so we're using createStore and wrapping them individually in their own StoreProvider, but in the places we're importing the store directly they're all looking at that same file (since we don't have a way to reference the store provided to the StoreProvider from outside of a React component). Is there anyway to access the store provided to the StoreProvider? What's the best solution here?

Thanks, we love easy-peasy!

**Comment by ctrlplusb** [comment]
Hey @m1yon,

There are two solutions that come to mind. Dependency injection or clever use of jests module/mocking APIs 

Could you throw together a simple example in CodeSandbox (they let you write jest tests too). 

I would be happy to amend it for you with a solution.

👍

**Comment by m1yon** [comment]
I ended up just changing all my vanilla JavaScript functions to custom hooks and it works great! Thanks for the quick response though.
