### ISSUE TITLE
All stores in one place in redux devtools

### ISSUE THREAD

**Issue by lishine** [ctrlplusb/easy-peasy#480]
Can actions of all the component and context and global store be shown under one store, in one page of the redux devtools?
If there is no such option, can it be developed? It is convenient to see all the actions in one list, don't you think?
There is reinspect BTW, it puts all react useState and useReducer in one devtools store.
Thanks

**Comment by ctrlplusb** [comment]
Hey @lishine 

Long time. 😊

Sounds like an interesting idea. It's worth an investigation at the least. 👍

**Comment by lishine** [comment]
Ye, great you remember me! I remember the beginning.
I enjoyed building two apps with easy-peasy. I used it also to cache API data. Also it was SSR, so was easier to have one global store.

Today I am leaning towards react-query approach for the purpose of data cache. And in general, use several context/feature based stores.

**Comment by ctrlplusb** [comment]
I agree with you on `react-query`. 💜

I am closing this issue for now due to lack of engagement by community. Hope that is ok.
