### ISSUE TITLE
update state after calling an asynchronous function

### ISSUE THREAD

**Issue by hjhimanshu01** [ctrlplusb/easy-peasy#481]
I have defined a model something like this

```
export default {
 collection: [],

  getCollection: action( async (state, payload) => {
    const res = await getCollectionFromServerFunction(payload); 
     state.collection.push(res);
  }),
};
```

This function gives an error `TypeError: Cannot perform 'get' on a proxy that has been revoked
` while if I don't call any asynchronous API, it doesn't gives the error.

I'm not sure if `thunk` is the only is way to do it or any changes here are possible ?

**Comment by sabirahmed121** [comment]
I believe you shouldn't call the state update after async call.
If you want to update your state after the call then make sure you have it as a different action.
```

export default {
 collection: [],
  addToCollection: action(state, payload) => {
  },
  getCollection: action( async (state, payload) => {
    const res = await getCollectionFromServerFunction(payload); 
     addToCollection(res);
  }),
};
```

This is to make sure the state is consistent after the async call.
