### ISSUE TITLE
StateMapper does not always work with branded types

### ISSUE THREAD

**Issue by anion155** [ctrlplusb/easy-peasy#482]
Currently using ts-brand for branding. StateMapper does not work properly with number brands. Example:

```typescript
type UserId = Brand<string, 'user-id'>;
type TimeStamp = Brand<number, 'utc-timestamp'>;
interface UserInteraction {
  timeStamp: TimeStamp;
  userId: UserId;
}
```

`timeStamp` field in this example will be `never`.

**Comment by ctrlplusb** [comment]
Hi @anion155 

I'm interested to know if you tried this with the 3.4.0 alpha (#459)?

**Comment by anion155** [comment]
> Hi @anion155
> 
> I'm interested to know if you tried this with the 3.4.0 alpha (#459)?

Not yet, will try later
