### ISSUE TITLE
Unable to dispatch a thunk using Store.dispatch()

### ISSUE THREAD

**Issue by jungans** [ctrlplusb/easy-peasy#484]
I'm trying to call the `dispatch()` method like this

```js
const actions = MyStore.getActions()
const { notify } = actions.global
MyStore.dispatch({
  type: notify.type,
  payload: {},
})
```
This is working fine when `notify` is an action but fails when it's a thunk.
Redux DevTools shows the dispatch but the thunk is not actually invoked.
Is this a known issue? Or maybe I'm not supposed to use `dispatch` for thunks?

**Comment by ctrlplusb** [comment]
Yeah, unfortunately you would need to add a bit more to the payload to get this to work.

The best way is to dispatch it via the actions object that you are already calling.

```javascript
MyStore.getActions().global.notify('Hello world');
```
