### ISSUE TITLE
Access to injections via `computed`

### ISSUE THREAD

**Issue by rzane** [ctrlplusb/easy-peasy#485]
I'm passing in a service via injections to my store. It's working great, so far!

However, I'm hoping to flip between the real implementation of a service and a fake implementation of that service based on some state.

Would it be possible to pass injections through to computed properties?

```javascript
const fakeService = createFakeService();

const settings = {
  isFakeService: false,
  toggleFakeService: action(state => {
    state.isFakeService = !state.isFakeService;
  }),
  service: computed((state, { injections }) => {
    return state.isFakeService ? fakeService : injections.service;
  })
}
```

**Comment by ctrlplusb** [comment]
Hey @rzane 

At the moment, no. 

I have been toying with the idea of exposing injections to all the model helpers, but a part of me is not 100% sure about this yet.

Let's keep this alive and hopefully some dialog around it forms.
