### ISSUE TITLE
store.getActions is not a function - shared store/state in a micro-frontend (easy-peasy.esm.js)

### ISSUE THREAD

**Issue by vtrikoupis** [ctrlplusb/easy-peasy#488]
A global store created with 
`export const store = createStore(storeModel);` 

is being federated in a separate module as 
```
const [store, setStore] = useState(null);
  federation("main", "store").then((storeResolved) => {
    setStore(storeResolved);
  });
```

It's then provided to the app as

```
 <StoreProvider store={store}>
      <App />
 </StoreProvider>
```

The error I get when an easy-peasy method such as useStoreActions is called is `store.getActions is not a function`thrown at easy-peasy.esm.js when useStoreActions is about to be defined.

When debugging, right before the error is thrown I can see that the store is initialised as such:

```
store: {…}
__esModule: true
store: {…}
   addModel(key, modelForKey)
   clearMockedActions()
   dispatch()
   getActions()
   getListeners()
   getMockedActions()
   getState:f()
   liftedStore: {…}
   persist: {…}
   reconfigure(newModel)
   removeModel(key)
   replaceReducer(n)
   subscribe(listener)
   Symbol(observable)()
```

Is there more I need to do than createStore when the store is being exported since the module is federated through webpack? Thanks

**Comment by ctrlplusb** [comment]
Hi @vtrikoupis 

This is likely because your application is resolving multiple versions/instances of Easy Peasy. The version would need to be consistent so that the exact same `StoreProvider` is referenced and used by the various Easy Peasy modules.

**Comment by vtrikoupis** [comment]
Hi @ctrlplusb 

I'm going to look at this and report back, I thought I had ensured a single instance being federated from the main app to the rest of the components but this indeed may not be the case. Thanks

**Comment by vtrikoupis** [comment]
Hi @ctrlplusb the federated easy-peasy dependencies weren't being overridden by the ones on the core model. So yes, ensured easy-peasy is a singleton and now everything works fine. The miicrofrontend doesn't itself need to run without the core app in my case so it doesn't need the store at its level. Providing at the core higher level, structure looks a bit like this.


 <StoreProvider store={store}>
      <HomeRoute />.  //core model
   </StoreProvider>


// Somewhere inside the core model
const FederatedComponent = lazy(() => import("microfrontend2/FederatedComponent"));

return (
    //Store is provided at a higher level
     <>
              <Suspense fallback={<div>...Loading</div>}>
                     <Route path='/microfrontend2/component_name' component={FederatedComponent} />
              </Suspense>
     </>

I'll try write this up in a nicer way
