### ISSUE TITLE
Integration with react-router url params

### ISSUE THREAD

**Issue by Nabellaleen** [ctrlplusb/easy-peasy#489]
I have routes with a parameter I would like to see saved as value in the store.

The naive approach is :

```
<Route path="page/:id">
  <Page />
</Route>

// ...

export const Page = () => {
  const { id } = useParams()
  const setId = useStoreActions((actions) => actions.variables.setId)
  useEffect(() => {
    setId(id)
  }, [id, setId])
  return (<ContentComponent />)
}

// ...

export const DeeplyNestedComponent = () => {
    const { id } = useStoreState((state) => state.variables)
    useEffect(() => heavyMethod(id), [id])
    return (<SomeContent />)
}
```

The problem is there are 2 render, one with the initial id value, and one with the updated value following the setId call.
And so, 2 calls to heavyMethod

So, I would like to perform the update to the store "before" the first rendering.
How could I do that ?

Use a class component an do it in the constructor is not possible, as `useStoreActions` is a hook and so, not available

Any idea ?

**Comment by ctrlplusb** [comment]
I feel like [`redux-first-history`}(https://github.com/salvoravida/redux-first-history#readme) may be of help here. 🙏
