### ISSUE TITLE
easy-peasy + redux-offline?

### ISSUE THREAD

**Issue by chamatt** [ctrlplusb/easy-peasy#492]
Is there a way to use this library with redux-offline? Does anyone have an example implementation?

**Comment by sanchitos** [comment]
Why don't you persist easy peasy using redux-persist?

That's how we are handling offline support.

[https://github.com/ctrlplusb/easy-peasy/issues/40#issuecomment-454493790](url) Here's an example.

**Comment by chamatt** [comment]
@sanchitos Yeah, I saw that issue, and I already use that approach in some of my projects.

But redux-offline is another layer on-top of redux-persist, to handle network problems, optimistic updates, rollbacks, etc.

It can all be done manually with redux-persist, but it helps out a bit.

**Comment by kipopov** [comment]
@chamatt Did you figure this one out? I am curious about using redux-offline with easy-peasy as well...
