### ISSUE TITLE
TypeError: Cannot set property of null

### ISSUE THREAD

**Issue by corysimmons** [ctrlplusb/easy-peasy#496]
Hey, I'm trying out 3.4. I got pretty far but just hit this nasty bug and can't figure it out after a few hours of fighting with it so I'm just giving up.

```typescript
// app.ts
const [state, actions] = useLocalStore<IFoo>({
  selectElement: action((_state, id) => {
    const oldSelectedNode = getSelectedNode(_state.nodes);
    oldSelectedNode.selected = false;
    const newSelectedNode = getNodeById(_state.nodes, id); // this returns null even though unit tests with mocked data work
    newSelectedNode.selected = true; // fails because null.selected
  }),
});
// ...
return <RecursiveElement nodes={state.nodes} actions={actions} />;

// RecursiveElement.ts
import { Element } from 'my-styled-components';

// ...
<Element
  // @ts-ignore
  as={node.tag}
  key={node.id}
  node={node} // pass this on to the styled-component
  onClick={(e) => {
    e.stopPropagation();
    console.log(node.id); // 🕵️‍♂️ works
    actions.selectElement(node.id); // 💩🛏
  }}
>
  {!!node.nodes.length && (
    <RecursiveElement nodes={node.nodes} actions={actions} />
  )}
</Element>;
```

Use case:
- I have a recursive component (rendering out a tree).
- When I click a component, I want to set ALL nodes to have "selected = false" and the clicked on component to get set to "selected: true"

What I'm trying:
- set store using `useLocalStore` within <Wrapper>
- pass `state` and **`actions`** to a child [of <Wrapper>] component
- in the child component, hit a utility function that steps through the tree figuring out what the selected node is, and also the node to get by ID.

Seems like a race condition. I'd try to debug it longer if the entire thing wasn't mangled in whatever that proxy stuff is... 😩

**Comment by corysimmons** [comment]
Can't reproduce in reduced test case and the project I'm working on is pretty good sized so I don't want to pull it all out to make a reduced test case. Just hoping someone randomly knows what's going on.

**Comment by ctrlplusb** [comment]
Hey @corysimmons;

Sorry to hear about your frustration.

Quick question... what `type` is being returned by `getSelectedNode` and `getNodeById`?

**Comment by corysimmons** [comment]
No worries. I liked easy-peasy a lot and seeing how well you maintain it is inspiring. I don't like that it obfuscates everything in the proxy part... I don't know if you can do anything about that, but it makes it really hard to debug stuff.

re: types. Everything is a `string`.

I don't want to paste code here, but I'll add you to the repo if you want to take a look.

**Comment by corysimmons** [comment]
Actually nevermind, I'm just going to go back to Redux. I think you're a great maintainer and everything, but I can't get bugged out of developing for a day or two.

![image](https://user-images.githubusercontent.com/224636/83088662-5adea000-a062-11ea-9251-571a440f9636.png)
What is this? If I try to console.log certain values, I get this thing instead of the value. It's the #1 reason I'm bailing. I can't begin to logically debug if some magic Proxy thing is mangling/obfuscating values. I just have to guess and check. Is this from Immer or Redux? I'm guessing Immer because of some mutable stuff?

**Comment by ctrlplusb** [comment]
Yo @corysimmons;

No problem dude, do what is best for yourself. 

There are few things in the pipeline which should alleviate this pain, one being the `immer@7.0.0` release (which I noted you have commented on already). The other being a minor extension to the `action` API allowing you to bail out of `immer` usage on a per action basis.

In the mean time you have two options.

1. Disable `immer` via the [store config](https://easy-peasy.now.sh/docs/api/store-config.html) and use standard reducer like results (i.e. object / array spreading).

```javascript
const model = {
  stuff: [],
  addToStuff: action((state, payload) => {
    return {
      ...state,
      stuff: [...state.stuff, payload],
    };
  })
}

const createStore(model, {
  disableImmer: true,  // 👈
});
```

2. Utilise the [debug helper](https://easy-peasy.now.sh/docs/api/debug.html) which will allow you see the _original_ value of the state

```javascript
import { debug } from 'easy-peasy';

const model = {
  stuff: [],
  addToStuff: action((state, payload) => {
    console.log(debug(state));
    state.push(payload);
  })
}
```

---

Whatever you go for, I'm sorry to hear some headbanging has been going on. I can empathise, and it's never fun to be in that state.

**Comment by corysimmons** [comment]
That `debug` thing might help a lot actually. I tried to use `original` from Immer but it didn't seem to help.

**Comment by ctrlplusb** [comment]
Sounds like a super tricky case. If you'd like a fresh pair of eyes on it I am happy to look for ya. You can revoke my access to the repo thereafter.

**Comment by corysimmons** [comment]
@ctrlplusb Invited you to org and will add you to repo. You have/use Discord perchance? Cory#1063

**Comment by ctrlplusb** [comment]
Ok, got the invite. I'm in your base. 😛

Yeah, just fired it up again. Updates done. Ready to go. My username is `ctrlplusb`. 👍

**Comment by corysimmons** [comment]
![image](https://user-images.githubusercontent.com/224636/83103882-9474d280-a085-11ea-9a61-7b5686cafd1b.png)


In Discord, need the #1234 as well

**Comment by ctrlplusb** [comment]
`#0618`

😊
