### ISSUE TITLE
adding persist causes error

### ISSUE THREAD

**Issue by Fahad999** [ctrlplusb/easy-peasy#497]
I'm not sure if I'm doing it the right way, but I just tried adding persist like this

const store = createStore(persist(model), {
  disableImmer: true,
  middleware: [thunk, configuredLogger]
});

now the store persists on refresh but i get the following error and blank page gets rendered
:
"index.js:1437 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."

**Comment by ctrlplusb** [comment]
Hi @Fahad999 

Would you be able to create a minimal reproduction in codesandbox?

FYI - thunk middleware is included by default. :)
