### ISSUE TITLE
[Question] Redux Persist and Easy-Peasy: How to change the structure of the persisted store.

### ISSUE THREAD

**Issue by sanchitos** [ctrlplusb/easy-peasy#499]
I came across with the problem of changing a model which already have been persisted.

I found out this article: https://blog.bam.tech/developer-news/redux-persist-how-it-works-and-how-to-change-the-structure-of-your-persisted-store

But I don't know how to make it work with easy-peasy or what you guys recommend if you are persisting data and then later (after you are in prod) need to change the structure.

Thank you very much. I hope I am in the right place.

**Comment by chamatt** [comment]
I'm not sure if you can do this with the builtin persist feature. But in case you cant, you should be able to use raw redux-persist and integrate it with easy-peasy. @ctrlplusb wrote an example of how to achieve that here:

https://github.com/ctrlplusb/easy-peasy/issues/40#issuecomment-454493790

**Comment by ctrlplusb** [comment]
v4 is going to include a lot to help with this. 🙏

Stay tuned for the upcoming release.
