### ISSUE TITLE
`computed` calls its function with incorrect state

### ISSUE THREAD

**Issue by dhmk083** [ctrlplusb/easy-peasy#500]
```js
import { createStore, computed, action } from 'easy-peasy'

const store = createStore({
  items: [],
  count: computed(state => state.items.length),
  add: action(state => {
    state.items.push(Math.random())
  }),
})

const s1 = store.getState()
store.getActions().add()

console.log(`expected ${s1.count} to equal ${s1.items.length}`)
// expected 1 to equal 0
```

It seems that `computed`'s state is always the latest state of a store. So, snapshots of old states (like `s1` here) are broken. Shouldn't they be immutable?

**Comment by VolanDeVovan** [comment]
Try to
`const s1 = store.getState().count`

**Comment by ctrlplusb** [comment]
Sorry, I had an epiphany about this.

This is now fixed in v4. Please watch out for the release.

It will now behave exactly as you expect it to. 💜
