### ISSUE TITLE
Typing for Computed is asking for result

### ISSUE THREAD

**Issue by filipesmedeiros** [ctrlplusb/easy-peasy#501]
Hey! Love the library, thanks for the work.

I was using TS and when I use a `Computed` property and access it through `useStoreState`, TS asks me to `.result`, although it works if I don't use it.

Example:

```typescript
export interface Model {
    selectedId: number
    selected: Computed<Model, SomeObject>
}

export init: Model {
    selectedId: 1,
    selected: computed(state => arrayOfObjects[state.selectedId])
}

function Component() {
    // This will be an object like { type: 'computed', result: SomeObject }
    // Although if I ignore it JS picks up the correct value
    const selected = useStoreState<StoreModel, SomeObject>(state => state.model.selected)
}
```

I've also tried state resolvers and the same thing happens

Btw, I'm only opening this because the docs never seem to mention this need to `stateProperty.result` thing!

**Comment by ctrlplusb** [comment]
Hey @filipesmedeiros 

I believe there were some issues with the typings for those. Would you mind trying out v3.4.0 and reporting back your experience?

**Comment by filipesmedeiros** [comment]
Hey! Thanks for the quick answer!

The issue persists on `3.4.0-beta.1`

Here is a screenshot: 

![image](https://user-images.githubusercontent.com/26208850/85037203-f0aaae00-b17c-11ea-92f7-d682bcf6ab28.png)

`selectedZone` is computed, and `zones` is a normal field of the state.

Error:

![image](https://user-images.githubusercontent.com/26208850/85037288-1041d680-b17d-11ea-9d72-e09cc214ad85.png)

Thanks in advance! If you need help with a PR I can take a look at it (although I assume you're much better suited to resolve this than me ahah)

**Comment by filipesmedeiros** [comment]
Actually on a second note, `3.4.0-beta.1` did even worse I think , because now `useStoreState` with no typings complains about the `state.zones` like this:

![image](https://user-images.githubusercontent.com/26208850/85037624-83e3e380-b17d-11ea-9014-b95e8ca45c29.png)

Which wasn't happening before, previous it just let me "do whatever what I want"

**Comment by ctrlplusb** [comment]
Hmmm, this doesn't sound right.

Would you mind putting together a small CodeSandbox minimal reproduction example for me?

I will investigate from there and make any recommendations if needed. 👍

**Comment by filipesmedeiros** [comment]
Sorry could only do it now.

I think this is what you need:

https://codesandbox.io/s/cocky-sea-3p8w3?file=/src/App.tsx

**Comment by ctrlplusb** [comment]
Looking fine here, on v4 branch though. 😅

https://codesandbox.io/s/cocky-sea-3p8w3?file=/src/App.tsx
