### ISSUE TITLE
Computed in nested store lost when using persist

### ISSUE THREAD

**Issue by Beaker73** [ctrlplusb/easy-peasy#503]
**prerequisites**
* using `persist()`
* computed properties in _nested_ store

**description**
When you have computed properties in a nested store with computed properties. These properties are lost when page is reloaded and loaded from persistence. `useStoreState` will fail when accessing the property due to it being undefined at that point.

**reproduction**
[Example on CodeSandBox](https://codesandbox.io/s/easy-peasy-computeds-lost-when-using-persist-sdgjc)
The above example will initially seem to work. Click a few times to update and persist the store.
Then when you press F5 to reload, the page will fail due to non existing computed properties in the nested store.
The root computed properties are correctly available, but those from the nested store not.

**Comment by fourteenmeister** [comment]
I confirm, I also stocked with this

**Comment by ThePaulMcBride** [comment]
Hey @ctrlplusb, I'm running into this issue too. Seems that computed values in a persisted store don't have access to the persisted state initially. I'm using the localForage storage provider and it still occurs. Is there anyway I can help debug this or help get it sorted?

**Comment by ctrlplusb** [comment]
Hey all, so the v4 release addresses this issue. The computed properties will be rebound correctly on rehydration.

I've made a ton of fixes and improvements to the persist API. It involves some breaking changes, however, I believe the improved reliability and consistency of the API will be worth it.

Keep your eye out for the v4 release notes and the updated docs on the persist API. 👍

**Comment by ctrlplusb** [comment]
btw, here is a modified version of your codesandbox showing the expected behaviour via the v4 release:

https://codesandbox.io/s/easy-peasy-computeds-lost-when-using-persist-forked-pcg40

Only had to change the dependencies. :)
