### ISSUE TITLE
Possible to use server-side, possibly without React?

### ISSUE THREAD

**Issue by mickmister** [ctrlplusb/easy-peasy#505]
Hello!

I have a React application with some music/midi related code in it, that heavily involves my easy-peasy store. I would like to use the store itself in a context outside of React, but I know it relies on React hooks.

My use case is to have this code run in an Ableton Max for Live device using [Node for Max](https://docs.cycling74.com/nodeformax/api). I have a decent amount of code that I want to plugin into the device, but I will not be rendering anything as I don't have a DOM to work with anyway. Everything is event-driven by events in Ableton such as the midi event NoteOn or NoteOff.

I have thought about having a dummy React "app" in the node script that constantly re-renders on each midi event, but I don't know if this is practical, nor do I know exactly what approach I would take to accomplish this. Any ideas on my situation?

Thanks for this amazing tool!

Edit: I suppose if the solution is going to use React, I could use server-side rendering, and use a `useEffect` hook to register my store-specific actions to a service. Then expose that service to the Ableton event-driven code. Then when state changes happen, I can handle them with a different `useEffect` when appropriate values have changed? I don't know, I probably need to try some things out and see what works. Or just extract the code I want to use out of the store. So many options.

**Comment by ctrlplusb** [comment]
Sorry i am afk but i have some suggestions i will drop here later.
