### ISSUE TITLE
[Question] Return some status from thunk

### ISSUE THREAD

**Issue by rbgfloripa** [ctrlplusb/easy-peasy#506]
Hi all,

Is there any way to return something from a thunk?
I have a thunk that I run on useEffect. How can I get the result if an error has occurred?
"actions.setError(true)" -> I don't think it's a good option.

```javascript
loadRoles: thunk(async (actions) => {
  API.get('/roles')
    .then((response) => actions.setRoles(response.data))
    .catch(() => {
      // return some information to caller
    })
}),
```

Thanks

**Comment by Beaker73** [comment]
You marked the function as async. So you can just use await for the api call and return the retrieved data.
If you want to use the then and catch promise methods, you should remove the async and return a Promise yourself. you can then resolve the promise with the value to return. Something like
``` javascript
loadRoles: thunk((actions) => {
  return new Promise((resolve, reject) => {
    API.get('/roles')
      .then((response) => actions.setRoles(response.data))
      .catch(() => {
        // either reject, which is normal for errors
        reject(myErrorData);
        // or if you really want it back as data, without rejecting
        resolve(myData);
      })
  }
}),
```

**Comment by ctrlplusb** [comment]
For those interested here is how to do it via async/await:

```javascript
loadRoles: thunk(async (actions) => {
  try {
    const { data } = await API.get('/roles');
    actions.setRoles(data);
    return data;
  } catch (err) {
    return err;
  }
}),
```

**Comment by omitchen** [comment]
@ctrlplusb @Beaker73 
According to the official website documentation, why do you have to return a promise in thunk, what will happen if you don't return it (like the title), thank you for your answer
<img width="954" alt="image" src="https://user-images.githubusercontent.com/23668478/175500741-ab654622-67b9-4ab2-adc5-41156ef48e27.png">
