### ISSUE TITLE
Good design for web sockets integration?

### ISSUE THREAD

**Issue by angelhodar** [ctrlplusb/easy-peasy#512]
Hey there guys, first of all thank you for creating easy-peasy, its really awesome and easy peasy to use ;). I was wondering if you have any example with some websocket library (SocketIO, SocketCluster, etc) using a store created with easy-peasy. I am watching a few videos about how to correctly integrate a web socket client into my project (making sure to only have one instance, how to pass the connection between components, etc).

I have doubts about how to persist the socket variable in a store created with easy-peasy to be able for any component to use it to listen to certain events, like for example listening for events to draw a [timeline](https://material-ui.com/es/components/timeline/).

I have thought about something like this:

1. Create an easy-peasy store with a format like this:

```js

// model.js
{
    socket: null,
    timeline: [],
    other stuff....

    // Actions
    updateSocket: action((state, socket) => {
    	state.socket = socket;
    });

    addTimelineEvent: action((state, event) => {
    	state.timeline.push(event);
    });
}
```

2. Implement the store for the App component:

```js
import React from "react";
import ReactDOM from "react-dom";
import { StoreProvider, createStore } from "easy-peasy";

import model from "./model";
import App from "./components/app";

const store = createStore(model);

function Root() {
  return (
    <StoreProvider store={store}>
      <App />
    </StoreProvider>
  );
}

ReactDOM.render(<Root />,  document.getElementById("root"));
```

3. In my App component, using the UseEffect hook i would establish the connection with the server:

```js
import React, { useEffect } from 'react';
import { useStoreActions } from 'easy-peasy';
import socketcluster from "socketcluster-client";
import Navigation from "./Navigation";

export default function App() {
  const updateSocket = useStoreActions(actions => actions.updateSocket);
  const addTimelineEvent = useStoreActions(actions => actions.addTimelineEvent);

  useEffect(() => {
    const socket = socketcluster.connect(url);

    socket.on("error", function (err) {
      console.error("Socket error - " + err);
    });

    socket.on("connect", () => {
      updateSocket(socket);

      socket.on("TimelineEvent", data => {
        addTimelineEvent(data);
      });
    });

  }, []);
  return (
    <Navigation></Navigation>
  );
}
```

4. Then my timeline component would just keep its state in sync with the store timeline variable:

```js
import React from "react";
import Timeline from "@material-ui/lab/Timeline";
import TimelineItem from "@material-ui/lab/TimelineItem";
import TimelineSeparator from "@material-ui/lab/TimelineSeparator";
import TimelineConnector from "@material-ui/lab/TimelineConnector";
import TimelineContent from "@material-ui/lab/TimelineContent";
import TimelineDot from "@material-ui/lab/TimelineDot";


export default function EventsTimeLine() {
  const timeline = useStoreState(state => state.timeline);
  const socket = useStoreState(state => state.socket);

  // I dont know if doing this or add it inside the socket.on("connect")
  // in the App component as in step 2.
  useEffect(() => {
    socket.on("TimelineEvent", data => {
      addTimelineEvent(data);
    });
  }, []);

  return (
    <Timeline align="alternate">
      {timeline.map((e) => (
        <TimelineItem key={e.eventName}>
          <TimelineSeparator>
            <TimelineDot color="primary" />
            <TimelineConnector />
          </TimelineSeparator>
          <TimelineContent>
            {e.eventName} - {e.timestamp}
          </TimelineContent>
        </TimelineItem>
      ))}
    </Timeline>
  );
}
```

If you notice I havent used the socket variable in the timeline component, I dont know if the best solution is to keep the socket as in the App component listening to all possible events or using the socket variable from the state in the UseEffect of the components and listen to certain events that only those components are going to use.

Im confused because I like to write well structured and maintainable code so I would be more confident watching to some websocket chat example from you guys. I would be pleased to add an extra example in codesandbox  with the final result of the discussion in this issue.

Thanks in advance :)

**Comment by ctrlplusb** [comment]
Hi @angelhodar 

I'm sorry I just don't have capacity to be able to analyse and answer these types of questions right now. My spare time is severely limited right now, and I donate what little I have to try and maintain the project. Please can you ask this on StackOverflow instead?
