### ISSUE TITLE
Does easy-peasy tries to access localStorage even though I don't persist my store?

### ISSUE THREAD

**Issue by baptisteArnaud** [ctrlplusb/easy-peasy#513]
Hello!

I have an app that uses easy-peasy and is embedded in an iframe in another web app. But the problem is when I try to load the iframe on a browser that blocks 3rd party cookies by default (ie: Brave):

It says `Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

I'm pretty sure it's caused by easy-peasy because I don't try to access `localStorage` anywhere. I tried to check the code, but I couldn't find an answer...
Does easy-peasy call localStorage even though the store isn't persisted?

**Comment by ctrlplusb** [comment]
Hi @baptisteArnaud 👋

Thanks for reporting this. I spotted the issue. The fix will be in the next release. 🙏
