### ISSUE TITLE
Persist transformers - incorrect order

### ISSUE THREAD

**Issue by czeslaaw** [ctrlplusb/easy-peasy#515]
Hi. While trying to make multiple transformers work (and almost losing my sanity) I encounter a bug with transformers order. Its caused by using transformers.reverse() method that mutates the array.

Expected result: transformers are applied **left to right** on persisting and **right to left** on rehydrating.

Actual result: transformers are applied **right to left** on persisting and **right to left** on rehydrating.

Pull request: https://github.com/ctrlplusb/easy-peasy/pull/514

**Comment by ctrlplusb** [comment]
Done in v4! Announcement soon. 💜
