### ISSUE TITLE
useStoreState tiggering on every store model change

### ISSUE THREAD

**Issue by kladnik** [ctrlplusb/easy-peasy#516]
Hi!

I am having issue with the library when using `useStoreState`. I would expect it to trigger only when a watched state is changed, but for some reason it triggers on every store change.

An example:
```javascript
const videoPlayback = useStoreState(
        ({ playback }) => {
            console.log('playback', playback);
            if (playback) {
                player.current.seekTo(playback.start, 'seconds');
            }
            return playback;
        },
        (prev, next) => prev?.start === next?.start
    );
```
Here I would expect it to only trigger if start changes, but it also logs when I change a different state (like url) that is not inside `playback`.

Is this intended or am I missing something?

Love the library otherwise, simplifies Redux insanely.

Thanks!

**Comment by Beaker73** [comment]
As far as I understand it, `useStoreState` is always called on every change. The selector then selects the data. EasyPeasy will then compare the value you returned against the previous value. (or as you did it here, call the second compare function you provided). Only if it changeed, then useStoreState will return with an updated value that triggers rerendering of your component. If the compare resulted in no change, then you component should not rerender.

It seems to me that you are also triggering 'business logic' (seek) inside the selector. Maybe you could move that to useEffect with a dependency on the store state you selected. If your business logic also requires any changes in the store, the useEffect could use a thunk/action to update the store.

**Comment by ctrlplusb** [comment]
Yep, @Beaker73 is correct here. Please avoid doing anything other than pure state resolution within your `useStoreState` hooks. You could lift out that logic into a `useEffect` hook:

```typescript
const playback = useStoreState(
  (state) => state.playback,
  (prev, next) => prev?.start === next?.start
);

const previousPlayback = React.useRef(playback);

React.useEffect(() => {
    if (playback && playback.start && playback.start !== previousPlayback.current?.start) {
      playback.current.seekTo(playback.start, 'seconds');
    }
    previousPlayback.current = playback;
}, [playback])
``` 

Hope that helps. 🙏
