### ISSUE TITLE
How to get normal action creator?

### ISSUE THREAD

**Issue by mgutz** [ctrlplusb/easy-peasy#518]
How to get a normal redux action creator from easy-peasy that returns an action object, ie `{type, payload}`? `useStoreActions` returns mapped functions.

```javascript
const somecAction = useStoreActions(actions => actions.slice.someAction);

// do not want mapped action
someAction(id).then(...)

// want plain redux action creator for use with dispatch
dispatch(someAction(id))
```

We have a custom `useDispatch` hook.

**Comment by ctrlplusb** [comment]
Hi @mgutz 

I am struggling to understand the motivation behind this request. Why do you need to use the custom `useDispatch` hook?
