### ISSUE TITLE
How to execute code once an action has updated the store?

### ISSUE THREAD

**Issue by paultannenbaum** [ctrlplusb/easy-peasy#52]
I am trying to execute code once the store has been updated from a model action, and I do not see an easy way to subscribe to this. 

If I trigger the action in an effect, I am still seeing the effect promise resolving before the triggered action has updated the store. Is there any kind of event we can hook directly into to the action callback or store to achieve this?

Here is some example code of what I am facing:

```
const defaultState = {
  user: {},
  counter: {},
  ....
}

// model
const model = {
  ...defaultState,
  // Action
  resetState: (state) => ({ ...state, ...defaultState }),
  // Effect
  logOut: effect(async dispatch => {
    const asyncCall = await ApiService.logOut();
    return dispatch.resetState();
  })
}

// View
const logOutButton = () => {
  const logOut = useAction(dispatch => dispatch.logOut);

  return <Button 
                onClick={() => logOut().then(() => console.log('Assume that the store has updated from the resetState action'))}
               >Log Out</Button>
}
```

In the above psuedo code, I am seeing the console.log function in the logout button firing before the store has finished updating from the `resetState` action. In the devtools I am actually seeing the resolved promise function being invoked before the `resetState` action has been triggered.

Any help would be appreciated.

**Comment by ctrlplusb** [comment]
Hey @paultannenbaum 

I am not seeing the same behaviour as you. I've thrown up a codesandbox that logs as the state is updated:

https://codesandbox.io/s/6v76wy322w

You will see the message update as the effect is parsed. Check the console log too. Two state updates followed by the resolution message.

Is there something more to the problem that you are experiencing that you aren't detailing here? What are you trying to do after the logout action is fired?

**Comment by paultannenbaum** [comment]
Thanks for the quick reply and example @ctrlplusb. 

I went ahead and added a debugger to the resolved promise function in your example. Here is the fork:

https://codesandbox.io/s/31pmz9oz61

Below are some screenshots of both the console and redux devtools at the time of the debugger statement:

Console:
<img width="831" alt="screenshot 2019-01-23 12 02 30" src="https://user-images.githubusercontent.com/220885/51633588-d6788c00-1f06-11e9-8111-5533465d2450.png">

Redux Devtools:
<img width="966" alt="screenshot 2019-01-23 12 03 34" src="https://user-images.githubusercontent.com/220885/51633626-f27c2d80-1f06-11e9-8f21-68d1bb39af23.png">

All the console.logs are firing, even though only the first `@action.updateMsg` action has been executed.

In my case (which granted is kinda wonky), my frontend lives inside of a rails application. I am logging the user out (which should reset the state), and then calling `window.location.assign(sign_in_path)` and letting the rails router render the sign in path (so a hard refresh). I am also using the `redux-persist` lib, and because that reset state never actually is executed, the stale state is rehydrated into memory when someone visits that old path in the same browser window, even if it is a different user. 

Right now I am able to get around the above race condition by wrapping my `window.location` assignment inside of a `setTimeout` function call, which adds it to the event loop queue and then executes everything in the correct order. But I do think it is worth bringing up that the effect resolved promises do seem to be resolved before the state tree itself has been fully resolved.

**Comment by ctrlplusb** [comment]
Ah I see now, in terms of the actions fired. Yeah, I think I know what this is. 

Are you listening for the `@effect.doSomething` action to be fired elsewhere?

**Comment by paultannenbaum** [comment]
When you say you are of two minds in moving the dispatch to after the effect body has completed, what would be the concerns in doing this? To me as a casual user of the library, I was expecting the promise returned from the effect to only resolve one the body has completed. 

I think having started/completed states makes a lot of sense since effects are async.

**Comment by ctrlplusb** [comment]
> I was expecting the promise returned from the effect to only resolve once the body has completed

This should be the case. Are you not experiencing this? If you ignore the redux dev tools and instead focus on the console.log statements this should be the case - i.e. the effect promise resolves after all the body has fired.  Could be a bug with the internals then.

**Comment by paultannenbaum** [comment]
Correct, in my case I documented above, I was receiving the resolved promise before the effect body had completed updating the state tree (or at least the updating of the local storage object. I know that the library is middleware and is hooking in before the store receives the body, but I am not sure if the library saving to storage is happening async or not). 

My scenario is a total edge case, and I was able to get around it by adding my function to the event loop queue (via `setTimeout`), but it does look like it is possible for that race condition to exist.

**Comment by ctrlplusb** [comment]
Hi @paultannenbaum;

I've added a test case to ensure that the state is updated synchronously when actions are dispatched within effects. The test passes, so I am now a bit confused here.

https://github.com/ctrlplusb/easy-peasy/blob/6768d758e855632cd918bf371da6bdbffa23e304/src/__tests__/easy-peasy.test.js#L635

Still need to make the adjustment in regards to effect starting / completing.

**Comment by paultannenbaum** [comment]
Hi @ctrlplusb 

I agree my case is a bit of a head scratcher. Looking at your test it looks like it is covering my scenario, so possibly there is something wrong with my implementation. I have reviewed my code several times and still can't find any obvious errors, but I am only one set of eyes. 

Since I am the only one who seems to be reporting the issue, I'm gonna close this issue and if it comes up again we can always use this issue as a reference. Thanks for taking the time to look into this.
