### ISSUE TITLE
TypeError when using reducer()

### ISSUE THREAD

**Issue by younes0** [ctrlplusb/easy-peasy#524]
When I import this reducer https://github.com/prescottprue/redux-firestore/blob/master/src/reducer.js
```js
import { firestoreReducer } from 'redux-firestore'

const store = createStore(
  {
    firestore: reducer(firestoreReducer)
  }
)
```
I get
```log
immer.module.js:211 Uncaught TypeError: 'ownKeys' on proxy: trap result did not include 'i'
    at Function.freeze (<anonymous>)
    at freeze (immer.module.js:211)
    at Immer.maybeFreeze (immer.module.js:1616)
    at Immer.processResult (immer.module.js:1456)
    at Immer.produce (immer.module.js:1348)
    at Object.queriesReducer [as queries] (queriesReducer.js:85)
    at reducers.js:60
    at Array.reduce (<anonymous>)
    at reducers.js:59
    at index.js:30 
    ...
```

This doesn't happen when I **disable immer**.

Tested on 3.3.1 & 3.4.0-beta

**Comment by younes0** [comment]
UPDATE: I found something that may be a bug

**Comment by younes0** [comment]
I managed to make it work by commenting this line.

![image](https://user-images.githubusercontent.com/886042/88836711-6754b580-d1d7-11ea-87d8-7d2e2c6f22e5.png)

What's the problem ?

**Comment by ctrlplusb** [comment]
Thanks for the report @younes0 

This is an interesting case. I'll definitely mark it for investigation.

**Comment by ctrlplusb** [comment]
Hey @younes0 

Would you be able to try the latest alpha to see if this is resolved? I create an isolated instance of Immer now, so it may be okay.

```
npm install easy-peasy@4.1.0-alpha.8
```

**Comment by ctrlplusb** [comment]
Closing this. Please keep me posted if it is still an issue. 👍

**Comment by younes0** [comment]
@ctrlplusb hey Sean! sorry just started a new work

I get a different error now:

```
Uncaught TypeError: Cannot perform 'getPrototypeOf' on a proxy that has been revoked
    at Function.getPrototypeOf (<anonymous>)

**Comment by ctrlplusb** [comment]
Hey @younes0, no worries. Didn't mean to seem like I was pressurizing you. I just prefer to close things I am not actively needing to look at to maintain my sanity. 😅

Oh dear, this is disappointing. Would you be able to help create a minimal reproduction for me in codesandbox?

**Comment by younes0** [comment]
@ctrlplusb aha okay, it makes sense 👍 
sure I've started already, will update once it's finished, before next week.

**Comment by younes0** [comment]
Voilà : https://codesandbox.io/s/great-swirles-x8fvd?file=/src/App.js:1241-1274

**Comment by ctrlplusb** [comment]
Fix coming in the next release. 🙏

https://codesandbox.io/s/suspicious-snow-d498f?file=/src/App.js

**Comment by younes0** [comment]
thank you so much!
