### ISSUE TITLE
How can I specify an optional payload while creating a thunk?

### ISSUE THREAD

**Issue by rashtay** [ctrlplusb/easy-peasy#537]
Consider the below-given example:

```
fetchAndSaveNearbyPlaces: Thunk<PlacesModel, PlaceAPIOption, Injections>;
```

Depending upon the use case, I might or might not provide a value for the payload parameter. But, typescript throws an error saying `An argument for payload was not provided`

**Comment by kautukkundan** [comment]
+1

**Comment by ctrlplusb** [comment]
You should be able to use a union to indicate this:

```typescript
fetchAndSaveNearbyPlaces: Thunk<PlacesModel, PlaceAPIOption | void, Injections>;
```

Hope that helps. 🙏
