### ISSUE TITLE
computed properties ought not be persisted

### ISSUE THREAD

**Issue by mighdoll** [ctrlplusb/easy-peasy#539]
When using `persist()` I'd expect computed properties not to be stored.

Root level computed properties are not persisted. But computed properties nested in the model are persisted as static values. I'd think computed values should never be persisted. 

In practice, the static property is overwritten with a computed getter in the rootReducer. So the statically stored value mostly just wastes space (and maybe causes a bit of confusion when debugging).

**Comment by ctrlplusb** [comment]
Hi @mighdoll 

I agree. Will mark this as a bug.

**Comment by ctrlplusb** [comment]
This is resolved in upcoming v4 release.

**Comment by johtso** [comment]
I wonder if this should also apply to what is displayed in redux dev tools? It can be quite messy if you have lots of computed properties and they are displayed with all your state diffs.
