### ISSUE TITLE
What does storeState reference when combining models? 

### ISSUE THREAD

**Issue by strawberrysunset** [ctrlplusb/easy-peasy#543]
From what I can tell it will always reference the uppermost node in the model tree. Is there any way for a child model to reference itself? I'm currently having to antipicate the structure of the final model to access the parent state of my current child model. Is there another way?

**Comment by ctrlplusb** [comment]
Hi @strawberrysunset, the `action` helper receives the local state as it's first argument, and the `thunk` helpers will also receive a `state`, which is the local state.

Hope that helps. 🙏
