### ISSUE TITLE
Context stores do not allow custom equality checking function?

### ISSUE THREAD

**Issue by DaneEveritt** [ctrlplusb/easy-peasy#544]
Hi there! I've been coming across a more frequent situation where I cannot figure out if the documentation is wrong, the typings are wrong, or I'm just unaware of something deep in the codebase.

I know for the normal global `useStoreState` calls you can pass an equality function to avoid re-rendering components unecessarily. However, I make use of context stores for some parts of my codebase, and it seems like the `Context.useStoreState()` doesn't allow for the equality comparison functions, even though the documentation seems to indicate it should be an identical call signature.

Is this intended, is the documentation incorrect, or is there just no way to do that with a context store?

If it is not possible, is it something that you would be open to a PR for? It would make my life a lot easier since I'm often working with a lot of object based values within a context store, so the normal `===` comparison is always going to be returning false.

**Comment by ctrlplusb** [comment]
Hi @DaneEveritt 

Thanks for reporting this. This was a bug with our TypeScript definitions. I have patched them. The fix will be in the next release. 🙏

**Comment by DaneEveritt** [comment]
I suppose I should have just tried it at some point, thanks for the clarification! :)
