### ISSUE TITLE
WATCH OUT in Production!! - Redux dev tools is enabled by default

### ISSUE THREAD

**Issue by raul-madrigal** [ctrlplusb/easy-peasy#548]
**Watch out!!! DevTools comes true as default.**

I'm building the app in production mode NODE_ENV=production, and after deploying the build folder, the redux dev tools extension can see the entire state. 
Additionally, I'm persisting and encrypting the local storage, this works fine, but the chrome extension can see the whole thing in plain text.

**EDIT:** Found this piece in the docs: 

```txt
devTools (boolean, optional, default=true)

Setting this to true will enable the Redux Dev Tools Extension.
```

Most people won't notice this and can have their store publicly accessible without knowing.

**Comment by ctrlplusb** [comment]
Haha, a bit dramatic for my tastes.

I'll queue in a patch to default it for dev environment only.

**Comment by raul-madrigal** [comment]
Great lib though, I've been using it for almost 2 years now but until now I noticed this, had to patch all my sites inmediately.

**Comment by ctrlplusb** [comment]
v4 will include the behaviour i described :)
