### ISSUE TITLE
How to customize context store with dynamic injections

### ISSUE THREAD

**Issue by paul-sachs** [ctrlplusb/easy-peasy#550]
This is more of an open question but I was trying to figure out how to inject some additional context (specifically react-intl functions) into my easy-peasy context store. Currently, i think the only way is through initialData but that seems clunky. I was thinking of some kind of API like:

```jsx
const intl = useIntl();

return <store.Provider additionalInjections={{ intl }}>
  ...
</store.Provider>
```

This is still me mostly just thinking out loud, but i feel like it could be useful elsewhere, where injections are a little more dynamic and runtime based.

**Comment by paul-sachs** [comment]
The other thing i thought of was storing the store itself in a context, creating it within a `useMemo` and pulling it of context instead of importing store from a module instead. This may be the most "accurate" way to do this:

```tsx
const storeContext = createContext({} as StoreType);
...
const intl = useIntl();
const store = useMemo(() => createContextStore(..., { injections: { intl }}));

return <storeContext.Provider value={store}>
  <store.Provider>
  ...
  </store.Provider>
</storeContext.Provider>
```

**Comment by ctrlplusb** [comment]
I've just added support for this in the unannounced v4 release (v3.4.0) is being bumped.

Here is the docs for the API:

### Defining injections at runtime

It is possible to provide the store injections at runtime. In order to do so you
can provide them the store's `Provider`.

```javascript
import CounterStore from './stores/counter';

function MyApp({ language }) {
  // Imagine we had a value that changes at runtime, which we intend to use
  // as an injection into our application
  const translator = useTranslator(language);

  return (
    <>
      <Header />
      {/* pass down the injections into the provider
                                               👇  */}
      <CounterStore.Provider injections={{ translator }}>
        <Main />
      </CounterStore.Provider>
      <Footer />
    </>
  );
}
```

This will override any previous injections that were defined when creating the
store. If you wish to instead update the existing injections you can utilise the
function form.

```javascript
import CounterStore from './stores/counter';

function MyApp({ language }) {
  // Imagine we had a value that changes at runtime, which we intend to use
  // as an injection into our application
  const translator = useTranslator(language);

  return (
    <>
      <Header />
      <CounterStore.Provider
        {/* Pass down a function into the injections.
            It receives the previous injections.
                          👇 */}
        injections={(previousInjections) => ({
          // Spread the existing inject values so we can keep them:
          ...previousInjections,
          // Then overwrite the "translator":
          translator,
        })}
      >
        <Main />
      </CounterStore.Provider>
      <Footer />
    </>
  );
}
```

---

Thoughts?

**Comment by ctrlplusb** [comment]
Closing this, but will keep an eye out for your response.

Don't switch to v4 yet though. 😅

**Comment by paul-sachs** [comment]
Oh man, super clean API. This is exactly what I needed. It'll also really helpful with integrating this into an existing redux store. Thanks @ctrlplusb
