### ISSUE TITLE
Computed value not updated when using custom persist storage

### ISSUE THREAD

**Issue by VolanDeVovan** [ctrlplusb/easy-peasy#552]
Computed value not updated when use custom persist storage like redux-persist-electron-storage (But all work properly with localStorage)

**Comment by ctrlplusb** [comment]
Hi @VolanDeVovan 

I'd super appreciate it if you could set up a CodeSandbox minimal reproduction for me. 💜

**Comment by VolanDeVovan** [comment]
> Hi @VolanDeVovan
> 
> I'd super appreciate it if you could set up a CodeSandbox minimal reproduction for me.

I cant reproduce it in codesandbox because i faced this problem in electron application with custom persist storage 
I created repository which can help to reproduce
https://github.com/VolanDeVovan/easy-peasy-issue-552

**Comment by VolanDeVovan** [comment]
![Screenshot_20200927_113159](https://user-images.githubusercontent.com/19747303/94360339-2aad1980-00b5-11eb-892e-e13c8791c792.png)

**Comment by ctrlplusb** [comment]
There was quite a few bugs in the persist API. They've had a major overhaul. Please stay tuned for the v4 release which will include much improved docs on the API too.

Please request to reopen this issue if it persists post v4 release.

**Comment by VolanDeVovan** [comment]
The problem is not solved with the 4.0.0 release

**Comment by ctrlplusb** [comment]
Hi @VolanDeVovan 

Sorry for the delay on this. Could you please try:

```
npm install easy-peasy@4.1.0-alpha.7
```

Also make sure to follow the rehydrate instructions on new docs. 🙏

**Comment by VolanDeVovan** [comment]
> Hi @VolanDeVovan
> 
> Sorry for the delay on this. Could you please try:
> 
> ```
> npm install easy-peasy@4.1.0-alpha.7
> ```
> 
> Also make sure to follow the rehydrate instructions on new docs. pray

Everything is working. Thank you so much  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:

**Comment by ctrlplusb** [comment]
Amazing. Won't be too long till I do an official release. 🙏

Thanks for your patience. 💜
