### ISSUE TITLE
Is thunkOn / actionOn guaranteed to run after computed values?

### ISSUE THREAD

**Issue by kensiebliss** [ctrlplusb/easy-peasy#553]
Contrived example code here. (Prolly such an easy question that no code is required, haha.)

When `actionOn` or `thunkOn` invoke, is it guaranteed to be after all computed values are complete?

![image](https://user-images.githubusercontent.com/70902885/93487594-0db16300-f8cb-11ea-8941-52145ee3177e.png)

**Comment by ctrlplusb** [comment]
Hey @kensiebliss 👋

Yes, it should have run in this case. The "on" APIs are responsive, so the update action would have happened already. 

[Demo here](https://codesandbox.io/s/easy-peasy-starter-forked-vw2nw?file=/src/store.js)

😊
