### ISSUE TITLE
Could we make a immer-peasy free build ?

### ISSUE THREAD

**Issue by el-gringo** [ctrlplusb/easy-peasy#555]
I don't use immer-peasy as it has a heavy overhead but also because it breaks the state driven design.
Following the state driven design we should return a whole new state on every action, not updating it. 
I know the spread syntax can be unreadable for new comers... 

Even though I can disable it in createStore options, it is a big dependency if we don't use it at all (27% of the whole bundle size). See https://bundlephobia.com/result?p=easy-peasy@3.3.1

That would be cool to find a way to not import it.

**Comment by joelmoss** [comment]
It doesn't actually break the state driven design you mention, as Immer uses JS proxies, which means it still returns a new state object every time.

I do however, understand the concerns around additional file size, but in my opinion, it's well worth it.

**Comment by el-gringo** [comment]
I know it's a helper and finally it returns a new state, I meant it doesn't reflect the state driven design. 

I am more concerned about runtime performance as I am working on SmartTV, which are very very slow.

**Comment by joelmoss** [comment]
I would suggest you use something much more lightweight then. If you want something that is full featured like easy-peasy, then you will inevitably pay the cost of large file sizes.

Not to take away from @ctrlplusb awesome work, but check out [zustand](https://github.com/pmndrs/zustand) which is very lightweight, but has very few features above simple state management.

...swings and roundabouts 😏😁

**Comment by ctrlplusb** [comment]
Agree with @joelmoss here.

I had considered making Easy Peasy plugin based. But it pulls it away from its core values.

Zustand is awesome. You can't go wrong there. 🙏

FYI - in v4 of Easy Peasy we are using native `immer`. It's smaller now that they have removed the browser polyfilling by default, but it's still not a huge drop in bytes.

**Comment by el-gringo** [comment]
@joelmoss  Thanks for the advice. I did'nt know about zustand, I'll get a look.
