### ISSUE TITLE
Using context store within another context store

### ISSUE THREAD

**Issue by ramiAbdou** [ctrlplusb/easy-peasy#556]
I have 2 separate (nested) context stores, one that is called `Form` and one that is called `Dropdown`. I have a `computed` property within the `Dropdown` store that is dependent upon a `computed` property in the `Form`. I know that the Computed API allows you to resolve a global store in the execution, but is it possible to resolve a context store?

**Comment by ctrlplusb** [comment]
Context Stores are isolated.

If you would like to great an integration layer you would have to pass in some injections, or utilize the `initialData` prop of the specific context store.

v4, which is soon to be released, also allows passing down injections at runtime - which could be helpful in this case. 👍
