### ISSUE TITLE
How can I access the store when being within a setInterval?

### ISSUE THREAD

**Issue by desmap** [ctrlplusb/easy-peasy#56]
Example here https://codesandbox.io/s/yjvpnvy46z 

Counter should reset to `0` when`3` is reached but doesn't because the fired function of `setInterval` seems to have a different context and can't access the current `count`. When putting the `useStore` directly into `useEffect` instead of `count` (in line 15) I get the typical _put hooks in function bodies only_ error message from React Hooks.

**Comment by ctrlplusb** [comment]
Your example had a fundamental misunderstanding of how hooks works. Your effect was running once only, closing over the original count value from state. I have adjusted your example to work, but I wouldn't really recommend what you are doing. I would also suggest you read the docs on hooks thoroughly and do some more experimentation to expand your understanding. 👍

https://codesandbox.io/s/l72w39mkyq

**Comment by desmap** [comment]
@ctrlplusb, thx for your reply.

I replicated our example with a delegated `useState` hook--this thing works buttersmooth and also with `[]` as second argument (code is at https://codesandbox.io/s/734roqp8nq and I commented the position which makes the difference). The received `set` function from a standard `useState` provides the current state which your easy-peasy API unfortunately doesn't (but the user expects). This would make things much simpler. I mean, just compare your last version with the last version I provided. So, IDK if my example had a fundamental misunderstanding of how hooks work...

**Comment by desmap** [comment]
@ctrlplusb , trust me, I need global state for my use case, it's not about localized data, our counter example is just a strong simplification (sorry but I can't codesandbox my prod code). Look, I test stuff in and out before I put anything into production and lock-in myself, especially a lib like yours with minimal downloads.

I like your API design, I like the way how responsive you are  but tbh something such as providing the state like the original useState is expected by the users (I know custom hooks can have their own signature but still). So, I think it's not even a nice-to-have feature but a must. Don't take this and other issues as negative criticism but rather as feedback which might improve your lib.

However, I must get work done now, I wish you good luck with easy-peasy!
