### ISSUE TITLE
Interacting between models

### ISSUE THREAD

**Issue by 1alexvash** [ctrlplusb/easy-peasy#560]
![easy-peasy](https://user-images.githubusercontent.com/46556479/95658344-5ce16100-0b22-11eb-8cc3-6cc38798d79d.png)
How can I update different module?

**Comment by w3bdesign** [comment]
@1alexvash 

Can you elaborate more in detail what exactly you are trying to accomplish?

**Comment by ctrlplusb** [comment]
@1alexvash you can update nested state within the action.

Actions receive the state local to them, which includes the state below them too.

We can complete your code like so:

```javascript
const store = createStore({
  products: {
    fruits: ["🍏", "🍊", "🍌"],
  },
  addFruit: action((state, payload) => {
    state.products.fruit.push(payload);
  }),
});

store.getActions().addFruit("🍉");
```

😊
