### ISSUE TITLE
When to expect v4 to drop

### ISSUE THREAD

**Issue by rmcarias** [ctrlplusb/easy-peasy#562]
Hi there. I am currently using this lib in our project and I LOVE IT! Thank you for this gem to help ease the pain of state management. 
I have been following the updated to v4 and am eager to use the localStore stuff you have and other features. Couple of questions:
1. When do you expect to drop the v4 version? I tried using the beta but ran into some issues with the minified 'esm' bundled version (which is the default file now for modules and I believe your bundler has changed for this version).
2. In the current version, I do not see any place where it states if a computed prop can have side-effect (like API call)? Is this something that is supported or even makes sense?
3. Is it possible to know when a listener(s) are done?

Thanks again! And can't wait for the updates!
Happy Coding

**Comment by ctrlplusb** [comment]
> Hi there. I am currently using this lib in our project and I LOVE IT!

💜

> When do you expect to drop the v4 version?

Very very very soon. 😊

> I tried using the beta but ran into some issues with the minified 'esm' bundled version

Oh dear! 😱 Would you mind elaborating on this ASAP? This needs to be addressed prior to the v4 release.

> In the current version, I do not see any place where it states if a computed prop can have side-effect (like API call)? 

The improved v4 docs will explicitly declare this as being an anti-pattern. Computed properties should remain pure, simply resolving derived state. You may be interested in the the `unstable_effectOn` API which will be experimentally shipping with v4.

> Is it possible to know when a listener(s) are done?

Could you provide an example of why you need this?

> Thanks again! And can't wait for the updates!

🥰

**Comment by ctrlplusb** [comment]
I've dropped esm build for now. Pending investigation. :)

**Comment by ctrlplusb** [comment]
No worries. :)

@rmcarias could you please test the latest alpha for me?

```
npm install easy-peasy@4.1.0-alpha.1
```

🤞

**Comment by rmcarias** [comment]
@ctrlplusb 
Tried the 4.1.0-alpha.2 and ended up getting the same error (isPlainObject) is not a function. And in further investigation, it seems that it's this piece of code:
`import  { isPlainObject } from 'is-plain-object';`
bringing it in as a named object causes a problem for some reason and it might be because the lib itself, doesn't export a default object? 
/*!```

 * is-plain-object <https://github.com/jonschlinkert/is-plain-object>
 *
 * Copyright (c) 2014-2017, Jon Schlinkert.
 * Released under the MIT License.
 */

function isObject(o) {
  return Object.prototype.toString.call(o) === '[object Object]';
}

function isPlainObject(o) {
  var ctor,prot;

  if (isObject(o) === false) return false;

  // If has modified constructor
  ctor = o.constructor;
  if (ctor === undefined) return true;

  // If has modified prototype
  prot = ctor.prototype;
  if (isObject(prot) === false) return false;

  // If constructor does not have an Object-specific method
  if (prot.hasOwnProperty('isPrototypeOf') === false) {
    return false;
  }

  // Most likely a plain Object
  return true;
}

export { isPlainObject };
```

Worth noting that it may just be because I use webpack 3 for building the system and maybe webpack automatically assumes default when none is provided? 
Can I ask why not just include this logic within your utils (it seem like such a small amount of code not sure why you need a whole npm pkg for this logic)?

Hope this helps. And currently trying 4.0.1

**Comment by ctrlplusb** [comment]
Thanks so much. Feedback has been super useful.

I am getting closer and have uncovered other issues relating to IE11.

Check out the latest attempt:

```
npm install easy-peasy@4.1.0-alpha.5
```

**Comment by rmcarias** [comment]
@ctrlplusb - The alpha.5 fixes the isPlain Object bundle issue. Thank you!
However, as others noted: This is issue still exists in IE 11: `[Immer] Cannot use proxies if Proxy, Proxy.revocable or Reflect are not available` 
even if import the es5 enablement recommendation from IMMER and yourself. Worth noting that by bundler add the Babel polyfills for Reflect.
Let me know how else I can help
