### ISSUE TITLE
Can't create optional thunk payload

### ISSUE THREAD

**Issue by yuschick** [ctrlplusb/easy-peasy#565]
**The Problem**

I am building out a store using TypeScript. In it, I have a thunk which should accept an optional payload. However, I do not know how to properly define this in TypeScript.

This is the type of my thunk.

    fetchStuff: Thunk<
      IStuffModel,
      { language: Language; } | undefined,
      void,
      IStoreModel
    >;

**The Goal**

The goal is to be able to call this thunk in two ways.

    fetchStuff();
    fetchStuff({ language: 'en' });

However, whenever I call it like `fetchStuff()` I receive the following type error.

    Expected 1 arguments, but got 0.ts(2554)
    index.d.ts(56, 4): An argument for 'payload' was not provided.

If I define the thunk payload type as `{language: Language } | void` I receive an error inside the thunk itself where I use `payload?.language`.  The error says that language does not exist on type void. The same goes if I use `null`.

Not sure if this is a bug or if I am just missing something silly.

**Comment by ctrlplusb** [comment]
Hi @yuschick 👋

Can you please try this instead;

```typescript
fetchStuff: Thunk<
  IStuffModel,
  { language: Language; } | void,
  void,
  IStoreModel
>;
```

**Comment by ctrlplusb** [comment]
Ok, I have a fix for this. Will need to write some more tests to guard this. New implementation should allow any combination of void, null, or undefined with it behaving as you expect it to.

**Comment by ctrlplusb** [comment]
Ok, I refined this a bit more and have updated the docs. The payload will only be optional if you union with `undefined` or `void`. If you union with `null` then we will expect you to be passing `null` or the alternative type into the payload. I think there are genuine cases where you may want to use `null` as a signifying value.

This patch will be released shortly.

**Comment by yuschick** [comment]
Wow, thanks so much! I'll keep my eyes open for the release. 💪

**Comment by ctrlplusb** [comment]
NP 👍 

It's released and deployed. 🙏

https://easy-peasy.now.sh/docs/typescript-api/thunk.html
