### ISSUE TITLE
Computed properties incorrectly types when used

### ISSUE THREAD

**Issue by yuschick** [ctrlplusb/easy-peasy#567]
I am using v4.0.1 and using TypeScript in my store, where I have a computed property in a model. However, when trying to use this is my React app, I receive a TypeScript error about the types not being correct.

**Model**
````
 packages?: Computed<
    IPackagesModel,
    { core: Package[]; waves: Package[][]; hasWavesContent: boolean },
    IStoreModel
  >;
````

**React**

````
 <Paths.Core packages={packages?.core} />
````

When doing this, though, I receive a TypeScript error:

````
Property 'core' does not exist on type 'Computed<IPackagesModel, { core: any[]; waves: any[][]; hasWavesContent: boolean; }, IStoreModel>'.ts(2339)
````

And when I hover `packages` it shows me the following type:

```
const strengthPackages: Computed<IPackagesModel, {
    core: any[];
    waves: any[][];
    hasWavesContent: boolean;
}, IStoreModel> | undefined
```

Looking through the v4 release notes, it looks like this was fixed, but I am still seeing issues when trying to use computed properties.

**Comment by ctrlplusb** [comment]
Hey @yuschick 

Yeah, this is a known issue with computed properties...

https://easy-peasy.now.sh/docs/known-issues/typescript-optional-computed-properties.html

That should fix your issue. 🙏

**Comment by yuschick** [comment]
No luck. It might work with something like `number | undefined` but something like ´{ one: 1, two: 2, isTest: true } | undefined` it still errors.

`Property 'name' does not exist on type 'Computed<IPackageModelState, any, {}>'

`activePackage: Computed<IPackageModelState, Package | undefined>;`

**Comment by ctrlplusb** [comment]
Ouch. Will check it out, thanks 👍

**Comment by ctrlplusb** [comment]
Just seen the other issue :)
