### ISSUE TITLE
Computed properties with object values typed incorrectly when used

### ISSUE THREAD

**Issue by yuschick** [ctrlplusb/easy-peasy#570]
I have referenced the known issue (thanks to the link on my previous issue) about the Computed property types being incorrect.
https://easy-peasy.now.sh/docs/known-issues/typescript-optional-computed-properties.html

However, I am still having issues with using computed properties in my UI.

**Model**
```
activePackage: Computed<IPackageModelState, Package | undefined>;
activePackageSlug?: PackageSlug;
```

**Package Type**
```
type Package = {
  description: string;
  imageAsset: ImageAsset;
  live: Live;
  name: string;
  slug: PackageSlug;
};
```

**Hook**
I create a custom set of hooks that use the typedHooks as described in the docs in order to only export out 'public' actions.

```
const typedHooks = createTypedHooks<IStoreModel>();
const useStoreState = typedHooks.useStoreState;
const usePackageState = () => useStoreState((state) => state.packages);
```

**React Usage**
```
const { activePackage } = usePackageState();

<p>{activePackage?.name}</p>
```

**TypeScript Error**
`Property 'name' does not exist on type 'Computed<IPackageModelState, any, {}>`

Easy-Peasy v4.0.1
TypeScript v4.0.3

**Comment by ctrlplusb** [comment]
Hi @yuschick 

I have tried writing a test case for this but it is working as expected.

<img width="526" alt="Screenshot 2020-10-19 at 15 20 53" src="https://user-images.githubusercontent.com/12164768/96413968-0c06f200-121f-11eb-8ad5-04e0153373e4.png">

I am using typescript@4.0.3 and easy-peasy@4.1.0-alpha.7

**Comment by ctrlplusb** [comment]
Updated to even more closely match your case...

<img width="475" alt="Screenshot 2020-10-19 at 15 26 01" src="https://user-images.githubusercontent.com/12164768/96414251-73bd3d00-121f-11eb-9acb-a7158ddc6137.png">

**Comment by ctrlplusb** [comment]
Closing this for now. Please let me know if it is still an issue for you.

I'll be releasing v4.1.0 soon. 🙏

**Comment by yuschick** [comment]
Yeah, this is still an issue for me.

![image](https://user-images.githubusercontent.com/563226/96968260-6a7ee980-1519-11eb-87c0-f0e5a0f122d4.png)

Even the computed types are off. Where it shows `any` should be the `Strength` type.

**Comment by yuschick** [comment]
Okay. So I did some `rm -rf node_modules` and removed lock files and did some reinstalls, closed VS Code and opened again and stuff and it looks to be cool now. Probably just a hiccup in the stack somewhere.

**Comment by yuschick** [comment]
So after removing node_modules and lock files and reinstalling, and closing VS Code and reopening, this looks to be okay now. Must have been a hiccup in the stack somewhere.

I will note though that this didn't work with the 4.1.0-alpha.  I did this for 4.0.1 and it worked. I repeated it again for the alpha and the error returned.
