### ISSUE TITLE
Cannot read persist of undefined when rehydrating

### ISSUE THREAD

**Issue by yuschick** [ctrlplusb/easy-peasy#571]
I'm having some problems with `persist` and `rehydrating`.  I followed the docs and receive the error `cannot read persist of undefined` when calling `useStoreRehydrated()`.

I have a store comprised of multiple models.

```
const store = createStore(
    {
      ...storeModel,
      settings: { ...storeModel.settings, env },
    },
    { injections: { client } }
  );
```

For this error, I am having issues with `settings.language`. So here's the settings model.

```
const settingsModel: ISettingsModel = persist(
  {
    ...state,
    ...actions,
    ...listeners,
  },
  {
    storage: 'localStorage',
    allow: ['language', 'theme'],
  }
);
```

A few of the child models use persist on themselves to store only their specific properties. This works so far.

However, since v4, my app renders before the store is rehydrated. So if the local storage language is English, the app will render with the default value of Finnish. This makes sense, again, according to the docs. So I need to rehydrate my store before rendering anything.

```
const PositiveProvider: React.FC<IProps> = ({
  children,
}) => {
  client.defaults.baseURL = baseUrl;

  const store = createStore(
    {
      ...storeModel,
      settings: { ...storeModel.settings, env },
    },
    { injections: { client } }
  );

  const isRehydrated = useStoreRehydrated();

  return isRehydrated ? <StoreProvider store={store}>{children}</StoreProvider> : null;
};
```

However, doing this results in the error that persist cannot be read from undefined.

I'm sorry to be posting another issue / question for you 😞

**Comment by yuschick** [comment]
Just a thought, do I need to delay calling `useStoreRehydrated()`?

**Comment by ctrlplusb** [comment]
No need to apologise. Thanks for raising such detailed issues. I'll look into this. Actually there was another report on this. I have done half a look into it and have some ideas. I think the resolution to this will satisfy 3/4 related issues.

**Comment by yuschick** [comment]
Thanks for digging into it again. Any idea what I could do in the meantime?  Using `overwrite` for the `mergeStrategy` worked, but in the event the local storage is empty for a new user, an empty object replaces settings. So not entirely sure how best to move forward.

**Comment by ctrlplusb** [comment]
I believe this is now fix in the next alpha:

```
npm install easy-peasy@4.1.0-alpha.7
```

Please could you try it out and let me know. 🙏

**Comment by yuschick** [comment]
This week is finishing up a sprint so it's a bit crunched. I will have a chance to verify this next week. Sorry for the hold up on this.
