### ISSUE TITLE
Issue with Immer polyfills after upgrading to version 4.0.1

### ISSUE THREAD

**Issue by jmyrland** [ctrlplusb/easy-peasy#573]
_First off: 👏 for the good work on the new release! I think I just had to change one line (in a test) after the upgrade for everything to be working 👏_

However, I've got a tiny issues with supporting older browser.  I've done as explained [here](https://easy-peasy.now.sh/docs/introduction/browser-support.html), to `enableES5()` for Immer - but it does not seem to be enough, as I still get an error (IE11):

![image](https://user-images.githubusercontent.com/837651/96282521-25b7f780-0fdb-11eb-8393-fd1404113b95.png)

The issue referred to, is [`20: "Cannot use proxies if Proxy, Proxy.revocable or Reflect are not available"`](https://github.com/immerjs/immer/blob/9257084c2b3c04fc9727e4c701d672483a7767b7/src/utils/errors.ts#L33).

Am I missing something, or is this an issue "upstream"?

**Comment by ctrlplusb** [comment]
Hey @jmyrland 

That is music to my ears (except for the Immer part).

I downloaded an IE11 VM and did some immer deep diving. I believe I have fixed this now.

Could you please try:

```
npm install easy-peasy@4.1.0-alpha.7
```

It still needs the enableES5 👍

**Comment by jmyrland** [comment]
Thanks for the quick patch! We are getting closer - the app now renders, but crashes due to `"[Immer] minified error nr: 19 ES5. Find the full error at: https://bit.ly/3cXEKWf"` ([`Immer error 19: "plugin not loaded"`](https://github.com/immerjs/immer/blob/9257084c2b3c04fc9727e4c701d672483a7767b7/src/utils/errors.ts#L32)):

![image](https://user-images.githubusercontent.com/837651/96417093-30e47080-11f1-11eb-8ba5-dcbe622b0305.png)

> 

I am loading & running `enableES5()` straight after running other react polyfills, followed by importing the rest and then rendrering the app:

```ts
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';

import { enableES5 } from 'immer';
enableES5(); // 👈

import { StoreProvider } from 'easy-peasy';
// ... import more stuff & render the app
```

Is this the correct sequence?

**Comment by ctrlplusb** [comment]
Yes, that looks exactly right. I did the same in my test project and it was working. 🤔

Can you try install immer@7 as an explicit dependency?

**Comment by ctrlplusb** [comment]
I guess there is 1 minor difference to how I am enabling the patch, but hoisting _shouldn't_ (?) be occurring on the imports right? So shouldn't make a diff.

<img width="927" alt="Screenshot 2020-10-19 at 16 12 20" src="https://user-images.githubusercontent.com/12164768/96418922-02cd5380-1226-11eb-8ff0-71a1e8e2f209.png">

**Comment by jmyrland** [comment]
> Can you try install immer@7 as an explicit dependency?

Yeah, I forgot to mention - I had to install immer explicitly in order to load the `enableES5` method. 

Maybe an `import "easy-peasy/polyfill"` would be nicer? 🤔

> I guess there is 1 minor difference to how I am enabling the patch, but hoisting shouldn't (?) be occurring on the imports right? So shouldn't make a diff.

Yeah, I've got almost the same setup 😁 Although, a slight variation - as I've grouped all polyfills in one file (from another package in a monorepo)

I agree, this shouldn't have any impact 🤔 I'll try to replicate yours, just to verify.

**Comment by jmyrland** [comment]
Okay, it is working now. I just had to add `immer` as an explicit dependency to the "app" as well.

Our polyfills are loaded via a "shared" package (which had immer as a dependency). However, this did not work, unless Immer is installed for the app as well 🤷‍♀️

I'm thinking of 2 ways to potentially prevent further issues:
1. Expose a polyfill for easy-peasy, i.e. `import "easy-peasy/polyfill"` (By doing this, I don't think Immer is required as an explicit dependency)
2. If an explicit dependency is required - it should be added as a peer-dependency for easy-peasy

I'm hoping that `1.` resolves this, so the `immer` dependency can be handled by `easy-peasy`.

Whats your thoughts?

**Comment by jmyrland** [comment]
I've added a little PR for testing `1.` above: #575 

(I'm unable to add any reviewers though)

**Comment by ctrlplusb** [comment]
That's perfect, thanks!
