### ISSUE TITLE
useLocalStore with persist

### ISSUE THREAD

**Issue by rmcarias** [ctrlplusb/easy-peasy#578]
@ctrlplusb  Is it possible to use the 'useLocalStore' with a model that persists some items to session/localstorage?
for example 

```javascript
useLocalStore({
 myProp: persist({bannerShown:false})
})
```

**Comment by ctrlplusb** [comment]
In theory, yes, you would need to name the store and then await the rehydration.


```javascript
function MyComponent() {
  const [state, actions, store] = useLocalStore(model, [], { 
    name: 'MyComponentStore'  // 👈 needs to be unique
  });

  const [stateRehydrated, setStateRehydrated] = React.useState(false);

  React.useEffect(() => {
    store.persist. resolveRehydration().then(() => {
      setStateRehydrated(true);
    });
  }, [setStateRehydrated, store]);

  if (!stateRehydrated) {
    return <div>Loading...</div>;
  }

  return <div>State is loaded!</div>
}
```

**Comment by rmcarias** [comment]
@ctrlplusb - thank you I will try the above. Originally I just tried using this hook: useStoreRehydrated()... which I think does the same thing correct?
Also, do you know when you'll drop the 4.1 build - I've held off on using the 4.x line because of the IE issue and would really want to use it (especially for that useLocalStore feature, for now Im on 3.3.1)

**Comment by ctrlplusb** [comment]
The `useStoreRehydrated` hook will be looking for your global store. It doesn't scope itself to local stores. But yeah, the logic is very much similar. 😀

I'll drop 4.1 as soon as you are happy your IE11 issues have been resolved. 👍
