### ISSUE TITLE
IE 11 Issue with dist code 4.1.0-beta.1

### ISSUE THREAD

**Issue by rmcarias** [ctrlplusb/easy-peasy#579]
@ctrlplusb 
I was testing the above beta on IE and found the following error:
Expected ';'
And in researching, I narrowed it down to this code:
```
var pReduce = function pReduce(iterable, reducer, initialValue) {
  return new Promise(function (resolve, reject) {
    var iterator = iterable[Symbol.iterator]();
    var index = 0;

    var next = async function next(total) { 👈🏽 // the async keyword I think is the problem
      var element = iterator.next();

      if (element.done) {
        resolve(total);
        return;
      }

      try {
        var value = await Promise.all([total, element.value]); // eslint-disable-next-line no-plusplus

        next(reducer(value[0], value[1], index++));
      } catch (error) {
        reject(error);
      }
    };

    next(initialValue);
  });
};
```
This is from the dist folder 'index.js' . Isn't this code supposed to be transpiled down to ES5 in the dist folder? Or is that my job? I ask because most of the other stuff seems to be ES5 code (or at least IE11 compatible code).

I used it with the top-level imports you recommended
```
import 'easy-peasy/proxy-polyfill';
import 'easy-peasy/map-set-support';
```

**Comment by ctrlplusb** [comment]
Thanks for this, can you please try the next beta. 💜

```
npm install easy-peasy@4.1.0-beta.2
```

**Comment by rmcarias** [comment]
@ctrlplusb tried it again and we still have one more place where it bombs
```
 return {
    persist: persist,
    clear: createPersistenceClearer(persistKey, references),
    flush: async function flush() { 👈🏽 // it seems your transpiler is not catching eveything?
      if (nextPersistOperation) {
        nextPersistOperation();
      }

      await persistPromise;
    }
  };
}
```

**Comment by ctrlplusb** [comment]
@rmcarias one last try... 🤞

```
npm install easy-peasy@4.1.0-beta.4
```

**Comment by ctrlplusb** [comment]
Oh, for interests sake, are you running a bespoke build environment or one from a framework?

**Comment by rmcarias** [comment]
> @rmcarias one last try... 🤞
> 
> ```
> npm install easy-peasy@4.1.0-beta.4
> ```

@ctrlplusb That did the trick! IE is up and running. 
For the builds, I am using a framework. Specifically a custom webpack 3.x/Babel 6/ TS 4
Thank you again for this help. 

On another note: I wanted to ask, do you have example sites that use easy-peasy with TS? I find the docs sometimes don't hav enough details on some of the APIs. For example, computed props. 
In one case, it seems I need to do this: 
`computed( [(state) => state, (state, globalState) => globalState], (state,globalState) => ....); `
which is not very clear in the docs that you need those two resolvers or else TS seems to point you to an error in the compFn . Maybe I am wrong. But I tried looking at the TS version but it wasn't enough to make it clear how to Type it correctly.

Point is, some of the APIs take an elaborate amount of props and the docs seem to only skim the surface on some of them. So if you had a more intermediate/adv sample app, we can see how it's really used. IDK, just an idea.

Thanks!

**Comment by ctrlplusb** [comment]
> That did the trick! IE is up and running.

🎉

> On another note: I wanted to ask, do you have example sites that use easy-peasy with TS? 

I am updating the comment blocks for the types themselves so you should hopefully get useful information within your IDE as you use them. In the interim have you looked at the API section of the docs? We do have docs for the TS types within there too. 👍
