### ISSUE TITLE
update nested array state within action

### ISSUE THREAD

**Issue by zhwatts** [ctrlplusb/easy-peasy#581]
I've got an array of objects as a single piece of state. I've got a thunk that polls an API for new data, and dispatches the add action to either overwrite or push onto that state array (depending on if the new prop previously exists in the state array). 

Is it considered anti pattern to conditionally map through the array prior to change? The below snippet is what i'm trying... however the conditional check always returns false, because existingObj is evaluated as a Proxy when debugging (due to immer). I understand from your documentation that destructuring will not work, but I would think calling the state object property object directly would be allowed?

I know in standard Redux that performing conditional logic inside an action may be considered a side effect and therefore would be bad practice. My thought would be to pass an additional payload parameter of the existing item array index, so I could directly overwrite it instead of checking in the action. 

	locations: [{ agencyId: 0, name: "Some Name" }],

	addLocation: action((state, payload) => {
		//payload example {agencyId: 0, name: 'Some New Name'}

		//check for existing array item
		var existingObj = state.locations.find(
			(location) => location.agencyId === payload.agencyId
		);

		//remove existing array item, if exists
		if (existingObj >= 0) {
			state.locations.filter(
				(location) => location.agencyId === payload.agencyId
			);
		}

		//add array item
		state.locations.push(payload);
	})

**Comment by zhwatts** [comment]
I wound up solving this by checking for an existing array item in my thunk, and then returning an immutable instance from the thunk dispatched action.

	addLocation: action((state, payload, draft) => {
		if (payload.existingId) {
			return {
				...state,
				locations: state.locations.map((location) => {
					if (location.agencyId === payload.existingId) {
						location = payload.data;
						return location;
					} else {
						return location;
					}
				}),
			};
		} else {
			state.locations.push(payload.data);
		}
	}),

**Comment by ctrlplusb** [comment]
Hi @zhwatts 👋

> Is it considered anti pattern to conditionally map through the array prior to change?

Nope, I think this is a reasonable requirement.

> The below snippet is what i'm trying... however the conditional check always returns false, because existingObj is evaluated as a Proxy when debugging (due to immer)

I reviewed your logic and I don't think it is to do with the proxy. You are evaluating the find result as though you used `Array.findIndex`, however, you used `Array.find`. Can you try the following adjusted code:

```javascript
	//check for existing array item
	var existingObj = state.locations.find(
		(location) => location.agencyId === payload.agencyId
	);

	//remove existing array item, if exists
	if (existingObj != null) {
```

There is also another issue with the first code snippet in that you are using an immutable operation (`Array.filter`), and therefore will need to reassign the property.

```javascript
		state.locations = state.locations.filter(
			(location) => location.agencyId === payload.agencyId
		);
```

> I know in standard Redux that performing conditional logic inside an action may be considered a side effect and therefore would be bad practice.

I don't agree. I think having logic around the updating of your state is completely reasonable, as long as it is consistent in it's behaviour. Side effects are impurities affecting something other than the state, e.g. api calls, tinkering with globals, etc.

**Comment by zhwatts** [comment]
@ctrlplusb Sean, thanks for the code review! It would appear I blended a few concepts (namely find vs findIndex). I believe findIndex is the method I need, as I'm hoping to overwrite the array item in place. However I still get a proxy error:

NOTE:  addLocation is asynchronously called several times in a row, back to back. 

	addLocation: action((state, payload) => {
		let existingId = state.locations.data.findIndex(
			(location) => location.agencyId === payload.agencyId
		);

		if (existingId < 0) {
			state.locations.data.push(payload.data);
		} else {
			state.locations.data[existingId] = payload.data;
		}
	})

returns 

`TypeError: Cannot read property 'agencyId' of undefined
    at /Users/zhwatts/Documents/_DEV/NewGuard/ng-lti-resource-page/src/state/AgencyModel.js:87:1
    at Proxy.findIndex (<anonymous>)`

^^note the **Proxy.findIndex** definition error... I assume that's because state.locations is in a draft state after the first async call of addLocation. 

perhaps i'm in a race condition... the first async call to finish properly updates... however the very next call to complete renders the "Proxy.findIndex type error"



It's also worth noting that I can make it work if I pass the existingId to the action from my thunk...

	fetchLocations: thunk(async (actions, payload, { getState }) => {
		var queryDate = getState().queryDate;

		try {
			const locations = await fetch(
				`${apiUrl}/Violation/EventTotalsForProcessing/LocationsByAgency/${payload.agencyId}?startDate=${queryDate.startDate}&endDate=${queryDate.endDate}`,
				{
					headers: {
						Authorization: `Bearer ${payload.accessToken}`,
					},
				}
			);

			const response = await locations.json();

			let existingId = getState().locations.data.findIndex(
				(location) => location.agencyId === payload.agencyId
			);

			if (existingId < 0) {
				actions.addLocation({ data: response.data, existingId: false });
			} else {
				actions.addLocation({
					data: response.data,
					existingId: existingId,
				});
			}

			return response.data;
		} catch (err) {
			console.log(err);

			return "error";
		}
	})


	addLocation: action((state, { data, existingId }) => {
		if (existingId) {
			state.locations.data[existingId] = data;
		} else {
			state.locations.data.push(data);
		}
	})
