### ISSUE TITLE
How to change global state

### ISSUE THREAD

**Issue by 1alexvash** [ctrlplusb/easy-peasy#582]
![image](https://user-images.githubusercontent.com/46556479/97011794-cbc1af80-154f-11eb-9585-4613fe83a50c.png)
How to access/edit **price** value inside **addProducts** function?

**Comment by ctrlplusb** [comment]
Two options.

**1. Lift the action to the root**

```javascript
const model = {
  products: {
    fruits: [],
  },
  price: 0,
  addProduct: action((state, payload) => {
    state.products.fruits.push(payload); 
    state.price += 10;
  }),
};
```

**2. Utilise an `actionOn` listener**

```javascript
const model = {
  products: {
    fruits: [],
    addProduct: action((state, payload) => {
      state.products.fruits.push(payload);
    }),
  },
  price: 0,
  onAddProduct: actionOn(
    actions => actions.product.addProduct, 
    (state, target) => {
      state.price += 10;
    }
  ),
};
```

I'd encourage you to familiarize yourself with the API documentation. 👍

**Comment by 1alexvash** [comment]
Hey, there I have found 2 mistakes in your code

![image](https://user-images.githubusercontent.com/46556479/97111194-24c34c00-16e6-11eb-8a6a-093f8f020499.png)

1) It is not possible to refer from **addProduct** function outside of its local scope
It wish it would be possible but 😟
If you know another they way to refer from local scope to global let me know. It will make my day

2) Looks like a typo to me. It should have been products instead of product

**Comment by ctrlplusb** [comment]
Sorry yep, should be:

```javascript
const model = {
  products: {
    fruits: [],
    addProduct: action((state, payload) => {
      state.fruits.push(payload);
    }),
  },
  price: 0,
  onAddProduct: actionOn(
    actions => actions.products.addProduct, 
    (state, target) => {
      state.price += 10;
    }
  ),
};
```

**Comment by 1alexvash** [comment]
Is there a way to reach global state inside addProduct function without ussing onAddProduct hook?
