### ISSUE TITLE
Proxy detection for node too

### ISSUE THREAD

**Issue by mighdoll** [ctrlplusb/easy-peasy#585]
I found that I needed to enable immer es5 support to run easy-peasy tests on node with 4.1.0-beta.4, even though I'm not using es5 code. 

@modderme123 points out that the es5 Proxy detection test in easy-peasy isn't quite right. I guess this line in easy-peasy's ```lib.js``` is the problem:

```js
typeof window !== 'undefined' && typeof window.Proxy !== 'undefined',
```

```window``` isn't necessarily defined in node. (I suppose it depends on the particular node bundler and test environment.)
 
I'd suggest easy-peasy use something more like immer's `Proxy` test (in `env.js`):

```js
export const hasProxies =
	typeof Proxy !== "undefined" &&
	typeof Proxy.revocable !== "undefined" &&
	typeof Reflect !== "undefined"

```

**Comment by ctrlplusb** [comment]
Aha, good catch. A complete oversight by myself. We'll get that patch queued in.

**Comment by ctrlplusb** [comment]
Will be fixed in the next release. 🙏
