### ISSUE TITLE
React 17 peer dependency

### ISSUE THREAD

**Issue by victoriafrench** [ctrlplusb/easy-peasy#588]
NPM warns `easy-peasy@4.0.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.` with React 17.

Please release with support for the peer dependency of React 17.

**Comment by ctrlplusb** [comment]
Will be fixed in the next release. 🙏

**Comment by kautukkundan** [comment]
Any workaround until this is fixed?

**Comment by raptoria** [comment]
+1 . when is the next release?
