### ISSUE TITLE
Question: How to use easy-peasy without using connect from redux

### ISSUE THREAD

**Issue by lamhtf** [ctrlplusb/easy-peasy#589]
I know that `easy-peasy` is also compatible with `redux`
but
i would like to know how to revamp my codes here in a tidy way without using `redux connect`

As you can find that having different component by connecting the state to the same component is a very tidy and light approach ( i have replaced the `redux selector` by state.standings.xxxx but the revamp is not completed yet so it comes out with some red highlights)

<img width="483" alt="Screenshot 2020-10-28 at 10 19 57 AM" src="https://user-images.githubusercontent.com/70745239/97383571-e0fc5c80-1908-11eb-9b08-61721ebee1d2.png">
<img width="473" alt="Screenshot 2020-10-28 at 10 19 44 AM" src="https://user-images.githubusercontent.com/70745239/97383575-e35eb680-1908-11eb-9d78-f86b96102e85.png">

**Comment by willkuerlich** [comment]
You have to use the hook-selectors you create (and export) in the store:

![image](https://user-images.githubusercontent.com/8741947/98319759-c2b9ef00-1fe1-11eb-9e24-fb870d0be836.png)

https://reactjs.org/docs/hooks-intro.html
