### ISSUE TITLE
Missing "module" field in package.json

### ISSUE THREAD

**Issue by 435352980** [ctrlplusb/easy-peasy#594]
Hello, i find `easy-peasy.esm.js` in the `dist` folder, but there is no "module" filed in package.json, this will cause module resolver error in some module bundler (eg: Vite).

**Comment by LuisOsta** [comment]
@435352980 Can you post your package.json and overall folder structure?

**Comment by 435352980** [comment]
```
  "main": "dist/easy-peasy.js",
  "umd:main": "dist/easy-peasy.umd.js",
  "module": "dist/easy-peasy.esm.js",// for esm, this is not in current version
  "source": "src/index.js",
  "types": "./index.d.ts",
```

**Comment by LuisOsta** [comment]
Oh, you're talking about the package.json for the library itself, not for your applications.
Why can't Vite find the module in this case? Can you link to either the documentation or create the smallest possible reproducible codebase? (either through code sandbox or a small GitHub repo if that won't work

**Comment by 435352980** [comment]
vite requires ES module, it use rollup to compile.
https://github.com/rollup/rollup/wiki/pkg.module

**Comment by LuisOsta** [comment]
@ctrlplusb Any ideas on how to solve this issue?

**Comment by ctrlplusb** [comment]
Apologies @LuisOsta 

This is going to be back in play in the v5 release. 👍

**Comment by ctrlplusb** [comment]
Fixed in the latest release!
