### ISSUE TITLE
How to initialize all states at once?

### ISSUE THREAD

**Issue by sooheesh** [ctrlplusb/easy-peasy#602]
how can I initialize all states?
where can I find documentation for initialState()?

**Comment by LuisOsta** [comment]
Which version are you using (v3 or v4)?

For v4, the parameters you pass to [createStore ](https://easy-peasy.now.sh/docs/api/create-store.html)define the initial state

**Comment by LuisOsta** [comment]
@sooheesh If you're specifically asking for docs on initialState. You can find them here: https://easy-peasy.now.sh/docs/tutorials/testing.html#utilising-initialstate

Is that what you were looking for?

**Comment by sooheesh** [comment]
@LuisOsta Thank you. I actually wanted to hydrate all states at once after the store is created, to log out the user for example. For now, I'm doing something like `actions.setState(undefined)` for all states..;;

**Comment by LuisOsta** [comment]
@sooheesh Oh okay, that makes sense. Yeah, I think that you'll want to do is create an action that logs out the user.
Kinda like this:
```
export const signOut: Action<IUserModel> = action((state) => {
  state = Object.assign(state, {
    _id: "",
    email: "",
    name: "",
    role: USER_ROLE.UNDEFINED,
    token: "",
  });
});
```

^ That's not the only way to do but hopefully it will be useful.

**Comment by sooheesh** [comment]
Thank you @LuisOsta .

**Comment by LuisOsta** [comment]
@sooheesh I'm glad you were able to find a good solution. Can you close this issue if its solved?
