### ISSUE TITLE
zustand like Transient updates (for often occurring state-changes) with Easy Peasy?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#606]
I love Easy-Peasy and have one eye on zustand. 😛

Is it possible to do something similar to [Transient Updates](https://github.com/pmndrs/zustand#transient-updates-for-often-occuring-state-changes) in EP?

**Comment by LuisOsta** [comment]
@GollyJer Can you post more details on your use case for transient updates?

**Comment by GollyJer** [comment]
@LuisOsta I don't currently but think it's an interesting concept. Closing as pretty much off topic. 🤪
