### ISSUE TITLE
Typescript error with useLocalStore?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#607]
When recreating [the docs example for useLocalStore](https://easy-peasy.now.sh/docs/api/use-local-store.html) I run in to this typescript error.

<img src="https://user-images.githubusercontent.com/689204/99928701-16754980-2cff-11eb-9c8b-17c962880c93.png" width=650>

Bug? Or something I'm doing wrong?

**Comment by ctrlplusb** [comment]
Hi @GollyJer 

Apologies for this, but can you provide me an example.

Just a quick question though, are you providing a model type via the generic argument to the function?

**Comment by GollyJer** [comment]
Hi @ctrlplusb.
Yeah. I'm not sure why I thought auto-typing magic was going to happen with the uselocalStore.

Here's how I got it working for future searchers.
```javascript 
import React from 'react';
import { Button, StyleSheet, View } from 'react-native';

import { Action, action, useLocalStore } from 'easy-peasy';

type MyComponentStoreModel = {
  count: number;
  increment: Action<MyComponentStoreModel>;
};

const MyComponent = () => {
  const [state, actions] = useLocalStore<MyComponentStoreModel>(() => ({
    count: 0,
    increment: action((_) => {
      _.count += 1;
    }),
  }));

  return (
    <View style={styles.container}>
      {state.count}
      <Button title={`Pressed ${state.count} Times`} onPress={() => actions.increment()} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
});

export default MyComponent;
```
