### ISSUE TITLE
Should you throw an Error in Actions?

### ISSUE THREAD

**Issue by LuisOsta** [ctrlplusb/easy-peasy#608]
In a defined Easy Peasy action, should one assume that the input parameter is properly formatted?
Or should you handle check for any issues and either throw an error or something like that?

The question boils down to whether actions should be "pure" functions and behave similarly to reducers in Redux. Or if they're something else entirely.

[Here are the Redux docs on reducers](https://redux.js.org/tutorials/fundamentals/part-2-concepts-data-flow#changes-are-made-with-pure-reducer-functions)

**Comment by ctrlplusb** [comment]
Hi @LuisOsta 

Yep, actions should be pure. They are the equivalent of reducers in Redux. In fact they are directly mapped into a Redux reducer by Easy Peasy.

Hope that helps. 👍
