### ISSUE TITLE
How to localStorage for persist?

### ISSUE THREAD

**Issue by corysimmons** [ctrlplusb/easy-peasy#609]
Docs say

>By default it uses the browser's sessionStorage, however, you can configure it to use localStorage, or provide a custom storage engine.

But there are no further instructions for how to use localStorage instead of sessionStorage unless I'm overlooking something. 😬

**Comment by hmontes** [comment]
+1

**Comment by hmontes** [comment]
In your model:

`const storeModel = persist(model, {
  storage: 'localStorage',
});`

That worked for me

**Comment by corysimmons** [comment]
Really? It was that easy? lol, thank you for the update. :)
