### ISSUE TITLE
nested state/action objects in model?

### ISSUE THREAD

**Issue by codemonkeynorth** [ctrlplusb/easy-peasy#611]
Hi,

is it bad practice (or potentially problematic) to nest actions within objects?

I don't want different store models for these but I originally had them all at top level (ie not in `status` or `ui` objects)

I guess the problem here is I can't reference the other object's state directly? ie I may need `getStoreState` etc to reference eg `ui.keyboardVisible` from `status.setLoading` ?

thanks
J

```
const model = {

  status: {
    loading: false,
    setLoading: action((state, payload) => {
      state.loading = payload // note we don't reference state.status.loading 
    }
  },

  ui: { 
   keyboardVisible: false,
   setKeyboardVisible: action((state, payload) => {
      state.keyboardVisible = payload // note we don't reference state.ui.keyboardVisible
   }   
  }

}
```

@ctrlplusb I saw you added a similar example here https://github.com/ctrlplusb/easy-peasy/issues/97 , but not how to communicate between the two state objects. Would it need a thunk?

**Comment by codemonkeynorth** [comment]
this method seems to work. I don't know if it's the best approach or not?

```
const model = {
  account: {
    status: {
      loading: false,
      setLoading: action((state, payload) => {
        state.loading = payload
      })
    },
    profile: {
      username: null,
      setUsernameThunk: thunk((actions, payload, { getStoreActions }) => {
        actions.setUsername(payload) // within the same account.profile object
        const storeActions = getStoreActions()
        storeActions.account.status.setLoading(true) // same model, different object
      })
    },
  },
};
```

**Comment by ctrlplusb** [comment]
Hi @codemonkeynorth 

There is absolutely no issue with defining them in a nested manner. We will walk your model and bind them as expected. Just be aware that actions/thunks are bound to the nested structure, so they only receive the nested state.

**Comment by codemonkeynorth** [comment]
I found with Typescript I had to do something like this

```Typescript
export type Model = {
  image: {
    gamma: number
    // note the array property on the following line
    setGamma: Action<Model["image"], number>
}

const model: Model = {
  image: { 
    gamma: 1,
    setGamma: action((state, payload) => {
      state.gamma = payload
    }),
}
```

is there a better solution? I guess I could create an ImageModel for the nested "image" object?

thanks
J
