### ISSUE TITLE
model get lost in `deepCloneStateWithoutComputed` when using webpack harmony export

### ISSUE THREAD

**Issue by magicdawn** [ctrlplusb/easy-peasy#616]
with tsconfig `compilerOptions.module = esnext`, the compiled code using `__webpack_require__.d`

![image](https://user-images.githubusercontent.com/4067115/103259485-9f556400-49d4-11eb-8ec6-1dad14794166.png)

&  it's using defineProperty

```js
// define getter function for harmony exports
	__webpack_require__.d = function(exports, name, getter) {
		if(!__webpack_require__.o(exports, name)) {
			Object.defineProperty(exports, name, { enumerable: true, get: getter });
		}
	};
```

will make code like

```ts
// @file src/models/index.ts

import count from './count'
export count
```

```ts
// @file src/store.ts
import * as models from './models/index'
```
models will have a `count` property with a getter. 
final with the created store, the count model is lost. 
when use `useStoreState(state => state.count.num)` will throw a error

demo code see
https://github.com/magicdawn/easy-peasy-demo
commit 1fd420c

**Comment by ctrlplusb** [comment]
Hi @magicdawn 

Unfortunately there were quite a few syntax errors in your project. 

You were importing your models incorrectly when creating the store, and had a few syntax errors in your components.

I fixed those and it seems to work.

You can see my changes here:

https://codesandbox.io/s/white-cherry-1n75x?file=/src/index.tsx
