### ISSUE TITLE
TypeIssue: Interop with an existing React Redux Typescript application. reducer function only takes State types in generic

### ISSUE THREAD

**Issue by feroz-shamsi** [ctrlplusb/easy-peasy#618]
I was installing easy-peasy in an already created redux based react app with typescript
the problem comes when i wrapped my redux stores in reducer function imported from easy-peasy
```
import { createStore, reducer } from "easy-peasy";
import buyerListingReducer from "./reducers/buyerListing";
import headerReducer from "./reducers/header";
import mapReducer from "./reducers/map";
import userReducer from "./reducers/user";
import messageReducer from "./reducers/messages";

const reduxReducer = {
	user: reducer(userReducer),
	buyerListing: reducer(buyerListingReducer),
	message: reducer(messageReducer),
	header: reducer(headerReducer),
};

const store = createStore(mainReducer);
```
i get error on every reducer :
Type 'AnyAction' is not assignable to type 'HeaderActionTypes'.

when i tried to find the problem it is in type definitions of easy-peasy
```export function reducer<State>(state: ReduxReducer<State>): Reducer<State>;```
line no: 843

and in redux type definition file
```
export type Reducer<S = any, A extends Action = AnyAction> = (
  state: S | undefined,
  action: A
) => S
```

its not passing action types to the reducer function in redux package and by default its AnyAction.
i did a workaround by disabling ts linter by using 	//@ts-ignore

Solution:
update typedef of easy-peasy
```
export function reducer<State, Action>(state: ReduxReducer<State, Action>): Reducer<State>;
```
on line number: 843

**Comment by jmyrland** [comment]
Is this still an issue for the latest version?
