### ISSUE TITLE
Update from 3.3.1 to 4.0.1 is triggering an Issue due the ts-toolbelt upgrade

### ISSUE THREAD

**Issue by mesvil7** [ctrlplusb/easy-peasy#622]
When updated easy-peasy from 3.3.1 to 4.0.1 the ts-toolbelt dependencie change from 8.0.7 to 8.4.0, this update is triggering an issue in my react project and the resolution according to the ts-toolbelt is to update our typescript version to >= 4.1

ts-toolbelt issue links:
https://github.com/millsp/ts-toolbelt/issues/157
https://github.com/millsp/ts-toolbelt/issues/173

Easy-peasy packages.json updates that create the ts-toolbelt 8.4.0:
"ts-toolbelt": "^6.1.6" -> "ts-toolbelt": "^8.0.7"
<img width="406" alt="Screen Shot 2021-02-02 at 8 43 51 PM" src="https://user-images.githubusercontent.com/1686006/106690466-7c9c0980-6597-11eb-9c91-9f767efc712b.png">

Just in the case, I updated easy peasy with  command "yarn upgrade-interactive --latest",  the yarn.lock file kept the ts-toolbelt 8.0.7 version, so you will get the issue if you remove the lock file. DON'T DO IT

**Comment by millsp** [comment]
Fixing this will cause breaking changes, it's not easy. Because there is global scope pollution. If I fix this, people using global imports will break, if I don't it breaks too - at least only for people that have two different versions of ts-toolbelt at the same time. This has been fixed in version `9`.

**Comment by lpatino10** [comment]
I'm also seeing this issue. I'm wondering if it would be possible to downgrade the `ts-toolbelt` version in `easy-peasy` to fix this for users? It's not straightforward to upgrade our project to use Typescript >= 4.1.

**Comment by Reflex-Gravity** [comment]
Is there any way how to fix this without upgrading the Typescript version?

**Comment by millsp** [comment]
It seems that there is at least a solution for yarn users:

```ts
// In your package.json
"resolutions": { "ts-toolbelt": "8.0.7" },
```

And if you use npm, you'll need to emulate this because there is no support for `overrides` yet and so far. You can use https://www.npmjs.com/package/npm-force-resolutions

**Comment by lpatino10** [comment]
Thanks for the suggestion @millsp. Since we're using npm, I'm not sure how I feel about adding a new package to circumvent this, but it's good to know there's an option.

**Comment by ctrlplusb** [comment]
Does this issue still stand in the v5 release?

**Comment by ctrlplusb** [comment]
I'm sincerely sorry for any friction with this. I tend to keep Easy Peasy evergreen as it becomes too much of a maintenance burden to manage multiple versions. I appreciate the frustration that this may cause in this case, and do again apologise.

**Comment by millsp** [comment]
It's my fault actually. By wanting to use experimental features like type bundling, I caused global namespace pollution (typescript types). Of course, I did not know that until it was too late. Sorry about this. @ctrlplusb I hope the migration to v9 went smooth.
