### ISSUE TITLE
(TS) Updated to 4.0.1, but still encoutering problem with optional Thunk payload

### ISSUE THREAD

**Issue by mapringg** [ctrlplusb/easy-peasy#623]
![Screen Shot 2021-02-03 at 11 51 45](https://user-images.githubusercontent.com/15067237/106699870-49e52600-6616-11eb-8668-f0bb72118fdb.png)
![Screen Shot 2021-02-03 at 11 51 56](https://user-images.githubusercontent.com/15067237/106699892-51a4ca80-6616-11eb-8f66-cd2877f79c48.png)

Currently there doesn't seem to be any workaround.

**Comment by ctrlplusb** [comment]
Hmmm, I double checked and I do have tests for the TypeScript implementation of this, which is behaving as expected.

Could you please create a simple reproduction on CodeSandbox for me?
