### ISSUE TITLE
Immer security risk

### ISSUE THREAD

**Issue by Andyandpandy** [ctrlplusb/easy-peasy#624]
easy-peasy@4.0.1 requires immer@7.0.9

Currently immer@7.0.9 has a high severity vulnerability. 

https://github.com/advisories/GHSA-9qmh-276g-x5pj

Please update to immer@8.0.1

**Comment by w3bdesign** [comment]
@ctrlplusb

**Comment by w3bdesign** [comment]
Bump

**Comment by ctrlplusb** [comment]
Apologies, there is a version coming out that addresses this. It's a major change unfortunately, but I have it bundled in the v5 release. Given the severity I am going to do an early release, likely tomorrow, and will backport some of the doc updates and release notes.

**Comment by ctrlplusb** [comment]
The v3/v4 -> v5 upgrade path shouldn't be significant. I anticipate for most users it will just be a version update in package.json. There are a few breaks for advanced usage cases though which I will describe.

**Comment by ctrlplusb** [comment]
Fixed in the v5 release!
