### ISSUE TITLE
NextJS with easy-peasy example

### ISSUE THREAD

**Issue by binajmen** [ctrlplusb/easy-peasy#627]
Hi folks,

First of all: thank you so much for this awesome library! 🥇 

I'm trying to use EP in a new project where I started using NextJS. I made some research and found interesting post on this github (mostly the issue #171) and on the web, but it seems all the examples I could find were outdated (compared to the current nextjs and redux-wrapper versions & guidelines).

I started from this repo: https://github.com/vercel/next.js/tree/canary/examples/with-redux-wrapper

I simplified the examples and integrated EP to end up with:
https://codesandbox.io/s/next-redux-wrapper-easy-peasy-98nr6?file=/store/store.js

**I would really appreciate if you (@ctrlplusb) or any skillful person over here could review this sandbox and give some feedbacks, especially on the following files and their comments:**

```js
// store/store.js

import { createStore, action, actionOn } from 'easy-peasy'
import { HYDRATE, createWrapper } from 'next-redux-wrapper'

const model = {
    count: 0,
    addCount: action((state) => {
        state.count += 1
    }),
    initCount: action((state, init) => {
        state.count = init
    }),
    // 👇 catch the HYDRATE actions (__NEXT_REDUX_WRAPPER_HYDRATE__)
    //
    // How would you do if you have a nested model ?
    // e.g.: const model = { counter: { count: 0, addCount: ... }, user: { name, getName: ... }) }
    //
    // TODO: client side state reconciliation during hydration
    // --> https://github.com/kirill-konshin/next-redux-wrapper#state-reconciliation-during-hydration
    ssrHydrate: actionOn(
        () => HYDRATE,
        (state, target) => {
            state.count = target.payload.count
        }
    )
}

const initStore = () => { return createStore(model) }

export const wrapper = createWrapper(initStore)
```

```js
// pages/_app.js

import { wrapper } from '../store/store'
import { useStore } from 'react-redux'
import { StoreProvider } from 'easy-peasy'

const WrappedApp = ({ Component, pageProps }) => {
    const store = useStore()

    return (
        <StoreProvider store={store}>
            <Component {...pageProps} />
        </StoreProvider>
    )
}

export default wrapper.withRedux(WrappedApp)
```

```js
// pages/other.js

import Page from '../components/Page'
import { wrapper } from '../store/store'

const Other = (props) => {
    return <Page title="Other Page" linkTo="/" />
}

// 👇 simulate data fetching to hydrate store
export const getServerSideProps = wrapper.getServerSideProps(
    ({ store }) => {
        console.log('ssr init count to 8')
        // 👇 is there a way to dispatch EP-style ? (eg: actions.initCount(8))
        store.dispatch({ type: '@action.initCount', payload: 8 })
    }
)

export default Other
```

As I don't fully grasp all the things happening behind the scene, I want to make sure I'm not going crazy and wrong stuff ;D

On top of that, it could be the start of a nice example to help other people. I will certainly make a TS version when everything is validated :)

Cheers !

Benjamin

**Comment by binajmen** [comment]
I answered most of my questions, that is:

1) Is there a way to dispatch an actions EP-style ? (eg: actions.initCount(8)) in `pages/other.js`

```js
export const getServerSideProps = wrapper.getServerSideProps(
    ({ store }) => {
        console.log('ssr init count to 8')
        // old: store.dispatch({ type: '@action.initCount', payload: 8 })
        //👇 new
        store.getActions().first.initCount(8)
    }
)
```

2) How would you do if you have a nested model ? in `store/store.js`

Well.. Just handle it 😅  Although, I've an additionnal question: it seems we can't do a full state assignement, am I correct? Is there a way to do so?

```js
const model = {
    first: firstModel,
    second: secondModel,
    // 👇 https://github.com/kirill-konshin/next-redux-wrapper#state-reconciliation-during-hydration
    ssrHydrate: actionOn(
        () => HYDRATE,
        (state, target) => {
            state.first = target.payload // 👈  doesn't work
        }
    )
}
```

I've published a repo to keep a trace of this sandbox. Feel free to improve it!
https://github.com/binajmen/next-with-easy-peasy

**Comment by binajmen** [comment]
I'm speaking alone but that's okay ;D

I've upgraded the example with a more interesting case using `persist()`. 

Available on [github](https://github.com/binajmen/next-with-easy-peasy) and codesandbox:
https://githubbox.com/binajmen/next-with-easy-peasy

I still have one issue: when visiting `/ssr`, the server-side hydration of the `inventory` model is working correctly but is followed by the `@actions.ePRS` (which I suppose is the `persistence` action). Normally, only the `basket` model should be persisted. Therefore, I would expect the inventory is untouched (and synced with the SSR hydration).

What am I doing wrong?

Below is the actions flow in DevTools when I visit `/ssr` in a brand new window:

```js
// first action
{
  type: '__NEXT_REDUX_WRAPPER_HYDRATE__',
  payload: {
    counter: {
      count: 0
    },
    shop: {
      basket: {}
    },
    inventory: {
      items: [
        'apple',
        'pear',
        'orange'
      ]
    }
  }
}
// second action
{
  type: '@actionOn.ssrHydrate',
  payload: {
    type: '__NEXT_REDUX_WRAPPER_HYDRATE__',
    payload: {
      counter: {
        count: 0
      },
      shop: {
        basket: {}
      },
      inventory: {
        items: [
          'apple',
          'pear',
          'orange'
        ]
      }
    },
    resolvedTargets: [
      '__NEXT_REDUX_WRAPPER_HYDRATE__'
    ]
  }
}
// third action
{
  type: '@action.ePRS',
  payload: {
    counter: {
      count: 0
    },
    shop: {
      basket: {}
    },
    inventory: {
      items: []
    }
  }
}
```

If I vist the links `/index` then `/ssr`, only the first two actions happen and the store is correctly (server-)hydrated (no `@actions.ePRS` as there's no hard refresh).

Any thoughts why `ePRS` overwrite the inventory while only the shop model is `persist()`ed?

**Comment by binajmen** [comment]
After trying to (more or less) decipher the source code of easy-peasy, I understand that any parts of the model not persisted will be overwritten with the default values defined in the model.

It seems it is just bad luck that `@actions.ePRS` arrived after `__NEXT_REDUX_WRAPPER_HYDRATE__`

Any idea how I could bypass/solve this? Maybe conceptually, I missed something..

**Comment by binajmen** [comment]
Reviewing the issue #171 and the comment https://github.com/ctrlplusb/easy-peasy/issues/171#issuecomment-500239785, I started from scratch using the example https://github.com/vercel/next.js/tree/master/examples/with-redux as a basis.

Last version available on https://github.com/binajmen/next-with-easy-peasy.

I would still want to use [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper#motivation) for all the plus-sides of this lib, including the
>proper handle of complex cases like App.getInitialProps (when using pages/_app) together with getStaticProps or getServerSideProps at individual page level.

I will certainly give another try 😅  I still need to find how to manage the ePRS (as mentioned in https://github.com/ctrlplusb/easy-peasy/issues/627#issuecomment-781350605). Perhaps with the `initialState` config when creating the store (I was not aware of the option 4 hours ago!).

If some of you could validate the overall example, we could make a PR out of it to make this example available on the repo of Next.js.

**Comment by ctrlplusb** [comment]
Great to see this evolving @binajmen. I am in the middle of a few other things EP related, but this is on my radar. 🙏

**Comment by smit2k14** [comment]
Don't really have much to add, other than the fact that this helps a lot. Thanks for this!

**Comment by clbn** [comment]
Thanks a lot for your example @binajmen!

I found there's one issue I don't really know how to fix. When I move between pages the store works great, but if I go to the same page that is open (e.g. clicking `/ssr` link while on `/ssr` page), the page reloads, but the store stops working. After navigating to a different page the store is working again.

I created a codesandbox to demonstrate this. It only contains your code from `binajmen/next-with-easy-peasy`, the only change I made to it is addition of "SSR (again)" link to `components/Page.js`:

- https://codesandbox.io/s/nextjs-with-easy-peasy-c24rg?file=/components/Page.js:355-435

So if you click that SSR link while on `/ssr` page, the buttons stop working and the state is not updated anymore.

I'm guessing that after _reloading the same page_ it tries to update the store instance that does not exist anymore, and for some reason that doesn't happen when navigating to a _different_ page. I tried to play with `initializeStore()` where it recreates the store, but unfortunately couldn't find a way to fix this. I'm hoping you can find why that's happening, it would be so nice to use Easy Peasy with Next.js. 😃

**Comment by binajmen** [comment]
Hi @clbn,

Thank you for pointing that out. I didn't try this scenario.. I tried locally and was able to reproduce the issue.

I'm not quite sure to understand what is happening. If I inspect the component `Shop`, you can see that the first hook eval returns a non-empty shop basket:

![Screenshot 2021-03-03 at 08 54 28](https://user-images.githubusercontent.com/15611419/109772533-63ba5e80-7bfe-11eb-9d95-573e74152164.png)

The corresponding code line is:
```
const basket = useStoreState(state => state.shop.basket)
```
But if I log `basket` in the console, it returns `{}`. In Redux Dev Tool, the store is empty as well. It seems it is _desynchronised_ at some point.. Can't invest more time at the moment but will try to figure it out as I would really like to use EP in my current project.

**Comment by binajmen** [comment]
This is very strange.. The buttons are in fact working. If you

1. Visit `/ssr`
2. Click on the _Add to basket_ button `n` times for a product
3. Visit `/ssr again`
4. Click on the _Add to basket_ button `m` times for the same product
5. Refresh the page OR Visit `/index`

You will notice that your basket has `n + m` products. I can't find why this is happening..

@ctrlplusb You are probably busy on other stuffs, but perhaps your knowledge of Easy-Peasy and Redux in general could point out the issue?

**Comment by braveheart-star** [comment]
hi.
thanks for your kindful works with next.js+ easy-peasy.
I used easy-peasy in the Next.js same as I worked in the react.
not sure what I have to do more for next.js 
I don't know well about Next.js and still studying on that.
I can share source code and want to discuss with you.

**Comment by Ulydev** [comment]
Hi @binajmen, just wondering if you've managed to fix this? I'm trying to migrate an existing CRA app to Next.js and it's been a total nightmare so far.

**Comment by binajmen** [comment]
From what I remember (not working with EP on my current project), I was not able to fix this. I just avoid the possibility to click on the same link again. This is far from a perfect solution, but I couldn't spend more time to understand what's going on. Please let me know if you find anything relevant!

**Comment by aliwaqar981** [comment]
@ctrlplusb @clbn @binajmen @Ulydev Just wondering if someone find out the root cause why that's happening or any hack to fix this issue.
