### ISSUE TITLE
Ability to use reducer-style action with Immer

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#628]
I have a large dataset that requires maximum update performance. This object is never mutated; only _replaced_ with a new dataset. A normal `action()` takes _many seconds_ to update state, even though it's a simple value setter...
````js
action((state, data) => {
  state.data = data;
})
````
It's Immer that is slow so I tried a reducer-style action to _bypass_ Immer. Since `data` is always a new object, immutability is automatic anyway. 
````js
action((state, data) => ({ ...state, data })
````

However I quickly found the return-state style does not work when Immer is enabled and there is a computed value (getter) in the model. This limitation seems to be in both v3 and v4. (I'm still using v3)

**My request is some way to _bypass_ Immer in an action.**
I _could_ use a `reducer()` method for this value and then `dispatch()` an action in the thunk to set it, but this syntax seems clumsy and non-standard. (But is what I'm doing for now.)

One obvious option is for the standard reducer-style return-state to work _without_ disabling Immer. 

Alternatively a _partial state_ could be returned from an action, which would be shallow-merged into state. This avoids having computed values included in the returned state data. For example...
````js
const model = {
  data: {},
  other: [],
  item: computed((state, id) => state.data[id]),
  setData: action((state, payload) => ({ data: payload }),
  fetch: thunk((actions, payload) => {
    getSomething(payload)
      .then(actions.setData);
  })
````
This could work like:
- The `setData()` action returns `{ data: {...} }`
- The model's `state` object is cloned for immutability
- The returned partial state is shallow-merged into state

This achieves the equivalent of `{ ...state, data: {...} }`, but without the issue of computed values inside the state object. Just one idea to work around the current problem.

**Comment by avevlad** [comment]
Same issue, why immer or easy-peasy so slow set state?

Store:

```tsx
// analogs.store.ts
setAnalogs: action((state, payload) => {
    state.analogs = payload;
}),
```

Handle click button action in react component:

```tsx

console.time("dgb: http request");
const response = await client.post(
  ENDPOINTS.assessmentApi + `/3564/analogs`,
  payload
);
console.timeEnd("dgb: http request");

console.time("dgb: setAnalogs");
// setAnalogsAsReactUseState(response.data.data.analogs);
assessmentActions.setAnalogs(response.data.data.analogs);
console.timeEnd("dgb: setAnalogs");

```

#### console.time setAnalogs `1260ms` :(

Test on: easy-peasy@3.3.0 and easy-peasy@4.0.1


https://user-images.githubusercontent.com/2889662/108488521-88830d80-72b1-11eb-8cf1-e5fb77959124.mp4

**Comment by ctrlplusb** [comment]
Hi both, I want to look into this. I had one previous report by someone who was assigning a large payload of JSON to their store. The perf hit comes with Immer doing Proxy wrapping and deep checking. I understand your data may be sensitive but I would really appreciate some sort of example of the size of data you are attempting to assign to your store so that I can build a test case based on this and come up with a recommendation for these cases. 🙏

**Comment by ctrlplusb** [comment]
Also, for your case could you please try Object.freeze the data before passing it into the action?

```javascript
actions.doSomething(Object.freeze(payload));
```

I read something a while ago about Immer behaviour and am interested if this may activate a shortcircuit in their logic.

**Comment by ctrlplusb** [comment]
Hi both, I am experimenting with a configuration option for `action` and `actionOn` that allows you disable Immer per action.

It is available via `easy-peasy@5.1.0-alpha.0`

Can you please try this and report back your experiences?

```javascript
setAnalogs: action((state, payload) => {
    state.analogs = payload;
}, { immer: false }),  // 👈 pass in a config as 2nd argument to `action`
```

**Comment by allpro** [comment]
The solution described would serve my need perfectly. However I won't be able to test it for a while because starting the final sprint of the current release. Therefore I can't do any upgrading and don't have time to create a test environment for this. I'll upgrade EP at the start of next release to this version, or whatever is current then. I'll test then and post back here.

**Comment by surethink** [comment]
@ctrlplusb I have updated to easy-peasy@5.1.0-alpha.0  and add { immer: false },  but there are error:
First argument to `createDraft` must be a plain object, an array, or an immerable object 

If remove the ' { immer: false }', the app is normal . 

the source code of easy peasy, seems no place for the new argument  :
`export function actionOn<
  Model extends object,
  StoreModel extends object,
  Resolver extends TargetResolver<Model, StoreModel>
>(
  targetResolver: Resolver,
  handler: (
    state: State<Model>,
    target: TargetPayload<PayloadFromResolver<Resolver>>,
  ) => void | State<Model>,
): ActionOn<Model, StoreModel>;`
