### ISSUE TITLE
devTools for createContextStore

### ISSUE THREAD

**Issue by chadams** [ctrlplusb/easy-peasy#629]
How would one expose a context store to redux-devtool, devTools=true option does not seem to work.

**Comment by ctrlplusb** [comment]
I believe you would need to set the name of the store via the configuration property.

```javascript
createContextStore(modelCreator, { name: 'MyContextStore' });
```

It should appear in the dropdown within the dev tools. Let me know. 🙏

**Comment by chadams** [comment]
just tried adding "name" to createContextStore. It is not showing in the dropdown.

```javascript
const ScheduleStore = createContextStore(
  {
    <... modelCreator>
  },
  { name: "DataDashbaord", devTools: true }
);
``` 

Redux Dev-Tools only shows the root redux store. and not this context store. using `"easy-peasy": "4.0.1"`

**Comment by chadams** [comment]
FIXED: removed Dev-Tools from Chrome and then re-added Dev-Tools from Chrome store. Works now. Must have been something on my side.
