### ISSUE TITLE
update configure store example in readme

### ISSUE THREAD

**Issue by monsieurBoutte** [ctrlplusb/easy-peasy#63]
The code snippet for configuring the store in the README is incorrect. Maybe consider replacing it with the following:

```
import { composeWithDevTools } from 'redux-devtools-extension';
import { createStore } from 'easy-peasy';
import { model } from './models';

/**
 * model, is used for passing through the base model
 * the second argument takes an object for additional configuration
 */

const store = createStore(model, {
  compose: composeWithDevTools({ realtime: true, trace: true })
  // initialState: {}
});

export default store;
```

**Comment by monsieurBoutte** [comment]
the readme states that you need to pass in:

```
const store = createStore(model, {
  config: {
    compose: composeWithDevTools({ realtime: true }),
  }
);
```

But the api is not expecting `{ config: { }}` as the second argument. The argument itself is implicitly the configuration

**Comment by ctrlplusb** [comment]
Excellent spot, thanks! Would you consider raising a PR? 😇

**Comment by monsieurBoutte** [comment]
sure thing

**Comment by monsieurBoutte** [comment]
I've branched off master and am trying to publish the branch to open a PR but I'm getting access denied 😕

Invalid permissions

**Comment by ctrlplusb** [comment]
Ah yeah, that won't work. You need to fork and then put a PR through, in the context of GitHub. You sound like you know your way around Git already, so pick out the videos from this series to help:

https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

Shout if you have any issues, I would love to get you started on contributing. 👍

**Comment by monsieurBoutte** [comment]
https://github.com/ctrlplusb/easy-peasy/pull/65

**Comment by ctrlplusb** [comment]
Thank you so much for your contribution!
