### ISSUE TITLE
Question: Dispatching actions from another model.

### ISSUE THREAD

**Issue by kasipavankumar** [ctrlplusb/easy-peasy#636]
Greetings.

First of all, thank you for such an amazing state management library. ❤

I have a question about **dispatching actions that are defined in another model**. For example, I have the following store consisting of 3 models. From the auth model, I'd like to dispatch actions defined in both user model & alert model. But after going through docs, I understood that, **models defined this way become private & only receive state (and actions) local to them**. I have gone through almost all the documentation & tried browsing the issues (closed & open) as well but couldn't get my answer.

> Firstly, note how the action receives a state argument. This argument will contain the state that is local to the action.
> \- [Documentation](https://easy-peasy.now.sh/docs/tutorials/primary-api.html#arguments)

```js
// store.js

import { createStore } from 'easy-peasy';
import { alertModel, authModel, userModel } from './models';

const model = {
  alert: alertModel,
  auth: authModel,
  user: userModel,
};

export default createStore(model);
```

```js
// auth.model.js

const auth = {
  // State & actions related to auth.

  login: thunk(async (actions, payload) => {
    try {
      // Process login

      // Action is defined in user.model.js
      actions.user.set({
        isLoggedIn: true,
        sessionToken,
      });
    } catch (error) {
      // Action defined in alert.model.js
      actions.alert.show({
        severity: 'error',
        message: error.message || 'Something went wrong!',
      });
    }
  }),
};

export default auth;
```

**Comment by mfbx9da4** [comment]
```js
const auth = {
  // State & actions related to auth.

  login: thunk(async (actions, payload, {getStoreActions}) => {
    try {
      // Process login

      // Action is defined in user.model.js
      actions.user.set({
        isLoggedIn: true,
        sessionToken,
      });
    } catch (error) {
      // Action defined in alert.model.js
      actions.alert.show({
        severity: 'error',
        message: error.message || 'Something went wrong!',
      });
    }
  }),
};
```

**Comment by kasipavankumar** [comment]
I missed this in documentation. 😅
Thank you.
