### ISSUE TITLE
Access other models

### ISSUE THREAD

**Issue by sm2017** [ctrlplusb/easy-peasy#641]
In the `actionOn` I need to access state of another model, How can I access` todos.items` in the `notes.onAddNote` ?

```js
import { createStore, StoreProvider, action, actionOn } from 'easy-peasy';

const todos= {
  items: [],
  addTodo: action((state, text) => {
    state.items.push(text)
  })
};

const notes = {
  items: [],
  addNote: action((state, text) => {
      state.items.push(text)
  }),
  onAddNote: actionOn(
    (actions, storeActions) => storeActions.notes.addNote,
    (state, target) => {
        // HOW TO READ todos items
    }
  ),
};

const models = {
   todos,
   notes 
};

const store = createStore(models);

```

**Comment by LuisOsta** [comment]
I would recommend making onAddNote a `thunkOn` instead of `actionOn`. That way you'll have access to both the storeActions and storeState.

One question though, why are you using storeActions to get the addNote action instead of just using actions?

**Comment by sm2017** [comment]
@LuisOsta Thanks for your response 

> One question though, why are you using storeActions to get the addNote action instead of just using actions?
Yes, You are right! 

**Viva la Texas**
