### ISSUE TITLE
Does the store Proxy work for non plain old javascript objects like Maps?

### ISSUE THREAD

**Issue by j-masci** [ctrlplusb/easy-peasy#646]
ie. Would there be any problems to doing things like this (sorry for my opinionated comment about the setter):

```
const store = {
    values: new Map(),
    // (gross trivial accessor)
    setValue: action( (state, payload) => {
        state.values.set(payload.key, payload.value);
    }
}
```

https://stackoverflow.com/questions/66910556/can-you-use-a-map-instance-as-an-easy-peasy-store-property

I didn't find anything in the docs for this. It just had some arrays as examples. In addition, I had to confirm myself that it worked properly on nested POJO's because the docs, which mentioned immer and Proxy's did not go into much detail about this. Perhaps the documentation can be clarified. Thanks. (https://easy-peasy.now.sh/docs/tutorials/primary-api.html#modifying-the-state)

**Comment by jmyrland** [comment]
Hey! I found this discussion: https://github.com/ctrlplusb/easy-peasy/issues/440

It might provide some answers 👍

**Comment by j-masci** [comment]
Ok, perfect, thanks.

So it looks like it is possible but you have to declare support for it. If you are reading this, check the link above for how to do it.
