### ISSUE TITLE
Use persist local storage store between two pages

### ISSUE THREAD

**Issue by WildEgor** [ctrlplusb/easy-peasy#649]
It may seem strange to my question, but is it possible to somehow use the same store between applications? I have two html pages with a React application. But they need to exchange data between each other. What is the best way to organize it or is it impossible?

**Comment by bueno12223** [comment]
Hello @WildEgor 
To exchange data  in react aps you can use **props**  [https://www.w3schools.com/react/react_props.asp](props)
for example if you wanna give to other page `const userName = 'Jesus'`
 1. Import the component that you want to pass the information `import Header from './header'`
 2. Give the information like was a classname `<Header userName={userName} ></Header>`, you can give any name that you want
 3. in the other compont use (props) if you are using functions , if you are using class use this in the constructor
 ` constructor(props) {
    super(props);
  }`
4. use `props.UserName` to use the data
  
if you web has many pages i recomend you to use **redux** , is a dependency that will help you to handle storagres
[https://redux.js.org/tutorials/essentials/part-1-overview-concepts](url)

**Comment by WildEgor** [comment]
Thanks!
