### ISSUE TITLE
TypeError: Proxy has already been revoked. No more operations are allowed to be performed on it

### ISSUE THREAD

**Issue by surethink** [ctrlplusb/easy-peasy#651]
On my page,I user a store action:
        getMessageContext(msgId).then(res => {
            if (res.status == "success") {
                console.log(129338)
            }
        })

**### It's ok, but when I set "console.log(res.data)“, there will be a warn:"TypeError: Proxy has already been revoked. No more operations are allowed to be performed on it"

I tracked the cause, It seems to relate to an actionOn function in my model, when I comment the "getMessageContext" case, everything will be ok。
please tell me how to deal with it，thank you**
ps:my easy-peasy version 5.0.3

my actionOn function is below:

 onUserRelatedActions: actionOn(
 (actions, storeActions) => [storeActions.message.getMessageContext],
(state, target) => {
const [getMessageContext]= target.resolvedTargets
  switch (target.type) {
                case getMessageContext:
                    if (target?.result?.status == "success" && target.result.data) {
                        updateUserFromMessage(state, target.result.data.target)
                        if (target.result.data.ancestor && target.result.data.ancestor.length > 0) {
                            target.result.data.ancestor.forEach(item => updateUserFromMessage(state, item))
                        }
                        if (target.result.data.childRelated && target.result.data.childRelated.length > 0) {
                            target.result.data.childRelated.forEach(item => updateUserFromMessage(state, item))
                        }
                    }
                    break
}
}
)

**Comment by zenshayan** [comment]
How did you solve this issue?
