### ISSUE TITLE
Problem with union types properties when Typescript has "strict" compilerOptions to true

### ISSUE THREAD

**Issue by Bazooo** [ctrlplusb/easy-peasy#66]
Having the `strict: true` compiler option in tsconfig.json creates an error for union types with null

![image](https://user-images.githubusercontent.com/8026631/52227093-96a59300-287c-11e9-8188-f96f3ba174bb.png)
![image](https://user-images.githubusercontent.com/8026631/52227516-bab5a400-287d-11e9-82ce-7759529cd85f.png)

My files
```javascript
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "baseUrl": ".",
    "jsx": "react"
  }
}
```

```javascript
// index.tsx
import React from "react";
import { render } from "react-dom";
import { Action, createStore } from "easy-peasy";

interface CartModel {
  products?: string[] | null;
  setProducts: Action<CartModel, string[] | null>;
}

interface Model {
  cart: CartModel;
}

const model: Model = {
  cart: {
    products: null,
    setProducts: (state, payload) => {
      state.products = payload;
    }
  }
};

const store = createStore<Model>(model);

const App = () => {
  return <h1>test</h1>;
};

render(<App />, document.getElementById("app"));
```

Codesandbox (have to download and run `tsc` to see the error): https://codesandbox.io/s/321ly1v241

Current workaround:
Set `strictNullChecks` to false

**Comment by ctrlplusb** [comment]
This _could_ be an issue with Typescript (don't hold me to that). Needs more thorough investigation.

**Comment by ctrlplusb** [comment]
I've done some more investigation and can confirm this is an issue with `easy-peasy`. Working to resolve. 👍

**Comment by ctrlplusb** [comment]
Have a solution! Just tidying up 👍

**Comment by ctrlplusb** [comment]
Wow, this actually exposed some bad assumptions by myself, my new types I am working on are way way way better. No more {} & {} & {}...
