### ISSUE TITLE
Remount createContextStoreProvider

### ISSUE THREAD

**Issue by rmcarias** [ctrlplusb/easy-peasy#666]
Hi @ctrlplusb  I read this in the docs:
"Note: this will only be used to initialize the model on the first render. If you wish to create a whole new runtime model you need to remount the Provider."
How do I do that? Remount the Provider so that it takes on new runtime model based on props or state change for example? (Sort of how local store works with dependencies)
```
// We will just return the runtime model that we expect to receive via the
// store's Provider
//                                      👇
const Counter = createContextStore((runtimeModel) => runtimeModel);

ReactDOM.render(
  <Counter.Provider
    // Provide the runtime model as a prop
    //    👇
    runtimeModel={{
      count: runtimeModel.count,
      inc: action((state) => {
        state.count += 1;
      }),
    }}
  >
    <CounterApp />
  </Counter.Provider>,
  document.querySelector('#app'),
```

**Comment by rmcarias** [comment]
Anyone who can update me on this pleasE?

**Comment by jmyrland** [comment]
Did you find a solution to this issue?

By the looks of it, it seems that you should have used the [`StoreProvider`](https://easy-peasy.dev/docs/tutorials/quick-start.html#binding-the-store-to-your-react-app) instead.
