### ISSUE TITLE
useStoreRehydrated always returning true?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#672]
For some reason `useStoreRehydrated` returns true even though it isn't.

I'm using
```javascript 
const isRehydrated = useStoreRehydrated();
console.log('isRehydrated', isRehydrated);
if (!isRehydrated) return null;
```
to protect the App from loading until state is rehydrated.

But this console logs `isRehydrated true` even on the first run and I can see the App render with empty data and then rerender with rehydrated data a second later.

Not sure what to check next. Thanks for any help!

**Comment by jmyrland** [comment]
Is this still an issue with the latest version?

**Comment by GollyJer** [comment]
@jmyrland Did you test this and find it to work? Or close because no response?

I can build a repro and see if the latter.

**Comment by ctrlplusb** [comment]
Would be great if you could provide a repro. ♥️

Sorry we had to close old issues with inactivity in a movement towards centring ourselves with what is priority for the community. 👍

**Comment by jmyrland** [comment]
> @jmyrland Did you test this and find it to work? Or close because no response?
> 
> I can build a repro and check, if still needed.

Yeah sorry - premature close due to no response. I've reopened the issue.

A sandbox to reproduce the issue would be nice. [I've got some you could fork if you'd like](https://codesandbox.io/dashboard/all/easy-peasy-examples?workspace=d19bb18f-8ddc-4ef7-98a7-7c36159678d2).

**Comment by GollyJer** [comment]
> 

I think those might be private sandboxes. They don't load for me.

**Comment by jmyrland** [comment]
> I think those might be private sandboxes. They don't load for me.

Oh, I guess linking to folders doesn't work. Try [this one](https://codesandbox.io/s/easy-peasy-example-simple-todo-fnidh1).

**Comment by GollyJer** [comment]
I generally use easy-peasy with react-native apps using Expo, so I built a quick example using snacks.expo.dev instead of codesandbox.

Turns out it works now, at least with the default storage engine on web. 🥳
You can click the "No Errors" button at the bottom left to pull up the console logs.
https://snack.expo.dev/@gollyjer/easy-peasy-rehydrate-bug

This did lead to finding a bug when trying to use an alternative storage engine 
`import ExpoFileSystemStorage from 'redux-persist-expo-filesystem';`

I have another snack set up for that and will create a separate issue.

**Comment by jmyrland** [comment]
> I generally use easy-peasy with react-native apps using Expo, so I built a quick example using snacks.expo.dev instead of codesandbox.
> 
> Turns out it works now, at least with the default storage engine on web. 🥳 You can click the "No Errors" button at the bottom left to pull up the console logs. https://snack.expo.dev/@gollyjer/easy-peasy-rehydrate-bug

Thanks for your input! Good to see that the `useStoreRehydrated` hook works as expected now 🎉

> This did lead to finding a bug when trying to use an alternative storage engine `import ExpoFileSystemStorage from 'redux-persist-expo-filesystem';`
>
> I have another snack set up for that and will create a separate issue.

Thanks for taking the time - appreciate it 👍
