### ISSUE TITLE
Seeing duplicate stores in redux devtools with useLocalStore

### ISSUE THREAD

**Issue by johtso** [ctrlplusb/easy-peasy#675]
For each store created, a duplicate seems to get made that is never used, and appears in redux devtools.

Am I doing something wrong, or is there something odd going on here?

I made a simple example:

https://nw7h9.csb.app/

<img width="477" alt="image" src="https://user-images.githubusercontent.com/830800/122816251-62f12980-d2ce-11eb-9562-9fcf253ad5c9.png">

**Comment by johtso** [comment]
Aha, so this is just standard `StrictMode` behavior. New to react so this was surprising to me.

Any idea if there's a way to not have devtools cluttered with those empty stores while developing?

**Comment by ctrlplusb** [comment]
Thanks for this @johtso. 

There is some valuable related discussions on this here:

- https://github.com/reduxjs/redux-devtools/issues/366
- https://github.com/reduxjs/redux/issues/3871

I am going to try a few things out.

**Comment by jmyrland** [comment]
Maybe this is fixed by #769 ?

**Comment by jmyrland** [comment]
Should be fixed by #769 - will reopen if it is still an issue.
