### ISSUE TITLE
Introduce "thunk", deprecate "effect"

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#68]
Now that we have the `listeners` API I feel like we should revisit the `effect` API. I don't like that it's first argument, `dispatch`, exposes the entire model rather than be scoped, as `state` is within actions. Equally I dislike the number of arguments that `effect` accepts - I would prefer if we limit this to 3 arguments.

I want to avoid introducing breaking changes and therefore suggest introducing `thunk`. It has the same responsibility as `effect` but with an adapted API. We can then console log out warnings that the `effect` API is deprecated and will be removed in next major release.

Current `effect` API:

```javascript
{
  todos: {
    items: {},
    add: (state, payload) => {
      state.items[payload.id] = payload;
    },
    //  arguments count: 😱     1         2       3           4        5
    fetchById: effect(async (dispatch, payload, getState, injections, meta) => {
	  const todo = await todoService.getById(payload);
      // 😱    👇 annoying having to path through every time
	  dispatch.todos.add(todo);
    })
  }
}
```

Proposed `thunk` API:

```javascript
{
  todos: {
    items: {},
    add: (state, payload) => {
      state.items[payload.id] = payload;
    },
    fetchById: thunk(async (actions, payload, helpers) => {
	  const todo = await todoService.getById(payload);
      // 👇 actions scoped to model
	  actions.add(todo);
      // 👇 "helpers" wraps up all the additional items that 
      //    typically won't be used very often (IMO)
      const { getState, injections, meta, dispatch } = helpers
    })
  }
}
```

Thoughts?

**Comment by axel-habermaier** [comment]
@ctrlplusb: Interestingly, what you dislike about ``effect`` is what I prefer over ``thunk``. Our model is split into three parts: ``entities`` (the core business objects), ``appState``, and ``uiState``. Now most of our thunks read or write some data from the backend, update an entity, and then set some app or UI state accordingly. Where would I place all of these thunks? Top-level at the model? Of course I can get ``dispatch`` in a ``thunk`` as well, but that's tedious to write an even requires the top-level type to be explicitly specified as the fourth generic argument of ``Thunk``. That's a bit too verbose for my taste, especially considering that your intention with this library was to reduce the necessary boilerplate :)

**Comment by ctrlplusb** [comment]
@axel-habermaier you can still gain access to the old behaviour for exceptional cases.

```typescript
doSomething: thunk((actions, payload, helpers) => {
  const { dispatch, getState } = helpers;
  dispatch.notification.set('Foo bar');
  console.log(getState().notification.msg);
});
```

**Comment by ivan-kleshnin** [comment]
What's the purpose of thunks? We can write the same code in `useEffect`, right?
