### ISSUE TITLE
Computed properties with a runtime argument missing when used with persistence?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#681]
With persistence turned on our app throws `Error in useStoreState: state.assets.getStakedAssetsByAddress is not a function.`.

It is a computed property with a runtime argument.
```javascript 
getStakedAssetsByAddress: computed(
  (state) => (address) => Object.values(state.stakedAssetsById[address]) || []
),
```

This exact issue was tackled in v4. https://github.com/ctrlplusb/easy-peasy/issues/503
Could there be a regression in v5?

**Comment by GollyJer** [comment]
For a anyone following along I hacked around this issue with a most supremely placed try/catch.

```javascript 
const ownedAssets = useStoreState((state) => {
  try {
    return state.assets.getStakedAssetsByAddress(theAddress);
  } catch {
    return [];
  }
});
```

**Comment by ctrlplusb** [comment]
Hi @GollyJer 

I tried updating the codesandbox in the related issue to the latest easy peasy but I didn't experience issues. Could you provide me a minimal reproduction in codesandbox?

**Comment by GollyJer** [comment]
Hi @ctrlplusb thanks for the response.

We're using Expo so I'll put together an example an example on snack.expo.io and post here when ready.

**Comment by GollyJer** [comment]
OK. I'm back with the example @ctrlplusb.

Here's the snack.
[easy-peasy-persist-computed-bug](https://snack.expo.dev/@gollyjer/easy-peasy-persist-computed-bug)

I set the store up in the exact same way we do our production app. You will notice we build a pretty complex import structure for the store but it's easier to manage in the long run.

You'll also notice import linting errors. Those are just misplaced errors by Expo Snack. They all work fine.

- Pick the Android emulator.
- When you initially load the app it works great.
- Then comment lines 15-23 and uncomment lines 25 - 33 and hit the Save button at the top right and then reload the app.
- You will get `state.thing1.getAllTheThings is not a function`.
- Now pick the iOS emulator.
- App will load fine the first time.
- Click Devices > Reload Apps at the bottom right menu of snack.
- You will get `state.thing1.getAllTheThings is not a function`.
- I believe this has something to do with persistence, since there isn't any persisted state when the app loads for the very first time but there is from that point forward.

And if you're wondering why I'm not using Easy Peasy's persistence.
👉 https://github.com/ctrlplusb/easy-peasy/issues/672
Unlikely, but maybe related?

**Comment by ctrlplusb** [comment]
Thanks for taking the time to put this together for me.

**Comment by jmyrland** [comment]
> OK. I'm back with the example @ctrlplusb.
> 
> Here's the snack. [easy-peasy-persist-computed-bug](https://snack.expo.dev/@gollyjer/easy-peasy-persist-computed-bug)
> 
> I set the store up the same way we do our production app. You will notice we build a pretty complex import structure for the store, but it's easier to manage in the long run.
> 
> * Pick the Android emulator.
> * When you initially load the app, with nothing persisted, it works great.
> * Then comment lines 15-23 and uncomment lines 25 - 33, hit the Save button at the top right, and reload the app.
> * You will get `state.thing1.getAllTheThings is not a function`.
> * Now, pick the iOS emulator.
> * App will load fine the first time.
> * Click Devices > Reload Apps at the bottom right menu of snack.
> * You will get `state.thing1.getAllTheThings is not a function`.
> * I think this has something to do with persistence because there isn't persisted state when the app initially loads (no error), but there is from that point forward (with error).
> 
> And if you're wondering why I'm not using Easy Peasy's persistence. 👉 #672 Maybe related?

Following the steps - but I'm not able to reproduce the issue (using `v6.0.1`). 

Can you verify that the issue is still present using the latest version, @GollyJer ?

**Comment by GollyJer** [comment]
Yeah. This appears to be fixed in the new version. Closing. 💪
