### ISSUE TITLE
How to type it in typescript?

### ISSUE THREAD

**Issue by 1alexvash** [ctrlplusb/easy-peasy#683]
![image](https://user-images.githubusercontent.com/46556479/128608004-407638c9-39ae-488d-9311-0d11c052089f.png)

How to avoid this error?

**Comment by GollyJer** [comment]
Have you already created typed hooks?
https://easy-peasy.vercel.app/docs/typescript-api/create-typed-hooks.html

**Comment by ctrlplusb** [comment]
Also, I saw your newer issue. Please make sure you are typing your store model effectively. 🙏
