### ISSUE TITLE
If you switched from Easy Peasy, where did you go?

### ISSUE THREAD

**Issue by GollyJer** [ctrlplusb/easy-peasy#688]
I'm curious where people are moving to from Easy Peasy.
When transitioning from pure Redux I tried a lot before landing here and have truly enjoyed using Easy Peasy from version 2 to today. 

I hope @ctrlplusb is doing well and completely understand if he's decided to put this in stasis mode. 

One thing I love is the Typescript support in Easy Peasy. Is there anything else this easy that also supports typescript? If you're reading this and have moved on, where did you go?

Best,
Jeremy

**Comment by rtcoms** [comment]
I have tried https://github.com/keajs/kea, but only for toy application. I really liked it, much less boilerlplate and easy to understand code,

**Comment by ctrlplusb** [comment]
Zustand is also pretty popular. :)

https://github.com/pmndrs/zustand

**Comment by GollyJer** [comment]
Hey @ctrlplusb!! Super happy to hear from you. 
Glad you're doing OK (are you doing ok?) 

No need to change if you're sticking around! 😛
