### ISSUE TITLE
Why typescript is throwing an error?

### ISSUE THREAD

**Issue by 1alexvash** [ctrlplusb/easy-peasy#689]
![image](https://user-images.githubusercontent.com/46556479/130364487-c6b7a826-0fcd-4bc0-aade-ba53a482b576.png)

**Comment by 1alexvash** [comment]
Adding type any to line 27 fixes this issue
but I would like to figure out what is wrong

![image](https://user-images.githubusercontent.com/46556479/130364513-85c88414-81e2-4853-b2d8-44916852d2fc.png)

**Comment by ctrlplusb** [comment]
I am not sure we support `any` as a type against a store model property. Why are you apprehensive to add an actual type here?

```typescript
type Task = { 
  name: string; 
}
type List = { 
  name: string;
  tasks: Task[];
}

interface StoreModel {
  lists: List[];
  addTask: Action<StoreModel, Task>; 
}
```

**Comment by 1alexvash** [comment]
Can I put this StoreModel inside d.ts file to reuse throughout entire application?

Because it looks like d.ts file doesn't allow any imports I'm taking about Action type

------------
What is the correct way to structure the application?

**Comment by ctrlplusb** [comment]
I would recommend reading the documentation, specifically the TypeScript sections. There is a util called `createTypedHooks` which will make this experience far more pleasant.
