### ISSUE TITLE
Bake in a "test" mode

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#69]
Been thinking about this a bit more and it would be great to have this story baked in from the get go.

One idea would be to rather expose a log of actions that got called, along with their payloads, but make the operations a no-op.

Also encourage good practices with examples, showing how taking advantage of the "injections" parameter can help with this.

**Comment by RPDeshaies** [comment]
I've definitely been using injections to be able to test thunks more easily and it's been a delight.

Another thing what could be nice would be to expose injections directly from the `store` created by `createStore`.

But having a way to see what has been called and with what would also simplify writing tests in general. 

Do you see those working kinda like [jest snapshots](https://jestjs.io/docs/en/snapshot-testing) work ?

**Comment by ctrlplusb** [comment]
Here are some of my current ideas for testing.

**Model under test**

```typescript
const todosModel = {
  items: {},
  add: (state, payload) => {
    state.items[payload.id] = payload
  },
  fetchById: thunk(async (actions, payload, helpers) => {
    const { injections } = helpers
    const todo = await injections.fetch(`/todos/${payload}`).then(r => r.json())
    actions.add(todo)
  }),
}
```

**Testing an action**

```typescript
it('action', () => {
  // arrange
  const todo = { id: 1, text: 'foo' }
  const store = createStore(todosModel)

  // act
  store.dispatch.add(todo)

  // assert
  expect(store.getState().items).toEqual({ [todo.id]: todo })
})
```

**Testing a thunk**

```typescript
import { createStore, thunkStartName, thunkEndName, actionName } from 'easy-peasy';

it('thunk', async () => {
  // arrange
  const todo = { id: 1, text: 'Test my store' }
  const fetch = createFetchMock(todo)
  const store = createStore(todosModel, {
    injections: { fetch }, // 👈 leverage injections to allow mocking
    recordActions: true,   // 👈 this will record all actions onto store.dispatched
  })

  // act
  await store.dispatch.fetchById(todo.id)

  // assert
  expect(fetch).toHaveBeenCalledWith(`/todos/${todo.id}`)
  expect(store.dispatched).toEqual([  // 👈 assert the expected actions were dispatched
    { type: thunkStartName(todosModel.fetchById), payload: todo.id },
    { type: actionName(todosModel.add), payload: todo },
    { type: thunkEndName(todosModel.fetchById), payload: todo.id },
  ])
})
```

**Comment by RPDeshaies** [comment]
A little bit like what you are already doing in the redux dev tool then ?

I like it.

Then to create tests faster, we can just print the `store.dispatched` in the console and copy that directly in the test scenario (super lazy mode).

Totally 👍

**Comment by ctrlplusb** [comment]
Hahaha, good hack that.
