### ISSUE TITLE
Property 'search' does not exist on type 'Dispatch<{}, Action<any>>'.

### ISSUE THREAD

**Issue by DmacLoyaltyOne** [ctrlplusb/easy-peasy#72]
Hey there! 
I love this library you have made. 

Just downloaded the newest version, but something strange is happening in my typescript.

`const saveText = useAction(dispatch => dispatch.search.saveText)`

I'm using this in one of my components, and typescript is throwing that error.

My store is created like this:

```
import { createStore } from 'easy-peasy'
import search from '../models/search/search'

const store = createStore({
  ...search
})
export default store
```

```
import { effect } from 'easy-peasy'

const search = {
  search: {
    text: '',
    saveSuccessful: false,
    // Actions
    setText: (state, payload: string) => {
      state.text = payload // 👈 you mutate state to update (we convert
      state.saveSuccessful = true
    },
    // Effects
    saveText: effect(async(dispatch, payload: string, getState) => {
      try {
        // const result = await axios.post('https://google.ca/whatever', payload)
        dispatch.search.setText(payload)
      } catch (e) {
        throw e
      }
    })
  }
}

export default search

```

If I hover over search in the createStore variable, it seems to pick it up fine, but within the Search.tsx component, it gives me that error.

Some help would be appreciated. I know extremely little about typescript, but I assume this would work. 😅 

I get a similar error for state:

```
Property 'search' does not exist on type 'State<{}>'.

    37   const saveSuccessful: boolean = useStore(state => state.search.saveSuccessful)
```

**Comment by ctrlplusb** [comment]
Any chance of creating an example via codesandbox.io? It will be far easier for us to debug then. 😀

**Comment by DmacLoyaltyOne** [comment]
https://codesandbox.io/s/0pp422jqxp

I made this to mimic my setup, but It doesn't show any errors. It just says `dispatch: type any`

Whereas in my project, i see `(parameter) dispatch: Dispatch<{}, Action<any>>`


```
(alias) useAction<{}, any>(mapAction: (actions: Dispatch<{}, Action<any>>) => any): any
import useAction
A React Hook allowing you to use actions within your component.

https://github.com/ctrlplusb/easy-peasy#useactionmapaction

@example

import { useAction, Dispatch } from 'easy-peasy';
```

**Comment by DmacLoyaltyOne** [comment]
In reality, I have a bit more complex setup. I'm using next.js and doing the StoreProvider in _app.tsx.

I'll see i I can make a demo setup for you.

**Comment by DmacLoyaltyOne** [comment]
Here is a demo repo for you.
Open it in vscode and you will see the issue.

https://github.com/DmacLoyaltyOne/Easy-Peasy-issue-72

Problem component:
https://github.com/DmacLoyaltyOne/Easy-Peasy-issue-72/blob/master/example/components/Footer.tsx

Creating the Store:
https://github.com/DmacLoyaltyOne/Easy-Peasy-issue-72/tree/master/example/models

Main Wrapper with StoreProvider
https://github.com/DmacLoyaltyOne/Easy-Peasy-issue-72/blob/master/example/pages/_app.tsx


nextjs will load _app.tsx on every page serve and wrap any component.
eg: localhost:3000/ will load index.js on the server, and then we can import any react components in the components folder.

I don't know if this is why it is breaking, but it seems like a very simple setup.
I'll try to help when I can.

Thanks again!

**Comment by ctrlplusb** [comment]
Hi @DmacLoyaltyOne;

Thanks for taking the time to put an example together.

I have had a look and can definitely say that are a few issues. I would also recommend that you change your strategy. It is a bit too much to try and explain here, but I am creating an example repository to be more of an illustrative example. 👍

Hopefully it will be up soon.

In the mean time I recommend you review the updated docs, specifically the Typescript section.

**Comment by ctrlplusb** [comment]
Hey @DmacLoyaltyOne 

I just published an article explaining the Typescript integration a bit more. 

https://medium.com/@ctrlplusb/easy-typed-state-in-react-with-hooks-and-typescript-eacd32901f05

Stay tuned for an example repository too.

👍

**Comment by ctrlplusb** [comment]
Closing this issue, as I don't there is an actual issue with the library/types. Hopefully the posts help. I will pick you when I post up the example repo. 👍

**Comment by DmacLoyaltyOne** [comment]
Yes I got it working. Thanks!
