### ISSUE TITLE
Is any perf issue with Using Easy Peasy hooks and React Redux connect

### ISSUE THREAD

**Issue by thesunilbagde** [ctrlplusb/easy-peasy#733]
https://easy-peasy.vercel.app/docs/recipes/interop-with-existing-react-redux-app.html#using-easy-peasy-hooks-and-react-redux-connect

I am currently using both Provides Will cause any perf issue. 

_### Passing two stores at two places._

```js
 <Provider store={store}> // react-redux
    <StoreProvider store={store}> // easy 
      <App />
    </StoreProvider>
  </Provider>
```

**Comment by ctrlplusb** [comment]
Nope there should be no significant change in performance by registering both providers.
