### ISSUE TITLE
Pull out property of computed value: TypeScript Error

### ISSUE THREAD

**Issue by Standupic** [ctrlplusb/easy-peasy#739]
`interface IBook {
id: string
tittle: string
...
}`

`const model = {
 currentBook?: Computed<Books, IBook | undefined, IBook>;
}`

`currentBook: computed((state) => state.books.find((book) => book.id === state.id))`

const Component  =>  {
  `currentBook?.id // **TypeScript Error Property 'id' does not exist on type 'Computed '.**`
  `currentBook?.title // **TypeScript Error Property 'title' does not exist on type 'Computed '.**`
  `currentBook?.result?.id // undefined`
}

 @ts-ignore
` const { publisher, synopsis, title, author, pageCount, id, coverImageUrl } = currentBook;  // WORKS`

**Comment by no-stack-dub-sack** [comment]
@Standupic see this known issue, it may be related to your problem: https://easy-peasy.dev/docs/known-issues/typescript-optional-computed-properties.html

**Comment by jacekk** [comment]
@Standupic Just change this line:

```ts
const model = { currentBook?: Computed<Books, IBook | undefined, IBook>; }
```

into this:

```ts
const model = { currentBook?: Computed<Books, IBook | undefined>; }
```

**Comment by Standupic** [comment]
@jacekk @no-stack-dub-sack  unfortunately no one of  provided suggestions do not work properly.
```typescript
export interface Books {
currentBook?: Computed<Books, IBook | undefined>;
}
```

```js
const book: Books = {
currentBook: computed((state) => state.books.find((book) => book.id === state.id))
}
```

```typescript
Books.currentBook?: Computed<Books, IBook | undefined, {}> | undefined
```

```js
 const currentBook = useStoreState((state: StoreModel) => state.books.currentBook);
  const { publisher, synopsis, title, author, pageCount, id, coverImageUrl } = currentBook;
}
```

```typescript
Property 'pageCount' does not exist on type 'Computed  | undefined'. //   so on so foth.
```

**Comment by jacekk** [comment]
@Standupic First of all, I cannot see `IBook` definition, it might be missing this very property. But...

please remember that `currentBook` is of type `IBook` or `undefined`. You need to checked whether this computed value is actually "Truthy". Most `const currentBook = ...` just check whether this is an object or not.

**Comment by jacekk** [comment]
@Standupic I can see the property --> https://github.com/Standupic/Book-discovery/blob/main/src/types/books.ts#L8 :wink: 
So just add a check in your `Book` component.

**Comment by Standupic** [comment]
@jacekk  It works properly, thanks for your time.
```js
 const currentBook = useStoreState((state: StoreModel) => state.books.currentBook);
  if (currentBook && currentBook.result) {
  const { publisher, synopsis, title, author, pageCount, id, coverImageUrl } = currentBook.result;
```
