### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by OlekRia** [ctrlplusb/easy-peasy#740]
After upgrading to react version 18, `easy-peasy` stopped working. When we call API it doesn't rerender a component which uses `useStoreState` hook.

**Comment by w3bdesign** [comment]
Something that is related to this is that @types/react 18.0.0 is not compatible with the latest version of Easy Peasy. 

Reference: https://github.com/ctrlplusb/easy-peasy/issues/741

**Comment by OlekRia** [comment]
@w3bdesign Oh, it's not about the typing... However, of course i am not acknowledge good with a source code. But the problem is that it doesn't work properly. It seems because react 18 becomes  "asyncronous"

**Comment by benkissi** [comment]
Experiencing the same issue after changing to use reacts `createRoot`

```
Does not work
------------------------
const root = createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <BrowserRouter>
      <StoreProvider store={store}>
        <App />
      </StoreProvider>
    </BrowserRouter>
  </React.StrictMode>
);
```

```
This works
-------------------

ReactDOM.render(
  <React.StrictMode>
    <StoreProvider store={store}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </StoreProvider>
  </React.StrictMode>,
  document.getElementById("root")
);
```

**Comment by c-ctkd** [comment]
i have the same problem here. Alse using `ReactDOM.render` is not an optimal solution because we're missing all the new features introduced on react 18

**Comment by codydeny** [comment]
using `ReactDOM.render` works.
Also, for me, it does not work only the in the development environment
but works fine when you build using `npm run build`
I am using 
` "easy-peasy": "5.0.4"`
`"react": "18.1.0"`
`"@types/react": "18.0.8"`

**Comment by zawupf** [comment]
Removing `React.StrictMode` works for me, so that easy-peasy store updates are fired again.

**Comment by OlekRia** [comment]
> Removing `React.StrictMode` works for me, so that easy-peasy store updates are fired again.

I guess the reason of existing React.Strict mode is quite respectful. I am afraid, you advice looks like not a solution.

**Comment by zawupf** [comment]
For sure that's just a workaround, until the underlying bug is fixed.

**Comment by geekact** [comment]
For typescript users, you can try to use [foca](https://github.com/foca-js/foca) which support `react 18` and type strong enough. Foca also based on redux + react-redux + immer

**Comment by w3bdesign** [comment]
> For typescript users, you can try to use [foca](https://github.com/foca-js/foca) which support `react 18` and type strong enough. Foca also based on redux + react-redux + immer

Documentation is in Chinese, so it is a bit hard to understand how to use.

@geekact

**Comment by OlekRia** [comment]
I don't use typescript. Because I am fed up with it. And I don't read Chinese. And don't get how a programmer may write a documentation using another language than English.

**Comment by geekact** [comment]
> I don't use typescript. Because I am fed up with it. And I don't read Chinese. And don't get how a programmer may write a documentation using another language than English.

@OlekRia @w3bdesign Yep, Chinese is not friendly for west country, I just searched this framework today, and actually I thank it's time to write English documentation since `foca` is great enough to show it to people who also love redux in the world.

**Comment by OlekRia** [comment]
You know. Modern React Toolkit isn't bad as well and mature.

**Comment by w3bdesign** [comment]
I believe https://github.com/pmndrs/zustand supports React 18

@OlekRia @geekact

**Comment by OlekRia** [comment]
Guys, thanks for your advertisement. But I am interested in easy-peasy.

**Comment by orbachar** [comment]
did you guys find a solution? im looking to upgrade react, but this is a showstopper.

**Comment by 1alexvash** [comment]
@ctrlplusb any update on it?

**Comment by 1alexvash** [comment]
Looking for an update, as while using next you can't really toggle strict mode, or any of the React 18 setup

**Comment by liamdefty** [comment]
@ctrlplusb Firstly, I love this lib. Use it on a few projects and it's helped me loads.

I'm keen to look at react 18 support, if it's something you don't have time for - is there any way I can help?

**Comment by juneroy1** [comment]
Hello everyone! I am having an issue in using easy-peasy in react 18, like for example when I change the value in the input it does not working properly the calling of api is not working also, can please help with this or am i the only experiencing this bug?

**Comment by larrykn** [comment]
Am also getting the same issue with easy-peasy  in react 18

**Comment by Digital-Coder** [comment]
@ctrlplusb I would really love to use easy-peasy, maybe by any chance you could look into this bug ?

**Comment by apuatcfbd** [comment]
Looks like the library is dead. leaving...

**Comment by ctrlplusb** [comment]
Hi ya'll. I'm going to begin looking into React 18 support. My initial intuition is that this might constitute a breaking change. I'll look into how other popular state libraries are handling this transition.

**Comment by OlekRia** [comment]
@ctrlplusb Man... It's too late...

**Comment by ctrlplusb** [comment]
I have to also reconsider the model of supporting Easy Peasy with this upgrade. From what I have gathered React 18's async mode is causing a lot of application friction. I suspect a large portion of Easy Peasy users will remain on React 17 for a while. 

I typically only support the latest major version of Easy Peasy, but I may need to consider supporting patching and releasing across two separate branches. 

This will need some consideration in terms of how versions are published to NPM.

I'd appreciate any thoughts on these points. ♥️

**Comment by ctrlplusb** [comment]
Ok, some good news. The React team released a shim which allows me to do backwards support for React 16 and 17.

I've done an initial integration and all the source tests are passing. 🎉

I still need to fix the TypeScript definitions, and also need to look into the SSR story as my initial read on this is that it may need additional work. Looking good thusfar.

If you are happy to be an alpha tester on this please ping in this issue.

**Comment by ctrlplusb** [comment]
Yeah, I definitely need to extend the provider to support SSR for React 18.

So if anyone is doing an SPA, please volunteer for alpha testing.

I'll ping when the SSR story is sorted for wider testing.

**Comment by ctrlplusb** [comment]
<img width="365" alt="Screenshot 2022-09-15 at 23 57 22" src="https://user-images.githubusercontent.com/12164768/190451233-cad8a1aa-6c74-4dcd-8899-4b5feaf6ed75.png">

😎

**Comment by ctrlplusb** [comment]
Ok ya'll. Anyone running an SPA, please could you test this alpha release;

```
yarn add easy-peasy@5.1.0-alpha.3
```

[CodeSandbox Example](https://codesandbox.io/s/easy-peasy-typescript-ycur0?file=/src/components/todos.tsx)

**Comment by ctrlplusb** [comment]
On face value the SSR support doesn't look difficult. We should be able to land this very soon if user feedback goes well in testing the alpha releases.

**Comment by rainerbruemmer** [comment]
> Ok ya'll. Anyone running an SPA, please could you test this alpha release;
I have tested the alpha version and it works smoothly. Our store is not too small. It has many actions, thunks, thunkOns, computed states etc. The store keeps much data.

Thank you very much for restarting work on this very cool library.
