### ISSUE TITLE
StoreProvider returns the error "Property 'children' does not exist on type..."

### ISSUE THREAD

**Issue by podeig** [ctrlplusb/easy-peasy#748]
Hi,
I have my issue at StackOverflow.
https://stackoverflow.com/questions/72055436/easy-peasy-storeprovider-returns-the-error-property-children-does-not-exist-o
🙏

**Comment by ahmednkhan24** [comment]
Having the same issue by just following the documentation lol.

https://github.com/ahmednkhan24/easy-peasy-todo-list

**Comment by ctrlplusb** [comment]
Fixed in v5.1.0 🎉
