### ISSUE TITLE
Issue with Easy-Peasy and @testing-library/user-event

### ISSUE THREAD

**Issue by MyElectricSheep** [ctrlplusb/easy-peasy#760]
Heya!

Whilst testing some React components for the first time with Easy-Peasy; I came across the following problem:

Whenever I was firing a user event with `@testing-library/user-event`'s `userEvent` method and checking if that action was dispatched / if the state was updated properly; it failed. 

But when I was firing the event myself with `store.getActions().someAction()` inside the test; it was working properly.

I was stuck for a good while trying to figure this one out, until I narrowed this down on the userEvent method itself. I swapped it with the `fireEvent` method from `@testing-library/react` and things were working again!

[Here's a sanbdox](https://codesandbox.io/s/react-18-easy-peasy-component-testing-2onfux?file=/src/Counter.test.js) in which you can see the problem / workaround.

I'm mostly posting this so that others stuck with the same issue might find this solution, but any chance of seeing `@testing-library/user-event` supported in Easy-Peasy at some point?

**Comment by jmyrland** [comment]
We're using `@testing-library/user-event` with `easy-peasy` stores without issues. 

[This should work](https://testing-library.com/docs/user-event/intro#writing-tests-with-userevent).
