### ISSUE TITLE
Documentation make no sense. (Typescript)

### ISSUE THREAD

**Issue by apuatcfbd** [ctrlplusb/easy-peasy#763]
Followed this: https://easy-peasy.vercel.app/docs/tutorials/typescript.html

then end-up like this
```
interface Todo {
    text: string;
    done: boolean;
}

interface StoreModel {
    todos: Todo[];
}

interface TodosModel {
    todos: Todo[];
    completedTodos: Computed<TodosModel, Todo[]>;
    addTodo: Action<TodosModel, Todo>;
    saveTodo: Thunk<TodosModel, Todo>;
}

const store = createStore<StoreModel>({
    todos: [],
    completedTodos: computed((state) => state.todos.filter((todo) => todo.done)),
    addTodo: action((state, payload) => {
        state.todos.push(payload);
    }),
    saveTodo: thunk(async (actions, payload) => {
        const result = await axios.post('/todos', payload);
        actions.addTodo(result.data);
    }),
});

export default store;
```
which look like this
https://prnt.sc/C-FuQtxZDvpU
then: https://prnt.sc/ZO6_XK27F_D-

I still can't figure out what is the issue. I see one issue is the documentation.

** `"easy-peasy": "^5.0.4"` `"typescript": "^4.6.4"` on `PHPStorm 2022.1`

**Comment by ctrlplusb** [comment]
Yeah, this is bad documentation. Soz.

**Comment by no-stack-dub-sack** [comment]
@apuatcfbd If you're going to have multiple "slices" in your store, you can do something like this:

```ts
interface Todo {
  text: string;
  done: boolean;
}

interface StoreModel {
  todos: TodosModel;
  // ...another slice here
}

interface TodosModel {
  todos: Todo[];
  completedTodos: Computed<TodosModel, Todo[]>;
  addTodo: Action<TodosModel, Todo>;
  saveTodo: Thunk<TodosModel, Todo>;
}

const store = createStore<StoreModel>({
  todos: {
    todos: [],
    completedTodos: computed((state) => state.todos.filter((todo) => todo.done)),
    addTodo: action((state, payload) => {
        state.todos.push(payload);
    }),
    saveTodo: thunk(async (actions, payload) => {
        const result = await axios.post('/todos', payload);
        actions.addTodo(result.data);
    }),
  }
  // ...another slice here
});
```

Or if your store is going to be flat:

```ts
interface Todo {
  text: string;
  done: boolean;
}

interface StoreModel {
  todos: Todo[];
  completedTodos: Computed<StoreModel, Todo[]>;
  addTodo: Action<StoreModel, Todo>;
  saveTodo: Thunk<StoreModel, Todo>;
}

const store = createStore<StoreModel>({
  todos: [],
  completedTodos: computed((state) => state.todos.filter((todo) => todo.done)),
  addTodo: action((state, payload) => {
    state.todos.push(payload);
  }),
  saveTodo: thunk(async (actions, payload) => {
    const result = await axios.post("/todos", payload);
    actions.addTodo(result.data);
  })
});
```

Either setup should fix your type errors.

**Comment by jmyrland** [comment]
Attempted to clarify the TS example in #770

**Comment by apuatcfbd** [comment]
> @apuatcfbd If you're going to have multiple "slices" in your store, you can do something like this:
> 
> ```ts
> interface Todo {
>   text: string;
>   done: boolean;
> }
> 
> interface StoreModel {
>   todos: TodosModel;
>   // ...another slice here
> }
> 
> interface TodosModel {
>   todos: Todo[];
>   completedTodos: Computed<TodosModel, Todo[]>;
>   addTodo: Action<TodosModel, Todo>;
>   saveTodo: Thunk<TodosModel, Todo>;
> }
> 
> const store = createStore<StoreModel>({
>   todos: {
>     todos: [],
>     completedTodos: computed((state) => state.todos.filter((todo) => todo.done)),
>     addTodo: action((state, payload) => {
>         state.todos.push(payload);
>     }),
>     saveTodo: thunk(async (actions, payload) => {
>         const result = await axios.post('/todos', payload);
>         actions.addTodo(result.data);
>     }),
>   }
>   // ...another slice here
> });
> ```
> 
> Or if your store is going to be flat:
> 
> ```ts
> interface Todo {
>   text: string;
>   done: boolean;
> }
> 
> interface StoreModel {
>   todos: Todo[];
>   completedTodos: Computed<StoreModel, Todo[]>;
>   addTodo: Action<StoreModel, Todo>;
>   saveTodo: Thunk<StoreModel, Todo>;
> }
> 
> const store = createStore<StoreModel>({
>   todos: [],
>   completedTodos: computed((state) => state.todos.filter((todo) => todo.done)),
>   addTodo: action((state, payload) => {
>     state.todos.push(payload);
>   }),
>   saveTodo: thunk(async (actions, payload) => {
>     const result = await axios.post("/todos", payload);
>     actions.addTodo(result.data);
>   })
> });
> ```
> 
> Either setup should fix your type errors.

Need slices in different file, there're many of them

**Comment by no-stack-dub-sack** [comment]
@apuatcfbd Have you figured out how to setup slices in different files? This is possible. It's also possible to define each thunk, action, computed prop, etc. in a different file if you prefer that kind of organization. If you'd like an example of how to do slices this way, let me know and I can share an example.

**Comment by jmyrland** [comment]
> @apuatcfbd Have you figured out how to setup slices in different files? This is possible. It's also possible to define each thunk, action, computed prop, etc. in a different file if you prefer that kind of organization. If you'd like an example of how to do slices this way, let me know and I can share an example.

We're open to PRs for more [examples](https://github.com/ctrlplusb/easy-peasy/tree/master/examples), so feel free to chuck one in there 👍

I'm currently working on adding some more (#773)

**Comment by apuatcfbd** [comment]
> > @apuatcfbd Have you figured out how to setup slices in different files? This is possible. It's also possible to define each thunk, action, computed prop, etc. in a different file if you prefer that kind of organization. If you'd like an example of how to do slices this way, let me know and I can share an example.
> 
> We're open to PRs for more [examples](https://github.com/ctrlplusb/easy-peasy/tree/master/examples), so feel free to chuck one in there 👍
> 
> I'm currently working on adding some more (#773)

An example would be helpful for me & others too.

**Comment by no-stack-dub-sack** [comment]
@jmyrland Ok, cool - I can work on one for multiple slices and how to organize across several files. May take a bit for me to put it together but I'll def get on it.

In the meantime @apuatcfbd, consider this folder structure:

![image](https://user-images.githubusercontent.com/18563015/191846490-98d5862e-2959-4799-adba-82b7595406ab.png)

For this, we can set up our slices and our store like this: 

```ts
// app/slices/todo/index.ts
import * as actions from "./actions";
import * as computed from "./computed";
import * as thunks from "./thunks";

export interface Todo {
  text: string;
  done: boolean;
}

type State = {
  todos: Todo[]
}

const initialState: State = {
  todos: []
};

const todoModel: TodoModel = {
  ...initialState,
  ...actions,
  ...thunks,
  ...computed,
};

export type TodoState = State;

export type TodoModel = TodoState &
  typeof actions &
  typeof thunks &
  typeof computed;

export default todoModel;
```

```ts
// app/store.ts
import { State, createStore, createTypedHooks } from "easy-peasy";
import todo, { TodoModel } from "./slices/todo";

export type StoreModel = {
  todo: TodoModel;
  // ...more slices here
};

export type RootState = State<StoreModel>;

export const { useStoreActions, useStoreState } =
  createTypedHooks<StoreModel>();

const store = createStore<StoreModel, RootState, Dependencies>({
    todo,
    // ... more slices here
});

export default store;
```
And in actions, thunks, computed, etc.:

```ts
// app/slices/todo/actions.ts
import { Action, action } from "easy-peasy";
import { Todo, TodoModel } from ".";

export const addTodo: Action<TodoModel, Todo> = action((state, payload) => {
  state.todos.push(payload);
});

// ...more actions
```

Let me know if this makes sense. I will try to throw together a codesandbox at some point. You can also go a step further if you have many actions / thunks / computed props and put them all in individual files and export them all from an index file (e.g. `actions` becomes a directory with an index file and all actions in the directory are exported from there so you can still do `import * as actions from "./actions";` and get the type required for slice model).

@jmyrland Sounds like you have lots of easy-peasy apps in prod, do you have a different approach or do you mostly have flat stores or slices defined in a single file?

**Comment by jmyrland** [comment]
Btw, [this model](https://github.com/ctrlplusb/easy-peasy/blob/4f175efae1de91a36625928a255c30c2916e0028/examples/kanban/src/store/model.ts) uses slices & store generators.

**Comment by no-stack-dub-sack** [comment]
Sounds like an interesting approach! I suppose this is all closed source? When you say sub-store, though, you still only have one top-level call to `createStore`, like in the example you linked to right? i.e. you can still access all of your nested models via a single `useStoreState` hook.

**Comment by no-stack-dub-sack** [comment]
Also, I initially thought you meant adding an additional section the docs tutorial section, but now I see you mean adding an example project. This may take me a bit more time to put together but I will still keep this on my todo list.

**Comment by jmyrland** [comment]
> When you say sub-store, though, you still only have one top-level call to createStore, like in the example you linked to right? i.e. you can still access all of your nested models via a single useStoreState hook.

Correct 👍

> Also, I initially thought you meant adding an additional section the docs tutorial section, but now I see you mean adding an example project. This may take me a bit more time to put together but I will still keep this on my todo list.

Oh I see 😅 sorry for the confusion. 

Any help is appreciated 👏
