### ISSUE TITLE
Community feedback on `unstable_effectOn`

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/easy-peasy#765]
I'd like to consider moving this API to stable pending feedback from the community.

Also looking to incorporate the work in [PR #598](https://github.com/ctrlplusb/easy-peasy/pull/598)

**Comment by jmyrland** [comment]
Haven't seen this one. What is the usecase for this, over `ActionOn` and `ThunkOn`?

**Comment by rainerbruemmer** [comment]
Hi,

we used the effectOn for serval months and it worked perfect and was very useful. But a a refactoring of our store, we could not use effectOn due to missing [PR #598] (https://github.com/ctrlplusb/easy-peasy/pull/598)

It would be great if the PR will be merged and effectOn gets moved to stable.

**Comment by ctrlplusb** [comment]
> Haven't seen this one. What is the usecase for this, over `ActionOn` and `ThunkOn`?

It allows you to track state rather than actions. Which can help avoid cases of having to track multiple actions in the case of ActionOn and ThunkOn.

**Comment by jmyrland** [comment]
Is #597 still an issue?

**Comment by methyl** [comment]
I think after merging #598 and fixing #597 separately, it will be stable. I didn't notice any other problems than those two and the api itself is really useful.

**Comment by tormodAase** [comment]
Hey, I use `unstable_effectOn` in one of my projects, and it's working great! The only downside with it, is it can only track up to 6 states in the store. I've managed to find some workarounds, but it would be great if it could listen to as many states as we want, similar to how `thunkOn` can listen to unlimited actions.

Thank you so much for maintaining easy-peasy!

**Comment by ctrlplusb** [comment]
Nice one. Yeah, we can look into that quality of life improvement too. 👍

**Comment by jmyrland** [comment]
> The only downside with it, is it can only track up to 6 states in the store. 

This is fixed by #787 👍

**Comment by ctrlplusb** [comment]
@jmyrland and @no-stack-dub-sack on fire. 🔥😎

**Comment by no-stack-dub-sack** [comment]
> I think after merging #598 and fixing #597 separately, it will be stable. I didn't notice any other problems than those two and the api itself is really useful. Thanks @ctrlplusb for finding time for this!

With #598 merged and #597 fixed by #812, I think we're in pretty good shape here. There are no other open issues related to `unstable_effectOn` and no comments in this thread that suggest its not ready to be made stable. 

What do you think @ctrlplusb, @jmyrland?

**Comment by jmyrland** [comment]
> With #598 merged and #597 fixed by #812, I think we're in pretty good shape here. There are no other open issues related to `unstable_effectOn` and no comments in this thread that suggest its not ready to be made stable. 
> 
> What do you think @ctrlplusb, @jmyrland?

I think we're ready for a release soon! 🚀
