### ISSUE TITLE
Typescript definitions of the EasyPeasyConfig define Injections as void

### ISSUE THREAD

**Issue by RPDeshaies** [ctrlplusb/easy-peasy#77]
Inside the typescript definitions of the easy peasy config, it says that the Injections are `void`

Because of that, injecting injections inside a store with typescript requires you to say `as any` to let the compiler pass.

I think this should use typescript generics like for the `Model` to make sure you can actually pass the type of injections you want

Problematic line: `Injections = void`
```
export interface EasyPeasyConfig<
  InitialState extends Object = {},
  Injections = void
> {
  compose?: typeof compose
  devTools?: boolean
  initialState?: InitialState
  injections?: Injections
  middlewares?: Array<Middleware<any, any, any>>
  reducerEnhancer?: (reducer: Reducer<any, any>) => Reducer<any, any>
}

```

Compared to the model that uses generics for example:

```
export function createStore<Model extends Object = {}>(
  model: Model,
  config?: EasyPeasyConfig,
): Store<Model>
```

**Comment by ctrlplusb** [comment]
Should be resolved with latest v1.12.2 release 👍

**Comment by RPDeshaies** [comment]
Awesome ! Will try it out !

**Comment by RPDeshaies** [comment]
when using the `thunk` helper, it still tells me that my injections are `any`

![image](https://user-images.githubusercontent.com/6224111/52636496-c404c900-2e9a-11e9-9239-a6b5f184ab88.png)

Maybe I'm missing something.

Do you have any example of using Injections along with typescript definitions ?

**Comment by ctrlplusb** [comment]
Ah, yeah, sorry this is because the types aren't fully documented yet.

Unfortunately it isn't enough to rely on the type information being passed into your store. You need to declare the injections type against your `Thunk` too.

e.g.

```
interface MyInjections  {
  axios: AxiosInstance;
}

interface TodosModel {
  save: Thunk<TodosModel, Todo, MyInjections>;
}
```

Full documentation on the types are to come soon.

**Comment by RPDeshaies** [comment]
Just realized its the same thing for the `getState` typing then ?

```
interface TodosModel {
  save: Thunk<TodosModel, Todo, MyInjections, MyGlobalModel>;
}
```

Right ?

**Comment by ctrlplusb** [comment]
Yep 👍
