### ISSUE TITLE
Non-stylistic differences between actions and thunks?

### ISSUE THREAD

**Issue by KevinMusgrave** [ctrlplusb/easy-peasy#783]
It seems like thunks can do everything actions can do, but more. So I could replace all my actions with thunks, and the code would still work. 

I'm guessing this is considered a bad idea, but I don't know why.

- Is it because thunks are slower than actions?
- Is it simply a code organization/style issue?

On a related note, the [documentation says](https://easy-peasy.dev/docs/api/thunk.html) "your thunk should not perform any mutation of this state. That would be considered an anti pattern. All state updates must be contained within actions." However, in this [example on codesandbox](https://codesandbox.io/s/ztuxzk), I was able to change the `postsModel.likePost` action to a thunk, and mutate state directly in the thunk:

```javascript
likePost: thunk((actions, payload, helpers) => {
    const post = helpers.getState().posts.find((item) => item.id === payload);

    if (post) {
      post.likes += 1;
    }
  }),
```

Is there a disadvantage to doing this?

**Comment by jmyrland** [comment]
Semantically `action`s and `thunk`s are different.

As the docs state:
> [Thunks](https://easy-peasy.dev/docs/api/thunk.html) are typically used to encapsulate side effects or complex workflow (e.g. if/else based logic) around action dispatching. They can be asynchronous or synchronous.
> [Actions](https://easy-peasy.dev/docs/api/action.html) is used to perform updates on your [store](https://easy-peasy.dev/docs/api/store.html).

However, as you pointed out - you are able to update state within a store by directly referencing and updating state via the `getState()` helper.

I would consider mutating state in a thunk an anti-pattern. I see it as separation of conserns, for example if your loading data from a service. You'd want the `thunk` to handle the loading part, and the `action` to handle the update part.

In your case, I would consider `likePost` as an `action`.

There is nothing stopping you from doing this, but we cannot guarantee that you'll always be able to mutate state via thunks for later versions.

**Comment by KevinMusgrave** [comment]
Ok makes sense, thanks!
