### ISSUE TITLE
How can I configure redux dev tools?

### ISSUE THREAD

**Issue by dusanjovanov92** [ctrlplusb/easy-peasy#79]
I have a really big object and I want to use the stateSanitizer option from dev tools.
Here's what I tried:
![code](https://user-images.githubusercontent.com/20474783/52527140-d24cbc80-2cc3-11e9-876b-0f499432b52e.png)

Is there any way to do this ?

**Comment by dusanjovanov92** [comment]
My bad...it actually works like this, be free to close it :)

**Comment by ctrlplusb** [comment]
👍
