### ISSUE TITLE
Example for listen(on) contains usage of listeners api which is deprecated

### ISSUE THREAD

**Issue by vinaydate** [ctrlplusb/easy-peasy#81]
Great lib. Helped me to reduce code and saved me from cognitive load with alternative approaches, as well.

I was going through new `listen` api. I think example for this api is using deprecated `listeners` api.

https://github.com/ctrlplusb/easy-peasy/tree/master#listenon

And since this example does not elaborate on listen api, please tell me, how should I refer to an action from another branch of the model, for the first argument of `on` function of `listen`?

**Comment by ctrlplusb** [comment]
Interesting case! I have a good idea. This will be super helpful for compatibility and migration cases. I will write up an example for you tomorrow. 👍

**Comment by ctrlplusb** [comment]
Docs updated 👍
