### ISSUE TITLE
Updating State

### ISSUE THREAD

**Issue by gokulstevee** [ctrlplusb/easy-peasy#821]
```js
//In App Component
updateUser({ id, name, phNumber });

//model.js
  updateUser: action((state, newData) => {
    state.users = state.users.map((user) => {
      if (user.id === newData.id) {
        console.log(user.id === newData.id);
        user.name = newData.name;
        user.phNumber = newData.phNumber;
      }
      return user;
    });
  }),
```

When updateUser is called from the component with the updated values(name, description, price) it carries the newData to model.js but the state of the user data is not changed remains same. so, how to update or modify the state of the store.

**Comment by no-stack-dub-sack** [comment]
@gokulstevee Your code is working fine, see this code sandbox:

[![Edit elated-williamson-n2q9q3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-williamson-n2q9q3?fontsize=14&hidenavigation=1&theme=dark)

In your comment you mention name, description and price, but this action seems to expect, id, name and phNumber. Are you definitely passing in the right payload?

**Comment by no-stack-dub-sack** [comment]
@gokulstevee Closing this for now as there doesn't seem to be an issue here. If you have further questions, please feel free to reopen and provide additional details.
