### ISSUE TITLE
Broken in NextJS 13 with React 18

### ISSUE THREAD

**Issue by ricardomatias** [ctrlplusb/easy-peasy#822]
I'm getting an error with `TypeError: maybeGetServerSnapshot is not a function` when rendering a component that calls useStoreState:

```
TypeError: maybeGetServerSnapshot is not a function
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
getServerSnapshotWithSelector
file:/Users/feral/Projects/trendradar/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim/with-selector.development.js (138:31)
Object.useSyncExternalStore
file:/Users/feral/Projects/trendradar/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5217:10)
useSyncExternalStore
file:/Users/feral/Projects/trendradar/node_modules/react/cjs/react.development.js (1676:21)
useSyncExternalStoreWithSelector
file:/Users/feral/Projects/trendradar/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim/with-selector.development.js (145:15)
useStoreState
file:/Users/feral/Projects/trendradar/node_modules/easy-peasy/dist/index.cjs.js (66:25)
```

Using the latest React/NextJS and easy-peasy in Node v18.15.0

**Comment by jmyrland** [comment]
I've bumped the versions of the example app, but I'm not able to reproduce the issue in this app.

However, I've been able to reproduce the issue in [this sandbox](https://codesandbox.io/p/sandbox/easy-peasy-issue-822-jxc95q?welcome=true&file=%2FREADME.md) (related to [this SO post](https://stackoverflow.com/questions/75761699/easy-peasy-nextjs-react-maybegetserversnapshot-is-not-a-function))

I'm not sure whats causing this issue, so we have to investigate this further.

**Comment by ricardomatias** [comment]
> I've bumped the versions of the example app, but I'm not able to reproduce the issue in this app.
> 
> However, I've been able to reproduce the issue in [this sandbox](https://codesandbox.io/p/sandbox/easy-peasy-issue-822-jxc95q?welcome=true&file=%2FREADME.md) (related to [this SO post](https://stackoverflow.com/questions/75761699/easy-peasy-nextjs-react-maybegetserversnapshot-is-not-a-function))
> 
> I'm not sure whats causing this issue, so we have to investigate this further.

I tried the example project that you referenced and it works fine. The only common information I could find on another project was [this](https://github.com/aws-amplify/amplify-ui/pull/1798).

**Comment by jmyrland** [comment]
I think the changes in #823 might remedy this issue.

@ricardomatias could you install `easy-peasy@5.2.1-alpha.0` to see if this fixes your issues?

**Comment by ricardomatias** [comment]
The error is gone, thanks @jmyrland!

**Comment by jmyrland** [comment]
> The error is gone, thanks @jmyrland!

Thanks for verifying 👍 I'll either publish a separate release with this change, or it will be a part of the upcoming `v6`-release.

Until then, you can just rely on the alpha release above.
