### ISSUE TITLE
Performance: Modifying data is too time-consuming

### ISSUE THREAD

**Issue by yongningfu** [ctrlplusb/easy-peasy#826]
![image](https://user-images.githubusercontent.com/9846613/231337132-9b59ee80-f6dd-421a-938a-2eb3ea33149f.png)
from: https://immerjs.github.io/immer/performance/

I'm dealing with performance issues, and I found that in easy-peasy, data operations are particularly time-consuming, because immer is not set to Freeze. 
We didn't use​ Computed properties and​ State persistence. 
Can immer freeze be used as a configuration property of createStore?

Thanks

**Comment by jmyrland** [comment]
hi @yongningfu ! 👋

Is this a general issue for you, or just for specific actions?

If this is just an issue for specific actions, you may [omit immer for these specific actions](https://easy-peasy.dev/docs/api/action.html#disabling-immer). Alternatively, you may disable immer for the whole store, [via the `disableImmer`](https://easy-peasy.dev/docs/api/store-config.html) config when creating the store.

**Comment by yongningfu** [comment]
hi @jmyrland，We still want to use immer development to improve efficiency

**Comment by jmyrland** [comment]
> hi @jmyrland，We still want to use immer development to improve efficiency

I see. Currently, if you experience performance issues, your best bet is to omit immer.

Freezing state is a feature that is not prioritized, given that we have the option to omit immer entirely for specific scenarios where performance is an issue.

However, if you have a solution in mind - feel free to contribute by submitting a pull request 👍
