### ISSUE TITLE
Property 'user' does not exist on type 'StateMapper<FilterActionTypes<{}>>'

### ISSUE THREAD

**Issue by waqaarali** [ctrlplusb/easy-peasy#827]
I noticed that this issue was fixed in previous pushes, but I still seem to have this issue.

Usage:

`const user = useStoreState((state) => state.user);`

Store:

```ts
const store = createStore<UserModel>({
    user: {
        name: '',
        loggedIn: false
    },
...
}
```
Any ideas what I may be doing wrong? I followed the documentation.

**Comment by jmyrland** [comment]
Hard to say without more context, but missing types in this case indicates that you are importing `useStoreState` directly from `easy-peasy` - which doesn't know the type of your store state.

Make sure that you have created and exported typed hooks via [`createTypedHooks`](https://easy-peasy.dev/docs/typescript-api/create-typed-hooks.html#createtypedhooks), and that you use this hook in your component.

If this is not the case, a [codesandbox](https://codesandbox.io/s/easy-peasy-typescript-tutorial-typed-injections-forked-5gkoyz) to reproduce the issue would be helpful.

**Comment by waqaarali** [comment]
> Hard to say without more context, but missing types in this case indicates that you are importing `useStoreState` directly from `easy-peasy` - which doesn't know the type of your store state.
> 
> Make sure that you have created and exported typed hooks via [`createTypedHooks`](https://easy-peasy.dev/docs/typescript-api/create-typed-hooks.html#createtypedhooks), and that you use this hook in your component.
> 
> If this is not the case, a [codesandbox](https://codesandbox.io/s/easy-peasy-typescript-tutorial-typed-injections-forked-5gkoyz) to reproduce the issue would be helpful.

Thanks, this did the trick. Not sure how I missed out this section.
