### ISSUE TITLE
Redux Devtools Extension freezes

### ISSUE THREAD

**Issue by vinaydate** [ctrlplusb/easy-peasy#83]
My store contains a nested field with thousands of items. 

In development mode, when I change some code, due to HMR, the app does refresh>

But when Redux DevTools chrome extension is opened, it freezes the app when I change the code.

When I remove the part that has thousands of items, from store, both (w and w/o ReduxDevtools extension) scenarios run smooth.
 
Please help me to sanitize the state.
or
to use Redux Devtools (not chrome extension)

I have tried both the options, with my limited competency. But failed.

**Comment by ctrlplusb** [comment]
Hey @vinaydate - I am not sure that this issue belongs here. Have you checked the issues list on Redux Dev Tools repo to see if there are similar reports?

**Comment by ctrlplusb** [comment]
Let me know what you find out. Closing for now.

**Comment by vinaydate** [comment]
Thanks for the quick reply. I tried to dig into Redux Dev Tools extension. There are few issues mentioning similar symptoms, but did not get any worthy clue to resolve my issue. Anyway, please guide me on the following

How to sanitize the state in easy-peasy
or
to use Redux Devtools (not chrome extension), I read about middleware and stateEnhancer, but with easy-peasy, I could not figure out how to do this.

Of course, in love of this lib, so hoping to get this working.

**Comment by ctrlplusb** [comment]
Does this help:
https://github.com/ctrlplusb/easy-peasy/issues/79

**Comment by vinaydate** [comment]
My bad. I had gone thr' this issue #79. But somehow missed the point. Will try this.
Thanks

**Comment by vinaydate** [comment]
Tried and through. Thanks
