### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by sirajalam049** [ctrlplusb/easy-peasy#830]
Hi,

I'm starting to write react after a few years, and I used easy-peasy and I loved it. Now I came to know about redux-toolkit and it solved the same problem that easy-peasy solved but not completely. So I'm thinking of going with easy-peasy again, so just wanted to know if it is still supported and maintained or not.

**Comment by jmyrland** [comment]
Hi @sirajalam049 👋

Yes it is maintained, but we are not working on any new features for the library - given the low activity.

I've been using the library for years, and it's great to work with!

Give it a try to see if it fits your needs 👍

**Comment by sirajalam049** [comment]
Hi @jmyrland ,

Thanks for the quick reply, I've used it and really loved it, but now I'm going to start on an enterprise-level application, so just before making it the dependency, I wanted to confirm.

Thanks for the confirmation.
