### ISSUE TITLE
Typescript definition problems with ListenAction['payload'] and Result types

### ISSUE THREAD

**Issue by skulptur** [ctrlplusb/easy-peasy#85]
Easy-peasy version: 1.12.3 (also tested with 1.13.0-alpha.0)
Typescript version: 3.3.3

![image](https://user-images.githubusercontent.com/6286968/52574075-40939b00-2dfa-11e9-9134-bd3212082a5a.png)

**Comment by ctrlplusb** [comment]
Can you share your rollup and tsconfig config?

**Comment by skulptur** [comment]
I'm using a slightly modified version of this: https://github.com/Hotell/typescript-lib-starter
I didn't touch the rollup or tsconfig files tho.

**Comment by ctrlplusb** [comment]
Fixed 👍

**Comment by skulptur** [comment]
Thanks!
