### ISSUE TITLE
Selector not updating

### ISSUE THREAD

**Issue by dusanjovanov** [ctrlplusb/easy-peasy#86]
I have a model that looks like this:
```js
  {
    ids: [1,2,3..],
    byId: {
      1: { item},
      2: {item},
     ...
   },
   list: select(state => state.ids.map(id => state.byId[id]),
   updateItem: (state,payload) => {
     state.byId[payload.id].someField = payload.value;
   }
```

When i update just one field in an item object, the list selector doesn't update. Is this normal behavior?

**Comment by ctrlplusb** [comment]
Thanks for the report @dusanjovanov - this is certainly not normal behaviour. Would you be okay with creating a minimal example on codesanbox.io? I will likely be able to debug it for you sooner then. 👍

**Comment by ctrlplusb** [comment]
Hmmm, ok, let me know if you spot anything.

FYI you can simplify you model. No need to track ids.

```javascript
import { select, createStore } from "easy-peasy";

export default createStore({
  byId: {
    1: {
      id: 1,
      text: "First todo"
    },
    2: {
      id: 2,
      text: "Second todo"
    },
    3: {
      id: 3,
      text: "Third todo"
    }
  },
  //                            👇
  list: select(state => Object.values(state.byId)),
  updateFirstTodo: (state, payload) => {
    state.byId[1].text = Math.random();
  }
});

```

**Comment by ctrlplusb** [comment]
@dusanjovanov I am going to close this for now, but we can reopen it if we can produce a reproducible example. 👍
