### ISSUE TITLE
Using a interface with an optional property as a model doesn't work

### ISSUE THREAD

**Issue by RPDeshaies** [ctrlplusb/easy-peasy#87]
I have an interface `ITheme` that has an optional `logo` property.

For some reason, when mapped via the easy-peasy typescript `State` type, it makes all property has `required` which then breaks all my actions returning a new state for this property.

```
 Types of property 'theme' are incompatible.
        Type 'ITheme' is not assignable to type 'State<ITheme>'.
          Property 'logo' is optional in type 'ITheme' but required in type 'State<ITheme>'.
```

This happened when upgrading from `1.11.1` to  `1.13.0`.

I think this is a breaking change in the contract which should have bumped the major version.
(Right now I understand that the project is still new and not a 100% stable but it's something to think about for the future :))

I think that `State` should just use what ever type is being passed to him as is without any modifications but maybe I'm missing context as well why this change was introduced in the first place

**Comment by ctrlplusb** [comment]
Yep, that would be classified as a bug.  Would you mind writing out a brief code example to help me bootstrap a test with.

**Comment by RPDeshaies** [comment]
of course gimme 5m

**Comment by RPDeshaies** [comment]
```

interface IAnimal {
  name?: string;
}

interface IModel {
  animal: IAnimal;
  setAnimal: Action<IModel, { animal: IAnimal }>;
}

const model: IModel = {
  animal: {
    name: "robert"
  },
  setAnimal: (state, payload) => {
    return { ...state, animal: payload.animal };
  }
};

const store = createStore(model);

```

Error: 


![image](https://user-images.githubusercontent.com/6224111/52640705-164ae780-2ea5-11e9-8bd5-9f9cd67d7944.png)

**Comment by ctrlplusb** [comment]
Thanks. A temp workaround would be to do the following:

```typescript
interface IAnimal {
  name: string | undefined;
}
```

**Comment by RPDeshaies** [comment]
Yeah, probably better than my current workaround

```
  setAnimal: (state, payload) => {
    return { ...state, animal: payload.animal  as IAnimal as any};
  }
```

**Comment by ctrlplusb** [comment]
Resolved in latest release 👍

**Comment by RPDeshaies** [comment]
Linked commit: https://github.com/ctrlplusb/easy-peasy/commit/d7e9414b6b5e3b8caa9fef4681e3694e27b7265b

**Comment by RPDeshaies** [comment]
Awesome thanks @ctrlplusb
