### ISSUE TITLE
TypeError: proxy handler is null

### ISSUE THREAD

**Issue by mohammed-sabra** [ctrlplusb/easy-peasy#872]
Hello,

I'm using easy-peasy v6 and I'm getting this error randomly `TypeError: proxy handler is null`.
I can't reproduce it and can't determine why I get it.

Any hints why this error could happen?

**Comment by no-stack-dub-sack** [comment]
@jmyrland Agreed. @mohammed-sabra Can you please provide some additional context around when you're receiving the error, or provide a stack trace from a time when it happened? Any extra detail here will help us look into this.

Thanks.

**Comment by no-stack-dub-sack** [comment]
Hi @mohammed-sabra - going to close this for now since more information is required to troubleshoot this issue. If this issue persists for you, please feel free to reopen the issue and provide more detail. 

Thank you!
