### ISSUE TITLE
Inquiry Regarding Bundle Size in easy-peasy v6.0.4

### ISSUE THREAD

**Issue by ayoubkhan558** [ctrlplusb/easy-peasy#904]
I noticed that the bundle size of easy-peasy v6.0.4 is 35.3 kB (minified) and 11.0 kB (compressed with GZIP). Given the emphasis on optimization in web development, are there plans to reduce this size without compromising functionality? Looking forward to your insights.

**Comment by jmyrland** [comment]
Hey @ayoubkhan558 !

There are currently no ongoing efforts in reducing the bundle size of easy-peasy.

However, we are open to pull requests if you feel inclined to reduce the footprint of this library while still keeping the same API and behaviour.

As [mentioned in the docs](https://easy-peasy.dev/docs/introduction/downsides.html#increased-bundle-size), 11kb gzipped is not crazy big - but it might not be the best fit in some cases where footprint is a major concern. In this case, you could look at [alternatives](https://easy-peasy.dev/docs/introduction/alternatives.html) to see if there are any candidates with a smaller footprint.

**Comment by no-stack-dub-sack** [comment]
@ayoubkhan558 closing this for now unless there are any further questions on the topic. Please reopen if you'd like to continue the discussion or are open to submitting a PR. Thanks for your interest!
