### ISSUE TITLE
why are the same migrations run multiple times even though the version is already set

### ISSUE THREAD

**Issue by proohit** [ctrlplusb/easy-peasy#912]
Hey and thanks for easy-peasy, it has simplified our state management significantly!

I am trying to use the persisted migration feature, but am having trouble to use it securely.

Given the following scenario, it appears that previous migrations are being executed, **even though their version is exceeded.**

```ts
migrations: {
  migrationVersion: 1,
  1: (state) => {
    state.test = "test";
  },
},
```

Running this migration results in:

```json
{"_migrationVersion": 1, "test": "test"}
```

After that we add second migration **and modify the first one** (for the sake of demonstration that is).

```ts
migrations: {
  migrationVersion: 2,
  1: (state) => {
    state.test = "test2"; // <-- added 2
  },
 2: (state) => {
    state.test2 = "test2";
  },
},
```

Running these results in:

```json
{"_migrationVersion": 2, "test": "test2", "test2": "test2"}
```

As shown, the first migration also runs, even though it has already ran before, resulting in a faulty state. Imagine doing migrations that mutate data based on the previous state, e.g. merging a `firstName` and `lastName` to a `fullName`, which would be done again after the first run, resulting in wrong data or even errors (because `firstName` and `lastName` may not exist anymore).

I would have expected that only migrations between the last and the specified version are executed.

**Comment by jmyrland** [comment]
hey @proohit !

Migrations should work as you expect them to, i.e. they should not run previously executed migrations, as you can see from [this test](https://github.com/ctrlplusb/easy-peasy/blob/0bbc885f8e4191e76b2cbc6f5c953897b14d5763/tests/migrations.test.js#L3-L17).

I'm not sure why this is not the case in your example.

I added a temporary test based on your example:
```ts
test('ISSUE 912', () => {
  // ARRANGE
  const result = migrate(
    { _migrationVersion: 1, test: 'test' },
    {
      migrationVersion: 2,
      1: (state) => {
        state.test = 'test2'; // <-- added 2
      },
      2: (state) => {
        state.test2 = 'test2';
      },
    },
  );

  // ASSERT
  expect(result.test).toBe('test');
  expect(result._migrationVersion).toBe(2);
});
```
This test passes.

Are you able to reproduce your issue in a [sandbox](https://codesandbox.io/)?

**Comment by proohit** [comment]
@jmyrland will check later if I can provide a reproducer.

Maybe important to note, our environment is react native + mmkv as the storage.

**Comment by no-stack-dub-sack** [comment]
Hey @proohit, any updates on this? If you're able to reproduce, please share a link and reopen the issue,. Or if this is no longer a priority, and since we're unable to reproduce, please feel free to allow it to remain closed. Thanks!
