### ISSUE TITLE
Destructuring state breaks Immer's proxy

### ISSUE THREAD

**Issue by Sharlaan** [ctrlplusb/easy-peasy#95]
I'm trying to use easy-peasy in my personal project, but i'm having problem to reset the state into INITIAL_STATE.

Here a snippet based on todolist :
https://codesandbox.io/s/01px98544p

How to reproduce with the above code :
1. Add a todo or remove the existing one (this works !)
2. click on RESET button => nothing happens ???!

In reduxDevTools i see `(states are equal)` while todos.items actually changed !

my console.log in model.reset shows a "Proxy object" instead of todos.items.

Honestly i'm not sure to understand what's going on.

Any help would be appreciated.

**Comment by ctrlplusb** [comment]
It's because you are destructuring the state in the action arguments. Hmmm... this seems to be breaking immer's proxying capabilities. I'll do some research.

This works:
https://codesandbox.io/s/5v8m16n0ol

**Comment by Sharlaan** [comment]
wow nice catch !
Thanks for fast answer, indeed removing the destructuring in the model.action argument makes the reset work.

Weird that other actions -which are also destructured- work ?

**Comment by ctrlplusb** [comment]
I think it is because you are replacing the instance itself. So the proxying breaks. Nice gotcha
