### ISSUE TITLE
nested models

### ISSUE THREAD

**Issue by macrozone** [ctrlplusb/easy-peasy#97]
Hi,

i am trying out easy-peasy and it looks very promising!

I try to migrate my usualy redux architecture with easy-peasy, but one thing that does not work is to have a model that is nested. I usually use another layer to the reducer to give some kind of "namespace"

e.g. here "account" would be this "namespace":

```
const model = {
  account: {
      profile: {
         username: null,
         setUsername: (state, payload) => payload
      }
  }
}
createStore(model)

```

problem is, that it will initialize `account` with an empty object as initial state, but it will use `undefined` as initial state for profile and will crash when using `useStore(state => state.account.profile.username)`

also it will crash when using `useActions(actions => actions.account.profile.setUsername` with `TypeError: Cannot read property 'profile' of undefined`

**Comment by ctrlplusb** [comment]
Thanks @macrozone 

I've looked and you aren't using your actions correctly. 

I've created a codesandbox showing you the correct form:
https://codesandbox.io/s/ojvm0pxop9

👍

**Comment by macrozone** [comment]
@ctrlplusb Hey, thank you for testing this out! 

I think i actually ran into this problem while testing it: https://github.com/ctrlplusb/easy-peasy/issues/100
