### ISSUE TITLE
Is it possible to use redux-form?

### ISSUE THREAD

**Issue by hayk94** [ctrlplusb/easy-peasy#99]
Is it possible to use redux-form with easy-peasy?

I try it like this

```
// @flow
import {
  type TRootReducer,
} from './TRootReducer';
import {
  createStore,
  reducer,
} from 'easy-peasy';
import createHistory from 'history/createBrowserHistory';
import { routerMiddleware, routerReducer } from './router';
import { reducer as formReducer } from 'redux-form';
import { reducer as permissions } from 'react-redux-permissions';
import auth from '../features/Auth/reducers';


export const history = createHistory();

const middleware = [routerMiddleware];

const store = createStore<TRootReducer>(
  {
    auth,
    permissions: reducer(permissions),
    router: reducer(routerReducer),
    form: reducer(formReducer),
  },
  {
    config: {
      middleware,
    },
  }
);

export default store;

```

Then on my form components

`export default reduxForm({ form: 'login' })(Login);`

But I get an error

`Could not find "store" in either the context or props of "Connect(Form(Login))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Form(Login))".
`

Well I guess that happens because reduxForm uses react-redux connect internally. Is there any way to work around this?

**Comment by ctrlplusb** [comment]
Hey @hayk94 

Yep you can wrap your app with the provider from react-redux and then provide the store that easy peasy gives you to it 👍
